ISSUES-10056 support identifier argument for MySQL Database engine
ClickHouse/ClickHouse pull request #10077
Opened 2020-04-07 05:16 UTC by zhang2014

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Bug Fix

Changelog entry:
Add some arguments check and support identifier arguments for MySQL Database Engine

2020-04-07 07:34 UTC, qoega commented
Docs should be fixed as well:
https://clickhouse.tech/docs/en/engines/database_engines/mysql/#creating-a-database

2020-04-07 12:26 UTC, zhang2014 commented
Test failure irrelevant to the modification

2020-04-07 14:05 UTC, qoega commented on docs/en/engines/database_engines/mysql.md
> +ENGINE = MySQL('host:port', ['database' | database], 'user', 'password')
Actually now I can't understand why we allow both variants here and have test `test_bad_arguments_for_mysql_database_engine` later.

There is different behavior in Storage and TableFunction?
```sql
CREATE TABLE default.t1_remote_mysql AS mysql('mysql1:3306', 'test', 't1_mysql_local', root, 'clickhouse')
```

2020-04-07 19:51 UTC, alexey-milovidov commented
All table functions:
- mysql
- odbc
- jdbc
- remote
- cluster

Should have consistent behaviour:
We should allow to database and table names without quotes.

The same for MySQL database engine.

2020-04-07 19:52 UTC, alexey-milovidov requested changes
The code for extraction of identifier/string should be reused somehow.

2020-04-08 19:57 UTC, alexey-milovidov approved these changes

2020-04-08 19:59 UTC, alexey-milovidov commented
Ok. I will also add a trivial functional test to check that the query
```
CREATE DATABASE conv_main ENGINE = MySQL('host:3306', conv_main, 'metrika', 'password')
```
does not segfault.

2020-04-08 19:59 UTC, merged

2020-04-09 04:49 UTC, zhang2014 commented
> Ok. I will also add a trivial functional test to check that the query

Could this possibly broken unbundled's test?