Helloworld
ClickHouse/ClickHouse pull request #10136
Opened 2020-04-08 21:34 UTC by mnkonkova

2020-04-08 21:51 UTC, alexey-milovidov commented
This is not meant to be merged, please switch to "draft" pull request.

2020-04-09 10:47 UTC, mnkonkova commented
The problem may have been that the gRPC_ZLIB_PROVIDER  was not set

2020-04-26 12:41 UTC, vitlibar requested changes

2020-04-26 12:41 UTC, vitlibar commented on programs/server/GRPCHandler.h
> +     enum CallStatus { CREATE, PREPARE, PROCESS, ONFINISH, FINISH };
These statuses make the code complicated and hard to understand.

2020-04-26 12:41 UTC, vitlibar commented on programs/server/GRPCHandler.h
> +          std::unique_ptr<grpc::Server> Server;
std::unique_ptr\<grpc::Server\> **s**erver;
See https://clickhouse.tech/docs/en/development/style/#formatting

2020-04-26 12:41 UTC, vitlibar commented on programs/server/GRPCHandler.h
> +     enum CallStatus { CREATE, PREPARE, PROCESS, ONFINISH, FINISH };
I looked at the function [RequestQuery](https://github.com/ClickHouse/ClickHouse/blob/2be1010cc0ab1db55674c19e6ec741d52ac41903/programs/server/GRPCHandler.cpp#L79). This function is declared in `GrpcConnection.grpc.pb.h` as follows
```
    void RequestQuery(::grpc::ServerContext* context, ::GRPCConnection::QueryRequest* request, ::grpc::ServerAsyncWriter< ::GRPCConnection::QueryResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
```
`new_call_cq` is responsible for finishing calls, and `notification_cq` is responsible for responding. You're passing the same completion queue for `new_call_cq` and for `notification_cq`. But you don't have to do so! Look:

```
GRPCServer(std::string server_address_, IServer& server_)
{
    ...
    notification_cq_ = builder.AddCompletionQueue();
    new_call_cq_.reset(new CompletionQueue());
    server = builder.BuildAndStart();
}

void HandleRpcs()
{
    new CallDataQuery(&service, new_call_cq.get(), notification_cq.get(), &iServer, log);
    
    auto handle_calls_completion = [&]()
    {
        while (true)
        {
            GPR_ASSERT(new_call_cq->Next(&tag, &ok));
            GPR_ASSERT(ok);
            delete static_cast<CallDataQuery*>(tag);
        }
    }

    auto handle_requests_completion = [&]
    {
        while (true)
        {
            GPR_ASSERT(notification_cq->Next(&tag, &ok));
            GPR_ASSERT(ok);
            auto thread = ThreadFromGlobalPool{&CallDataQuery::respond, static_cast<CallDataQuery*>(tag)};
            thread.detach();
        }

    notification_cq_thread = ThreadFromGlobalPool{handle_requests_completion};
    new_call_cq_thread = ThreadFromGlobalPool{handle_calls_completion};
}

CallDataQuery::CallDataQuery(GRPC::AsyncService* Service_, grpc::CompletionQueue* new_call_cq_, ServerCompletionQueue* notification_cq_, IServer* server_, Poco::Logger * log_)
{
Service->RequestQuery(&gRPCcontext, &request, &responder, new_call_cq, notification_cq, this);
}

CallDataQuery::respond()
{
    new CallDataQuery(Service, new_call_cq, notification_cq, iServer, log);

    context.setUser(request.user(), ...)
    ...
    parseQuery(...)
    ...
    executeQuery(...)
    ...
    responder.Write(...)
    ...
    responder.Finish()
}
```
No statuses at all!

2020-04-26 12:41 UTC, vitlibar commented on programs/grpc-client/grpc_client.cpp
> +class GRPCClient {
As I already said, please convert this file into an integration unit-test.
It seems it must not be difficult, see https://grpc.io/docs/quickstart/python/

2020-04-26 12:41 UTC, vitlibar commented on programs/server/GRPCHandler.h
> +     enum CallStatus { CREATE, PREPARE, PROCESS, ONFINISH, FINISH };
Or, if you're making the real streaming, then call `responder.Write()` from `WriteBufferFromGRPC::nextImpl()` and call `responder.Finish()` from `WriteBufferFromGRPC::finalize()`.

2020-09-21 22:22 UTC, vitlibar commented
I'll finish the work in https://github.com/ClickHouse/ClickHouse/pull/15111

2020-09-21 22:22 UTC, closed without merging