Wait for insertion in distributed
ClickHouse/ClickHouse pull request #1031
Opened 2017-07-26 14:43 UTC by KochetovNicolai

2017-07-26 16:31 UTC, ekonkov commented
autotest

2017-07-26 21:08 UTC, alexey-milovidov requested changes

2017-07-26 21:08 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.cpp
> +            throw Exception("Timeout exceeded. Inserted blocks: " + std::to_string(blocks_inserted), ErrorCodes::TIMEOUT_EXCEEDED);
Probably there will be many similar messages for each shard. But these messages doesn't contain shard name and indistinguishable.

2017-07-26 21:08 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.cpp
> +            throw Exception("Timeout exceeded. Inserted blocks: " + std::to_string(blocks_inserted), ErrorCodes::TIMEOUT_EXCEEDED);
What about to add another ProfileEvent for this?

2017-07-26 21:08 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.cpp
> +            LOG_ERROR(log, message);
If we rethrow, don't need to log the message.

2017-07-26 21:08 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.h
> +    void writePrefix() override { deadline = std::chrono::system_clock::now() + std::chrono::seconds(insert_timeout); }
Deadline is initialized twice. Do we have any places where `writePrefix` is not called?
Maybe we could remove useless and misleading initialization from constructor.

2017-07-26 21:08 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.cpp
> +void DistributedBlockOutputStream::writeToShardDirect(const Block & block, const std::vector<std::string> & dir_names, std::atomic<bool> & timeout_exceeded)
Why `timeout_exceeded` is not const reference?

2017-07-26 21:08 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.h
> +    void writeToShardDirect(const Block & block, const std::vector<std::string> & dir_names, std::atomic<bool> & timeout_exceeded);
Missing comment.

2017-07-26 21:08 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.h
> +    UInt64 insert_timeout = 1;
This default value probably have no meaning.

2017-07-26 21:08 UTC, alexey-milovidov commented on dbms/src/Storages/StorageDistributed.cpp
> +        *this, rewriteInsertQuery(query, remote_database, remote_table), cluster, settings.insert_distributed_sync, settings.insert_distributed_timeout);
It means, that default value of last argument of constructor of DistributedBlockOutputStream is not really needed.

2017-07-26 21:08 UTC, alexey-milovidov commented on dbms/tests/integration/test_sync_insert_into_distributed/test.py
> +        raw_input("Cluster created, press any key to destroy...")
Thank you for test!

2017-07-29 19:58 UTC, alexey-milovidov requested changes
As discussed.

2017-08-10 04:38 UTC, alexey-milovidov requested changes

2017-08-10 04:38 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.h
> +    /// Returns the number of blocks was read for each cluster node. Uses during exception handling.
Written?

2017-08-10 04:38 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.cpp
> +    auto & pool = this->pool;
Looks non obvious. It's possible to capture `this`.
See also "capture with an initializer":
http://en.cppreference.com/w/cpp/language/lambda#Lambda_capture

2017-08-10 04:38 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.cpp
> +            if (!cond_var.wait_until(lock, time_point, cond))
See "spurious wakeups" in documentation:
http://en.cppreference.com/w/cpp/thread/condition_variable/wait_until

2017-08-10 04:38 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.cpp
> +        wait();
Why we need "wait" as lambda?

2017-08-10 04:38 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.cpp
> +            std::rethrow_exception(exception);
Relation with code below is ok but very non-obvious.

2017-08-10 04:38 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.cpp
>              writeImpl(splitted_blocks[shard_idx], shard_idx);
Should rename this method to mension async nature.

2017-08-10 04:38 UTC, alexey-milovidov commented on dbms/src/Storages/Distributed/DistributedBlockOutputStream.cpp
> +    const auto & dir_name = shard_info.dir_names[replica_id];
Not very good, that we refer to "directory names" when there are no directories.

2017-08-11 18:35 UTC, merged