Add -Distinct combinator
ClickHouse/ClickHouse pull request #10930
Opened 2020-05-14 19:54 UTC by Sonichka1311

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add -Distinct combinator for aggregate functions.

2020-05-15 00:10 UTC, CurtizJ requested changes
Please, provide some tests.

2020-05-15 00:10 UTC, CurtizJ commented on src/AggregateFunctions/AggregateFunctionDistinct.h
> +        columns[0]->updateHashWithValue(row_num, hash);
Functions with several arguments also can be supported. E.g. `corr(x, y)`.

2020-05-17 03:11 UTC, Sonichka1311 commented on src/AggregateFunctions/AggregateFunctionDistinct.h
> +    void insertResultInto(AggregateDataPtr place, IColumn & to) const override
Why? All aggregate functions uses `ConstAggregateDataPtr` as it declared in `IAggregateFunction`

2020-05-18 08:15 UTC, alexey-milovidov commented
Discussed one issue in TG chat.

2020-06-26 10:40 UTC, merged