Kafka virtual column headers
ClickHouse/ClickHouse pull request #11283
Opened 2020-05-29 09:05 UTC by filimonov

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add 2 more virtual columns for engine=Kafka to access message headers.

Detailed description / Documentation draft:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers

Implements #9337
```
_headers.name Array(String)
_headers.value Array(String)
```

Not implementing that for Producer right now (it would a bit too stupid to write them both to datastream and to headers). Maybe after that: https://github.com/ClickHouse/ClickHouse/issues/9436 

PR is on the top of https://github.com/ClickHouse/ClickHouse/pull/11260

2020-05-29 09:08 UTC, filimonov commented
2 concerns:
1) optionate filling of those columns? 
2) use `Array(LowCardinality(String))` for header names?

2020-05-29 10:40 UTC, alesapin commented on src/Storages/Kafka/KafkaBlockInputStream.cpp
> +    , virtual_header(storage.getSampleBlockForColumns({"_topic", "_key", "_offset", "_partition", "_timestamp","_timestamp_ms","_headers.name","_headers.value"}))
I think we should also add them to the storage virtuals list https://github.com/clickhouse/ClickHouse/blob/master/src/Storages/Kafka/StorageKafka.cpp#L720-L729.

2020-05-29 10:41 UTC, alesapin requested changes
Just check storage virtuals. If it's OK, than PR LGTM.

2020-05-29 10:44 UTC, filimonov commented on src/Storages/Kafka/StorageKafka.cpp
> +        {"_headers.value", std::make_shared<DataTypeArray>(std::make_shared<DataTypeString>())}
@alesapin ^^^

2020-06-01 09:05 UTC, alesapin commented on src/Storages/Kafka/StorageKafka.cpp
> +        {"_headers.value", std::make_shared<DataTypeArray>(std::make_shared<DataTypeString>())}
Really)

2020-06-01 09:05 UTC, alesapin approved these changes

2020-06-01 09:06 UTC, merged