Metrika sync 3
ClickHouse/ClickHouse pull request #113
Opened 2016-09-16 14:28 UTC by PKartaviy

- add tryGetInstance in Daemon
- add ability to increment error counter in pool

2016-09-16 14:28 UTC, PKartaviy commented
@aprudaev

2016-09-16 17:17 UTC, alexey-milovidov commented on libs/libdaemon/include/daemon/BaseDaemon.h
> +	static boost::optional<BaseDaemon &> tryGetInstance() { return tryGetInstance<BaseDaemon>(); }
Missing comment. Unclear meaning.

2016-09-16 17:18 UTC, alexey-milovidov commented on libs/libdaemon/include/daemon/BaseDaemon.h
> +	static boost::optional<Daemon &> tryGetInstance();
We are using `std::experimental::optional` instead of `boost::optional` everywhere. There is no practical difference, but better to be consistent.

2016-09-16 17:19 UTC, alexey-milovidov commented on libs/libdaemon/include/daemon/BaseDaemon.h
> +	}
Better to add comment, when this specific case happens.

2016-09-16 17:23 UTC, alexey-milovidov commented on dbms/include/DB/Common/PoolWithFailoverBase.h
> +			if (pool.pool->contains(entry))
Cannot find `contains` method. (Maybe missed something.)

2016-09-16 17:24 UTC, alexey-milovidov requested changes

2016-09-21 12:35 UTC, PKartaviy commented on libs/libdaemon/include/daemon/BaseDaemon.h
> +	static boost::optional<Daemon &> tryGetInstance();
std::experimental::optional doesn't support references.
http://stackoverflow.com/questions/26858034/stdoptional-specialization-for-reference-types

this class already using boost::optional in getLayer.

2016-09-21 12:42 UTC, PKartaviy commented on libs/libdaemon/include/daemon/BaseDaemon.h
> +	static boost::optional<Daemon &> tryGetInstance();
it's also posible to return ``` Daemon * ```

2016-09-21 13:29 UTC, PKartaviy commented on dbms/include/DB/Common/PoolWithFailoverBase.h
> +			if (pool.pool->contains(entry))
it exists at sqxxl::IPool

2016-09-21 20:55 UTC, merged