add SYSTEM STOP/START FETCHES and SYNC REPLICA description
ClickHouse/ClickHouse pull request #11444
Opened 2020-06-04 15:36 UTC by Slach

Signed-off-by: Slach <bloodjazman@gmail.com>
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation (changelog entry is not required)

2020-06-04 15:42 UTC, blinkov requested changes

2020-06-04 15:42 UTC, blinkov commented on docs/en/sql-reference/statements/system.md
> +Wait when ReplicatedMergeTree table will synced with other replicas in cluster, will run until receive_timeout if fetches currently disabled for table:
```suggestion
Wait until a `ReplicatedMergeTree` table will be synced with other replicas in a cluster. Will run until `receive_timeout` if fetches currently disabled for the table.
```

2020-06-04 16:49 UTC, Slach commented on docs/en/sql-reference/statements/system.md
> +Provides possibility to stop background fetches for inserted parts for tables in the ReplicatedMergeTree family:
nothing happens when I ran `SYSTEM STOP FETCHES` as I see ;)

2020-06-04 17:51 UTC, Slach commented on docs/en/sql-reference/statements/system.md
> +Provides possibility to stop background fetches for inserted parts for tables in the ReplicatedMergeTree family:
@blinkov could you provide any side effects when STOP FETCHES will run twice and more?

2020-06-05 06:10 UTC, Slach commented
@blinkov could you look this PR again? I add all missed SYSTEM statements descriptions

2020-06-05 13:40 UTC, blinkov commented
> @blinkov could you look this PR again? I add all missed SYSTEM statements descriptions
It looks like there's an issue with an incorrect link on single-page version:
```
INFO:root:Tag <a href="#query_language-system-restart-replicas">RESTART REPLICAS</a>
INFO:root:Link to nowhere: #query_language-system-restart-replicas
```

2020-06-08 11:46 UTC, Slach commented
@blinkov link fixed on https://github.com/ClickHouse/ClickHouse/pull/11444/commits/62707935307688a6ff0f321674118d4ae6c8f31d

2020-06-08 15:23 UTC, merged