Fix Pipeline stuck in ConcatProcessor
ClickHouse/ClickHouse pull request #11455
Opened 2020-06-04 22:14 UTC by azat

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix pipeline stuck for INSERT SELECT FINAL where SELECT (max_threads>1) has multiple streams but INSERT has only one (max_insert_threads==0)

Cc: @KochetovNicolai

2020-06-05 09:14 UTC, KochetovNicolai requested changes

2020-06-05 09:14 UTC, KochetovNicolai commented on src/Processors/ConcatProcessor.cpp
> +void ConcatProcessor::prepareInitializeInputs()
I'm afraid this brakes pretty important invariant of `ConcatProcessor`: we don't activate any input until it's turn to read from. I will improve comment.

2020-06-05 09:24 UTC, KochetovNicolai commented on src/Processors/ConcatProcessor.cpp
> +void ConcatProcessor::prepareInitializeInputs()
But, generally, you right. Let's just replace `ConcatProcessor` to `Resize`.

2020-06-05 09:35 UTC, azat commented on src/Interpreters/InterpreterInsertQuery.cpp
> +            res.pipeline.resize(out_streams_size);
Nice idea, didn't though about this

2020-06-05 09:52 UTC, KochetovNicolai approved these changes

2020-06-06 09:36 UTC, merged

2020-06-08 14:33 UTC, KochetovNicolai commented
No backport because there are no affected releases.