Array functions concat slice push pop
ClickHouse/ClickHouse pull request #1146
Opened 2017-08-24 17:06 UTC by KochetovNicolai

2017-08-29 10:19 UTC, KochetovNicolai commented
autotest

2017-08-31 17:06 UTC, alexey-milovidov requested changes

2017-08-31 17:06 UTC, alexey-milovidov commented on dbms/src/Functions/FunctionsArray.cpp
> +FunctionPtr FunctionArray::create(const Context &context)
.

2017-09-01 12:26 UTC, KochetovNicolai commented on dbms/src/Common/TypeList.h
> +#pragma once
unified

2017-09-01 12:29 UTC, KochetovNicolai commented on dbms/src/Common/TypeList.h
> +    using Type = typename AppendToTypeList<TypeToAppend, typename List::Tail, Types ..., typename List::Head>::Type;
TypeList doesn't get permuted. New type is pushed as head.
Renamed to PrependToTypeList

2017-09-01 13:50 UTC, KochetovNicolai commented on dbms/src/Functions/GatherUtils.h
> +            slice.elements->get(slice.begin + i, field);
There is a comment above that columns should have the same type.

2017-09-01 17:30 UTC, merged