New optimization added
ClickHouse/ClickHouse pull request #11667
Opened 2020-06-14 20:34 UTC by xPoSx

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
This optimization eliminates min/max/any aggregators of GROUP BY keys in SELECT section.
...

Detailed description / Documentation draft:

...

2020-06-15 02:50 UTC, alexey-milovidov commented on src/Interpreters/SyntaxAnalyzer.cpp
> +                              function_node->name == "any"))
+ anyLast.

2020-06-15 12:44 UTC, 4ertus2 requested changes
Need a test with enabled and disabled setting and `select` + `analyze select` combination.

2020-06-15 12:44 UTC, 4ertus2 commented on src/Interpreters/SyntaxAnalyzer.cpp
> +        optimizeAggregateFunctionsOfGroupByKeys(select_query);
We need a setting to disable the optimisation. It' possible to combine with some other setting that enables group by optimisation on make a new one.

2020-06-15 12:44 UTC, 4ertus2 commented on src/Interpreters/SyntaxAnalyzer.cpp
> +using SelectChildrenVisitor = InDepthNodeVisitor<SelectChildrenMatcher, true>;
Make less general name: which select children visitor is it? There're could be lots of other select children visitors in other places.

2020-06-15 12:44 UTC, 4ertus2 commented on src/Interpreters/SyntaxAnalyzer.cpp
> +        auto * function_node = ast->as<ASTFunction>();
Make separate `visit(ASTFunction & ...)` instead of operations over ASTFunction in general `visit(ASTPtr & ...)`

2020-06-15 12:44 UTC, 4ertus2 commented on src/Interpreters/SyntaxAnalyzer.cpp
> +struct KeepAggregateFunctionMatcher
Move this and other Matchers/Visitors out of SyntaxAnalyzer.h into own file: `<...>Visitor.h`.

2020-06-15 12:45 UTC, 4ertus2 commented on src/Interpreters/SyntaxAnalyzer.cpp
> +    static void visit(ASTIdentifier * ident, Data & data)
Here and there. It cannot ne nullptr so make it a reference, not a pointer.

2020-06-16 09:49 UTC, 4ertus2 requested changes
Need a functional test with enabled and disabled setting and `select` + `analyze select`.
Need a perf test.

2020-06-16 13:46 UTC, 4ertus2 commented on src/Interpreters/SyntaxAnalyzer.cpp
> +    for (auto & group_key : group_keys)
There's almost the same code in `optimizeGroupByFunctionKeys()`. We need a function that extracts such ckeys instead of code duplication

2020-06-16 15:06 UTC, 4ertus2 approved these changes

2020-06-17 09:32 UTC, merged