Added clickhouse-benchmark enhancements.
ClickHouse/ClickHouse pull request #122
Opened 2016-09-28 16:54 UTC by ludv1x

Three new options:
* launches limit
* time limit
* final results in json file

2016-09-28 17:13 UTC, alexey-milovidov requested changes

2016-09-28 17:13 UTC, alexey-milovidov commented on dbms/src/Client/Benchmark.cpp
> +		std::ofstream jout(filename);
Let use WriteBufferFromFile and DB/IO/Operators.h
By the way, it truncates existing file.

2016-09-28 17:13 UTC, alexey-milovidov commented on dbms/src/Client/Benchmark.cpp
> +		if (!json_path.empty() && Poco::File(json_path).exists()) /// Clear file with previous results
See below.

2016-09-28 17:13 UTC, alexey-milovidov commented on dbms/src/Client/Benchmark.cpp
> +		print_percentile(95);
Empty line here will be helpful.

2016-09-28 17:13 UTC, alexey-milovidov commented on dbms/src/Client/Benchmark.cpp
> +		jout << "{\n";
`jout` name is annoying for me, for unknown reason.
Let it be json_out.

2016-09-28 17:13 UTC, alexey-milovidov commented on dbms/src/Client/Benchmark.cpp
> +		for (size_t i = 0; !(max_iterations > 0) || i < max_iterations; ++i)
Why not
`!max_iterations`
instead of
`!(max_iterations > 0)`
?

2016-09-30 12:43 UTC, ludv1x commented on dbms/src/Client/Benchmark.cpp
> +		if (!json_path.empty() && Poco::File(json_path).exists()) /// Clear file with previous results
It is expected behavior. It allow to avoid reading data from previous test launches if current test is failed.

2016-09-30 13:20 UTC, merged