Fixed `merge_with_ttl_timeout` logic
ClickHouse/ClickHouse pull request #12548
Opened 2020-07-16 13:00 UTC by excitoon

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fixed `merge_with_ttl_timeout` logic which did not work well when partitioning is faster than one piece per time period.

2020-07-17 06:10 UTC, excitoon commented on src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp
> +        if (!has_more_parts_with_expired_ttl)
Идея тут в том, чтобы мёржить до самого конца раз в сутки, пока есть что мёржить. @Akazz мб кстати стоит это под настройку внести? Но вообще, от старого поведения все только страдали, кто пользовался TTL и имел > 1 партиции на единицу времени. То есть как бы это "количество партиций на ед. вр." должно влиять на таймаут, делим длительность партиции на количество, получаем правильный таймаут, который нужно задать.

2020-07-17 06:18 UTC, excitoon commented on src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp
> +        if (!has_more_parts_with_expired_ttl)
Гипотетически, есть риск, что TTL слияния забьют обычные, если там большое отставание по удалению по TTL :man_shrugging: . Может быть их как-то стоит "честно" ставить в очередь? Типа хотя бы поровну?

2020-07-21 11:12 UTC, Akazz commented on src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp
> +        if (!has_more_parts_with_expired_ttl)
Текущий код `MergeTreeDataMergerMutator::selectPartsToMerge()` отдает предпочтение TTL-слияниям (перед обычными слияниями), когда они возможны. Проблема с предложенным сейчас в PR решением заключается в отсутствии гарантии завершения за конечное время: если за время до полного исчерпания TTL-слияний число устаревших записей продолжит расти, то возникнут условия для незавершения этого процесса.

Чтобы гарантировать завершение слияний за конечное время, можно зафиксировать момент времени начала TTL-слияний (момент первого запуска задачи слияния после кулдауна `merge_with_ttl_timeout`) и далее использовать это значение при генерировании всех TTL-слияний.
Что дает это решение:

1. Будут выполнены все TTL-слияния, которые требовались на момент первого запуска процесса.
2. Время завершения фонового процесса TTL-слияний будет конечным даже если записи продолжат устаревать во время работы процесса.

2020-07-23 08:59 UTC, Akazz requested changes

2020-07-23 08:59 UTC, Akazz commented on src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp
> +    time_t next_ttl_merge_time = last_merge_with_ttl != 0 ? last_merge_with_ttl + data_settings->merge_with_ttl_timeout : current_time;
Получилось, что мы работаем здесь с моментом времени из будущего. Довольно неудачно.

Я ранее предложил, наоборот, полностью обрабатывать все, что принадлежит уже закрытому интервалу. То есть для этого нам и требуется фиксировать момент времени первого (по истечении `data_settings->merge_with_ttl_timeout`) старта TTL-слияния. Далее несложно использовать этот момент в качестве точки отсчета для определения устаревших записей.

2020-07-23 08:59 UTC, Akazz commented on src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp
> +        if (ttl && ttl < next_ttl_merge_time)
Здесь возможно преждевременное срабатывание условия поскольку `next_ttl_merge_time` - момент из будущего

2020-07-23 08:59 UTC, Akazz commented on src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp
> +    bool can_merge_with_ttl = next_ttl_merge_time >= current_time;
Опять же, `next_ttl_merge_time` - почти всегда момент времени из будущего по построению. Таким образом это условие почти всегда будет выполнено.

2020-07-23 09:01 UTC, Akazz commented on tests/integration/test_ttl_replicated/test.py
> +def test_merge_with_ttl_timeout(started_cluster):
Предлагаю добавить тест для проверки запуска TTL-слияний не чаще, чем раз в merge_with_ttl_timeout

2020-07-23 14:15 UTC, excitoon commented on src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp
> +        if (ttl && ttl < next_ttl_merge_time)
Это не страшно, тут просто считаем сколько кусков попадут под TTL. Возможно, с ними ничего не будем делать, это проверяется отдельно. Но я вставил маленькую оптимизацию, чтобы этот кусок не выполнялся слишком часто.

2020-07-23 14:16 UTC, excitoon commented on src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp
> +    bool can_merge_with_ttl = next_ttl_merge_time >= current_time;
Опечатка, поправил.

2020-07-23 14:34 UTC, excitoon commented on tests/integration/test_ttl_replicated/test.py
> +def test_merge_with_ttl_timeout(started_cluster):
Добавил в существующий.

2020-07-27 09:51 UTC, Akazz approved these changes
В целом, LGTM

2020-07-27 09:51 UTC, Akazz commented on src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp
> +    time_t next_ttl_merge_time = last_merge_with_ttl != 0 ? last_merge_with_ttl + data_settings->merge_with_ttl_timeout : current_time;
Согласно текущей логики, после запуска сервера/появления таблицы стартуют все TTL-слияния. У меня нет уверенности, что мы хотим одновременный массовый старт этих слияний для всех таблиц с TTL.
@alesapin, @CurtizJ ?

2020-07-27 10:02 UTC, excitoon commented on src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp
> +    time_t next_ttl_merge_time = last_merge_with_ttl != 0 ? last_merge_with_ttl + data_settings->merge_with_ttl_timeout : current_time;
Я только хотел бы сказать, что до этого ПР было так же.

2020-07-27 14:13 UTC, Akazz commented
Do not merge just yet!

2020-07-28 14:40 UTC, Akazz commented
Merged in #12982

2020-07-28 14:40 UTC, closed without merging

2020-07-28 20:02 UTC, filimonov commented
Does is resolve #11576 and #10128 p.2 ?

2020-07-28 20:18 UTC, alexey-milovidov commented
@filimonov Yes, you can close / check the checkbox.