table function view
ClickHouse/ClickHouse pull request #12567
Opened 2020-07-17 16:24 UTC by amosbird

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add table function `view` which turns an subquery into a table object. This helps passing queries around. For instance, it can be used in remote/cluster table functions.

Detailed description / Documentation draft:

Document needs update. Nothing special.

2020-08-28 01:30 UTC, alexey-milovidov requested changes
I'd like to make code more generic to avoid
`name == "view"`

2020-08-28 01:30 UTC, alexey-milovidov commented on src/Parsers/ASTFunction.cpp
> +    if (name == "view")
Maybe just remove this code completely? What will be worse?

2020-08-28 01:32 UTC, alexey-milovidov commented on src/Parsers/ExpressionElementParsers.cpp
> +bool ParserTableFunction::parseImpl(Pos & pos, ASTPtr & node, Expected & expected)
Maybe just allow to have query as an argument to any function?
And then throw exception on query analysis stage if it's wrong place...

Thus we can avoid having special case for "view" here.

2020-08-28 01:33 UTC, alexey-milovidov commented on src/Parsers/ExpressionElementParsers.cpp
> +        || ParserTableFunction().parse(pos, node, expected)
This looks very strange...

2020-09-02 12:45 UTC, alexey-milovidov approved these changes
```
Alexey Milovidov, [02.09.20 15:43]
Ok. About table function view - maybe better to treat query as function argument (put to arguments) rather than special query field in ASTFunction?

Amos Bird, [02.09.20 15:44]
[In reply to Alexey Milovidov]
but that will complex all function visitors...

Alexey Milovidov, [02.09.20 15:44]
Ok, then will keep it as is.
```

2020-09-02 14:07 UTC, merged

2020-09-22 17:28 UTC, simPod commented
I read tests but don't very understand what is this good for 🤔

2020-09-23 17:36 UTC, alexey-milovidov commented
It's intended to pass arbitrary query as is to several remote servers via composition of `remote`/`cluster` and `view` functions.

2021-05-07 02:21 UTC, lelezhan commented
So when we could use the view function? I tested it, it also executes subquery in view for local shard firstly,then executes remote shard. Compared with distribute table, can it improve the performance of query execution when combining it with clusters function, like WITH CTE subquery