Fix MySQL broken link
ClickHouse/ClickHouse pull request #12739
Opened 2020-07-23 19:34 UTC by qoega

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

...

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

2020-07-23 19:36 UTC, alesapin approved these changes
Ok, but wait for tests

2020-07-24 12:28 UTC, alexey-milovidov requested changes
Bug: missing whitespace in the report:
![Screenshot_20200724_152659](https://user-images.githubusercontent.com/18581488/88391110-2cf7ac80-cdc2-11ea-85b2-7bc14655bb61.png)

2020-07-27 10:01 UTC, qoega commented on docker/test/integration/base/Dockerfile
> +RUN curl 'https://cdn.mysql.com//Downloads/Connector-ODBC/8.0/mysql-connector-odbc-8.0.21-linux-glibc2.12-x86-64bit.tar.gz' --output 'mysql-connector.tar.gz' && tar -xzf mysql-connector.tar.gz && cd
```suggestion
RUN curl 'https://cdn.mysql.com//Downloads/Connector-ODBC/8.0/mysql-connector-odbc-8.0.21-linux-glibc2.12-x86-64bit.tar.gz' --output 'mysql-connector.tar.gz' && tar -xzf mysql-connector.tar.gz && cd mysql-connector-odbc-8.0.21-linux-glibc2.12-x86-64bit/lib && mv * /usr/local/lib && ln -s /usr/local/lib/libmyodbc8a.so /usr/lib/x86_64-linux-gnu/odbc/libmyodbc.so
```

2020-07-27 13:10 UTC, alesapin commented
> Bug: missing whitespace in the report:
> ![Screenshot_20200724_152659](https://user-images.githubusercontent.com/18581488/88391110-2cf7ac80-cdc2-11ea-85b2-7bc14655bb61.png)

![image](https://user-images.githubusercontent.com/3684697/88545461-b0fc9f00-d023-11ea-9ecd-33ba32a11de3.png)

2020-07-27 16:50 UTC, alesapin commented
integration OK.

2020-07-27 16:51 UTC, merged