AvroConfluent: skip Kafka tombstone records
ClickHouse/ClickHouse pull request #13161
Opened 2020-07-31 04:47 UTC by oandrew

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
AvroConfluent: Skip Kafka tombstone records
...

Detailed description / Documentation draft:
Kafka tombstone records have null value and should be skipped instead of throwing an error.
...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

2020-07-31 05:03 UTC, oandrew commented
@filimonov

2020-07-31 12:06 UTC, alexey-milovidov commented
@azat

2020-07-31 12:06 UTC, alexey-milovidov requested changes
Missing integration test.

2020-08-01 06:54 UTC, closed without merging

2020-08-01 07:01 UTC, oandrew commented
I closed this PR on accident, here is the new one: 
https://github.com/ClickHouse/ClickHouse/pull/13203

2020-08-01 09:00 UTC, azat commented
>I closed this PR on accident, here is the new one:

You can actually reopen the PR