Automatic update of remote servers configuration.
ClickHouse/ClickHouse pull request #132
Opened 2016-10-11 14:24 UTC by ludv1x

Also update of users' config from users.d dir introduced.

2016-10-13 02:41 UTC, alexey-milovidov requested changes

2016-10-13 02:41 UTC, alexey-milovidov commented on dbms/src/Storages/StorageDistributed.cpp
> +	/// resharding_worker не нуждается во владении cluster, здесь используется только мета-информация
Please write in english.

2016-10-14 13:33 UTC, ludv1x commented on dbms/include/DB/Interpreters/Context.h
> +	void setClustersConfig(ConfigurationPtr config);
We not just apply passed config, we also store config to apply it in the future (on first getClusters() call). So we need to store it (at least for clusters).
Currently, to do this we just copy shared_ptr (Poco::AutoPtr).
If we pass reference, we will must make copy of Poco::Util::AbstractConfiguration created inside ConfigReloader.

2016-10-14 13:47 UTC, ludv1x commented on dbms/include/DB/Interpreters/Context.h
> +	void setClustersConfig(ConfigurationPtr config);
Reference to shared_ptr - OK.

2016-10-14 14:01 UTC, ludv1x commented on dbms/src/Server/ConfigReloader.h
> +		bool operator == (const FileWithTimestamp & rhs) const
Ok.
BTW. But such inconsistencies appears quite often outside Matlab-like programming world.

2016-10-14 17:27 UTC, ludv1x commented on dbms/src/Common/ConfigProcessor.cpp
> +	for (auto & merge_file : getConfigMergeFiles(path_str))
If I am not mistaken derived type of `auto` will be `const std::string`, so the resulting type `const std::string &` is the same as in `const auto &` case.

2016-10-14 17:57 UTC, ludv1x commented on dbms/src/Common/ConfigProcessor.cpp
> +	for (auto & merge_file : getConfigMergeFiles(path_str))
Ok, like small enhancement. Behavior isn't changed anyway.

2016-10-14 19:32 UTC, merged

2016-10-15 19:50 UTC, alexey-milovidov commented
What if file is written non-atomically and in moment of reload, server observe a file with incorrect XML?
When will be next reload after exception?

BTW, we already have this problem with dictionaries: if file is modified not with atomic rename, there are rare race conditions, when dictionaries are not updated.

2016-10-17 09:36 UTC, ludv1x commented
To update config on next reload modification time observed at previous iteration should differs from currently observed modification time.
So, config will be reloaded if OS sets file's modification time after all data modifications.
Otherwise, described case can occur.

To avoid this, we need to save modification time if and only if XML was loaded successfully.
But in that case if a user saves incorrect config and forget to check that changes was successfully applied, server will try to reload incorrect XML and write error logs during all remain lifetime.

So, I faced with that use case and decided to save modification time even if XML parsing failed.

2016-10-17 19:40 UTC, alexey-milovidov commented
> So, config will be reloaded if OS sets file's modification time after all data modifications.

I am not sure about it.

> To avoid this, we need to save modification time if and only if XML was loaded successfully.

Also it is possible to reset modification time to zero on exception (means - retry next time).

> But in that case if a user saves incorrect config and forget to check that changes was successfully applied, server will try to reload incorrect XML and write error logs during all remain lifetime.

I think, it is Ok.

> So, I faced with that use case and decided to save modification time even if XML parsing failed.
It seems that, shared file lock doesn't have drawbacks. -)

We could postpone this issue until we face it.

2017-01-25 00:26 UTC, DmitryBe commented
Do you consider an option of centralised storing remote server config in ZK?

2017-01-25 01:48 UTC, alexey-milovidov commented
We was thinking about possibility to load any configuration sections from ZK.

2017-01-27 00:13 UTC, DmitryBe commented
What have you decided in results? Do you plan to support ZK based config in the nearest future? If yes, approximately when?

2017-01-27 00:32 UTC, alexey-milovidov commented
I have added it to the list, we will decide time estimate for this task at next week.

2017-01-27 00:39 UTC, DmitryBe commented
Sounds great! Thanks a lots for quick reply.