specific ReplicatedMergeTree settings
ClickHouse/ClickHouse pull request #13573
Opened 2020-08-10 11:31 UTC by amosbird

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Allow user to specify default `replicated_merge_tree` settings in the config file. There are some settings which are useful defaults for replicated tables but don't make sense for normal tables, and using `merge_tree` settings will complicate system tables.

Detailed description / Documentation draft:

Document has been updated.

2020-08-11 10:35 UTC, abyss7 requested changes
Can you add a simple test, please? To check that new settings work and really have higher priority.

2020-08-11 14:41 UTC, amosbird commented
Tests are added but not verified locally (I don't have docker right now). Let's see if I can get it right ...

2020-09-17 09:02 UTC, KochetovNicolai approved these changes

2020-09-20 21:30 UTC, abyss7 approved these changes

2020-09-20 22:36 UTC, merged