Fixed Debug build.
ClickHouse/ClickHouse pull request #138
Opened 2016-10-16 20:03 UTC by ludv1x

2016-10-16 23:33 UTC, alexey-milovidov requested changes

2016-10-16 23:33 UTC, alexey-milovidov commented on dbms/src/Server/ConfigReloader.cpp
> +		auto sleep_duration = reload_interval;
Motivation is absolutely unclear without context of this task.

2016-10-16 23:33 UTC, alexey-milovidov commented on dbms/src/Server/ConfigReloader.cpp
> +		auto sleep_duration = reload_interval;
Definition in .cpp file is much more straightforward.

2016-10-17 10:35 UTC, ludv1x commented on dbms/src/Server/ConfigReloader.cpp
> +		auto sleep_duration = reload_interval;
Ok

2016-10-17 18:23 UTC, merged