Allow FETCH PARTITION from other zookeepers
ClickHouse/ClickHouse pull request #14155
Opened 2020-08-27 04:13 UTC by amosbird

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Now it's possible to `ALTER TABLE table_name FETCH PARTITION partition_expr FROM 'zk://<host>:<port>/path-in-zookeeper'`. It's useful for shipping data to new clusters.

Detailed description / Documentation draft:

Documentation needs syncing.

2020-08-27 09:53 UTC, alesapin commented
`00834_cancel_http_readonly_queries_on_client_close` known flaky test.

2020-08-27 10:05 UTC, alesapin approved these changes
LGTM, but need to add a test at least with our own ZK.

2020-08-27 10:05 UTC, alesapin commented on src/Storages/StorageReplicatedMergeTree.cpp
> +            part->is_temp = false;
Add a comment on why we need it. It's really important.

2020-08-27 12:52 UTC, alexey-milovidov commented
Does it respect `remote_host_filter`?
Otherwise we have SSRF and the possibility of DoS via ClickHouse.

2020-08-27 12:53 UTC, alexey-milovidov commented on src/Storages/StorageReplicatedMergeTree.cpp
> +    if (uri.getScheme() == "zk")
It `zk` somehow standard for URLs?

2020-08-27 12:54 UTC, alexey-milovidov commented on src/Storages/StorageReplicatedMergeTree.cpp
> +        zkhost = uri.getHost() + ":" + toString(uri.getPort());
Looks like IPv6 is not supported?

[::]:123

2020-08-27 12:55 UTC, alexey-milovidov commented on src/Storages/StorageReplicatedMergeTree.cpp
> +        zkhost = uri.getHost() + ":" + toString(uri.getPort());
ZooKeeper is a cluster... how to write multiple hosts in URL?

2020-08-27 12:56 UTC, alexey-milovidov requested changes
Looking for the possiblity of SSRF it will be better to add the support for remote_host_filter and also add a setting in config.xml to enable these queries that is disabled by default (because almost no one enables remote_host_filter).

2020-08-27 12:58 UTC, alexey-milovidov commented
The overall solution is limited because it does not support ZK clusters with authentication.
It also looks like it does not allow to connect to ZK with TLS.

Maybe it will be better to have multiple named ZK clusters in config?
It will open up the possibility to specify different ZK clusters for different Replicated tables in future.

2020-08-27 14:23 UTC, amosbird commented
@alexey-milovidov reimplemented as suggested.

2020-08-28 11:15 UTC, alesapin reviewed
I'm not sure about the name `<auxiliary_zookeepers>` in config.xml if we have any plans to use it for other purposes. The rest part is OK.

2020-08-28 20:39 UTC, alesapin approved these changes
LGTM

2020-08-31 06:54 UTC, merged