DOCSUP-1675 Docs for the cast_keep_nullable setting
ClickHouse/ClickHouse pull request #14508
Opened 2020-09-04 22:10 UTC by olgarev

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Documentation for #11733

2020-09-08 15:54 UTC, blinkov commented
converstion => conversion

2020-09-08 16:24 UTC, BayoNet commented on docs/en/operations/settings/settings.md
> +Enables or disables converstion to nullable types for [CAST](../../sql-reference/functions/type-conversion-functions.md#type_conversion_function-cast) operator.
```suggestion
Enables or disables keeping of the `Nullable` data type in [CAST](../../sql-reference/functions/type-conversion-functions.md#type_conversion_function-cast) operations.
```

2020-09-08 16:24 UTC, BayoNet commented on docs/en/operations/settings/settings.md
> +Enables or disables converstion to nullable types for [CAST](../../sql-reference/functions/type-conversion-functions.md#type_conversion_function-cast) operator.
Also we need a link to Nullable.

2020-09-08 16:28 UTC, BayoNet commented on docs/en/operations/settings/settings.md
> +-   1 — Nullable type converstion enabled.
```suggestion
-  0 — The final type of `CAST` exactly the destination data type specified.
-  1 — The final type of `CAST` becomes `Nullable(DestinationDataType).
```

2020-09-08 16:33 UTC, BayoNet commented on docs/en/operations/settings/settings.md
> +Query with nullable type converstion disabled:
```suggestion
The following query exactly results in the destination data type:
```

2020-09-08 16:34 UTC, BayoNet commented on docs/en/operations/settings/settings.md
> +Query with nullable type converstion enabled:
```suggestion
The following query results in the `Nullable` modification on the destination data type:
```

2020-09-19 13:41 UTC, alexey-milovidov commented on docs/ru/operations/settings/settings.md
> +Включает или отключает финальное преобразование аргумента функции [CAST](../../sql-reference/functions/type-conversion-functions.md#type_conversion_function-cast) к типу `Nullable`.
Not clear enough.

2020-09-19 13:41 UTC, alexey-milovidov requested changes

2020-09-19 13:41 UTC, alexey-milovidov commented on docs/ru/operations/settings/settings.md
> +Если настройка включена, то функция `CAST(something_nullable AS Type)` возвращает `Nullable(Type)`.
Plain wrong.

2020-09-20 20:10 UTC, alexey-milovidov commented
The setting allow to *keep nullable* if the data type is already nullable.

2020-09-20 20:10 UTC, alexey-milovidov commented
Please make some experiments and edit the text...

2020-09-25 08:41 UTC, olgarev commented on docs/ru/operations/settings/settings.md
> +Если настройка включена, то функция `CAST(something_nullable AS Type)` возвращает `Nullable(Type)`.
I updated the text.

2020-09-25 16:48 UTC, BayoNet commented on docs/ru/operations/settings/settings.md
> +Если настройка включена, то функция `CAST(something_nullable AS Type)` возвращает `Nullable(Type)`.
You have updated the text from the previous commentary :-). 

The latter commentary from Alexey clarifies the situation: "The setting allows to keep nullable if the data type is already nullable." This means that the sentence "Если настройка включена, то функция `CAST(something_nullable AS Type)` возвращает `Nullable(Type)`." is really wrong.

2020-10-13 21:05 UTC, alexey-milovidov approved these changes

2020-10-13 21:06 UTC, merged