DOCSUP-2040: Translate PR to RU
ClickHouse/ClickHouse pull request #14551
Opened 2020-09-07 15:39 UTC by ka1bi4

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation (changelog entry is not required)

Detailed description / Documentation draft:

1. Add Arrow and Add ArrowStream.
2. Add function fuzzBits.
3. Add {to,from}UnixTimestamp64{Milli,Micro,Nano} functions.

2020-09-08 12:27 UTC, qoega requested changes

2020-09-08 12:27 UTC, qoega commented on docs/ru/sql-reference/functions/random-functions.md
> +Случайная/Размытая строка с тем же типом, что и `s`.
```suggestion
Измененная случайным образом строка с тем же типом, что и `s`.
```

2020-09-08 12:27 UTC, qoega commented on docs/ru/sql-reference/functions/type-conversion-functions.md
> +Преобразует значение `DateTime64` в значение `Int64` с фиксированной точностью до секунды.
`Converts a DateTime64 to a Int64 value with fixed sub-second precision`
```suggestion
Преобразует значение `DateTime64` в значение `Int64` с фиксированной точностью менее одной секунды. 
```

2020-09-08 12:27 UTC, qoega commented on docs/ru/sql-reference/functions/type-conversion-functions.md
> +Преобразует значение `Int64` в значение `DateTime64` с фиксированной субсекундной точностью и дополнительным часовым поясом. Входное значение округляется соответствующим образом вверх или вниз в зави
Корректно ли слово `субсекундной` с точки зрения словарей?

2020-09-08 13:44 UTC, ka1bi4 commented on docs/ru/sql-reference/functions/type-conversion-functions.md
> +Преобразует значение `Int64` в значение `DateTime64` с фиксированной субсекундной точностью и дополнительным часовым поясом. Входное значение округляется соответствующим образом вверх или вниз в зави
Действительно. Такого слово нет, заменил на (менее одной секунды).

2020-09-10 18:45 UTC, BayoNet commented on docs/ru/sql-reference/functions/random-functions.md
> +- `s` - `String` or `FixedString`
Тире длинные надо.

2020-09-10 18:46 UTC, BayoNet commented on docs/ru/sql-reference/functions/type-conversion-functions.md
> +-   `value` — значение DateTime64 с любой точностью.
```suggestion
-   `value` — значение `DateTime64` с любой точностью.
```

2020-09-10 18:47 UTC, BayoNet commented on docs/ru/sql-reference/functions/random-functions.md
> +- `prob` - constant `Float32/64`
```suggestion
- `s` — `String` or `FixedString`
- `prob` — constant `Float32/64`
```

2020-09-10 18:47 UTC, BayoNet commented on docs/ru/sql-reference/functions/type-conversion-functions.md
> +-   значение `value`, преобразованное в тип данных `Int64`.
```suggestion
-   Значение `value`, преобразованное в тип данных `Int64`.
```

2020-09-10 18:48 UTC, BayoNet commented on docs/ru/sql-reference/functions/type-conversion-functions.md
> +-   значение `value`, преобразованное в тип данных `DateTime64`.
```suggestion
-   Значение `value`, преобразованное в тип данных `DateTime64`.
```

2020-09-11 12:47 UTC, merged