DOCS-323: LowCardinality
ClickHouse/ClickHouse pull request #14772
Opened 2020-09-12 17:38 UTC by otrazhenia

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Documentation for https://github.com/ClickHouse/ClickHouse/pull/11060

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

2020-09-13 23:28 UTC, den-crane requested changes

2020-09-13 23:28 UTC, den-crane commented on docs/ru/operations/settings/settings.md
> +Включает или выключает использование единого словаря для частей данных.
Включает или выключает использование единого словаря для куска (парта).

2020-09-13 23:28 UTC, den-crane commented on docs/ru/operations/settings/settings.md
> +Задает максимальную длину строк в общем глобальном словаре для типа данных `LowCardinality`, который может быть записан в файловую систему хранилища. Настройка предоствращает проблемы с оперативной п
Задает максимальный размер общего глобального словаря (в строках)  для типа данных `LowCardinality`, который может быть записан в файловую систему хранилища. Настройка предотвращает проблемы с оперативной памятью в случае неограниченного увеличения словаря. Все данные, которые не могут быть закодированы из-за ограничения максимального размера словаря, ClickHouse записывает обычным способом.

2020-09-15 14:07 UTC, otrazhenia commented on docs/ru/operations/settings/settings.md
> +Включает или выключает использование единого словаря для частей данных.
Отредактировала

2020-09-15 14:07 UTC, otrazhenia commented on docs/ru/operations/settings/settings.md
> +Задает максимальную длину строк в общем глобальном словаре для типа данных `LowCardinality`, который может быть записан в файловую систему хранилища. Настройка предоствращает проблемы с оперативной п
Тоже отредактировала

2020-09-20 20:07 UTC, alexey-milovidov approved these changes

2020-09-20 20:07 UTC, merged