Implemented clickhouse-local application
ClickHouse/ClickHouse pull request #150
Opened 2016-10-25 17:38 UTC by ludv1x

example of clickhouse-local
```bash
dbms/src/Server/clickhouse-server --local-mode --query "CREATE TABLE table (database String, name String, engine String, metadata_modification_time DateTime) ENGINE = File(JSONEachRow, stdin); SELECT database, uniqExact(engine) AS enginesNum FROM table GROUP BY database FORMAT Pretty;   " < system_tables.json 
```

2016-10-28 17:47 UTC, ludv1x commented
A lot of documentation should be added for `clickhouse-local` program and `File` storage. It is better to make in separate PR.

2016-10-28 19:10 UTC, alexey-milovidov commented
> A lot of documentation should be added for clickhouse-local program and File storage. It is better to make in separate PR.

Ok.

2016-10-30 00:23 UTC, alexey-milovidov commented on dbms/src/Server/LocalServer.cpp
> +	context->setUser("default", "", Poco::Net::IPAddress{}, 0, "");
Does not compile (after recent changes).

2016-10-30 18:06 UTC, ludv1x commented on dbms/src/Server/LocalServer.cpp
> +	context->setUser("default", "", Poco::Net::IPAddress{}, 0, "");
Fixed

2016-11-09 21:06 UTC, alexey-milovidov requested changes
Need some minimal functional tests for ENGINE = File(...).

2016-11-09 21:06 UTC, alexey-milovidov commented on dbms/src/Storages/StorageFactory.cpp
> +				source_path = std::move(table_source);
And also nice to have possibility to specify file descriptors as numbers.
Example:

```
clickhouse-local --query="CREATE TABLE ... ENGINE = File(TabSeparated, 3); SELECT * FROM table;" 3<file
```

So you could read from many file descriptors.
Quite obscure feature, but usable in shell scripts.

2016-11-09 21:07 UTC, alexey-milovidov commented
Also, I don't see changes in /debian directory. Has been checked that packages is building successfully?
(`./release` script)

2016-11-11 13:40 UTC, ludv1x commented on dbms/src/Storages/StorageFile.cpp
> +			if (storage.table_fd_was_used)
I worried about misleading in such case:
1) select -> data1; insert data2; select -> data1 + data2;
3) insert data2 (overwrites data1); select -> data2;

But such cases is possible when FD is binded to real file, which is quite rare.

So, multiple writes and write after read for FD should be possible, so there are no any checks are required.

2016-11-11 14:01 UTC, ludv1x commented on dbms/src/Server/LocalServer.cpp
> +			.argument (" config.xml")
Otherwise `--help` will print:
`-Cconfig.xml, --config-file=config.xml`
instead of
`-C config.xml, --config-file= config.xml`
`Cc` is ugly.

2016-11-11 14:59 UTC, alexey-milovidov commented on dbms/src/Server/LocalServer.cpp
> +			.argument (" config.xml")
Ok.

2016-11-13 01:45 UTC, alexey-milovidov commented
Almost ready to merge :)

2016-11-13 23:04 UTC, ludv1x commented
It seems, that division by zero occur [here](https://github.com/yandex/ClickHouse/blob/1d836b2bf8fef378d47258957ff74ed3a4aff136/dbms/src/Interpreters/Quota.cpp#L112)

2016-11-13 23:12 UTC, alexey-milovidov commented
But no problem if you specify no intervals at all.

2016-11-14 00:02 UTC, ludv1x commented
Updated. Removed <intervals> section and added zero check for interval duration.

2016-11-14 00:03 UTC, merged

2016-11-14 00:34 UTC, alexey-milovidov commented
Release script does not work:

```
$ CC=gcc-6 CXX=g++-6 ./release --standalone
...
cp: cannot stat ‘debian/tmp//etc/clickhouse-client/config.xml’: No such file or directory
```