DOCSUP-2042: Edit and translate to Russian.
ClickHouse/ClickHouse pull request #15462
Opened 2020-09-30 08:04 UTC by damozhaeva

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Documentation (changelog entry is not required)

Detailed description / Documentation draft:

- edit the English version of the text
- translate the text to Russian

2020-10-03 13:30 UTC, alexey-milovidov commented on docs/ru/operations/settings/settings.md
> +Если эта настройка включена, замените пустые поля ввода в TSV значениями по умолчанию. Для сложных выражений по умолчанию также должна быть включена настройка `input_format_defaults_for_omitted_field
Некорректная форма глагола.

2020-10-03 13:30 UTC, alexey-milovidov commented on docs/ru/operations/settings/settings.md
> +-   Положительное целое число от 1 до 15.
На самом деле больше.

2020-10-03 13:30 UTC, alexey-milovidov commented on docs/ru/operations/settings/settings.md
> +Запросы, переданные в ClickHouse с этой установкой, логируются согласно правилам конфигурационного параметра сервера [query\_log](../../operations/server-configuration-parameters/settings.md#server_c
Недостаточно точное описание - читателю не будет ясно различие между системными таблицами и текстовым логом.

2020-10-03 13:31 UTC, alexey-milovidov commented on docs/ru/operations/settings/settings.md
> +Управляет скоростью обнуления ошибок в распределенных таблицах. Если реплика недоступна в течение некоторого времени, накапливает 5 ошибок, а distributed\_replica\_error\_half\_life установлена на 1
Не объяснён смысл.

2020-10-03 13:33 UTC, alexey-milovidov commented on docs/ru/operations/settings/settings.md
> +Обеспечивает параллельный анализ форматов данных с сохранением порядка. Поддерживается только для форматов TSV, TKSV, CSV и JSONEachRow.
Неправильный подбор слов делает документацию запутанной.

2020-10-03 13:34 UTC, alexey-milovidov commented on docs/ru/operations/settings/settings.md
> +Минимальный размер блока в байтах, который каждый поток будет анализировать параллельно.
Не объяснена мотивация для наличия этой настройки. У читателя будет отсутствовать понимание смысла.

2020-10-03 13:34 UTC, alexey-milovidov commented on docs/ru/operations/settings/settings.md
> +Позволяет изменить кодировку, которая используется для печати грид-границ. Доступны следующие кодировки: UTF-8, ASCII.
Отсутствует перевод.

2020-10-03 13:35 UTC, alexey-milovidov commented on docs/ru/operations/settings/settings.md
> +Позволяет изменить кодировку, которая используется для печати грид-границ. Доступны следующие кодировки: UTF-8, ASCII.
Не объяснена мотивация наличия этой настройки.

2020-10-03 13:35 UTC, alexey-milovidov requested changes
.

2020-10-13 15:29 UTC, BayoNet commented
Комментарии обработаем в другой задаче.

2020-10-13 15:29 UTC, merged

2021-02-07 16:08 UTC, damozhaeva commented on docs/ru/operations/settings/settings.md
> +-   Положительное целое число от 1 до 15.
Подскажи, пожалуйста, какое правильное значение указать в переводе?
В оригинале так:
"Positive integer from 1 to 15."

2021-02-07 17:13 UTC, damozhaeva commented on docs/ru/operations/settings/settings.md
> +Запросы, переданные в ClickHouse с этой установкой, логируются согласно правилам конфигурационного параметра сервера [query\_log](../../operations/server-configuration-parameters/settings.md#server_c
Я выполняла перевод с оригинала. Там была вот такая фраза:
"Queries sent to ClickHouse with this setup are logged according to the rules in the [query_log](../../operations/server-configuration-parameters/settings.md#server_configuration_parameters-query-log) server configuration parameter."
Подскажи, какую информацию сюда добавить, чтобы было понятнее?

2021-02-07 17:20 UTC, damozhaeva commented on docs/ru/operations/settings/settings.md
> +Минимальный размер блока в байтах, который каждый поток будет анализировать параллельно.
В оригинале была вот такая фраза:
"The minimum chunk size in bytes, which each thread will parse in parallel". 
Какую информацию сюда можно добавить?

2021-02-07 17:57 UTC, damozhaeva commented on docs/ru/operations/settings/settings.md
> +Если эта настройка включена, замените пустые поля ввода в TSV значениями по умолчанию. Для сложных выражений по умолчанию также должна быть включена настройка `input_format_defaults_for_omitted_field
Замечание поправила в этом PR https://github.com/ClickHouse/ClickHouse/pull/20190/files

2021-02-07 17:58 UTC, damozhaeva commented on docs/ru/operations/settings/settings.md
> +Обеспечивает параллельный анализ форматов данных с сохранением порядка. Поддерживается только для форматов TSV, TKSV, CSV и JSONEachRow.
Замечание поправила в этом PR https://github.com/ClickHouse/ClickHouse/pull/20190/files