Select final
ClickHouse/ClickHouse pull request #15938
Opened 2020-10-13 19:17 UTC by Avogar

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Do not merge parts across partitions in SELECT FINAL

Detailed description / Documentation draft:
Define a new setting `do_not_merge_across_partitions_select_final`. If it's true we will merge parts only with the same partition, moreover, if there is only one part in partition and it's level > 0 we won't merge it.

2020-10-13 20:49 UTC, UnamedRus commented
>  Define a new setting do_not_merge_across_partitions_select_final. If it's true we will merge parts only with the same partition, moreover, if there is only one part in partition and it's level > 0 we won't merge it.

There is a possibility that partition was attached from ./detached dir or from another table and already has level > 0 and duplicates, so it isn't a reliable way to check this, or we would need to reset the level of that partition to zero in that kind of parts manipulation.

2020-10-13 21:11 UTC, alexey-milovidov commented
Maybe better to have simple rule: one part in partition - do not postprocess it.

2020-10-20 14:43 UTC, CurtizJ requested changes
It will be useful to add a perf test and also to check the difference in performance with case, when all partitions are merged.

2020-10-20 14:43 UTC, CurtizJ commented on src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp
> +            LOG_DEBUG(log, "Output ports size: {}", ports.size());
Did you forget to remove debug output? If you want to leave it, please, add more context to message.

2020-10-20 14:43 UTC, CurtizJ commented on src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp
> +                case MergeTreeData::MergingParams::Ordinary: {
Style. According to out style guide, curly bracket should be on new line or can be ommitted.

2020-10-21 17:39 UTC, Avogar commented
> It will be useful to add a perf test and also to check the difference in performance with case, when all partitions are merged.

@CurtizJ I've never written perf tests before, can you explain what should I do in performance test? Just make a query with `SELECT ... FINAL`? And how to check the difference in performance in different cases in such tests?

2020-10-21 20:15 UTC, CurtizJ commented
You can find examples of performance tests in tests/performance. A test is .xml file with bunch of queries for measuring time of their executing and possible some additional queries for preparation. Also you can set specific settings for tests. A good [example](https://github.com/ClickHouse/ClickHouse/blob/master/tests/performance/read_in_order_many_parts.xml), where all sections exist. It's recommended for execution time of query to be in 0.1-1s.

> And how to check the difference in performance in different cases in such tests?

It's ok to compare two modes of `FINAL` locally, just to be sure, that performance has been improved.

2020-10-22 17:22 UTC, Avogar commented
> You can find examples of performance tests in tests/performance. Test is a .xml file with bunch of queries for measuring time of their executing and possible some additional queries for preparation. Also you can set specific settings for tests. A good [example](https://github.com/ClickHouse/ClickHouse/blob/master/tests/performance/read_in_order_many_parts.xml), where all sections exist. It's recommended for execution time of query to be in 0.1-1s.
> 
> Yes, just add a query with `SELECT ... FINAL` and your setting to check that in the future performance of this behaviour won't be broken.
> 
> > And how to check the difference in performance in different cases in such tests?
> 
> It's ok to compare two modes of `FINAL` locally, just to be sure, that performance has been improved.

Thanks for clear explanation! I will try to do it at this week

2020-10-23 11:59 UTC, akuzm commented on tests/performance/optimized_select_final.xml
> +    <fill_query>INSERT INTO optimized_select_final SELECT toDate('2020-01-01'), number FROM numbers(1000000)</fill_query>
It makes sense to add `optimize table` as the final fill query -- this way, you can be sure that all background merges have completed before the test queries start, and will get more stable results.

2020-10-28 19:40 UTC, Avogar commented
@CurtizJ I see this exception in my perf test: `DB::Exception: Unknown setting do_not_merge_across_partitions_select_final.` But I added this setting in this pr and I can't understand the reason of exception, it works locally, do you know what's wrong?

2020-10-29 01:15 UTC, alexey-milovidov commented
@Avogar It because performance test runs two servers: old and new.
This error is Ok for old server.

2020-10-29 11:04 UTC, CurtizJ approved these changes

2020-11-03 10:49 UTC, CurtizJ commented
`00840_long_concurrent_select_and_drop_deadlock` is broken in master.

2020-11-03 10:49 UTC, merged

2021-01-19 22:36 UTC, den-crane commented
hm, I don't see much improvement:

```sql

CREATE TABLE T (p Int64, d Date, some_col String)
Engine=ReplacingMergeTree 
Partition by toYYYYMM(d)
Order by (p, d);


insert into T select number, '2020-01-01', '' from numbers(100000000);
insert into T select number, '2020-01-01', 'updated' from numbers(100000000);

optimize table T final;

select distinct(_part) from T;
┌─_part──────────┐
│ 202001_1_192_4 │
└────────────────┘

select max(d) from T final where some_col = 'updated';
Elapsed: 2.095 sec. Processed 100.00 million rows, 2.60 GB (47.73 million rows/s., 1.24 GB/s.)

select max(d) from T final where some_col = 'updated' SETTINGS do_not_merge_across_partitions_select_final = 1;
Elapsed: 2.063 sec. Processed 100.00 million rows, 2.60 GB (48.47 million rows/s., 1.26 GB/s.)

expected:
select max(d) from T  where some_col = 'updated';
Elapsed: 0.202 sec. Processed 100.00 million rows, 1.80 GB (494.28 million rows/s., 8.90 GB/s.)

```

2021-01-21 17:46 UTC, Avogar commented
> hm, I don't see much improvement:
 Yes, you're right. I forgot to add parallel select in this case. I added it here https://github.com/ClickHouse/ClickHouse/pull/19375