Auto-balance big parts in JBOD array
ClickHouse/ClickHouse pull request #16481
Opened 2020-10-28 15:24 UTC by amosbird

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

JBOD volume is notorious in that only a small subset of disks can be fully utilized for a given query. This PR focuses on a particular common sceniaro: partition-wise queries. Now big new parts are assigned to different disks of a JBOD volume in a balanced way.  
A new merge tree setting `min_bytes_to_rebalance_partition_over_jbod` is introduced to define "big".

TODO

- ReplicatedMergeTree's fetch part and merge log entry
- Other actions related to part/partition movements

It might be useful for https://github.com/ClickHouse/ClickHouse/issues/16300 .

Detailed description / Documentation draft:

TODO

2021-02-19 10:19 UTC, amosbird commented
@azat  Another uncaught exception from dtor. Please take a look.  https://clickhouse-test-reports.s3.yandex.net/16481/5d150cce4778dd14f58dcff67435bdec1efa155b/stress_test_(thread).html#fail1

2021-02-19 19:03 UTC, azat commented
>@azat Another uncaught exception from dtor. Please take a look. https://clickhouse-test-reports.s3.yandex.net/16481/5d150cce4778dd14f58dcff67435bdec1efa155b/stress_test_(thread).html#fail1

Here is another patch - #20981

2021-02-23 17:10 UTC, amosbird commented
Test failure looks unrelated https://clickhouse-test-reports.s3.yandex.net/16481/605dd9a971d72c91a721148e0c489c08dd4f86c7/integration_tests_(thread)/integration_run_test_storage_kafka_test_py_1.txt.out.log

2021-02-24 13:26 UTC, alesapin requested changes
Maybe I'm a little confused, but we just have three types of parts:
1) Existing parts.
2) Currently merging source parts that will become outdated (included in 1).
3) Currently merging parts that will be added as a result of the merge.

For each new merged/fetched part we are trying to find a disk that has a minimum size of data in the same partition. So we just summing sizes by a disk of all existing parts from this same partition excluding parts 2) and adding parts 3). After that, we choose the smallest occupied disk.

The code looks slightly more complicated :)

Btw, how it will work with background moves? Also without tests merge is impossible.

2021-02-24 13:26 UTC, alesapin commented on src/Storages/MergeTree/MergeTreeData.cpp
> +            auto lock_parts = lockParts();
Maybe we should move this lock into `if (covered_parts.empty())`?

2021-02-24 13:26 UTC, alesapin commented on src/Storages/MergeTree/MergeTreeData.cpp
> +                merging_parts.insert(part->name);
Why they are already not here? Ho we can have covered parts which are not in `currently_submerging_parts`? Also why we don't check?
```
part->isStoredOnDisk() && part->getBytesOnDisk() >= min_bytes_to_rebalance_partition_over_jbod
                && part_info.partition_id == part->info.partition_id
```

2021-02-24 13:26 UTC, alesapin commented on src/Storages/MergeTree/MergeTreeData.cpp
> +            if (big_parts.find(name) == big_parts.end())
Again, no checks -- maybe this part from a different partition or small?

2021-02-24 13:26 UTC, alesapin commented on src/Storages/MergeTree/MergeTreeData.cpp
> +        std::map<String, std::vector<String>> disk_parts;
Add a comment: "Used only for logging"

2021-02-24 13:26 UTC, alesapin commented on src/Storages/MergeTree/MergeTreeData.cpp
> +                merging_parts.insert(part->name);
`big_submerging_parst_from_partition`?

2021-02-24 13:26 UTC, alesapin commented on src/Storages/MergeTree/MergeTreeData.cpp
> +        std::map<String, size_t> disk_occupation;
Why `map` and not `unordered_map`?

2021-02-24 15:25 UTC, amosbird commented on src/Storages/MergeTree/MergeTreeData.cpp
> +        std::map<String, size_t> disk_occupation;
Disk names are usually sorted.

2021-03-08 04:21 UTC, amosbird commented on src/Storages/MergeTree/MergeTreeData.cpp
> +            LOG_WARNING(log, "currently_submerging_parts is missing parts. JBOD might lose balance");
Fixed

2021-03-08 04:21 UTC, amosbird commented on src/Storages/MergeTree/MergeTreeData.h
> +    /// Parts that currently submerging (merging to bigger parts) or emerging
They will be outdate after the merge is complete.

2021-03-08 04:21 UTC, amosbird commented on src/Storages/MergeTree/MergeTreeData.h
> +    std::map<String, EmergingPartInfo> currently_emerging_parts;
Done.

2021-03-08 04:21 UTC, amosbird commented on src/Storages/MergeTree/MergeTreeData.h
> +    String name;
done.

2021-03-08 04:21 UTC, amosbird commented on src/Storages/MergeTree/MergeTreeData.h
> +    MergeTreeData::DataPartsVector parts;
done.

2021-03-08 04:21 UTC, amosbird commented on src/Storages/MergeTree/registerStorageMergeTree.cpp
> +        if (storage_settings->min_bytes_to_rebalance_partition_over_jbod > 0
Done

2021-03-08 04:21 UTC, amosbird commented on src/Storages/StorageMergeTree.h
> +        std::optional<CurrentlySubmergingEmergingTagger> tagger;
Done.

2021-03-09 16:19 UTC, alesapin commented on src/Storages/MergeTree/MergeTreeData.cpp
> +            LOG_WARNING(log, "currently_submerging_big_parts doesn't contain part {} to erase. This is a bug", part->name);
Probably it should be LOGICAL_ERROR?

2021-03-09 16:20 UTC, alesapin commented on src/Storages/MergeTree/MergeTreeData.cpp
> +                writeString(fmt::format("  {}: [{}]\n", disk_name, boost::algorithm::join(per_disk_parts, ", ")), log_str);
btw, `fmt::join` looks prettier.

2021-03-09 16:21 UTC, alesapin commented on src/Storages/MergeTree/MergeTreeSettings.cpp
> +        && min_bytes_to_rebalance_partition_over_jbod < max_bytes_to_merge_at_max_space_in_pool / 1024)
what is 1024?

2021-03-09 16:21 UTC, amosbird commented on src/Storages/MergeTree/MergeTreeData.cpp
> +            LOG_WARNING(log, "currently_submerging_big_parts doesn't contain part {} to erase. This is a bug", part->name);
we cannot throw in dtor...

2021-03-09 16:28 UTC, amosbird commented on src/Storages/MergeTree/MergeTreeData.cpp
> +                writeString(fmt::format("  {}: [{}]\n", disk_name, boost::algorithm::join(per_disk_parts, ", ")), log_str);
nice

2021-03-09 18:56 UTC, amosbird commented on tests/integration/test_jbod_balancer/test.py
> +                node2.query("SYSTEM SYNC REPLICA tbl")
Add timeouts. We can safely ignore any exceptions. The test checks the final state of disk balance.

2021-03-11 09:27 UTC, alesapin approved these changes
Ok, quite isolated and useful code. Also, we have a setting that allows disabling this behavior.

2021-03-11 09:27 UTC, alesapin commented on src/Storages/MergeTree/MergeTreeSettings.h
> +    M(UInt64, min_bytes_to_rebalance_partition_over_jbod, 512 * 1024 * 1024, "Minimal amount of bytes to enable part rebalance over JBOD array (0 - disabled).", 0) \
Let's disable it by default.

2021-03-12 08:07 UTC, merged

2021-07-29 21:13 UTC, sevirov commented
Internal documentation ticket: DOCSUP-12425