Fixing the inability to deserialize AVRO into table if it contains LowCardinality columns
ClickHouse/ClickHouse pull request #16521
Opened 2020-10-29 17:28 UTC by myrrc

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fixes https://github.com/ClickHouse/ClickHouse/issues/16188
Now when parsing AVRO from input the LowCardinality is removed from type

2020-10-29 17:37 UTC, alexey-milovidov approved these changes

2020-10-29 17:37 UTC, alexey-milovidov requested changes
Need a test.

2020-10-29 18:30 UTC, alexey-milovidov approved these changes

2020-10-30 08:31 UTC, alesapin commented
`00840_long_concurrent_select_and_drop_deadlock` known flaky test

2020-10-30 08:31 UTC, merged