DOCSUP 3744: Update the SQL-statement CREATE TABLE
ClickHouse/ClickHouse pull request #16526
Opened 2020-10-29 17:52 UTC by antarctictardigrade

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Documentation for #15823.

2020-11-05 20:33 UTC, alexey-milovidov commented on docs/en/sql-reference/statements/create/table.md
> +Both of these syntaxes are valid when creating a primary key with only one field.
It also works with several fields.

2020-11-05 20:33 UTC, alexey-milovidov commented on docs/en/sql-reference/statements/create/table.md
> +You can also define a `PRIMARY KEY` constraint on multiple columns.
It's not a constraint.

2020-11-05 20:34 UTC, alexey-milovidov requested changes
.

2020-11-06 08:10 UTC, closed without merging

2020-11-06 08:10 UTC, BayoNet commented
I think we need just close this PR.
Another person will do this task.