better change the config
ClickHouse/ClickHouse pull request #16630
Opened 2020-11-03 09:34 UTC by sundy-li

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
 
- Improvement
 

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

None.

Detailed description / Documentation draft:

Better change the config as PR #16627  did after discussing with @amosbird 

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

2020-11-03 09:40 UTC, amosbird approved these changes

2020-11-03 09:47 UTC, amosbird requested changes

2020-11-03 09:47 UTC, amosbird commented on tests/integration/test_reload_zookeeper/test.py
>          config.close()
It should be removed too.

2020-11-03 09:47 UTC, amosbird commented on tests/integration/test_reload_zookeeper/test.py
>          config.close()
So as `ZK_CONFIG_PATH` and `SCRIPT_DIR`

2020-11-03 10:12 UTC, sundy-li commented on tests/integration/test_reload_zookeeper/test.py
>          config.close()
yes

2020-11-04 08:36 UTC, alexey-milovidov approved these changes

2020-11-04 08:36 UTC, merged