fix Aggregation Function not found error after #16123
ClickHouse/ClickHouse pull request #16774
Opened 2020-11-07 04:18 UTC by ucasFL

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Continue of [#16123](https://github.com/ClickHouse/ClickHouse/pull/16123)

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

2020-11-07 10:30 UTC, alexey-milovidov commented on src/Interpreters/TreeRewriter.cpp
> +                func.name = Poco::toLower(func.name) + customized_func_suffix;
This is strange, because we have non-lowercase names, e.g. sumWithOverflow.

2020-11-07 10:30 UTC, alexey-milovidov requested changes
.

2020-11-08 13:21 UTC, ucasFL commented
The problem `MAXOrNull` doesn't work is because that combinators doesn't apply for case insensitive names currently, only for native names, can we cancel this constraint or we shoule keep it? @alexey-milovidov

2020-11-08 14:26 UTC, alexey-milovidov commented
@ucasFL Yes, let's cancel this constraint.

2020-11-12 10:50 UTC, alexey-milovidov approved these changes

2020-11-12 10:50 UTC, merged