[In progress] DOCSUP-3122: Document two expression ALTER
ClickHouse/ClickHouse pull request #17059
Opened 2020-11-16 09:28 UTC by AnaUvarova

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:

- Documentation for #14742

2020-12-15 17:31 UTC, BayoNet commented on docs/en/sql-reference/statements/alter/column.md
> +```
It looks like these lines are not required for the description.

2020-12-18 01:04 UTC, olgarev commented on docs/en/sql-reference/statements/alter/ttl.md
> +
## REMOVE TTL {#remove-ttl}

# missed in anchor

2020-12-18 01:07 UTC, olgarev commented on docs/en/sql-reference/statements/alter/column.md
> +
Missed anchor here

2020-12-18 01:08 UTC, olgarev commented on docs/ru/sql-reference/statements/alter/column.md
> +
Missed anchor here

2020-12-18 01:08 UTC, olgarev commented on docs/ru/sql-reference/statements/alter/ttl.md
> +
"#" missed in anchor. Should be {#remove-ttl}

2020-12-22 10:59 UTC, alesapin requested changes

2020-12-22 10:59 UTC, alesapin commented on docs/en/sql-reference/statements/alter/ttl.md
> +OPTIMIZE TABLE table_with_ttl FINAL;
No table definition and now info about data. How reader can guess it?

2020-12-22 10:59 UTC, alesapin commented on docs/en/sql-reference/statements/alter/ttl.md
> +--2020-12-11 12:44:57    1       username1
Comments `--`?

2020-12-22 10:59 UTC, alesapin commented on docs/en/sql-reference/statements/alter/ttl.md
> +2020-12-11 12:44:57    1       username1
Need formatted output, not tab separated.

2020-12-22 10:59 UTC, alesapin commented on docs/en/sql-reference/statements/alter/ttl.md
> +And now we have nothing to delete.
Now TTL removed and nothing will be deleted.

2020-12-22 10:59 UTC, alesapin commented on docs/en/sql-reference/statements/alter/ttl.md
> +To start the background cleaning using TTL, make this:
Trigger TTL forcefully with OPTIMIZE query.

2020-12-27 06:02 UTC, olgarev commented on docs/en/sql-reference/statements/alter/ttl.md
> +
missed ; at the end

2020-12-31 10:58 UTC, AnaUvarova commented
@alesapin 
Hello, Alexander, please take a look.

2021-01-12 11:04 UTC, alesapin approved these changes

2021-01-12 11:04 UTC, merged