introduce zstd compression
ClickHouse/ClickHouse pull request #17144
Opened 2020-11-17 16:06 UTC by fibersel

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
add ```*.zst``` compression/decompression support.It enables using ```*.zst``` in ```file()``` function and ```Content-encoding: zstd``` in http.This closes [#16791 ](https://github.com/ClickHouse/ClickHouse/issues/16791)

2020-11-19 21:32 UTC, nikitamikhaylov commented
JFYI: You can write `git commit --allow-empty -m 'Bump'`

2020-11-20 22:42 UTC, fibersel commented
@alexey-milovidov @akuzm Can someone merge or review this MR?
It seems that fallen test don't belong to my MR.

2020-11-23 04:05 UTC, alexey-milovidov reviewed
How we can control compression level when data is compressed in HTTP interface or when file is written?

For ZLib it's controlled by `http_zlib_compression_level` but:
- there are no such settings for xz, br, zst...
- there is no way to control it for files.

We can think of it and make changes in another PR.

2020-11-23 04:06 UTC, alexey-milovidov commented on src/IO/CompressionMethod.h
> +    ///  This option corresponds to HTTP Content-Encoding: zstd
zst?

2020-11-23 04:09 UTC, alexey-milovidov commented on src/Server/HTTPHandler.cpp
> +        used_output.out_maybe_delayed_and_compressed
Formatted code is obviously worse but it's passable.

2020-11-23 04:12 UTC, alexey-milovidov commented on src/IO/ZstdDeflatingWriteBuffer.h
> +    /// Flush all pending data and write zlib footer to the underlying buffer.
Wrong copy-pasted comment (zlib).

2020-11-23 04:14 UTC, alexey-milovidov commented on src/IO/ZstdDeflatingWriteBuffer.cpp
> +    ZSTD_CCtx_setParameter(cctx, ZSTD_c_compressionLevel, compression_level);
These functionc can also return errors.

2020-11-23 04:16 UTC, alexey-milovidov commented on src/IO/ZstdDeflatingWriteBuffer.cpp
> +    bool last_chunk = hasPendingData();
Difficult to understand the meaning of this variable.
How it's possible that "if there is more data it is the last chunk"?

2020-11-23 04:16 UTC, alexey-milovidov commented on src/IO/ZstdDeflatingWriteBuffer.cpp
> +    bool last_chunk = hasPendingData();
Do we have a test with more than 1MB of data?

2020-11-23 04:17 UTC, alexey-milovidov requested changes
Minor changes needed.

2020-11-29 11:33 UTC, alexey-milovidov commented
It is almost ready.

2020-11-30 07:23 UTC, troll2016 commented
> Changelog category (leave one):
> 
>     * New Feature
> 
> 
> Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
> add `*.zst` compression/decompression support.It enables using `*.zst` in `file()` function and `Content-encoding: zstd` in http client.This closes [#16791 ](https://github.com/ClickHouse/ClickHouse/issues/16791)

that`s great!!!

2020-12-02 19:41 UTC, alexey-milovidov approved these changes

2020-12-02 19:41 UTC, merged

2021-08-19 18:41 UTC, bharatnc commented on tests/queries/0_stateless/01059_storage_file_brotli.sql
> +INSERT INTO file SELECT * FROM numbers(1000000);
@evillique I've noticed this behavior (before as well while I was doing the initial implementation) where inserting into file / table with large number of rows causes the query to hang. So I added this test (similar to other compression methods) to confirm and it still hangs according to my local test.

Can also reproduce using (query never completes):

```
tower :) insert into function file('test2.lz4', 'TSV', 'number UInt64', 'lz4') select * from numbers(0,1000000);

INSERT INTO FUNCTION file('test2.lz4', 'TSV', 'number UInt64', 'lz4') SELECT *
FROM numbers(0, 1000000)

Query id: 3fa90fbe-9bab-4d92-9aaf-79763ddc5de1

→ Progress: 1.00 million rows, 8.00 MB (9.12 million rows/s., 72.99 MB/s.)  99%
```