DOCSUP-4706 edit and translate
ClickHouse/ClickHouse pull request #17942
Opened 2020-12-09 18:22 UTC by damozhaeva

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Documentation (changelog entry is not required)

Detailed description / Documentation draft:

- edit the Russian version of the text
- translate the text to English

2020-12-10 20:41 UTC, adevyatova commented on docs/ru/operations/system-tables/errors.md
> +-   `value` ([UInt64](../../sql-reference/data-types/int-uint.md)) — число, возникающих ошибок.
```suggestion
-   `value` ([UInt64](../../sql-reference/data-types/int-uint.md)) — количество ошибок.
```

2020-12-10 20:41 UTC, adevyatova commented on docs/ru/sql-reference/data-types/date.md
> +**1.** Создание таблицы со столбцом типа `DateTime` и добавление в неё данных:
Эта фраза избыточна. И к тому же, неправильная) Столбец в таблице имеет тип Date.

2020-12-10 22:40 UTC, alexey-milovidov commented on docs/en/operations/settings/settings.md
> +Minimum query execution time to navigate to the following tables:
Wrong.

2020-12-10 22:40 UTC, alexey-milovidov requested changes
.

2020-12-11 07:23 UTC, adevyatova commented on docs/en/operations/settings/settings.md
> +Minimum query execution time to navigate to the following tables:
@azat Fix it, please!

2020-12-12 00:05 UTC, azat commented on docs/en/operations/settings/settings.md
> +Minimum query execution time to navigate to the following tables:
```suggestion
If enabled (non-zero), queries faster then the value of this setting will not be logged (you can think about this as a `long_query_time` for [MySQL Slow Query Log](https://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html)), and this basically means that you will not find them in the following tables:
```

P.S. not sure that information about mysql should be included though

2020-12-30 14:08 UTC, alexey-milovidov commented on docs/ru/sql-reference/functions/hash-functions.md
> +Создает 64-битное значение [FarmHash](https://github.com/google/farmhash) или значение Fingerprint. `farmFingerprint64` предпочтительнее для стабильных и перемещаемых значений.
The words are very wrong.

2020-12-30 14:12 UTC, merged