DOCSUP-4712 Transferred system.metric_log description  to another page
ClickHouse/ClickHouse pull request #18102
Opened 2020-12-15 15:00 UTC by AnaUvarova

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category 
- Documentation for #6467

2020-12-20 19:46 UTC, alexey-milovidov requested changes
It is enabled by default long time ago.
Now the user don't have to enable it but can possibly disable.

2020-12-21 11:43 UTC, AnaUvarova commented
@alexey-milovidov 

Hi, Alexey. Okay, what should the user do to disable it?

We can rewrite the text so:
- the setting is enabled by default;
- the user can enable it manually (in a case of something) by described manipulations.
- how to disable and when it is needed to be done?

> It is enabled by default long time ago.
> Now the user don't have to enable it but can possibly disable.

2020-12-28 06:00 UTC, olgarev commented
@alexey-milovidov Hi, can you, please, answer the question above? Do we need to describe when and how this feature can be disabled?

2020-12-28 13:49 UTC, AnaUvarova commented
> @alexey-milovidov Hi, can you, please, answer the question above? Do we need to describe when and how this feature can be disabled?

@olgarev 
Привет! Есть инфа от Никиты "выключить можно в config.xml просто  закомментировав все что связано с metric_log", но мне кажется, что этого может не хватит для красивой инструкции. Как думаешь?

2020-12-28 22:33 UTC, olgarev commented
> @olgarev
> Привет! Есть инфа от Никиты "выключить можно в config.xml просто закомментировав все что связано с metric_log", но мне кажется, что этого может не хватит для красивой инструкции. Как думаешь?

@AnaUvarova Привет. Да нет, по-моему норм )

2020-12-29 06:21 UTC, filimonov commented
Да, можно просто закомментировать, но best practice - это не менять конфигурационные файлы поставляемые с дистрибутивом, а производить все изменения добавляя отдельные файлы для настройки того или иного или иного поведения. 

Например, в этом случае можно создать файл 
`/etc/clickhouse-server/config.d/disable_metric_log.xml`

Со следующим содержимым:
```xml
<yandex>
<metric_log remove="1" />
</yandex>
```

2020-12-31 00:29 UTC, merged