DOCSUP-4617: Document the union_default_mode setting
ClickHouse/ClickHouse pull request #18153
Opened 2020-12-16 17:09 UTC by sevirov

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:

- Documentation for #16338

2020-12-20 09:12 UTC, olgarev commented on docs/ru/sql-reference/statements/select/union-all.md
> +
"будет сгенерировано" вместо "сгенерируется"?

2020-12-20 17:34 UTC, sevirov commented
@akuzm Please, review this PR.

2020-12-20 19:40 UTC, alexey-milovidov commented on docs/en/operations/settings/settings.md
> +Sets a special mode for combining `SELECT` query results using the [UNION](../../sql-reference/statements/select/union-all.md) expression.
Nothing special with this mode.

2020-12-20 19:42 UTC, alexey-milovidov commented on docs/en/operations/settings/settings.md
> +Sets a special mode for combining `SELECT` query results using the [UNION](../../sql-reference/statements/select/union-all.md) expression.
It should be highlighted that it relates only to UNION without explicit UNION ALL or UNION DISTINCT specification.

2020-12-20 19:43 UTC, alexey-milovidov commented on docs/ru/sql-reference/statements/select/union-all.md
> +# Секция UNION {#union-clause}
Надо переписать - пусть будет всё про одну секцию UNION, которая специфицируется с помощью указания ALL или DISTINCT.

2020-12-20 19:43 UTC, alexey-milovidov requested changes
ю

2020-12-27 10:26 UTC, sevirov commented
@alexey-milovidov Please, review this PR.

2020-12-29 17:31 UTC, alexey-milovidov commented on docs/en/sql-reference/statements/select/union.md
> +Queries that are parts of `UNION` can’t be enclosed in round brackets. [ORDER BY](../../../sql-reference/statements/select/order-by.md) and [LIMIT](../../../sql-reference/statements/select/limit.md)
Now they can.

```
(SELECT 1 UNION SELECT 2) UNION (SELECT 3 UNION SELECT 2);
```

2020-12-29 21:52 UTC, sevirov commented
@alexey-milovidov Please, check this PR. I fixed it.

2020-12-30 14:01 UTC, alexey-milovidov approved these changes

2020-12-30 14:01 UTC, alexey-milovidov commented
Perftect.

2020-12-30 14:01 UTC, merged

2020-12-30 14:02 UTC, alexey-milovidov commented
I decided to make a change in https://github.com/ClickHouse/ClickHouse/pull/18615 and has reflected it in the docs.