Disallow floating point as partition key
ClickHouse/ClickHouse pull request #18464
Opened 2020-12-24 10:35 UTC by hexiaoting

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Disallow floating point column as partition key
related to : https://github.com/ClickHouse/ClickHouse/issues/18421#event-4147046255

2020-12-24 17:11 UTC, alexey-milovidov commented on src/Storages/MergeTree/registerStorageMergeTree.cpp
> +            throw Exception("Donot support float point as partition key: " + metadata.partition_key.column_names[i], ErrorCodes::BAD_ARGUMENTS);
If should be allowed to ATTACH table even with bad partition key
(so the server can startup after version update).

See args.attach.

2020-12-24 17:13 UTC, alexey-milovidov commented on src/Storages/MergeTree/registerStorageMergeTree.cpp
> +        if (strncmp(data_types[i]->getFamilyName(), "Float", 5) == 0)
strncmp is not the best way to check.
See IDataType.h, isFloat().

2020-12-24 17:14 UTC, alexey-milovidov requested changes
.

2020-12-28 13:33 UTC, alexey-milovidov commented
@hexiaoting One test should be adjusted.

We have two ways to do it:
1. Introduce a setting `allow_floating_point_partition_key`, 0 by default. Set it to 1 in this test. The setting will be also useful for some special cases.
2. Change `/` operator to `intDiv` in the test.

2020-12-29 03:15 UTC, hexiaoting commented
I will add this setting in MergeTreeSetting, not added in system setting.
Because I think this setting is only used at the time of create a Storage. Is that OK?

2020-12-29 09:55 UTC, alexey-milovidov commented
Yes, it will be perfect.

2021-01-09 21:13 UTC, alexey-milovidov commented
@hexiaoting It is almost ready to merge.

2021-01-11 02:18 UTC, hexiaoting commented
> @hexiaoting It is almost ready to merge.

yes, the setting is already added.

2021-01-11 05:25 UTC, alexey-milovidov commented
One existing test has to be adjusted...

2021-01-12 02:22 UTC, hexiaoting commented
@alexey-milovidov ready to merge

2021-01-12 10:08 UTC, merged