Merging geometry functions
ClickHouse/ClickHouse pull request #19257
Opened 2021-01-18 23:52 UTC by nikitamikhaylov

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

#11871

2021-01-21 10:21 UTC, nikitamikhaylov commented
Need to get rid of `std::stringstream` and add `GeographicPoint` support in every possible function. Also need to do some cosmetics.

2021-02-10 18:54 UTC, nikitamikhaylov commented
I benchmarked a function for area calculation in comparison to Postgis. Hopefully, there will be some benchmarks for all of functions in the near future.

Dataset
https://datahub.io/core/geo-countries#readme

```python
from shapely.geometry import shape
import geojson
import wget

url = 'https://datahub.io/core/geo-countries/r/countries.geojson'
#dataset = wget.download(url)

with open("countries.geojson") as f:
    gj = geojson.load(f)

fout1 = open("polygons.txt", 'w')
fout2 = open("multipolygons.txt", 'w')

for i in list(gj["features"]):
    wkt = shape(i["geometry"])
    if i["geometry"]["type"] == 'Polygon':
        print(i["properties"]["ADMIN"], wkt, file = fout1, sep='\t')
    if i["geometry"]["type"] == 'MultiPolygon':
        print(i["properties"]["ADMIN"], wkt, file = fout2, sep='\t')
```

Posgres: 
```sql
create table polygons_wkt(name TEXT primary key, p TEXT);
COPY polygons_wkt FROM '/home/jakalletti/geometry/polygons.tsv' DELIMITER E'\t'
```

# Polygons

<details><summary>ClickHouse with output</summary>

```sql
jakalletti-build.sas.yp-c.yandex.net :) SELECT name, polygonAreaGeographic([readWktPolygon(p)]) from polygons_wkt;

SELECT
    name,
    polygonAreaGeographic([readWktPolygon(p)])
FROM polygons_wkt

Query id: e38d9fd9-b572-48b9-ab4c-694a249919f0

┌─name──────────────────────────────┬─polygonAreaGeographic(array(readWktPolygon(p)))─┐
│ Aruba                             │                              169577139.16965556 │
│ Afghanistan                       │                               642167900272.3896 │
│ Albania                           │                              28333199144.361954 │
│ Andorra                           │                               452435116.3027964 │
│ Ashmore and Cartier Islands       │                               2696604.934766531 │
│ Austria                           │                               83991121319.18462 │
│ Burundi                           │                              27040491570.295235 │
│ Belgium                           │                              30672391955.146103 │
│ Benin                             │                               116112410615.0725 │
│ Burkina Faso                      │                                272767288590.487 │
│ Bulgaria                          │                              112764344223.58502 │
│ Bahrain                           │                               585431263.0854981 │
│ Bosnia and Herzegovina            │                               51828357828.41153 │
│ Bajo Nuevo Bank (Petrel Is.)      │                              29452.023965717835 │
│ Saint Barthelemy                  │                              24595825.379134282 │
│ Belarus                           │                                207495810105.695 │
│ Bolivia                           │                              1086795900906.9669 │
│ Barbados                          │                               444196434.0171095 │
│ Bhutan                            │                               40362932122.31417 │
│ Botswana                          │                               579022741098.7659 │
│ Central African Republic          │                                 617982165547.58 │
│ Switzerland                       │                               41437057065.91086 │
│ Clipperton Island                 │                               5042420.197242386 │
│ Cameroon                          │                              464311319438.72986 │
│ Republic of Congo                 │                               344887275569.6976 │
│ Coral Sea Islands                 │                              20628.814559882598 │
│ Curaçao                           │                              463207585.46491855 │
│ Czech Republic                    │                                78760344674.6365 │
│ Djibouti                          │                               21846149321.62891 │
│ Dominica                          │                               730475415.6568394 │
│ Algeria                           │                              2308849474058.0337 │
│ Dhekelia Sovereign Base Area      │                              127533079.61976177 │
│ Ethiopia                          │                               1127370045816.251 │
│ Georgia                           │                                69572475312.1097 │
│ Ghana                             │                               238667399375.4801 │
│ Gibraltar                         │                               3831411.425579383 │
│ Guinea                            │                              244302369135.70804 │
│ Gambia                            │                               10500266198.29552 │
│ Guatemala                         │                              108814357554.73698 │
│ Guam                              │                               564430992.5413051 │
│ Heard Island and McDonald Islands │                               395072268.1670339 │
│ Hungary                           │                               93204530860.01508 │
│ Isle of Man                       │                                574622349.494572 │
│ Iraq                              │                               437362923805.3326 │
│ Israel                            │                              21904844963.118687 │
│ Jamaica                           │                              11032909044.896214 │
│ Jersey                            │                              119197004.74155779 │
│ Jordan                            │                               88852268129.02553 │
│ Baykonur Cosmodrome               │                               6501480908.525035 │
│ Siachen Glacier                   │                              2088368280.5907485 │
│ Kyrgyzstan                        │                              198994443084.13907 │
│ Kosovo                            │                              10914986098.918686 │
│ Laos                              │                              228111317610.61636 │
│ Lebanon                           │                               9999649537.471163 │
│ Liberia                           │                               95296808053.31958 │
│ Libya                             │                              1623756106733.3518 │
│ Saint Lucia                       │                               604940965.7688961 │
│ Liechtenstein                     │                              136883538.31794572 │
│ Lesotho                           │                              30106906646.093895 │
│ Luxembourg                        │                                2607643781.07639 │
│ Latvia                            │                               64575248440.99925 │
│ Saint Martin                      │                               68198732.01942295 │
│ Morocco                           │                               591718146420.7856 │
│ Monaco                            │                              18750590.193543613 │
│ Moldova                           │                               33208636034.02909 │
│ Macedonia                         │                              25384586732.242413 │
│ Mali                              │                              1252723270893.3118 │
│ Montenegro                        │                               13729482553.35579 │
│ Mongolia                          │                              1564646094140.0706 │
│ Montserrat                        │                               99396603.21229354 │
│ Namibia                           │                               822688081865.0507 │
│ Niger                             │                              1181298791018.5469 │
│ Norfolk Island                    │                                41003910.8372144 │
│ Niue                              │                              220827518.96565723 │
│ Nepal                             │                               147103938328.7791 │
│ Nauru                [...]

2021-02-11 15:56 UTC, nikitamikhaylov commented
:(

```sql
jakalletti-build.sas.yp-c.yandex.net :) select c, d, polygonsIntersectionGeographic(readWktMultiPolygon(a), readWktMultiPolygon(b)) from (select first.p as a, second.p as b, first.name as c, second.name as d from multipolygons_wkt as first cross join multipolygons_wkt as second limit 100) format Null;

SELECT
    c,
    d,
    polygonsIntersectionGeographic(readWktMultiPolygon(a), readWktMultiPolygon(b))
FROM 
(
    SELECT
        first.p AS a,
        second.p AS b,
        first.name AS c,
        second.name AS d
    FROM multipolygons_wkt AS first
    CROSS JOIN multipolygons_wkt AS second
    LIMIT 100
)
FORMAT Null

Query id: 9836f89d-de0f-4af5-9e79-af49fe077e78

Ok.

0 rows in set. Elapsed: 9.559 sec. 
```


```sql
postgres@jakalletti-build:~$ psql -d postgis_db <<<"\timing on                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
\set ECHO queries                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select c, d, ST_Intersection(ST_GeomFromText(a), ST_GeomFromText(b)) from (select first.p as a, second.p as b, first.name as c, second.name as d from multipolygons_wkt as first cross join multipolygons_wkt as second limit 100) as subjuery;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
Timing is on.    

...

Time: 439.511 ms
```

2021-02-12 13:06 UTC, nikitamikhaylov commented
![image](https://user-images.githubusercontent.com/25705399/107771759-48210e00-6d4c-11eb-883a-a9db4a1b02b4.png)

2021-02-18 12:11 UTC, kitaisreal commented on src/DataTypes/DataTypeCustomGeo.cpp
> +    static const auto data_type = std::make_shared<const DataTypeTuple>(
Consider to use global constant.

2021-02-18 12:12 UTC, kitaisreal commented on src/DataTypes/DataTypeCustomGeo.cpp
> +    static auto data_type = std::make_shared<const DataTypeArray>(DataTypeCustomPointSerialization::nestedDataType());
Consider to use global constant.

2021-02-18 12:12 UTC, kitaisreal commented on src/DataTypes/DataTypeCustomGeo.cpp
> +    static auto data_type = std::make_shared<const DataTypeArray>(DataTypeCustomRingSerialization::nestedDataType());
Consider to use global constant.

2021-02-18 12:12 UTC, kitaisreal commented on src/DataTypes/DataTypeCustomGeo.cpp
> +    static auto data_type = std::make_shared<const DataTypeArray>(DataTypeCustomPolygonSerialization::nestedDataType());
Consider to use global constant.

2021-02-18 12:17 UTC, kitaisreal commented on src/Functions/geometryConverters.h
> +namespace bg = boost::geometry;
Consider to remove from .h file.

2021-02-18 12:30 UTC, kitaisreal commented on src/Functions/geometryConverters.h
> +    typename std::enable_if_t<std::is_same_v<Q, CartesianPoint>, CartesianGeometry> createContainer() const
using Container = std::conditional_t<std::is_same_v<PointType, CartesianPoint>,  CartesianGeometry, GeographicGeometry>;

2021-02-18 12:32 UTC, kitaisreal commented on src/Functions/geometryConverters.h
> +        const auto & tuple = dynamic_cast<const ColumnTuple &>(*col_);
PointFromColumnParser use type_id cast or assert_cast.

2021-02-18 12:33 UTC, kitaisreal commented on src/Functions/geometryConverters.h
> +        , offsets(static_cast<const ColumnArray &>(*col_).getOffsets())
Consider to use assert_cast.

2021-02-18 12:34 UTC, kitaisreal commented on src/Functions/geometryConverters.h
> +        , offsets(static_cast<const ColumnArray &>(*col_).getOffsets())
Consider to use assert_cast.

2021-02-18 12:42 UTC, kitaisreal commented on src/Functions/polygonArea.cpp
> +        auto res_column = ColumnFloat64::create();
Preallocate space using res_column->getData().reserve(input_rows_count).

2021-02-18 12:56 UTC, kitaisreal commented on src/Functions/geometryConverters.h
> +        size_t l = offsets[i - 1];
Check if i == 0;

2021-02-18 13:04 UTC, kitaisreal commented on src/Functions/geometryConverters.h
> +        get(boost::get<MultiPolygon<Point>>(container), i);
It will throw exception if container does not contain MultiPolygon<Point>.

2021-02-18 13:22 UTC, kitaisreal commented on src/Functions/geometryConverters.h
> +        if (isNaN(first[i]) || isNaN(second[i]))
Check for isInfinity ?

2021-02-18 13:23 UTC, kitaisreal commented on src/Functions/geometryConverters.h
> +        size_t l = offsets[i - 1];
Add check i == 0;

2021-02-18 14:07 UTC, kitaisreal requested changes
Consider to refactor parser interface.

2021-02-18 14:17 UTC, nikitamikhaylov commented on src/DataTypes/DataTypeCustomGeo.cpp
> +    static const auto data_type = std::make_shared<const DataTypeTuple>(
Fixed.

2021-02-18 14:18 UTC, nikitamikhaylov commented on src/DataTypes/DataTypeCustomGeo.cpp
> +    static auto data_type = std::make_shared<const DataTypeArray>(DataTypeCustomRingSerialization::nestedDataType());
Fixed.

2021-02-18 14:18 UTC, nikitamikhaylov commented on src/DataTypes/DataTypeCustomGeo.cpp
> +    static auto data_type = std::make_shared<const DataTypeArray>(DataTypeCustomPolygonSerialization::nestedDataType());
Fixed.

2021-02-18 14:18 UTC, nikitamikhaylov commented on src/DataTypes/DataTypeCustomGeo.cpp
> +    static auto data_type = std::make_shared<const DataTypeArray>(DataTypeCustomPointSerialization::nestedDataType());
Fixed.

2021-02-18 14:19 UTC, nikitamikhaylov commented on src/Functions/geometryConverters.h
> +namespace bg = boost::geometry;
Fixed.

2021-02-18 14:22 UTC, nikitamikhaylov commented on src/Functions/geometryConverters.h
> +    typename std::enable_if_t<std::is_same_v<Q, CartesianPoint>, CartesianGeometry> createContainer() const
Fixed.

2021-02-18 14:42 UTC, nikitamikhaylov commented on src/Functions/geometryConverters.h
> +        const auto & tuple = dynamic_cast<const ColumnTuple &>(*col_);
Fixed.

2021-02-18 14:47 UTC, nikitamikhaylov commented on src/Functions/geometryConverters.h
> +        , offsets(static_cast<const ColumnArray &>(*col_).getOffsets())
Used `typeid_cast` everywhere.

2021-02-18 14:47 UTC, nikitamikhaylov commented on src/Functions/geometryConverters.h
> +        , offsets(static_cast<const ColumnArray &>(*col_).getOffsets())
Used `typeid_cast` everywhere.

2021-02-19 18:08 UTC, nikitamikhaylov commented on src/Functions/polygonArea.cpp
> +        auto res_column = ColumnFloat64::create();
Fixed.

2021-02-19 18:09 UTC, nikitamikhaylov commented on src/Functions/geometryConverters.h
> +        get(boost::get<MultiPolygon<Point>>(container), i);
Deleted this code.

2021-02-19 18:09 UTC, nikitamikhaylov commented on src/Functions/geometryConverters.h
> +        if (isNaN(first[i]) || isNaN(second[i]))
Fixed.

2021-02-19 18:09 UTC, nikitamikhaylov commented on src/Functions/geometryConverters.h
> +        size_t l = offsets[i - 1];
Deleted this code.

2021-02-19 18:12 UTC, kitaisreal commented on src/Functions/describeGeometry.cpp
> +            {
Probably we should handle exceptions.

2021-02-19 18:24 UTC, alexey-milovidov commented on src/Functions/describeGeometry.cpp
> +            {
We can simply don't catch them.

2021-02-19 18:53 UTC, nikitamikhaylov commented on src/Functions/describeGeometry.cpp
> +            {
I will delete this function

2021-02-19 22:30 UTC, kitaisreal commented on src/Functions/polygonArea.cpp
> +            using TypeParser = std::decay_t<decltype(type)>;
Consider to use type adapter.

2021-02-19 22:49 UTC, nikitamikhaylov commented on src/Functions/polygonArea.cpp
> +            using TypeParser = std::decay_t<decltype(type)>;
Fixed.

2021-02-26 13:13 UTC, kitaisreal requested changes
Almost finished.

2021-02-26 13:13 UTC, kitaisreal commented on tests/queries/0_stateless/01303_polygons_equals.sql
> +select polygonsEqualsCartesian([[[(1., 1.),(1., 4.),(4., 4.),(4., 1.)]]], [[[(1., 1.),(1., 4.),(4., 4.),(4., 1.),(1., 1.)]]]);
No newline at end of file.

2021-02-26 13:13 UTC, kitaisreal commented on tests/queries/0_stateless/01306_polygons_intersection.sql
> +select polygonsIntersectionGeographic([[[(4.3613577, 50.8651821), (4.349556, 50.8535879), (4.3602419, 50.8435626), (4.3830299, 50.8428851), (4.3904543, 50.8564867), (4.3613148, 50.8651279)]]], [[[(4.
No newline at end of file.

2021-02-26 13:13 UTC, kitaisreal commented on tests/queries/0_stateless/01307_polygon_perimeter.sql
> +select polygonPerimeterCartesian([[[(0., 0.), (0., 5.), (5., 5.), (5., 0.), (0., 0.)]]]);
No newline at end of file.

2021-02-26 13:13 UTC, kitaisreal commented on tests/queries/0_stateless/01308_polygon_area.sql
> +SELECT polygonAreaCartesian([]); -- { serverError 36 }
No newline at end of file.

2021-02-26 13:13 UTC, kitaisreal commented on src/Functions/geometryConverters.cpp
> +std::vector<Polygon<Point>> PolygonFromColumnConverter<Point>::convert() const
Consider to make it static method because Converters does not have any state.

2021-02-26 13:13 UTC, kitaisreal commented on src/Functions/geometryConverters.h
> +#include <boost/variant.hpp>
Consider to remove boost variant.

2021-02-26 13:13 UTC, kitaisreal commented on src/Functions/geometryConverters.h
> +    friend class MultiPolygonFromColumnConverter<Point>;
Consider to remove friend.

2021-02-26 13:13 UTC, kitaisreal commented on src/Functions/readWkt.cpp
> +class FunctionReadWktPoint : public FunctionReadWkt<DataTypeCustomPointSerialization, CartesianPoint, PointSerializer<CartesianPoint>>
Consider to pass name to FunctionReadWkt without subclasses.

2021-02-26 13:13 UTC, kitaisreal commented on src/Functions/svg.cpp
> +            bool has_style = arguments.size() > 1;
Consider to move code that does not depends on Converter out of lambda.

2021-02-26 13:13 UTC, kitaisreal commented on src/Functions/svg.cpp
> +                std::stringstream str; // STYLE_CHECK_ALLOW_STD_STRING_STREAM
Consider to eliminate std::stringstream.

2021-02-26 13:13 UTC, kitaisreal commented on src/Functions/wkt.cpp
> +                std::stringstream str; // STYLE_CHECK_ALLOW_STD_STRING_STREAM
Consider to eliminate stringstream.

2021-02-26 13:46 UTC, nikitamikhaylov commented on src/Functions/geometryConverters.h
> +    ColumnFloat64::Container & first_container;
?

2021-02-27 01:00 UTC, hamedtayeban commented
12chzBKTn5pcj1GNvtVZriKgEQKEv2CKZe

2021-02-27 01:03 UTC, hamedtayeban commented
> 12chzBKTn5pcj1GNvtVZriKgEQKEv2CKZe

#11871

2021-03-01 21:44 UTC, hamedtayeban commented
#19257

2021-03-05 23:13 UTC, nikitamikhaylov commented
I had a talk with a teacher of geometry at Moscow State University and he told that there is no way to map a sphere to a plane map a sphere to a plane with the segments saved as is. Segments will map into straight lines or circular arcs always because of the curvature of the sphere. 
That's why I will revert all my commits with Mercator projection.

2021-03-12 14:03 UTC, kitaisreal approved these changes
LGTM

2021-03-12 14:05 UTC, nikitamikhaylov commented
Last commit contains only extra suppression for UBSan. Merge.

2021-03-12 14:05 UTC, merged