DOCSUP-4962: Documented support of WHERE and GROUP BY in TTL expressions
ClickHouse/ClickHouse pull request #19519
Opened 2021-01-23 18:26 UTC by olgarev

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Documentation for #10537

2021-01-28 00:53 UTC, olgarev commented
@CurtizJ Hi, will you review this, pls?

2021-01-28 14:03 UTC, CurtizJ requested changes

2021-02-01 23:50 UTC, olgarev commented
@CurtizJ Hi, thank you for the review, I've made the changes. OK now?

2021-02-02 11:39 UTC, CurtizJ approved these changes

2021-02-02 11:39 UTC, merged