DOCSUP-3539 Отработать замечания по переводу
ClickHouse/ClickHouse pull request #20190
Opened 2021-02-07 17:52 UTC by damozhaeva

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Documentation (changelog entry is not required)

Detailed description / Documentation draft:

- edit the Russian version of the text
- translate the text to English

2021-02-08 08:16 UTC, qoega requested changes

2021-02-08 08:16 UTC, qoega commented on docs/ru/operations/settings/settings.md
> +ППозволяет изменить кодировку, которая используется для рисования таблицы при выводе результатов запросов. Доступны следующие кодировки: UTF-8, ASCII.
```suggestion
Позволяет изменить кодировку, которая используется для отрисовки таблицы при выводе результатов запросов. Доступны следующие кодировки: UTF-8, ASCII.
```

2021-02-08 08:16 UTC, qoega commented on docs/en/operations/settings/settings.md
> +>>>>>>> 6325b15a63335e2efd7de1ae92d2907493a07a9c
Not ready to merge

2021-02-08 08:16 UTC, qoega commented on docs/en/operations/settings/settings.md
> +>>>>>>> 547db452d63ba42b88e82cbe9a2aa1f5c683403f
Not ready to merge

2021-02-08 08:16 UTC, qoega commented on docs/en/operations/settings/settings.md
> +>>>>>>> 6325b15a63335e2efd7de1ae92d2907493a07a9c
Not ready to merge

2021-02-08 08:16 UTC, qoega commented on docs/en/operations/settings/settings.md
> +=======
Not ready to merge

2021-02-08 08:16 UTC, qoega commented on docs/en/operations/settings/settings.md
> +>>>>>>> 6325b15a63335e2efd7de1ae92d2907493a07a9c
Not ready to merge

2021-02-08 08:16 UTC, qoega commented on docs/en/operations/settings/settings.md
> +>>>>>>> 6325b15a63335e2efd7de1ae92d2907493a07a9c
Not ready to merge

2021-02-16 12:46 UTC, nikitamikhaylov approved these changes

2021-02-16 12:47 UTC, merged