DOCSUP-6294: Document the parseDateTimeBestEffortUSOrZero and parseDateTimeBestEffortUSOrNull functions
ClickHouse/ClickHouse pull request #20294
Opened 2021-02-10 19:05 UTC by sevirov

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:

- Documentation for #19712

2021-02-15 05:23 UTC, olgarev commented on docs/en/sql-reference/functions/type-conversion-functions.md
> +parseDateTimeBestEffortUSOrNull(time_string [, time_zone]);
```suggestion
parseDateTimeBestEffortUSOrNull(time_string [, time_zone])
```

2021-02-15 05:24 UTC, olgarev commented on docs/en/sql-reference/functions/type-conversion-functions.md
> +-   `time_string` — String containing a date and time to convert. [String](../../sql-reference/data-types/string.md).
```suggestion
-   `time_string` — Date and time to convert. [String](../../sql-reference/data-types/string.md).
```

2021-02-15 05:28 UTC, olgarev commented on docs/en/sql-reference/functions/type-conversion-functions.md
> +-   `time_zone` — Time zone. The function parses `time_string` according to the time zone. [String](../../sql-reference/data-types/string.md).
```suggestion
-   `time_zone` — [Timezone](../../operations/server-configuration-parameters/settings.md#server_configuration_parameters-timezone). The function parses `time_string` according to the time zone. [String](../../sql-reference/data-types/string.md).
```

2021-02-15 05:31 UTC, olgarev commented on docs/en/sql-reference/functions/type-conversion-functions.md
> +-   A string that includes the date and time along with time zone offset information: `YYYY-MM-DD hh:mm:ss ±h:mm`, etc. For example, `2020-12-12 17:36:00 -5:00`.
```suggestion
-   A string containing 9..10 digits [unix timestamp](https://en.wikipedia.org/wiki/Unix_time).
-   A string with a date and a time components: `YYYYMMDDhhmmss`, `MM/DD/YYYY hh:mm:ss`, `MM-DD-YY hh:mm`, `YYYY-MM-DD hh:mm:ss`, etc.
-   A string with a date, but no time component: `YYYY`, `YYYYMM`, `YYYY*MM`, `MM/DD/YYYY`, `MM-DD-YY` etc.
-   A string with a day and time: `DD`, `DD hh`, `DD hh:mm`. In this case, `YYYY-MM` are substituted with `2000-01`.
-   A string that includes date and time along with timezone offset information: `YYYY-MM-DD hh:mm:ss ±h:mm`, etc. For example, `2020-12-12 17:36:00 -5:00`.
```

2021-02-15 05:33 UTC, olgarev commented on docs/en/sql-reference/functions/type-conversion-functions.md
> +-   `NULL`.
```suggestion
`time_string` converted to the [DateTime](../../sql-reference/data-types/datetime.md) data type or `NULL`.
```

2021-02-15 05:38 UTC, olgarev commented on docs/en/sql-reference/functions/type-conversion-functions.md
> +AS parseDateTimeBestEffortUSOrNull;
```suggestion
SELECT parseDateTimeBestEffortUSOrNull('02/10/2021 21:12:57') AS parseDateTimeBestEffortUSOrNull;
```

2021-02-15 05:40 UTC, olgarev commented on docs/en/sql-reference/functions/type-conversion-functions.md
> +Same as for [parseDateTimeBestEffortUS](#parsedatetimebesteffortUS) except that it returns zero date or zero date time when it encounters a date format that cannot be processed.
```suggestion
Same as [parseDateTimeBestEffortUS](#parsedatetimebesteffortUS) except that it returns zero date or zero date time when it encounters a date format that cannot be processed.
```

2021-02-15 05:40 UTC, olgarev commented on docs/en/sql-reference/functions/type-conversion-functions.md
> +Same as for [parseDateTimeBestEffortUS](#parsedatetimebesteffortUS) except that it returns `NULL` when it encounters a date format that cannot be processed.
```suggestion
Same as [parseDateTimeBestEffortUS](#parsedatetimebesteffortUS) except that it returns `NULL` when it encounters a date format that cannot be processed.
```

2021-02-18 12:34 UTC, olgarev commented on docs/ru/sql-reference/functions/type-conversion-functions.md
> +Похожа на функцию [parseDateTimeBestEffortUS](#parsedatetimebesteffortUS), но разница состоит в том, что возвращает `NULL`, если входная строка не может быть преобразована в тип данных [DateTime](../
```suggestion
Работает аналогично функции [parseDateTimeBestEffortUS](#parsedatetimebesteffortUS), но в отличие от нее возвращает `NULL`, если входная строка не может быть преобразована в тип данных [DateTime](../../sql-reference/data-types/datetime.md).
```

2021-02-18 12:36 UTC, olgarev commented on docs/ru/sql-reference/functions/type-conversion-functions.md
> +Похожа на функцию [parseDateTimeBestEffortUS](#parsedatetimebesteffortUS), но разница в том, что возвращает нулевую дату или нулевую дату со временем, если входная строка не может быть преобразована
```suggestion
Работает аналогично функции [parseDateTimeBestEffortUS](#parsedatetimebesteffortUS), но в отличие от нее возвращает нулевую дату или нулевую дату со временем, если входная строка не может быть преобразована в тип данных [DateTime](../../sql-reference/data-types/datetime.md).
```

2021-02-24 18:02 UTC, sevirov commented
@kitaisreal Please, review this PR.

2021-02-24 18:08 UTC, kitaisreal commented on docs/ru/sql-reference/functions/type-conversion-functions.md
> +-   Строка в формате [unix timestamp](https://en.wikipedia.org/wiki/Unix_time), содержащая 9-10 символов.
9-10 цифр

2021-02-24 18:09 UTC, kitaisreal commented on docs/ru/sql-reference/functions/type-conversion-functions.md
> +-   Строка в формате [unix timestamp](https://en.wikipedia.org/wiki/Unix_time), содержащая 9-10 символов.
9-10 цифр

2021-02-24 18:11 UTC, kitaisreal requested changes

2021-02-24 18:11 UTC, kitaisreal commented on docs/ru/sql-reference/functions/type-conversion-functions.md
> +-   Строка в формате [unix timestamp](https://en.wikipedia.org/wiki/Unix_time), содержащая 9-10 символов.
9-10 цифр

2021-02-24 18:11 UTC, kitaisreal commented on docs/ru/sql-reference/functions/type-conversion-functions.md
> +-   Строка в формате [unix timestamp](https://en.wikipedia.org/wiki/Unix_time), содержащая 9-10 символов.
9-10 цифр

2021-02-24 18:50 UTC, kitaisreal approved these changes

2021-02-24 18:52 UTC, merged