Show create database
ClickHouse/ClickHouse pull request #2033
Opened 2018-03-13 13:47 UTC by KochetovNicolai

2018-03-13 22:59 UTC, alexey-milovidov commented on dbms/src/Databases/IDatabase.h
> +    /// Get the CREATE TABLE query for the table or CREATE DATABASE query for database if name is empty.
I think it will be better to have separate method, and rename methods to:
```
getCreateTableQuery
getCreateDatabaseQuery
```

2018-03-14 02:34 UTC, alexey-milovidov requested changes
.

2018-03-14 18:52 UTC, alexey-milovidov requested changes
.

2018-03-15 11:34 UTC, KochetovNicolai commented
autotest

2018-03-28 02:29 UTC, merged