Add ALTER TABLE UNFREEZE command.
ClickHouse/ClickHouse pull request #21142
Opened 2021-02-24 14:40 UTC by Jokser

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add ALTER TABLE UNFREEZE command

Detailed description / Documentation draft:

2021-02-27 23:41 UTC, alexey-milovidov commented on src/Storages/MergeTree/MergeTreeData.cpp
> +    String backup_path = "shadow/" + backup_name + "/" + relative_data_path;
Path traversal vulnerability.

2021-02-27 23:41 UTC, alexey-milovidov commented on src/Storages/MergeTree/MergeTreeData.cpp
> +    String backup_path = "shadow/" + backup_name + "/" + relative_data_path;
Please also rewrite with std::filesystem.

2021-02-27 23:43 UTC, alexey-milovidov commented on tests/integration/test_merge_tree_s3/test.py
> +    node.query("ALTER TABLE s3_test UNFREEZE 'backup1'")
This command looks inconsistent.
Maybe better to make it look `UNFREEZE WITH NAME '...'`?
And also add `UNFREEZE PARTITION`?

2021-02-27 23:46 UTC, alexey-milovidov requested changes
.

2021-03-11 12:45 UTC, alesapin approved these changes
Need simple functional tests with the table in old syntax.

2021-03-19 07:43 UTC, Jokser commented
@alesapin Could you please check the change again?

2021-03-23 10:40 UTC, alesapin commented
No realted failures

2021-03-23 11:05 UTC, merged