DOSCUP-6545: Edit and translate
ClickHouse/ClickHouse pull request #21497
Opened 2021-03-06 12:40 UTC by olgarev

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Documentation for #19267, 19297, 19527

2021-03-06 19:48 UTC, adevyatova commented on docs/ru/engines/table-engines/mergetree-family/mergetree.md
> +Таблицы семейства `MergeTree` могут использовать для хранения данных сервис [S3](https://aws.amazon.com/s3/) с диском типа `s3`.
```suggestion
Таблицы семейства `MergeTree` могут использовать для хранения данных сервиса [Amazon S3](https://aws.amazon.com/s3/) с диском типа `s3`.
```

2021-03-06 19:48 UTC, adevyatova commented on docs/ru/engines/table-engines/mergetree-family/mergetree.md
> +-   `min_bytes_for_seek` — минимальное количество байтов, которые используются для операций поиска вместо последовательного чтения. Значение по умолчанию: 1 Mb.
```suggestion
-   `min_bytes_for_seek` — минимальное количество байтов, которые используются для операций поиска вместо последовательного чтения. Значение по умолчанию: 1 МБайт. 
```

2021-03-06 19:48 UTC, adevyatova commented on docs/ru/engines/table-engines/mergetree-family/mergetree.md
> +Если диск сконфигурирован как `cold`, данные будут переноситься в S3 либо когда свободное место на локальном диске станет меньше порогового значения, которое определяется как `move_factor * disk_size
```suggestion
Если диск сконфигурирован как `cold`, данные будут переноситься в S3 при срабатывании правил TTL, либо когда свободное место на локальном диске станет меньше порогового значения, которое определяется как `move_factor * disk_size`. 
```

2021-03-06 19:48 UTC, adevyatova commented on docs/ru/operations/utilities/clickhouse-local.md
> +-   `-c`, `--config-file` — путь к файлу конфигурации. По умолчанию `clickhouse-local` запускается с пустой конфигурацией. Конфигурационный файл имеет тот же формат, что и для сервера ClickHouse и в
```suggestion
-   `-c`, `--config-file` — путь к файлу конфигурации. По умолчанию `clickhouse-local` запускается с пустой конфигурацией. Конфигурационный файл имеет тот же формат, что и для сервера ClickHouse, и в нём можно использовать все конфигурационные параметры сервера. Обычно подключение конфигурации не требуется; если требуется установить отдельный параметр, то это можно сделать ключом с именем параметра.
```

2021-03-06 21:32 UTC, olgarev commented
@vdimir Hi, will you review this PR, please? 

Concerning the "Using S3 for Data Storage" section. 
This is an "Edit and translate" ticket, so I've just translated the english text. But are you sure the section about S3 is in the right place? Seems that the next "Details" section (it has level <h3>) is not related to the S3 section (level <h2>). May be S3 section should be moved to the end of the page, after "Details"?

2021-03-11 10:43 UTC, nikitamikhaylov requested changes

2021-03-11 10:43 UTC, nikitamikhaylov commented on docs/ru/engines/table-engines/mergetree-family/mergetree.md
> +Таблицы семейства `MergeTree` могут использовать для хранения данных сервиса [Amazon S3](https://aws.amazon.com/s3/) с диском типа `s3`.
```suggestion
Таблицы семейства `MergeTree` могут хранить данные в сервисе [S3](https://aws.amazon.com/s3/) при использовании диска типа `s3`.
```

2021-03-11 10:43 UTC, nikitamikhaylov commented on docs/ru/engines/table-engines/mergetree-family/mergetree.md
> +-   `endpoint` — URL конечной точки S3 в запросах `path` или `virtual hosted` [styles](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html). URL конечной точки должен содержать бакет
```suggestion
-   `endpoint` — URL точки приема запроса на стороне S3 в [форматах](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html) `path` или `virtual hosted`. URL точки должен содержать бакет и путь к корневой директории на сервере, где хранятся данные.
```

2021-03-11 10:43 UTC, nikitamikhaylov commented on docs/ru/engines/table-engines/mergetree-family/mergetree.md
> +-   `cache_enabled` — признак, разрешено ли хранение меток кеша и индексных файлов в локальном файловом хранилище. Значение по умолчанию: `true`.
```suggestion
-   `cache_enabled` — признак, разрешено ли хранение кэша засечек и файлов индекса в локальной файловой системе. Значение по умолчанию: `true`. 
```

2021-03-11 10:43 UTC, nikitamikhaylov commented on docs/ru/engines/table-engines/mergetree-family/mergetree.md
> +-   `cache_path` — путь к локальному файловому хранилищу, где хранятся метки кеша и индексные файлы. Значение по умолчанию: `/var/lib/clickhouse/disks/<disk_name>/cache/`.
```suggestion
-   `cache_path` — путь в локальной файловой системе, где будут храниться кэш засечек и файлы индекса. Значение по умолчанию: `/var/lib/clickhouse/disks/<disk_name>/cache/`. 
```

2021-03-11 10:43 UTC, nikitamikhaylov commented on docs/ru/engines/table-engines/mergetree-family/mergetree.md
> +-   `skip_access_check` — признак, выполнять ли проверку доступа к диску при запуске диска. Если установлено значение `true`, то проверка не выполняется. Значение по умолчанию: `false`.
```suggestion
-   `skip_access_check` — признак, выполнять ли проверку доступов при запуске диска. Если установлено значение `true`, то проверка не выполняется. Значение по умолчанию: `false`.
```

2021-03-11 10:43 UTC, nikitamikhaylov commented on docs/en/sql-reference/functions/math-functions.md
> +Extracts the sign of a real number.
```suggestion
Returns the sign of a real number.
```

2021-03-11 10:43 UTC, nikitamikhaylov commented on docs/ru/sql-reference/functions/math-functions.md
> +Выделяет знак действительного числа.
```suggestion
Возвращает знак действительного числа.
```

2021-03-11 10:43 UTC, nikitamikhaylov commented on docs/ru/sql-reference/functions/math-functions.md
> +Знак для отрицательного значения:
```suggestion
Результат sign() для отрицательного аргумента:
```

2021-03-11 10:43 UTC, nikitamikhaylov commented on docs/ru/sql-reference/functions/math-functions.md
> +Знак для положительного значения:
```suggestion
Результат sign() для положительного аргумента:
```

2021-03-11 10:43 UTC, nikitamikhaylov commented on docs/ru/sql-reference/functions/math-functions.md
> +Знак для нулевого значения:
```suggestion
Результат sign() для нуля:
```

2021-03-12 02:16 UTC, olgarev commented
@nikitamikhaylov Thanks a lot for review, I applied all suggestions. What about "Details" section (see my question above)?

2021-03-12 12:49 UTC, olgarev commented
@nikitamikhaylov Headers corrected.

2021-03-12 13:04 UTC, nikitamikhaylov approved these changes

2021-03-12 13:04 UTC, merged