DOCSUP-5854: Documented the SHOW SETTINGS statement
ClickHouse/ClickHouse pull request #21493
Opened 2021-03-06 09:29 UTC by olgarev

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Documentation for #18056

2021-03-06 18:53 UTC, adevyatova commented on docs/_description_templates/template-engine.md
> +**See Also** {#see-also}
```suggestion
**See Also** 
```

2021-03-06 18:53 UTC, adevyatova commented on docs/_description_templates/template-function.md
> +-   `z` — Description. Optional (only for optional parameters). Possible values: <values list>.Default value: <value>. [Type name](relative/path/to/type/dscr.md#type).
```suggestion
-   `z` — Description. Optional (only for optional parameters). Possible values: <values list>. Default value: <value>. [Type name](relative/path/to/type/dscr.md#type).
```

2021-03-09 08:59 UTC, alesapin requested changes

2021-03-09 08:59 UTC, alesapin commented on docs/en/sql-reference/statements/show.md
> +`LIKE` clause needs a setting name or part of the name without globs.
The only difference between like and `LIKE` and `ILIKE` is case insensitiveness (ILIKE == case insensitive like). So `%` and `_` are also allowed. And I think we should give any details about `LIKE|ILIKE` hire, just something common: 
"`LIKE|ILIKE` allows to specify a matching pattern for setting name".

2021-03-09 08:59 UTC, alesapin commented on docs/_description_templates/template-function.md
> +-   `x` — Description. Optional (only for optional arguments). Possible values: <values list>. Default value: <value>. [Type name](relative/path/to/type/dscr.md#type).
Not related to this PR?

2021-03-10 07:03 UTC, olgarev commented on docs/_description_templates/template-function.md
> +-   `x` — Description. Optional (only for optional arguments). Possible values: <values list>. Default value: <value>. [Type name](relative/path/to/type/dscr.md#type).
No, it is not. Just a small fix.

2021-03-10 07:46 UTC, alesapin approved these changes

2021-03-11 08:47 UTC, merged