optimize select final with prewhere primary key
ClickHouse/ClickHouse pull request #21830
Opened 2021-03-17 10:53 UTC by foolchi

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Optimize select final performance, change primary key filter to prewhere
...

Detailed description / Documentation draft:
Change primary key filter (where) to prewhere to reduce data load.

...

2021-03-22 16:20 UTC, CurtizJ requested changes
Please, can you add a test to check if columns are correctly moved/not moved in queries with `FINAL`. You can use `EXPLAIN SYNTAX` query for this.

2021-03-22 16:20 UTC, CurtizJ commented on src/Storages/MergeTree/MergeTreeWhereOptimizer.cpp
> +    , primary_key_columns{metadata_snapshot->getPrimaryKey().column_names}
You need the sorting key here. Sorting key is used as key in special `MergeTree` engines and may differ from the primary key.

2021-03-22 16:22 UTC, CurtizJ commented on src/Storages/MergeTree/MergeTreeWhereOptimizer.h
> +    const Names primary_key_columns;
It's better to save these name to `unordered_set` to avoid linear search for every check of column.

2021-03-24 15:42 UTC, foolchi commented
@CurtizJ 
test case added, please review again

2021-03-25 12:28 UTC, CurtizJ approved these changes

2021-03-25 12:29 UTC, CurtizJ commented
Test failures are not related to changes.

2021-03-25 12:32 UTC, merged