Conditional computations.
ClickHouse/ClickHouse pull request #2272
Opened 2018-04-24 08:03 UTC by ilyshnikova

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

В этом реквесте содержится правка, которая позволяет вычислять аргументы функции and не везде, а только на определенных подмножествах строк. 

Включается эта функциональность опцией клиента enable_conditional_computation. По-дефолту, функциональность выклчена

Пример работы
```
ubuntu.members.linode.com :) select arrayMap(x -> x and modulo(1,x), [0,1,2]);

SELECT arrayMap(x -> (x AND (1 % x)), [0, 1, 2])

Received exception from server (version 1.1.54380):
Code: 153. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Division by zero. 

0 rows in set. Elapsed: 0.402 sec. 

ubuntu.members.linode.com :) set enable_conditional_computation=1;

SET enable_conditional_computation = 1

Ok.

0 rows in set. Elapsed: 0.002 sec. 

ubuntu.members.linode.com :) select arrayMap(x -> x and modulo(1,x), [0,1,2]);

SELECT arrayMap(x -> (x AND (1 % x)), [0, 1, 2])

┌─arrayMap(lambda(tuple(x), and(x, modulo(1, x))), [0, 1, 2])─┐
│ [0,0,1]                                                     │
└─────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.011 sec. 

ubuntu.members.linode.com :)
```

Особенность реквеста: приходится пробрасывать в execute количество входных строк, из-за кейсов, где аргумент фукнции "and" может не иметь никаких входных параметров и угадать число строк результата невозможно внутри выполнения функции, только подсказать ей снаружи, как в примере ```f and emptyArrayUInt8()``` 

В остальном все просто: добавлены функции проекции, восстановления и взятия композиции проекций и построен способ выбора экшенов, который использует эти функции для вычисления результата.

2018-04-28 13:37 UTC, ludv1x commented on dbms/src/Interpreters/ExpressionActions.h
> +    /// For projections
Плохое имя для, т.к. в этом же и смежно классе под проекцией понимается совршенно [другая вещь](https://github.com/yandex/ClickHouse/pull/2272/commits/12c8014e5cf5ae82c00e576a79080df3dff3a1e8#diff-40339821324f38b3be4fa88d7a15096fR93
).

2018-04-28 13:38 UTC, ludv1x commented on dbms/src/Interpreters/ExpressionActions.h
> +    /// For projections
Очень не хватает комментариев в коде, без них сложно разобраться в алгоритме.

2018-04-28 13:49 UTC, ludv1x commented on dbms/src/Interpreters/ExpressionAnalyzer.cpp
> +    if (!isThereArrayJoin(ast) && settings.enable_conditional_computation && !only_consts)
Тут не совсем очевидна мотивация.
По идее если при выполнении arrayJoin делать replicate() виртуальных столбцов с масками, то должно все работать (?).
Еще есть вариант выполнять все arrayJoin'ы после всех обычных функций.

2018-04-28 13:53 UTC, ludv1x commented on dbms/src/Interpreters/ExpressionAnalyzer.cpp
> +    if (!isThereArrayJoin(ast) && settings.enable_conditional_computation && !only_consts)
(Это не первочередное проблема)

2018-04-29 23:01 UTC, KochetovNicolai requested changes

2018-05-01 19:08 UTC, merged