Tests dt64 ext
ClickHouse/ClickHouse pull request #22729
Opened 2021-04-06 22:11 UTC by zvonand

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Testflows tests for DateTime64 Extended Range

Detailed description / Documentation draft:
Testflows tests for DateTime64 Extended Range

2021-04-07 04:13 UTC, alexey-milovidov requested changes

2021-04-07 04:13 UTC, alexey-milovidov commented on tests/testflows/datetime64_extended_range/regression.py
> +#!/usr/bin/env python3
Wrong license.
All code with incompatible licenses will be removed.

2021-04-20 16:42 UTC, alexey-milovidov commented
@zvonand The tests take 848 seconds of time.
They will run for every commit and every PR.

It's too much for a single feature. Could you make this tests faster?
I'm sure that most of the time these tests do nothing.

2021-05-08 19:41 UTC, vzakaznikov commented
@alexey-milovidov, @zvonand, let's disable these tests in regression.py to merge this PR. We will enable them in another PR that will run them in parallel.

2021-05-08 19:41 UTC, vzakaznikov commented
@alexey-milovidov, @zvonand, let's disable these tests in regression.py to merge this PR. We will enable them in another PR that will run them in parallel.

2021-05-08 20:29 UTC, alexey-milovidov approved these changes

2021-05-08 20:29 UTC, merged