Perfomance metrics refinement
ClickHouse/ClickHouse pull request #233
Opened 2016-12-07 16:08 UTC by ludv1x

METR-19372
METR-23305

2016-12-07 20:58 UTC, alexey-milovidov requested changes

2016-12-07 20:58 UTC, alexey-milovidov commented on dbms/src/Interpreters/executeQuery.cpp
> +		if (!res.out || !dynamic_cast<CountingBlockOutputStream *>(res.out.get()))
This is not needed right now?
(Misleading message for every non-INSERT query.)

2016-12-07 20:58 UTC, alexey-milovidov commented on dbms/src/Storages/MergeTree/MergeTreeDataMerger.cpp
Missing comment about this class.

2016-12-07 21:17 UTC, ludv1x commented on dbms/include/DB/Interpreters/QueryLog.h
> +	/// NOTE: Not obvious metric.
So, as I metioned on next line, result_rows will be equal to written_rows (?)

2016-12-09 10:24 UTC, ludv1x commented
Updated

2016-12-09 20:05 UTC, alexey-milovidov commented on doc/benchmark.html
> +    for (j = 0; j < filtered_results.length; j++) {
No `var`?

2016-12-09 20:08 UTC, alexey-milovidov commented on CMakeLists.txt
> +option (TEST_COVERAGE "Enables flags for test coverage" OFF)
Need instruction on how to install newer CMake in build.md.

2016-12-12 16:23 UTC, ludv1x commented on doc/benchmark.html
> +    for (j = 0; j < filtered_results.length; j++) {
It seems that both variant work properly in this context. But local `var` is really better.

2016-12-12 16:28 UTC, ludv1x commented on CMakeLists.txt
> +option (TEST_COVERAGE "Enables flags for test coverage" OFF)
Do you mean describe behavior of additional options?
Default behavior remains the same, and scripts from `build.md` seem to be workable.

2016-12-12 16:32 UTC, ludv1x commented on CMakeLists.txt
> +option (TEST_COVERAGE "Enables flags for test coverage" OFF)
Let merge this PR containing mixture of different changes and refine separate changes lately.

2016-12-12 16:56 UTC, alexey-milovidov commented on CMakeLists.txt
> +option (TEST_COVERAGE "Enables flags for test coverage" OFF)
Ok.
What I mean:

I have 
```
$ cmake --version
cmake version 2.8.12.2
```

and when I try to install newer CMake from sources,
I just get immediate segfault on cmake invocation.

2016-12-12 16:56 UTC, merged