Improved `test_storage_s3_get_unstable`
ClickHouse/ClickHouse pull request #23976
Opened 2021-05-08 21:58 UTC by excitoon

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Progress on #23911

2021-05-31 19:51 UTC, alexey-milovidov requested changes
.

2021-05-31 19:51 UTC, alexey-milovidov commented on tests/integration/test_storage_s3/s3_mocks/unstable_server.py
> +sum_4 = 0
Mysterious variable name.

2021-05-31 19:52 UTC, alexey-milovidov commented on tests/integration/test_storage_s3/s3_mocks/unstable_server.py
> +lines = b"".join((gen_line() for _ in range(500000))) + f"0,0,0,{-sum_4}\n".encode()
What's the logic behind this?
Please write in comments in the code.

2021-06-07 08:04 UTC, excitoon commented
@alexey-milovidov This patch improves testing capabilities of the test, but I was unable to reproduce #23911 on it anyway. I guess the problem is only disk-related.

2021-06-08 00:52 UTC, alexey-milovidov commented
@mergifyio update

2021-06-09 02:47 UTC, alexey-milovidov commented
@excitoon You did not provide access to your fork.

2021-06-10 07:08 UTC, excitoon commented
@alexey-milovidov Rebased it.

2021-06-12 01:04 UTC, alexey-milovidov commented
Cool!

2021-06-12 01:04 UTC, merged