fix bug in issue #2298 : 'Expected end of line' in Kafka Engine
ClickHouse/ClickHouse pull request #2398
Opened 2018-05-22 03:55 UTC by LiuYangkuan

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
ReadBuffer will make messages from kafka into a stream without separator between each other, but for Row-based inputstream such as CSV or TSV, there should be a '\n' separator between each message;

2018-05-25 18:47 UTC, alexey-milovidov commented on dbms/src/Storages/StorageKafka.cpp
> +    std::shared_ptr<String> msg_ctx;
Why shared_ptr?

2018-05-25 18:50 UTC, alexey-milovidov commented on dbms/src/Storages/StorageKafka.cpp
> +            msg_ctx->append("\n");
This won't work for RowBinary (and any non-text) format.

Why we have messages without terminating line feed in Kafka?
Is it possible that messages have line feeds in some use cases?
Is it possible to have many rows in single Kafka message?

2018-05-25 18:51 UTC, alexey-milovidov requested changes
The questions remain.

2018-06-04 20:41 UTC, alexey-milovidov commented on dbms/src/Storages/StorageKafka.cpp
> +            msg_ctx = String(reinterpret_cast<char *>(msg->payload), msg->len);
Excessive copy even if the message already contains \n.

2018-06-04 20:41 UTC, alexey-milovidov commented on dbms/src/Storages/StorageKafka.cpp
> +                msg_ctx.append("\n");
Append may do reallocation and another copy in most cases.

2018-06-04 20:43 UTC, alexey-milovidov commented on dbms/src/Storages/StorageKafka.cpp
> +        if (format_name == "Native" || format_name == "RowBinary" || format_name == "Values" || format_name == "CapnProto")
This explicit list looks ugly, especially for this branch.
We should add a property of formats "rows must be separated by newlines" and use it here.

2018-07-25 15:54 UTC, alexey-milovidov commented
Superseded by https://github.com/yandex/ClickHouse/pull/2701

2018-07-25 15:56 UTC, alexey-milovidov commented
PS. I preferred that PR, because here we have introduced strange notation
```
if (storage.format_name.back() == '~')
```
that is questionable (will be difficult to extend).

2018-07-25 15:56 UTC, closed without merging

2018-07-31 10:09 UTC, LiuYangkuan commented
Yes, #2701 is an extendable solution!