Update cloud.md
ClickHouse/ClickHouse pull request #24063
Opened 2021-05-12 15:33 UTC by SergTT

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Documentation (changelog entry is not required)

Detailed description:
Add SberCloud as a ClickHouse Cloud Service Provider

2021-05-12 15:41 UTC, qoega requested changes

2021-05-12 15:41 UTC, qoega commented on docs/en/commercial/cloud.md
> +-   significantly reduces the time to market of your products.
Not relevant to ClickHouse

2021-05-12 16:05 UTC, SergTT commented on docs/en/commercial/cloud.md
> +-   significantly reduces the time to market of your products.
Updated.

2021-05-25 16:23 UTC, SergTT commented
@qoega, as I can see, two checks were not successful. Should I do something with it?

2021-05-26 01:28 UTC, merged