Implement antlr parser for projections
ClickHouse/ClickHouse pull request #24245
Opened 2021-05-18 10:35 UTC by amosbird

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Implement the missing antlr parser for projections as suggested by @abyss7 

Detailed description / Documentation draft:

.

2021-05-18 16:27 UTC, abyss7 requested changes
Looks like something off with an indentation in code

2021-05-18 16:27 UTC, abyss7 commented on src/Parsers/New/AST/AlterTableQuery.h
>              ELEMENT = 0,  // TableElementExpr
If you use this value for some other clause types, then please mark in comments all possible AST classes, like `Identifier`, etc.

2021-05-18 16:27 UTC, abyss7 commented on src/Parsers/New/AST/AlterTableQuery.h
> +            COLUMN = 0,
Same here

2021-05-20 09:06 UTC, qoega commented
Can you commit anything to trigger build with newer master? Or I can use mergify to update branch

2021-05-20 09:39 UTC, amosbird commented
> Can you commit anything to trigger build with newer master? Or I can use mergify to update branch

done

2021-06-01 11:33 UTC, abyss7 approved these changes
Please fix the conflict.

2021-06-01 14:21 UTC, amosbird commented
> Please fix the conflict.

Done

2021-06-02 15:09 UTC, merged