Do not write preprocessed configs to /etc/ [WIP]
ClickHouse/ClickHouse pull request #2443
Opened 2018-05-29 20:54 UTC by proller

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

2018-05-30 09:27 UTC, meshpaul commented
Hi

  We actually use these as part of our Ansible management to see if we need to bounce ClickHouse.  So what will be new behavior to tell us Config changes have been processed?

2018-05-30 22:49 UTC, meshpaul commented
That makes sense.  Thank you.

2018-08-30 11:48 UTC, alexey-milovidov reviewed
"Submodule librdkafka updated 128 files"
is it intentional?

2018-08-30 11:49 UTC, alexey-milovidov commented on dbms/programs/local/LocalServer.cpp
> +    if (!config().has("path") || (path = config().getString("path")).empty())
`getString` has default parameter.

2018-08-30 11:49 UTC, alexey-milovidov commented on dbms/programs/local/LocalServer.cpp
> +    if (!config().has("path") || (path = config().getString("path")).empty())
Why we check for empty string?
If the user write `<path></path>` it's their fault.

2018-08-30 11:50 UTC, alexey-milovidov commented on dbms/programs/local/LocalServer.cpp
> +    if (!config().has("path") || (path = config().getString("path")).empty())
Why should `clickhouse-local` save anything to /var/lib/clickhouse?

2018-08-30 11:56 UTC, alexey-milovidov commented on libs/libdaemon/src/BaseDaemon.cpp
> +    ConfigProcessor::main_config_path = Poco::Path(config_path).makeParent().toString();
Using global variables with non-trivial constructor across translation units is undefined behaviour.

2018-08-30 11:57 UTC, alexey-milovidov commented on debian/clickhouse-server.service
> +ExecStartPre=-/bin/ln -s `/usr/bin/clickhouse-extract-from-config --config=/etc/clickhouse-server/config.xml --key=path`/preprocessed_config /etc/clickhouse-server/preprocessed
Should be names preprocessed_configs, not preprocessed_config.

2018-08-30 11:58 UTC, alexey-milovidov requested changes
.

2018-08-30 11:59 UTC, alexey-milovidov commented on dbms/src/Common/Config/ConfigProcessor.h
> +    void savePreprocessedConfig(const LoadedConfig & loaded_config, std::string preprocessed_dir = "");
Missing comment.

2018-08-30 12:00 UTC, alexey-milovidov commented on dbms/src/Common/Config/ConfigProcessor.h
> +    void savePreprocessedConfig(const LoadedConfig & loaded_config, std::string preprocessed_dir = "");
We don't need default value.

2018-10-09 23:48 UTC, alexey-milovidov commented on dbms/programs/server/Server.cpp
> +    std::string path = getCanonicalPath(config().getString("path", "/var/lib/clickhouse/"));
Need to introduce #define for default path.

2018-10-09 23:49 UTC, alexey-milovidov commented on dbms/src/Common/Config/ConfigProcessor.cpp
> +                std::cerr << StackTrace().toString() <<"\n";
Don't understand logging methods are mixed.

2018-10-09 23:49 UTC, alexey-milovidov commented on dbms/src/Common/Config/ConfigProcessor.cpp
> +                LOG_WARNING(log, "no dir for preprocessed_dir ");
Cryptic message.

2018-10-09 23:50 UTC, alexey-milovidov commented on dbms/src/Common/Config/ConfigProcessor.cpp
> +void ConfigProcessor::savePreprocessedConfig(const LoadedConfig & loaded_config, std::string preprocessed_dir)
No comment about possible empty value of `preprocessed_dir`.

2018-10-09 23:51 UTC, alexey-milovidov commented on dbms/src/Common/Config/ConfigProcessor.cpp
> +        std::replace( new_path.begin(), new_path.end(), '/', '_');
Style.

2018-10-09 23:54 UTC, alexey-milovidov commented on debian/clickhouse-client.postinst
> -chown -R ${CLICKHOUSE_USER} /etc/clickhouse-client || true
Maybe remove old preprocessed configs to avoid confusion (need to do it extra carefully)?

2018-10-09 23:58 UTC, alexey-milovidov commented on dbms/src/Common/Config/ConfigProcessor.cpp
> +std::string main_config_path;
Why don't pass it to ConfigProcessor::setPreprocessedConfig?

2018-11-24 01:20 UTC, alexey-milovidov approved these changes

2018-11-26 13:16 UTC, filimonov commented
👍 

Это была одна из претензий наших ОПсов к кликхаусу :)

2018-11-27 16:11 UTC, merged

2019-01-25 14:36 UTC, filimonov commented
Small issue with that: when starting clickhouse-server like that

```clickhouse-server --config /etc/clickhouse-server/config.xml -- --path=/tmp/bbb --http_port=30000 --tcp_port=30001 --interserver_http_port=30002 --logger.log=/dev/null --logger.errorlog=/dev/null```

it still tries to access `/var/lib/clickhouse//preprocessed_configs/config.xml`