Docsup 9474: document table comments
ClickHouse/ClickHouse pull request #24548
Opened 2021-05-26 18:51 UTC by kirillikoff

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation for #23548

2021-05-28 07:03 UTC, olgarev commented on docs/en/sql-reference/statements/create/table.md
> +    The comment is supported for all table engines besides [Kafka](../../../engines/table-engines/integrations/kafka.md) and [RabbitMQ](../../../engines/table-engines/integrations/rabbitmq.md).
```suggestion
!!!note "Note"
    The comment is supported for all table engines except [Kafka](../../../engines/table-engines/integrations/kafka.md) and [RabbitMQ](../../../engines/table-engines/integrations/rabbitmq.md).
```

2021-05-28 07:05 UTC, olgarev commented on docs/en/sql-reference/statements/create/table.md
> +SELECT name,comment FROM system.tables WHERE name = 't1';
```suggestion
SELECT name, comment FROM system.tables WHERE name = 't1';
```

2021-05-29 15:00 UTC, olgarev commented on docs/en/sql-reference/statements/create/table.md
> +## COMMENT TABLE {#comment-table}
```suggestion
## COMMENT Clause {#comment-table}
```

2021-05-29 15:00 UTC, olgarev commented on docs/en/sql-reference/statements/create/table.md
> +COMMENT 'Comment';
```suggestion
COMMENT 'Comment'
```

2021-05-29 15:01 UTC, olgarev commented on docs/ru/sql-reference/statements/create/table.md
> +COMMENT 'Comment';
```suggestion
COMMENT 'Comment'
```

2021-05-29 15:01 UTC, olgarev commented on docs/ru/sql-reference/statements/create/table.md
> +## COMMENT TABLE {#comment-table}
```suggestion
## Секция COMMENT {#comment-table}
```

2021-05-30 16:04 UTC, kssenii requested changes

2021-05-31 06:54 UTC, kirillikoff commented on docs/en/sql-reference/statements/create/table.md
> +    The comment is supported for all table engines except [Kafka](../../../engines/table-engines/integrations/kafka.md) and [RabbitMQ](../../../engines/table-engines/integrations/rabbitmq.md).
I suggest adding information about the embeddedRocksDB engine. And delete the note as soon as the code is finalized.

2021-05-31 08:11 UTC, kssenii approved these changes

2021-05-31 08:11 UTC, merged