Add CI check for PPC64le
ClickHouse/ClickHouse pull request #25486
Opened 2021-06-18 15:25 UTC by abyss7

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add CI check for PPC64le cross-compilation

2021-06-18 15:35 UTC, abyss7 commented on utils/s3tools/s3uploader
> +#!/usr/bin/env python3.8
Revert this

2021-06-21 16:40 UTC, abyss7 commented
@Mergefy update

2021-06-21 16:40 UTC, abyss7 commented
@Mergify update

2021-06-21 18:30 UTC, alexey-milovidov approved these changes

2021-06-23 14:26 UTC, abyss7 commented
@Mergifyio update

2021-06-23 19:52 UTC, alexey-milovidov commented
I cannot find it in https://clickhouse-builds.s3.yandex.net/25486/2622fbf9671f669f7560a5546da0ef2c72bdc1b7/clickhouse_special_build_check/report.html

2021-06-23 20:27 UTC, abyss7 commented
> I cannot find it in https://clickhouse-builds.s3.yandex.net/25486/2622fbf9671f669f7560a5546da0ef2c72bdc1b7/clickhouse_special_build_check/report.html

It's not there yet - I have to add in Arcadia (I guess) after this PR gets merged.

2021-06-24 12:57 UTC, abyss7 commented
> > I cannot find it in https://clickhouse-builds.s3.yandex.net/25486/2622fbf9671f669f7560a5546da0ef2c72bdc1b7/clickhouse_special_build_check/report.html
> 
> It's not there yet - I have to add in Arcadia (I guess) after this PR gets merged.

Looks like I'm wrong, I will try to add build via ci_config.json

2021-06-27 20:33 UTC, alexey-milovidov commented
Does not work on Ubuntu 20.04 due to too new glibc:

```
milovidov@milovidov-desktop:~/work/ClickHouse/programs/server$ wget https://clickhouse-builds.s3.yandex.net/25486/2855831adaca71084db89b9a55e896711eba72fa/clickhouse_special_build_check/clang-11-ppc64le_relwithdebuginfo_none_bundled_unsplitted_disable_False_binary/clickhouse
--2021-06-27 23:26:47--  https://clickhouse-builds.s3.yandex.net/25486/2855831adaca71084db89b9a55e896711eba72fa/clickhouse_special_build_check/clang-11-ppc64le_relwithdebuginfo_none_bundled_unsplitted_disable_False_binary/clickhouse
Resolving clickhouse-builds.s3.yandex.net (clickhouse-builds.s3.yandex.net)... 2a02:6b8::2:158, 93.158.134.158
Connecting to clickhouse-builds.s3.yandex.net (clickhouse-builds.s3.yandex.net)|2a02:6b8::2:158|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2039041016 (1,9G) [application/octet-stream]
Saving to: ‘clickhouse’

clickhouse                                           100%[====================================================================================================================>]   1,90G  21,7MB/s    in 89s     

2021-06-27 23:28:16 (21,9 MB/s) - ‘clickhouse’ saved [2039041016/2039041016]

milovidov@milovidov-desktop:~/work/ClickHouse/programs/server$ chmod a+x ./clickhouse
milovidov@milovidov-desktop:~/work/ClickHouse/programs/server$ mv ./clickhouse ./clickhouse-ppc64le
milovidov@milovidov-desktop:~/work/ClickHouse/programs/server$ docker run -it --rm --volume $(pwd):/ClickHouse multiarch/ubuntu-core:ppc64el-wily /ClickHouse/clickhouse-ppc64le
/ClickHouse/clickhouse-ppc64le: /lib/powerpc64le-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /ClickHouse/clickhouse-ppc64le)
/ClickHouse/clickhouse-ppc64le: /lib/powerpc64le-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /ClickHouse/clickhouse-ppc64le)
/ClickHouse/clickhouse-ppc64le: /lib/powerpc64le-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /ClickHouse/clickhouse-ppc64le)
/ClickHouse/clickhouse-ppc64le: /lib/powerpc64le-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /ClickHouse/clickhouse-ppc64le)
/ClickHouse/clickhouse-ppc64le: /lib/powerpc64le-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /ClickHouse/clickhouse-ppc64le)
milovidov@milovidov-desktop:~/work/ClickHouse/programs/server$ docker run -it --rm --volume $(pwd):/ClickHouse ppc64le/ubuntu:latest /ClickHouse/clickhouse-ppc64le
Unable to find image 'ppc64le/ubuntu:latest' locally
latest: Pulling from ppc64le/ubuntu
830138a32e2b: Pull complete 
Digest: sha256:b57bc0aa04bd1e6e64199bc146f73db6bc7a7827375a5ca77804dde58d90d887
Status: Downloaded newer image for ppc64le/ubuntu:latest
/ClickHouse/clickhouse-ppc64le: /lib/powerpc64le-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /ClickHouse/clickhouse-ppc64le)
milovidov@milovidov-desktop:~/work/ClickHouse/programs/server$ docker run -it --rm --volume $(pwd):/ClickHouse ppc64le/ubuntu:latest cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

2021-06-27 20:40 UTC, alexey-milovidov commented on docker/packager/binary/Dockerfile
> +RUN wget -nv https://clickhouse-datasets.s3.yandex.net/toolchains/toolchains/advanced-toolchain-14.0-3-ppc64le.tar.xz
Information about the source must be provided.

2021-06-27 20:44 UTC, alexey-milovidov commented
```
$ docker run -it --rm --volume $(pwd):/ClickHouse ppc64le/ubuntu:latest ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

2021-06-28 20:53 UTC, abyss7 commented
I will check why all of those dependencies on glibc version sneaked in - possibly the build-mode is wrong:
```ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked```

2021-06-28 22:58 UTC, alexey-milovidov commented
The toolchain has glibc 2.32 and Ubuntu 20.04 has glibc 2.31 - no surprise.

I recommend instead of using the official toolchain with ~500 MB of assorted files, just extract only some required files from the Ubuntu image.

2021-07-13 08:48 UTC, alexey-milovidov requested changes
.

2021-09-28 10:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=25486) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=25486) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=25486) it.</sub>

2021-10-11 23:11 UTC, closed without merging