[WIP] add bin/unbin support #25422
ClickHouse/ClickHouse pull request #25609
Opened 2021-06-23 04:36 UTC by zxc111

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add bin/unbin functions support
...

Detailed description / Documentation draft:

...

By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

2021-06-29 13:36 UTC, vdimir requested changes
Thank you for you work!

Core implementation is good, I left some comments, I think most of them you will easily resolve.

One of them is suggestion to generalize implementation between bin and hex functions, I can help with it.

2021-06-29 13:36 UTC, vdimir commented on src/Functions/FunctionsCoding.h
> +            if (*pos == '1')
We consider all non `1` chars as zero. I thought that we can throw error if input not valid (contains anything else `0` or `1`), but `unhex` also process unknown symbols, so it's ok.

But we can make this "unspecified" behavior a bit clearer if all non zero chars will be treated as `1`.
Like `012` now is equivalent to `010`, but `011` seems more logic.

What do you think?

2021-06-29 13:36 UTC, vdimir commented on src/Functions/FunctionsCoding.h
> +        }
Need a comment. What we are doing here, what `7` means, why we make such steps etc.

2021-06-29 13:36 UTC, vdimir commented on src/Functions/FunctionsCoding.h
> +            int c = 0;
Should it be byte, not int?
```suggestion
            UInt8 c = 0;
```

2021-06-29 14:52 UTC, zxc111 commented
@vdimir Thanks for review and suggest, I'm glad to resolve these comments.

2021-07-05 12:11 UTC, vdimir reviewed
Now without copy-paste looks much better!


I made commits with minor style changes and fixes for some corner cases (I left comments for it too, but it fixed in my branch).
Also feel free to comment my changes.

I can't push it onto your PR. (I suppose [this thing](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) not enabled).
Let me push to PR, or you can merge my commits from my branch by youself.


See: https://github.com/ClickHouse/ClickHouse/tree/vdimir/function-bin-unbin

2021-07-05 12:11 UTC, vdimir commented on tests/queries/0_stateless/01926_bin_unbin.reference
> +
In your previous version it works correctly, `bin(0)` should return  `'0'`. I'll fix it.

2021-07-05 12:11 UTC, vdimir commented on src/Functions/FunctionsCoding.h
It's the same case, isn't it? I'll fix it in my branch

2021-07-05 12:11 UTC, vdimir commented on src/Functions/FunctionsCoding.h
> +    static void executeOneUInt(T x, char *& out)
I suppose `writeBinByte` can be used here. See commit my branch.

2021-07-05 12:11 UTC, vdimir commented on src/Functions/FunctionsCoding.h
> +class UnConversion : public IFunction
Too generic name, I've changed it to `DecodeFromBinaryRepr`, but I'm not sure that it also good if you have any other ideas, you can snuggest it.

2021-07-05 14:35 UTC, zxc111 commented
thanks a lot.
I've rebased on you branch.

2021-07-06 09:57 UTC, vdimir commented
@zxc111 

Oh, I broke build with my comment. let me push into this PR and I'll fix it not to ask rebase branch every time.

Also I looked to `hex` function always adds leading zero (like `hex(1) = '01'`), so we can add leading zeros to `bin` too, to be consistent. I'll make it too.

2021-07-06 10:58 UTC, zxc111 commented
@vdimir 
The option is enable already.
Anything else I need to enable?
Maybe you push incorrect repository, https://github.com/zxc111/ClickHouse-1 is right and https://github.com/zxc111/ClickHouse is golang driver. 😭
![image](https://user-images.githubusercontent.com/2883637/124588436-5ef70700-de8b-11eb-9331-eecdae743865.png)

2021-07-06 12:25 UTC, vdimir approved these changes

2021-07-07 06:36 UTC, merged

2021-07-15 02:39 UTC, gyuton commented
Internal documentation ticket: DOCSUP-11553.