DOCSUP-10112: Documented logical functions
ClickHouse/ClickHouse pull request #25797
Opened 2021-06-28 18:29 UTC by gyuton

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation for #6048

2021-06-29 19:16 UTC, adevyatova commented on docs/en/sql-reference/functions/logical-functions.md
> +-   `NULL`, if there is at least one `NULL` values.
This is incorrect, because "SELECT 1 OR NULL returns 1"

2021-06-29 19:16 UTC, adevyatova commented on docs/en/sql-reference/functions/logical-functions.md
> +-   `1`, if the `val` is a `0`.
```suggestion
-   `1`, if the `val` is `0`.
```

2021-06-29 19:16 UTC, adevyatova commented on docs/en/sql-reference/functions/logical-functions.md
> +Result
```suggestion
Result:
```

2021-06-29 21:45 UTC, adevyatova commented on docs/en/sql-reference/functions/logical-functions.md
> +-   `NULL`, if there aren't any non-zero values besides `NULL`.
```suggestion
-   `NULL`, if there are only zero values and `NULL`.
```

2021-06-29 21:45 UTC, adevyatova commented on docs/ru/sql-reference/functions/logical-functions.md
> +-   `NULL`, если среди аргументов нет никаких других ненулевых значений кроме `NULL`.
```suggestion
-   `NULL`, если среди аргументов нет ненулевых значений, и есть `NULL`.
```

2021-06-29 21:45 UTC, adevyatova commented on docs/ru/sql-reference/functions/logical-functions.md
> +Вычисляет результат логической исключающей дизъюнкции между двумя и более значениями. При более чем двух значениях функция работает, как-будто сначала вычисляет `XOR` для первых двух значений, а пото
```suggestion
Вычисляет результат логической исключающей дизъюнкции между двумя и более значениями. При более чем двух значениях функция работает так: сначала вычисляет `XOR` для первых двух значений, а потом использует полученный результат при вычислении `XOR` со следующим значением и так далее. Соответствует [Оператору логического исключающего ‘ИЛИ’](../../sql-reference/operators/index.md#logical-xor-operator).
```

2021-06-29 21:45 UTC, adevyatova commented on docs/ru/sql-reference/operators/index.md
> +## Оператор логического ‘И’ {#logical-and-operator}
```suggestion
## Оператор логического "И" {#logical-and-operator}
```

2021-06-29 21:45 UTC, adevyatova commented on docs/ru/sql-reference/operators/index.md
> +## Оператор логического ‘ИЛИ’ {#logical-or-operator}
```suggestion
## Оператор логического "ИЛИ" {#logical-or-operator}
```

2021-06-29 21:45 UTC, adevyatova commented on docs/ru/sql-reference/operators/index.md
> +## Оператор логического исключающего ‘ИЛИ’ {#logical-xor-operator}
```suggestion
## Оператор логического исключающего "ИЛИ" {#logical-xor-operator}
```

2021-07-02 01:44 UTC, alexey-milovidov requested changes

2021-07-02 01:44 UTC, alexey-milovidov commented on docs/ru/sql-reference/operators/index.md
> +Синтаксис `SELECT a XOR b` — вычисляет логическую исключающую дизъюнкцию между `a` и `b` функцией [xor](../../sql-reference/functions/logical-functions.md#logical-xor-function).
We don't have it:
```
milovidov-desktop :) SELECT 1 XOR 1

Syntax error: failed at position 14 ('1')
```

2021-07-07 21:34 UTC, alexey-milovidov approved these changes

2021-07-07 21:34 UTC, merged