DOCSUP-11416: Implement IDisk interface for HDFS
ClickHouse/ClickHouse pull request #26324
Opened 2021-07-14 18:45 UTC by sevirov

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:

- Documentation for #11058

2021-07-18 18:36 UTC, kssenii requested changes

2021-07-18 18:36 UTC, kssenii commented on docs/en/engines/table-engines/mergetree-family/mergetree.md
> +-   `thread_pool_size` — The number of threads in the Global Thread pool.
I do not think it is worth mentioning this second setting. It is more implementation like and mostly for code compatibility with s3 and the usage benefits of this setting are not proved.

2021-07-18 18:36 UTC, kssenii commented on docs/en/engines/table-engines/mergetree-family/mergetree.md
> +-   `endpoint` — HDFS endpoint URL in `path`. Endpoint URL should contain a bucket and root path to store data. The parameter is used to look up the HDFS configuration for retrieving files.
In hdfs there are no buckets in the same way as in s3. Here should only mention `root path`. 
Also second sentence does not sound correct. This parameter is **not** to look up **configuration**, but to look up the **files** actually as they are stored by those paths.

2021-07-22 16:41 UTC, sevirov commented
@kssenii Hi! Please, review this PR again.

2021-07-25 20:55 UTC, kssenii commented on docs/en/engines/table-engines/mergetree-family/mergetree.md
> +-   `endpoint` — S3 endpoint URL in `path` or `virtual hosted` [styles](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html). Endpoint URL should contain a root path to store data.
Previous explanation was more correct. See https://github.com/ClickHouse/ClickHouse/blob/master/src/IO/S3Common.h#L58-L64.

2021-07-26 20:59 UTC, kssenii approved these changes

2021-07-26 20:59 UTC, merged