Fix event_time_microseconds for REMOVE_PART in system.part_log
ClickHouse/ClickHouse pull request #26720
Opened 2021-07-22 21:59 UTC by azat

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix event_time_microseconds for REMOVE_PART in system.part_log

Fixes: #20027 (cc @bharatnc )

2021-07-22 22:04 UTC, kitaisreal approved these changes

2021-07-22 22:48 UTC, bharatnc approved these changes

2021-07-24 12:07 UTC, alexey-milovidov commented
@azat Changelog entry does not explain the change for users.

2021-07-24 12:07 UTC, alexey-milovidov requested changes
^

2021-07-24 12:08 UTC, alexey-milovidov approved these changes

2021-07-24 12:09 UTC, merged

2021-07-24 12:09 UTC, alexey-milovidov commented
I've fixed it.