clickhouse-local enhancements
ClickHouse/ClickHouse pull request #273
Opened 2016-12-19 22:58 UTC by ludv1x

Added --stacktrace option to clickhouse-local. [#METR-23765]
Added support of path config variable and ability to load clickhouse-server data. [#METR-20000]
Default database of clickhouse-local is changed to "_local" to avoid collisions with clickhouse-server.

Small fixes and enhancements of command line options (setting and limits). [#METR-23101]

2016-12-19 23:07 UTC, alexey-milovidov requested changes

2016-12-19 23:07 UTC, alexey-milovidov commented on dbms/src/Server/LocalServer.cpp
> +/// If path specified and isn't empty, try setup server enviroment and load existsing metadata
Typo.

2016-12-19 23:07 UTC, alexey-milovidov commented on dbms/src/Server/Server.cpp
> +	Logger * log = &logger();
Why this is necessary?

2016-12-20 11:40 UTC, ludv1x commented on dbms/src/Server/Server.cpp
> +	Logger * log = &logger();
It's a matter of taste-)
It was strange to me that main server function begins with explicit low-level string manipulations.
Reverted.

2016-12-20 13:09 UTC, alexey-milovidov commented on dbms/src/Server/Server.cpp
> +	Logger * log = &logger();
I mention only `Logger * log = &logger();` line.

2016-12-20 14:53 UTC, ludv1x commented on dbms/src/Server/Server.cpp
> +	Logger * log = &logger();
The same line is in [master](https://github.com/yandex/ClickHouse/blob/master/dbms/src/Server/Server.cpp#L183) now. It is used in `Server::main` for [logging](https://github.com/yandex/ClickHouse/blob/master/dbms/src/Server/Server.cpp#L235).

2016-12-20 15:57 UTC, alexey-milovidov commented on dbms/src/Server/Server.cpp
> +	Logger * log = &logger();
Now it is unused variable?

2016-12-20 20:06 UTC, ludv1x commented on dbms/src/Server/Server.cpp
> +	Logger * log = &logger();
It is used now.

2016-12-20 20:11 UTC, merged

2016-12-20 20:55 UTC, alexey-milovidov commented on dbms/src/Server/LocalServer.cpp
> -	{ \
:-1:

2016-12-20 21:00 UTC, alexey-milovidov commented on dbms/src/Server/LocalServer.cpp
> -	{ \
https://github.com/yandex/ClickHouse/commit/bade1519ba543c355d2e4f607a474b418346043f
https://github.com/yandex/ClickHouse/commit/b6fb08c77fda64936bf7e7b1dc0d66d9ffef3eae

2016-12-20 21:47 UTC, ludv1x commented on dbms/src/Server/LocalServer.cpp
> -	{ \
Do you check that `--help` works properly after this chnage?