Make query with param ast result consistent with as without it
ClickHouse/ClickHouse pull request #27386
Opened 2021-08-07 12:32 UTC by kssenii

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make query with parameter ast result consistent with as without it because otherwise it leads to incorrect query result. Closes https://github.com/ClickHouse/ClickHouse/issues/26912.

p.s. The issue is present with query parameter via http and not via clickhouse client, because with client the same query is parsed into ast twice - before and after changing query param in ast and as a result it gets consistent with as how it would have been if it was not a parameter. With http it is done only once - when it gets into executeQuery.

2021-08-09 08:57 UTC, kitaisreal approved these changes

2021-08-09 08:57 UTC, kitaisreal commented on src/Interpreters/ReplaceQueryParameterVisitor.cpp
> +    ast = parseQuery(parser, cast, cast.data() + cast.size(), settings.max_query_size, settings.max_parser_depth);
@kssenii why this is needed. Consider to add example with better explanation.

2021-08-10 17:10 UTC, tavplubix requested changes
It does not fix the root cause of the issue

2021-08-10 17:11 UTC, tavplubix commented
```
$ echo "select groupArray(1) from numbers(22) where number = (select toInt64(1))" | curl 'http://localhost:8123/' --data-binary @-
curl: (52) Empty reply from server
$ grep -Fa Fatal info.log
2021.08.10 20:08:05.877461 [ 38069 ] {490a8fa3-597e-4829-bc13-a5422de115b3} <Fatal> : Logical error: 'Bad cast from type DB::ColumnVector<signed char> to DB::ColumnVector<char8_t>'.
2021.08.10 20:08:05.879014 [ 38851 ] {} <Fatal> BaseDaemon: ########################################
2021.08.10 20:08:05.879305 [ 38851 ] {} <Fatal> BaseDaemon: (version 21.9.1.1, build id: B680AFA06A6B1469) (from thread 38069) (query_id: 490a8fa3-597e-4829-bc13-a5422de115b3) Received signal Aborted (6)
2021.08.10 20:08:05.879500 [ 38851 ] {} <Fatal> BaseDaemon: 
2021.08.10 20:08:05.879774 [ 38851 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f6e6ecc718b 0x7f6e6eca6859 0x132f9066 0x132f9175 0x1360f246 0x14c1b0d5 0x14c1b7e7 0x1e40b808 0x1e3b8994 0x1f8e738d 0x1f8e5421 0x1f5c8efc 0x1f5c8e5f 0x1f5c8dfd 0x1f5c8dbd 0x1f5c8d95 0x1f5c8d5d 0x13347e09 0x13346f35 0x1f5c774d 0x1f5c8139 0x1f5c5fe4 0x1f5c52d3 0x1e960b8d 0x1f49056d 0x1f49226d 0x1f520562 0x23bbf91c 0x23bc01a4 0x23d1a783 0x23d1703d 0x23d15dc8 0x7f6e6ee8d609 0x7f6e6eda3103
2021.08.10 20:08:05.881692 [ 38851 ] {} <Fatal> BaseDaemon: 4. /build/glibc-YYA7BZ/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51: __GI_raise @ 0x4618b in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2021.08.10 20:08:05.887165 [ 38851 ] {} <Fatal> BaseDaemon: 5. /build/glibc-YYA7BZ/glibc-2.31/stdlib/abort.c:81: abort @ 0x25859 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2021.08.10 20:08:06.182050 [ 38851 ] {} <Fatal> BaseDaemon: 6. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Common/Exception.cpp:53: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&) @ 0x132f9066 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:06.438541 [ 38851 ] {} <Fatal> BaseDaemon: 7. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Common/Exception.cpp:60: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x132f9175 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:06.791889 [ 38851 ] {} <Fatal> BaseDaemon: 8. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Common/assert_cast.h:47: DB::ColumnVector<char8_t> const& assert_cast<DB::ColumnVector<char8_t> const&, DB::IColumn const&>(DB::IColumn const&) @ 0x1360f246 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:07.038739 [ 38851 ] {} <Fatal> BaseDaemon: 9. /home/avtokmakov/ch/ClickHouse/build_debug/../src/AggregateFunctions/AggregateFunctionGroupArray.h:161: DB::GroupArrayNumericImpl<char8_t, DB::GroupArrayTrait<false, (DB::Sampler)0> >::add(char*, DB::IColumn const**, unsigned long, DB::Arena*) const @ 0x14c1b0d5 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:07.292342 [ 38851 ] {} <Fatal> BaseDaemon: 10. /home/avtokmakov/ch/ClickHouse/build_debug/../src/AggregateFunctions/IAggregateFunction.h:391: DB::IAggregateFunctionHelper<DB::GroupArrayNumericImpl<char8_t, DB::GroupArrayTrait<false, (DB::Sampler)0> > >::addBatchSinglePlace(unsigned long, char*, DB::IColumn const**, DB::Arena*, long) const @ 0x14c1b7e7 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:08.441329 [ 38851 ] {} <Fatal> BaseDaemon: 11. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/Aggregator.cpp:845: void DB::Aggregator::executeWithoutKeyImpl<false>(char*&, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, DB::Arena*) @ 0x1e40b808 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:09.576500 [ 38851 ] {} <Fatal> BaseDaemon: 12. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/Aggregator.cpp:988: DB::Aggregator::executeOnBlock(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >, unsigned long, DB::AggregatedDataVariants&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >&, std::__1::vector<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >, std::__1::allocator<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > > >&, bool&) @ 0x1e3b8994 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:10.137170 [ 38851 ] {} <Fatal> BaseDaemon: 13. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Processors/Transforms/AggregatingTransform.cpp:533: DB::AggregatingTransform::consume(DB::Chunk) @ 0x1f8e738d in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:10.686042 [ 38851 ] {} <Fatal> BaseDaemon: 14. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Processors/Transforms/AggregatingTransform.cpp:494: DB::AggregatingTransform::work() @ 0x1f8e5421 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:11.198006 [ 38851 ] {} <Fatal> BaseDaemon: 15. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Processors/Executors/PipelineExecutor.cpp:88: DB::executeJob(DB::IProcessor*) @ 0x1f5c8efc in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:11.689080 [ 38851 ] {} <Fatal> BaseDaemon: 16. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Processors/Executors/PipelineExecutor.cpp:105: DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const @ 0x1f5c8e5f in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:12.191593 [ 38851 ] {} <Fatal> BaseDaemon: 17. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x1f5c8dfd in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:12.677060 [ 38851 ] {} <Fatal> BaseDaemon: 18. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x1f5c8dbd in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:13.176316 [ 38851 ] {} <Fatal> BaseDaemon: 19. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/functional:1608: std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()>::operator()() @ 0x1f5c8d95 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:13.657744 [ 38851 ] {} <Fatal> BaseDaemon: 20. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/functional:2089: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x1f5c8d5d in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:13.909091 [ 38851 ] {} <Fatal> BaseDaemon: 21. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/functional:2221: std::__1::__function::__policy_func<void ()>::operator()() const @ 0x13347e09 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2021.08.10 20:08:14.154610 [ 38851 ] {} <Fatal> BaseDaemon: 22. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/functional:2560: std::__1::function<void ()>::operator()() const @ 0x13346f35 in /home/avtokmakov/ch/ClickH [...]

2021-12-14 20:02 UTC, closed without merging