CLICKHOUSE-3847 add restore replica
ClickHouse/ClickHouse pull request #2758
Opened 2018-07-30 16:32 UTC by VadimPE

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

2018-07-30 17:42 UTC, VadimPE commented on dbms/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp
> +    if (code && code != ZooKeeperImpl::ZooKeeper::ZNODEEXISTS)
Is it correct?

2018-07-30 18:38 UTC, alexey-milovidov commented on dbms/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp
> +    if (code && code != ZooKeeperImpl::ZooKeeper::ZNODEEXISTS)
Not quite.

2018-07-31 12:26 UTC, yurial requested changes

2018-07-31 12:26 UTC, yurial commented on dbms/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp
> +        if (zookeeper->exists(storage.zookeeper_path + "/replicas/" + replica + "/is_active"))
Возможно, я не до конца понял код, но мне кажется, что сейчас записи в логе сохраняются только для is_active реплик, в то время как в задаче идет речь про !is_lost. В текущей реализации даже кратковременное выключение реплики приведет к удалению из лога записей для нее.

На мой взгляд, правильный код должен выглядеть так:
```
if (!zookeeper->exists(storage.zookeeper_path + "/replicas/" + replica + "/is_lost")) {
    min_pointer = std::min(min_pointer, log_pointer);
    if (!zookeeper->exists(storage.zookeeper_path + "/replicas/" + replica + "/is_active")) {
        log_pointers_lost_replicas[replica] = log_pointer;
        }
}
```

Перед установкой флага is_lost необходимо проверять, что log_pointer выходит за лимит количества записей лога.

2018-07-31 13:00 UTC, VadimPE commented on dbms/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp
> +        if (zookeeper->exists(storage.zookeeper_path + "/replicas/" + replica + "/is_active"))
Нет, выключение реплики не всегда будет приводить к удалению записей для нее (только если ее log_pointer будет указывать на удаляемые записи ). Сейчас происходит проверка на  то, что log_pointer выходит за границы.

2018-07-31 14:46 UTC, alexey-milovidov commented on dbms/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp
> +        if (zookeeper->exists(storage.zookeeper_path + "/replicas/" + replica + "/is_active"))
Alexey Milovidov, [31.07.18 17:43]
Правильная логика:

Только неактивные реплики можно пометить как is_lost,
если их log_pointer слишком отстал.

Alexey Milovidov, [31.07.18 17:44]
Для активных - сохраняются все логи даже если они отстают.

Alexey Milovidov, [31.07.18 17:44]
Причина такого поведения - избежать сложные рейсы, когда реплика начала отставать, когда она живая.

Vadim Plh, [31.07.18 17:44]
Так сейчас и происходит у меня

Alexey Milovidov, [31.07.18 17:45]
Значит ты всё правильно сделал :)
Код ещё не смотрел. Я пока попросил Алексея тоже посмотреть.

2018-08-01 15:45 UTC, VadimPE commented on dbms/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp
> +        if (zookeeper->exists(storage.zookeeper_path + "/replicas/" + replica + "/is_active"))
@yurial Да, все верно.

2018-08-01 22:32 UTC, alexey-milovidov commented on dbms/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp
> +        if (zookeeper->exists(storage.zookeeper_path + "/replicas/" + replica + "/is_active"))
Надо две настройки.
Одна - говорит о том, что столько записей держать всегда, даже если они не нужны.
Другая - говорит о том, сколько максимум записей держать, если они нужны каким-то репликам.

2018-08-01 22:33 UTC, alexey-milovidov commented on dbms/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp
> +        if (zookeeper->exists(storage.zookeeper_path + "/replicas/" + replica + "/is_active"))
Давай в качестве второй настройки будем использовать `max_replicated_logs_to_keep`, а в качестве первой введём `min_replicated_logs_to_keep`.

2018-08-02 15:40 UTC, ztlpn requested changes

2018-08-02 15:40 UTC, ztlpn commented on dbms/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp
> +            ops.emplace_back(zkutil::makeCreateRequest(storage.zookeeper_path + "/replicas/" + pair.first + "/is_lost", "",
But for each replica we should use a transaction to simultaneously check that `log_pointer` hasn't changed in the meantime and the replica is still inactive.

2018-08-08 13:47 UTC, ztlpn commented on dbms/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp
> +    String min_saved_record_log_str = entries[std::max(0, entries.size() - storage.data.settings.max_replicated_logs_to_keep.value)];
`entries.size()` and  `storage.data.settings.max_replicated_logs_to_keep.value` are both unsigned, so subtracting them is very dangerous.

2018-08-13 21:01 UTC, ztlpn requested changes

2018-08-27 16:30 UTC, ztlpn approved these changes
LGTM 👍
Still missing test.

2018-08-28 00:46 UTC, merged