Introduce "settings" configuration key to system tables
ClickHouse/ClickHouse pull request #27790
Opened 2021-08-17 13:51 UTC by alexeypavlenko

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Introduce `settings` options for system table configuration.

Detailed description / Documentation draft:
Configuration of system table (like e.g. query_log) currently allows to specify partitioning and ttl. The latter, however, may be not efficient alone, unless they are complemented with setting like `ttl_only_drop_parts=1`. This PR intends to add a new option `settings` to system table configuration, thus bringing it on par with `engine` key.

> By adding documentation, you'll allow users to try your new feature immediately, not when someone else will have time to document it later. Documentation is necessary for all features that affect user experience in any way. You can add brief documentation draft above, or add documentation right into your patch as Markdown files in [docs](https://github.com/ClickHouse/ClickHouse/tree/master/docs) folder.

> If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ClickHouse Documentation](https://github.com/ClickHouse/ClickHouse/tree/master/docs/README.md) guide first.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

2021-08-18 14:24 UTC, alexeypavlenko commented
@nikitamikhaylov , if currently tests are flaky or does it seem to be strongly related to the PR?

2021-08-18 20:04 UTC, alexeypavlenko commented
Rebased.

2021-08-26 15:02 UTC, nikitamikhaylov approved these changes

2021-08-27 01:37 UTC, alexey-milovidov requested changes

2021-08-27 12:46 UTC, closed without merging