Set force_restore_data in stress tests
ClickHouse/ClickHouse pull request #28296
Opened 2021-08-28 09:29 UTC by azat

CI report [1]:

<details>

```
    $ pigz -cd clickhouse-server.log.gz | fgrep 'Application: DB::Exception:' -m1
2021.08.25 11:34:10.208309 [ 9275 ] {} <Error> Application: DB::Exception: The local set of parts of table test_96v1zj.dst_10 doesn't look like the set of parts in ZooKeeper: 4.00 rows of 4.00 total rows in filesystem are suspicious. There are 1 unexpected parts with 4 rows (0 of them is not just-written with 0 rows), 0 missing parts (with 0 blocks).: Cannot attach table `test_96v1zj`.`dst_10` from metadata file /var/lib/clickhouse/metadata/test_96v1zj/dst_10.sql from query ATTACH TABLE test_96v1zj.dst_10 (`p` UInt64, `k` UInt64, `v` UInt64) ENGINE = ReplicatedMergeTree('/test/01154_move_partition_long_test_96v1zj/dst', '10') PARTITION BY p % 10 ORDER BY k SETTINGS index_granularity = 8192: while loading database `test_96v1zj` from path /var/lib/clickhouse/metadata/test_96v1zj
```

</details>

  [1]: https://clickhouse-test-reports.s3.yandex.net/27881/e8d87053c04e8e30bb35fa46298abb521818731f/stress_test_(undefined).html#fail1

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

2021-08-28 10:21 UTC, alexey-milovidov requested changes
This situation should not happen in stress test.
We should fix the root cause.

2021-09-09 07:19 UTC, azat commented
>This situation should not happen in stress test.

Indeed, but there problem here is DROP fails in the middle, `parts/*` znodes had been removed already but replica path had not been completely removed, so later this replica will not be considered as new replica.

Maybe replica should set some flag in dropReplica (not under replica_path), and later attach can check it, and attach table in read-only mode if it set? @alesapin what do you think? 

### Logs

```
2021.09.02 23:10:16.203598 [ 18964 ] {86789434-b69c-4367-b021-26ab33d4ef4c} <Debug> executeQuery: (from [::1]:55820) (comment: '/usr/share/clickhouse-test/queries/0_stateless/00993_system_parts_race_condition_drop_zookeeper.sh') DROP TABLE IF EXISTS alter_table_4
2021.09.02 23:10:16.308794 [ 18964 ] {86789434-b69c-4367-b021-26ab33d4ef4c} <Information> test_1.alter_table_4: Removing replica /clickhouse/tables/00993_system_parts_race_condition_drop_zookeeper_test_1/alter_table/replicas/r_4, marking it as lost
2021.09.02 23:10:31.612931 [ 18964 ] {86789434-b69c-4367-b021-26ab33d4ef4c} <Error> executeQuery: Code: 999. Coordination::Exception: Operation timeout. (KEEPER_EXCEPTION) (version 21.10.1.7982) (from [::1]:55820) (comment: '/usr/share/clickhouse-test/queries/0_stateless/00993_system_parts_race_condition_drop_zookeeper.sh') (in query: DROP TABLE IF EXISTS alter_table_4), Stack trace (when copying this message, always include the lines below):
... # so it failed during recursive removal of replica path, and it removes parts, but does not removes the root
2021.09.02 23:25:36.963361 [ 13472 ] {b81137a0-396c-4238-85eb-e02aa16b45d5} <Trace> InterpreterSystemQuery: Restarting replica on test_1.alter_table_4
2021.09.02 23:25:39.437203 [ 1828 ] {} <Debug> test_1.alter_table_4: Loading data parts
2021.09.02 23:26:08.953889 [ 13472 ] {b81137a0-396c-4238-85eb-e02aa16b45d5} <Error> executeQuery: Code: 231. DB::Exception: The local set of parts of table test_1.alter_table_4 doesn't look like the set of parts in ZooKeeper: 295.09 thousand rows of 295.09 thousand total rows in filesystem are suspicious. There are 57 unexpected parts with 295090 rows (9 of them is not just-written with 42556 rows), 0 missing parts (with 0 blocks). (TOO_MANY_UNEXPECTED_DATA_PARTS) (version 21.10.1.7982) (from [::1]:58192) (comment: 01646_system_restart_replicas_smoke.sql) (in query: SYSTEM RESTART REPLICAS;), Stack trace (when copying this message, always include the lines below):
... and here it fails, because there are no parts in keeper
```

### Keeper

```
(CONNECTED [127.1:2182]) /> json_cat /clickhouse/tables/00993_system_parts_race_condition_drop_zookeeper_test_1/alter_table/replicas/r_4/is_lost
1
(CONNECTED [127.1:2182]) /> stat /clickhouse/tables/00993_system_parts_race_condition_drop_zookeeper_test_1/alter_table/replicas/r_4/is_lost
Stat(
  czxid=0xc3d5
  mzxid=0xed1b
  ctime=1630613343856
  mtime=1630613416310
  version=2
  cversion=0
  aversion=0
  ephemeralOwner=0x0
  dataLength=1
  numChildren=0
  pzxid=0xc3d5
)
(CONNECTED [127.1:2182]) /> ls /clickhouse/tables/00993_system_parts_race_condition_drop_zookeeper_test_1/alter_table/replicas/r_4
columns
flags
host
is_lost
log_pointer
max_processed_insert_time
metadata
metadata_version
min_unprocessed_insert_time
mutation_pointer
parts
queue
(CONNECTED [127.1:2182]) /> ls /clickhouse/tables/00993_system_parts_race_condition_drop_zookeeper_test_1/alter_table/replicas/r_4/parts

# no parts
```

2021-09-28 08:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=28296) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=28296) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=28296) it.</sub>

2021-10-02 07:57 UTC, azat commented
More of this - https://clickhouse-test-reports.s3.yandex.net/0/41924c9a2bc7834f80f57f2f27aa4fbf84f8a7f1/stress_test_(memory).html#fail1

2021-10-27 18:38 UTC, closed without merging