CLICKHOUSE-3211 add TOP m, and OFFSET k
ClickHouse/ClickHouse pull request #2840
Opened 2018-08-10 11:13 UTC by VadimPE

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

2018-08-10 11:27 UTC, zhang2014 commented
What does this do? It looks like it's the same as the `limit`

2018-08-10 11:32 UTC, VadimPE commented
@zhang2014 You are right) It seems like a `LIMIT`

2018-08-10 15:29 UTC, zhang2014 commented
So why do we need it?

2018-08-10 15:46 UTC, VadimPE commented
@zhang2014 
![image](https://user-images.githubusercontent.com/18518081/43967668-98ad10b4-9ccd-11e8-8dcb-bb2368036f91.png)

2018-08-10 15:50 UTC, VadimPE commented
![image](https://user-images.githubusercontent.com/18518081/43967882-3ee4e056-9cce-11e8-8d42-def7555ef4e4.png)

2018-08-10 15:55 UTC, VadimPE commented
@zhang2014
For TOP ... WITH TIES

2018-08-10 17:29 UTC, derekperkins commented
Does this solve this issue in https://github.com/yandex/ClickHouse/issues/2198?

2018-08-10 17:30 UTC, alexey-milovidov commented
> Does this solve this issue in #2198?

No. The task #2198 is still unassigned.

2018-08-10 17:36 UTC, alexey-milovidov commented
> So why do we need it? I'm just curious : )

LIMIT OFFSET is required for compatibility.
This syntax exist in PostgreSQL and was standardized in SQL 2008.
Some tools will generate queries using this syntax (instead of `LIMIT n, m`).
It also was added in MySQL with the same motivation.

And `SELECT TOP` is a bonus (compatibility with MS SQL + allows the implementation `WITH TIES`. We could add `WITH TIES` also after `LIMIT` but it's more known in MS SQL `TOP` syntax).

2018-08-10 17:40 UTC, alexey-milovidov requested changes
We should throw an exception if offset is specified in both forms `LIMIT 10, 20 OFFSET 30` or if both `LIMIT` and `TOP` are specified.

Test should check that exceptions are thrown.

2018-08-13 23:43 UTC, alexey-milovidov commented on dbms/tests/queries/0_stateless/00687_top_and_offset.sql
> +SELECT TOP 2 * FROM test.test;
The test is non-deterministic due to lack of ORDER BY.

2018-08-13 23:45 UTC, alexey-milovidov commented on dbms/tests/queries/0_stateless/00687_top_and_offset.sql
> +SELECT TOP 2 * FROM test.test LIMIT 2; -- { clientError 406 }
Negative test for `LIMIT n, m OFFSET k` is pending.

2018-08-14 09:55 UTC, merged