DOCSUP-13875: Document the replication_wait_for_inactive_replica_timeout setting
ClickHouse/ClickHouse pull request #28464
Opened 2021-09-01 20:38 UTC by sevirov

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:

- Documentation for #27931

2021-09-03 06:16 UTC, olgarev commented on docs/en/operations/settings/settings.md
> +Allows to specify waiting for actions to manipulate the partitions.
```suggestion
Allows to specify the delay for actions that manipulate the partitions.
```

2021-09-03 06:31 UTC, olgarev commented on docs/en/operations/settings/settings.md
> +-   2 — To wait for everyone.
```suggestion
-   0 — Do not wait. Means that the next action can start any time, not waiting for the previous action to be completed.
-   1 — Wait for own execution. Means that the next action on the partition starts only after the previous action is completed on this partition.
-   2 — Wait for everyone. Means that the next action starts only after the previous action is completed on all partitions.
```

2021-09-03 06:32 UTC, olgarev commented on docs/en/operations/settings/settings.md
> +Allows to specify how long (in seconds) to wait for inactive replicas to execute [ALTER](../../sql-reference/statements/alter/index.md), [OPTIMIZE](../../sql-reference/statements/optimize.md) or [TRU
```suggestion
Specifies how long (in seconds) to wait for inactive replicas to execute [ALTER](../../sql-reference/statements/alter/index.md), [OPTIMIZE](../../sql-reference/statements/optimize.md) or [TRUNCATE](../../sql-reference/statements/truncate.md) queries.
```

2021-09-03 06:33 UTC, olgarev commented on docs/en/operations/settings/settings.md
> +-   Positive integer — The number of seconds of waiting.
```suggestion
-   Negative integer — Wait for unlimited time.
-   Positive integer — The number of seconds to wait.
```

2021-09-03 06:34 UTC, olgarev commented on docs/en/sql-reference/statements/alter/index.md
> +You can to specify how long (in seconds) to wait for inactive replicas to execute all `ALTER` queries by the [replication_wait_for_inactive_replica_timeout seconds](../../../operations/settings/setti
```suggestion
You can to specify how long (in seconds) to wait for inactive replicas to execute all `ALTER` queries with the [replication_wait_for_inactive_replica_timeout seconds](../../../operations/settings/settings.md#replication-wait-for-inactive-replica-timeout) setting.
```

2021-09-03 06:36 UTC, olgarev commented on docs/en/sql-reference/statements/alter/index.md
> +    For all `ALTER` queries, if the `replication_alter_partitions_sync` setting is `2` and some replicas are not active for more than the time specified by the `replication_wait_for_inactive_replica_
```suggestion
    For all `ALTER` queries, if `replication_alter_partitions_sync = 2` and some replicas are not active for more than the time, specified in the `replication_wait_for_inactive_replica_timeout seconds` setting, then an exception `UNFINISHED` is thrown.
```

2021-09-03 06:38 UTC, olgarev commented on docs/en/sql-reference/statements/optimize.md
> +    If the [replication_alter_partitions_sync](../../operations/settings/settings.md#replication-alter-partitions-sync) setting is `2` and some replicas are not active for more than the time specifie
```suggestion
    If the [replication_alter_partitions_sync](../../operations/settings/settings.md#replication-alter-partitions-sync) is set to `2` and some replicas are not active for more than the time, specified by the [replication_wait_for_inactive_replica_timeout seconds](../../operations/settings/settings.md#replication-wait-for-inactive-replica-timeout) setting, then an exception `UNFINISHED` is thrown.
```

2021-09-03 06:39 UTC, olgarev commented on docs/en/sql-reference/statements/truncate.md
> +You can to specify how long (in seconds) to wait for inactive replicas to execute `TRUNCATE` queries by the [replication_wait_for_inactive_replica_timeout seconds](../../operations/settings/settings.
```suggestion
You can to specify how long (in seconds) to wait for inactive replicas to execute `TRUNCATE` queries with the [replication_wait_for_inactive_replica_timeout seconds](../../operations/settings/settings.md#replication-wait-for-inactive-replica-timeout) setting.
```

2021-09-03 06:39 UTC, olgarev commented on docs/en/sql-reference/statements/truncate.md
> +    If the [replication_alter_partitions_sync](../../operations/settings/settings.md#replication-alter-partitions-sync) setting is `2` and some replicas are not active for more than the time specifie
```suggestion
    If the [replication_alter_partitions_sync](../../operations/settings/settings.md#replication-alter-partitions-sync) is set to `2` and some replicas are not active for more than the time, specified by the [replication_wait_for_inactive_replica_timeout seconds](../../operations/settings/settings.md#replication-wait-for-inactive-replica-timeout) setting, then an exception `UNFINISHED` is thrown.
```

2021-09-08 00:21 UTC, olgarev commented on docs/en/operations/settings/settings.md
> +-   2 — Wait for everyone. Means that the next action starts only after the previous action is completed on all partitions.
```suggestion
-   0 — Do not wait. The next action can start any time, not waiting for the previous action to be completed.
-   1 — Wait for own execution. The next action on the partition starts only after the previous action is completed on this partition.
-   2 — Wait for everyone. The next action starts only after the previous action is completed on all partitions.
```

2021-09-08 00:22 UTC, olgarev commented on docs/en/sql-reference/statements/alter/index.md
> +You can to specify how long (in seconds) to wait for inactive replicas to execute all `ALTER` queries with the [replication_wait_for_inactive_replica_timeout seconds](../../../operations/settings/set
```suggestion
You can specify how long (in seconds) to wait for inactive replicas to execute all `ALTER` queries with the [replication_wait_for_inactive_replica_timeout seconds](../../../operations/settings/settings.md#replication-wait-for-inactive-replica-timeout) setting.
```

2021-09-08 00:22 UTC, olgarev commented on docs/en/sql-reference/statements/optimize.md
> +You can to specify how long (in seconds) to wait for inactive replicas to execute `OPTIMIZE` queries by the [replication_wait_for_inactive_replica_timeout seconds](../../operations/settings/settings.
```suggestion
You can specify how long (in seconds) to wait for inactive replicas to execute `OPTIMIZE` queries by the [replication_wait_for_inactive_replica_timeout seconds](../../operations/settings/settings.md#replication-wait-for-inactive-replica-timeout) setting.
```

2021-09-08 00:23 UTC, olgarev commented on docs/en/sql-reference/statements/truncate.md
> +You can to specify how long (in seconds) to wait for inactive replicas to execute `TRUNCATE` queries with the [replication_wait_for_inactive_replica_timeout seconds](../../operations/settings/setting
```suggestion
You can specify how long (in seconds) to wait for inactive replicas to execute `TRUNCATE` queries with the [replication_wait_for_inactive_replica_timeout seconds](../../operations/settings/settings.md#replication-wait-for-inactive-replica-timeout) setting.
```

2021-09-08 00:24 UTC, olgarev commented on docs/ru/operations/settings/settings.md
> +-   2 — ждать выполнения действия на всех партициях. Означает, что следующее действие начинается только после завершения предыдущего действия на всех партициях.
```suggestion
-   0 — не ждать. Означает, что следующее действие может начаться в любое время, не дожидаясь завершения предыдущего действия.
-   1 — ждать выполнения действия на одной партиции. Означает, что следующее действие на партиции начинается только после завершения предыдущего действия на этой партиции.
-   2 — ждать выполнения действия на всех партициях. Означает, что следующее действие начинается только после завершения предыдущего действия на всех партициях.
```

2021-09-08 00:24 UTC, olgarev commented on docs/ru/operations/settings/settings.md
> +Значение по умолчанию: `120`.
```suggestion
Значение по умолчанию: `120` секунд.
```

2021-09-08 00:25 UTC, olgarev commented on docs/en/operations/settings/settings.md
> +Default value: `120`.
```suggestion
Default value: `120` seconds.
```

2021-09-08 19:27 UTC, sevirov commented
@tavplubix Please, review this PR.

2021-09-09 09:49 UTC, tavplubix requested changes

2021-09-09 09:49 UTC, tavplubix commented on docs/en/operations/settings/settings.md
> +-   2 — Wait for everyone. The next action starts only after the previous action is completed on all partitions.
What is "the next action" and "the previous action"?

2021-09-09 09:49 UTC, tavplubix commented on docs/en/sql-reference/statements/alter/index.md
> +    For all `ALTER` queries, if `replication_alter_partitions_sync = 2` and some replicas are not active for more than the time, specified in the `replication_wait_for_inactive_replica_timeout second
It's rather a note than a warning

2021-09-09 17:43 UTC, tavplubix approved these changes

2021-09-09 17:43 UTC, tavplubix commented on docs/en/sql-reference/statements/optimize.md
> +When `OPTIMIZE` is used with the [ReplicatedMergeTree](../../engines/table-engines/mergetree-family/replication.md) family of table engines, ClickHouse creates a task for merging and waits for execut
It waits for all replicas if `replication_alter_partitions_sync` is set to 2 (and waits for current replica if it is set to 1)

2021-09-09 20:33 UTC, merged