Fix replication queue accumulation caused by the entries that has bee…
ClickHouse/ClickHouse pull request #29130
Opened 2021-09-17 11:58 UTC by zhongyuankai

…n failing

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

replication queue accumulation caused by the entries that has been failing.
```
database:               growth
table:                  aily_report_for_clickhouse_pages_local
replica_name:           03
position:               289
node_name:              queue-0000156831
type:                   REPLACE_RANGE
create_time:            2021-08-23 02:25:00
required_quorum:        0
source_replica:         04
new_part_name:
parts_to_merge:         []
is_detach:              0
is_currently_executing: 0
num_tries:              2638
last_exception:         Code: 234, e.displayText() = DB::Exception: Not found part 4a2e094c228d15c6c534804cdb411458_7_7_0 (or part covering it) neither source table neither remote replicas (version 102.1.1)
last_attempt_time:      2021-09-17 01:35:15
num_postponed:          8895
postpone_reason:
last_postpone_time:     2021-09-17 11:12:21

SELECT
    table,
    count(*)
FROM replication_queue
GROUP BY table

┌─table─────────────────────────────────────────────────────┬─count()─┐
│ daily_report_for_clickhouse_pages_local                   │     682 │
└───────────────────────────────────────────────────────────┴─────────┘
```
This failed entries cannot be successful no matter how many retries, I think it should be removed.

2021-09-17 14:40 UTC, nvartolomei commented
Em. This would likely lead to diverging replicas and broken invariants. Entries should be deleted from replica's queue only when we know for sure that all replicas will reach the same end state. Eg this is already done for GET_PART, where if we discover that no replicas have the part we just create an empty part instead. Otherwise, the server which wrote the log entry may be experiencing a network partition/be down and we'll delete the lgo entry, but if it comes up in few hours then it will have the part while all the other replicas won't have it anymore. This should not happen. Similar with replace range, maybe some replicas actaully suceeded running replace range but one is failing because the source server went down or something else...

2021-09-18 00:23 UTC, amosbird commented
(version 102.1.1) look like a local fork build.

2021-09-18 01:50 UTC, zhongyuankai commented
@nvartolomei What you said is correct, but in the face of some entries that are impossible to succeed, if they remain in the replication queue forever, all `ALTER TABLE` operations will be delayed, Maybe we can delete the timeout entries like avoiding deadlocks, like settings `max_replication_queue_entry_to_keep_seconds=7 * 24 * 60 * 60`.

2021-09-18 01:51 UTC, zhongyuankai commented
> (version 102.1.1) look like a local fork build.

Yes, this is the problem we encountered online.

2021-09-18 08:26 UTC, nvartolomei commented
@zhongyuankai there must be a better way. Do you understand how the server got into this state? Can you reproduce the issue? Maybe we need to add some new invariants. Like preventing dropping of the source range (complicated). Or, if we reach a state where we discover that data disappeared from the source replicas, and we can prove that this range won't appear in destination replicas and all replicas are in the same "blocked" state then drop this event with a warning/error log about "data lost forever". I guess that would be implemented in `executeReplaceRange`.

There might be a possibility that only some parts are lost rather than all (concurrent drop part(ition)?). In that case rather than dropping the whole entry we would want to ignore the missing parts but still transfer partially data. Or, abandon/rollback the operation (again, we must ensure that all replicas will reach the same result). 

PS. I'm not very familiar with `REPLACE_RANGE` mechanism. There might be some mistakes in my assumptions.

2021-09-19 22:03 UTC, tavplubix requested changes
It's bad idea to remove log entries, because replicas will diverge. See #25820

2021-09-19 22:21 UTC, tavplubix commented
The only thing we can (relatively) safely do is to call `enqueuePartForCheck`, but for `REPLACE_RANGE` entries we should search part in both source and destination tables. And we need to know what happened to part `4a2e094c228d15c6c534804cdb411458_7_7_0` and why it disappeared from all replicas. Some issues that might cause `REPLACE_RANGE` entry to stuck were recently fixed (for example, #24208,  #28035)

2021-09-22 08:46 UTC, zhongyuankai commented
@nvartolomei @tavplubix part 4a2e094c228d15c6c534804cdb411458_7_7_0 should be merged, Thus disappeared.

2021-09-26 04:58 UTC, zhongyuankai commented
@nvartolomei @tavplubix The reason for the problem is   `replica1` executes `ALTER TABLE table2 REPLACE PARTITION 20210926 FROM table1` of the same partition twice, but `replica2` starts the first `REPLACE PARTITION` after the two executions of `replica1` are completed. As a result, the part that needs to obtain `replica1` is deleted by the second `REPLACE PARTITION`, which leads to infinite retries,how do you think to avoid this situation.

2021-09-26 10:05 UTC, closed without merging