Add socket timeout values into SOCKET_TIMEOUT exception
ClickHouse/ClickHouse pull request #29180
Opened 2021-09-19 21:40 UTC by azat

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

2021-09-19 22:07 UTC, alexey-milovidov approved these changes

2021-09-20 01:24 UTC, alexey-milovidov requested changes

2021-09-20 01:24 UTC, alexey-milovidov commented on src/Client/Connection.cpp
> +            socket->getReceiveTimeout().totalMilliseconds(),
nullptr dereference after disconnect()

2021-09-20 06:54 UTC, azat commented on src/Client/Connection.cpp
> +            socket->getReceiveTimeout().totalMilliseconds(),
Indeed, nice catch, fixed

2021-09-20 09:28 UTC, alexey-milovidov approved these changes

2021-09-21 19:20 UTC, alexey-milovidov commented
#29231

2021-09-21 20:41 UTC, merged