Implemented modifying table comments with `ALTER TABLE t MODIFY COMMENT 'value'`
ClickHouse/ClickHouse pull request #29264
Opened 2021-09-22 14:51 UTC by Enmk

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Implemented `ALTER TABLE x MODIFY COMMENT`

Detailed description / Documentation draft:
Users can now add\remove\modify comments on existing tables.
 - `ALTER TABLE x MODIFY COMMENT 'new comment'` - sets table comment to be a `new comment`, regardless if it was set before or not.
 - `ALTER TABLE x MODIFY COMMENT ''` - removes a table comment.

Comment change is reflected in both `system.tables` and `SHOW CREATE TABLE`.

2021-09-23 10:51 UTC, alesapin requested changes

2021-09-23 10:51 UTC, alesapin commented on tests/queries/0_stateless/2020_alter_table_modify_comment.sh
> +test_table_comments "MergeTree() ORDER BY k"
Please, add a test with ReplicatedMergeTree.

2021-09-23 10:51 UTC, alesapin commented on tests/queries/0_stateless/2020_alter_table_modify_comment.sh
> +    $CLICKHOUSE_CLIENT --query="ALTER TABLE comment_test_table MODIFY COMMENT 'another comment on a table';"
Add detach table/attach table and check one more time.

2021-09-27 15:00 UTC, alesapin approved these changes

2021-09-27 15:01 UTC, alesapin commented
Integration tests not affected.

2021-09-27 15:02 UTC, merged

2021-09-27 16:45 UTC, sevirov commented
Internal documentation ticket: DOCSUP-15458

2023-06-23 03:15 UTC, alexey-milovidov commented
@alesapin, it's funny that even the test in this PR is wrong. It "cemented" the incorrect behavior.

2023-09-04 05:11 UTC, alexey-milovidov commented
@Enmk, it does not work at all.