DOCSUP-14788: Edit and translate to Russian
ClickHouse/ClickHouse pull request #30029
Opened 2021-10-12 11:32 UTC by karnevil13

Changelog category (leave one):

- Documentation for #27476 #23028, #28771

2021-10-12 12:13 UTC, KochetovNicolai approved these changes

2021-10-12 13:59 UTC, gyuton requested changes

2021-10-14 09:25 UTC, KochetovNicolai requested changes
.

2021-10-15 08:38 UTC, KochetovNicolai approved these changes

2021-10-15 08:38 UTC, merged