Low cardinality group by
ClickHouse/ClickHouse pull request #3138
Opened 2018-09-14 18:01 UTC by KochetovNicolai

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

2018-09-17 22:49 UTC, alexey-milovidov commented on dbms/src/Columns/IColumnUnique.h
> +    virtual const UInt64 * tryGetSavedHash() const = 0;
Missing comment (about the purpose of this method).

2018-09-20 17:44 UTC, alexey-milovidov commented on dbms/src/DataTypes/DataTypeWithDictionary.h
> +DataTypePtr removeLowCardinality(const DataTypePtr & type);
Missing comment.

2018-09-20 17:48 UTC, alexey-milovidov commented on dbms/src/Interpreters/Aggregator.h
> +    static const bool no_consecutive_keys_optimization = true;
Why it was changed?

2018-09-20 17:50 UTC, alexey-milovidov commented on dbms/src/Interpreters/Aggregator.h
> +    static StringRef getRef(const typename Data::value_type & value)
Does it mean "getKeyRef"? If so, why we pass value_type instead of key?

2018-09-20 17:50 UTC, alexey-milovidov commented on dbms/src/Interpreters/Aggregator.h
> +    static constexpr bool low_cardinality_optimization = false;
Inconsistent const/constexpr.

2018-09-20 18:01 UTC, alexey-milovidov commented on dbms/src/Interpreters/Aggregator.cpp
>      /// NOTE When editing this code, also pay attention to SpecializedAggregator.h.
TODO?

2018-09-20 18:02 UTC, alexey-milovidov commented on dbms/src/Interpreters/Aggregator.cpp
> +                     key, no_more_keys, overflow_row_ptr);
.

2018-09-20 18:03 UTC, alexey-milovidov requested changes
Almost Ok.

2018-09-21 09:55 UTC, KochetovNicolai commented on dbms/src/Interpreters/Aggregator.cpp
>      /// NOTE When editing this code, also pay attention to SpecializedAggregator.h.
TODO

2018-09-21 10:38 UTC, merged