Fix 'there are no such cluster here'
ClickHouse/ClickHouse pull request #31723
Opened 2021-11-24 17:46 UTC by tavplubix

Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed `there are no such cluster here` error on execution of `ON CLUSTER` query if specified cluster name is name of `Replicated` database.

2021-11-24 17:47 UTC, KochetovNicolai approved these changes

2021-11-25 01:59 UTC, alexey-milovidov commented
Please also fix the error message to `there is no such cluster here.`

2021-11-25 02:00 UTC, alexey-milovidov requested changes
.

2021-11-25 09:04 UTC, tavplubix commented
Stateless tests (memory, actions) - 02010_lc_native - fixed in master
Stateless tests (thread, actions) - 00979_live_view_watch_live is flaky, cc: @vzakaznikov

2021-11-25 14:28 UTC, merged