Check what will happen if we build ClickHouse with Musl
ClickHouse/ClickHouse pull request #31833
Opened 2021-11-25 21:10 UTC by alexey-milovidov

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

2022-04-18 00:38 UTC, alexey-milovidov commented
Need to merge with master after #36337.

2022-04-18 00:41 UTC, alexey-milovidov commented
Waiting for #36361.

2022-04-20 09:21 UTC, alesapin commented
Built without failures:
```
$ ldd ./clickhouse-keeper 
        statically linked
```
But for some reason, a lot of integration tests failed during keeper start.

2022-04-20 09:22 UTC, alesapin commented
@mergifyio update

2022-04-20 09:25 UTC, alesapin commented
@mergify up

2022-04-20 09:28 UTC, alesapin commented
@Mergifyio update

2022-04-20 09:42 UTC, alesapin commented
clear to me now -- we don't need to disable the embedded keeper build at all. We need to avoid symlink creation.

2022-04-21 21:26 UTC, alesapin commented
Works now

2022-04-21 21:34 UTC, alesapin commented
Waiting for all tests.

2022-04-22 09:19 UTC, alesapin commented
`02180_group_by_lowcardinality` -- flaky test.

2022-04-22 09:21 UTC, alesapin commented
Clear win:
![image](https://user-images.githubusercontent.com/3684697/164677007-7f20ef87-fc56-41aa-a52a-2ef784751f30.png)

2022-04-22 09:28 UTC, Felixoid requested changes
There're last things to check

2022-04-22 09:28 UTC, Felixoid commented on CMakeLists.txt
> +option(CREATE_KEEPER_SYMLINK "Create symlink for clickhouse-keeper to main server binary" ON)
I'd use here another construct
```suggestion
if (NOT BUILD_STANDALONE_KEEPER)
    option(CREATE_KEEPER_SYMLINK "Create symlink for clickhouse-keeper to main server binary" ON)
else ()
    option(CREATE_KEEPER_SYMLINK "Create symlink for clickhouse-keeper to main server binary" OFF)
endif ()
```

2022-04-22 09:28 UTC, Felixoid commented on docker/packager/packager
> +                cmake_flags.append("-DBUILD_STANDALONE_KEEPER=1")
A positive condition is more readable
```suggestion
            if is_cross_arm:
                cmake_flags.append("-DBUILD_STANDALONE_KEEPER=1")
            else:
                result.append("BUILD_MUSL_KEEPER=1")
```

2022-04-22 09:28 UTC, Felixoid commented on programs/CMakeLists.txt
> +endif ()
Pretty much the same thing about positive conditions for me :-j
```suggestion
if (USE_MUSL)
    # Only clickhouse-keeper can be built with musl currently
    option (ENABLE_CLICKHOUSE_ALL "Enable all ClickHouse modes by default" OFF)
else ()
    option (ENABLE_CLICKHOUSE_ALL "Enable all ClickHouse modes by default" ON)
endif ()
```

2022-04-22 09:28 UTC, Felixoid commented on programs/CMakeLists.txt
> +        endif()
It looks redundant to me. We need define ENABLE_CLICKHOUSE_KEEPER as `BUILD_STANDALONE_KEEPER OR CREATE_KEEPER_SYMLINK` above

2022-04-22 10:34 UTC, Felixoid approved these changes
let's wait for builds

2022-04-22 20:17 UTC, alesapin commented
Finally we did it.

2022-04-22 20:41 UTC, merged