Add a test with 20000 mutations in one query
ClickHouse/ClickHouse pull request #32122
Opened 2021-12-02 11:58 UTC by KochetovNicolai

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes #23503 and #31251
Bug was fixed in #19587 (and would't be backported).

2021-12-02 13:10 UTC, KochetovNicolai commented
`2021.12.02 09:03:08.033644 [ 468 ] {} <Fatal> Application: Child process was terminated by signal 12`

2021-12-02 16:33 UTC, alexey-milovidov requested changes
Should add drop tables to more convenient running the test manually.

2021-12-05 13:35 UTC, alexey-milovidov commented
@KochetovNicolai Test has failed.

2021-12-06 15:38 UTC, KochetovNicolai commented
`AST fuzzer (TSan, actions)  : ThreadSanitizer: out-of-memory`
`AST fuzzer (debug, actions) `
```
2021.12.02 15:47:45.823288 [ 105 ] {} <Trace> BaseDaemon: Received signal 10
2021.12.02 15:47:45.823399 [ 105 ] {} <Debug> BaseDaemon: Received signal to close logs.
```
`Stateful tests (debug, actions)`
```
2021.12.02 08:47:46.547304 [ 188 ] {} <Trace> BaseDaemon: Received signal 15
```
`02125_many_mutations - Timeout dropping database test_xzqjftrg after test`

2021-12-06 19:09 UTC, merged

2021-12-07 08:54 UTC, tavplubix commented
@KochetovNicolai, Style Check failure looks related

2021-12-07 08:57 UTC, tavplubix commented
And new test is flaky, because 20000 queries is too much for debug build and builds with sanitizers