Use ack/rel semantic for MergeTreeBackgroundExecutor mertic.
ClickHouse/ClickHouse pull request #32125
Opened 2021-12-02 12:33 UTC by KochetovNicolai

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

2021-12-02 12:42 UTC, nikitamikhaylov approved these changes

2021-12-02 16:30 UTC, alexey-milovidov requested changes

2021-12-02 16:30 UTC, alexey-milovidov commented on src/Storages/MergeTree/MergeTreeBackgroundExecutor.h
> +        CurrentMetrics::values[metric].fetch_add(1);
Missing a comment with motivation.

2021-12-06 12:21 UTC, nikitamikhaylov commented
Style check is Ok.

2021-12-06 12:21 UTC, merged