[WIP] Efficiently finish sorting by (x, y) stream, that already sorted by (x) [CLICKHOUSE-4022]
ClickHouse/ClickHouse pull request #3292
Opened 2018-10-04 15:08 UTC by CurtizJ

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

2018-10-10 21:21 UTC, alexey-milovidov commented
TODO:
- style errors;
- rename `FinishMergeSortingBlockInputStream` to `FinishSortingBlockInputStream` because it doesn't merge anything.

2018-10-18 17:53 UTC, ztlpn requested changes

2018-10-18 17:53 UTC, ztlpn commented on dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
> +        if (block)
Suggestion: maybe it is better to move this code inside the loop before `break` - this way it is more evident that the block is cut in two only if it contains the next key.

2018-10-18 17:53 UTC, ztlpn commented on dbms/src/DataStreams/MergeSortingBlockInputStream.h
> +/** Takes stream already sorted by `x` and finishes sorting it by (`x`, `y`).
Looks like the stream expects that each block in the stream is individually sorted by `description_to_sort` but it isn't reflected in the comment.

2018-10-18 17:53 UTC, ztlpn commented on dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
> +    removeConstantsFromSortDescription(header, description_to_sort);
We should check that `description_sorted` is a prefix of `description_to_sort`

2018-10-18 17:53 UTC, ztlpn commented on dbms/src/DataStreams/MergeSortingBlockInputStream.h
> +/** Takes stream already sorted by `x` and finishes sorting it by (`x`, `y`).
BTW there is no mention of that in the task. Or is this stream intended to use always in conjunction with `PartialSortingBlockInputStream(description_to_sort)`?

2018-10-19 12:49 UTC, ztlpn approved these changes
Everything looks ok, a couple of small corrections are still needed.

2018-10-19 12:49 UTC, ztlpn commented on dbms/src/DataStreams/tests/finish_sorting_stream.cpp
> -    catch (const Exception & e)
Doesn't compile without these lines :)

2018-10-19 12:49 UTC, ztlpn commented on dbms/src/DataStreams/tests/finish_sorting_stream.cpp
> +        stream = std::make_shared<PartialSortingBlockInputStream>(stream, sort_descr_final);
PartialSorting is unnecessary now.

2018-10-19 12:49 UTC, ztlpn commented on dbms/src/DataStreams/tests/finish_sorting_stream.cpp
> +    {
Catch clause is still necessary :)

2018-10-19 12:49 UTC, ztlpn commented on dbms/src/DataStreams/FinishSortingBlockInputStream.cpp
> +        throw Exception("Can`t finish sorting. SortDescription of already sorted streamis not prefix of SortDescription needed to sort", ErrorCodes::LOGICAL_ERROR);
```suggestion
        throw Exception("Can`t finish sorting. SortDescription of already sorted stream is not prefix of"
            "SortDescription needed to sort", ErrorCodes::LOGICAL_ERROR);
```

2018-10-19 12:49 UTC, ztlpn commented on dbms/src/DataStreams/FinishSortingBlockInputStream.cpp
> +        size_t tail_pos = 0;
`block` and `tail_pos` can be moved closer to where they are used

2018-10-23 08:32 UTC, alexey-milovidov commented on dbms/src/DataStreams/FinishSortingBlockInputStream.cpp
> +    if (limit && total_rows_processed == limit)
Maybe this is correct, but I prefer `>=` to be sure.

2018-10-23 08:34 UTC, merged

2018-10-25 13:07 UTC, nvartolomei commented
Keeping in mind how columns are resolved during query parsing, the following query might change it's behaviour if FinishSortingBlockInputStream is plumbed as is.

```sql
select -a as a, b
from (
      select a, b
      from (
            select number as a, rand() as b from system.numbers limit 10
             )
      order by a)
order by a, b;
```

SortDescription equality in that case will be true, right?

2018-10-26 16:54 UTC, ztlpn commented
FinishSortingBlockInputStream is intended as a building block for implementing ORDER BY clause execution that uses the ordering in MergeTree parts. Your example (at least for now) will just be sorted twice.

2018-10-29 19:37 UTC, nvartolomei commented
@ztlpn I was hoping this is a building block for #1344 :)