Warning about vulnerability of ODBC driver
ClickHouse/ClickHouse pull request #3303
Opened 2018-10-05 15:40 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

2018-10-05 16:23 UTC, blinkov requested changes

2018-10-08 09:52 UTC, BayoNet commented on docs/en/query_language/dicts/external_dicts_dict_sources.md
> +!!!attention
Ok, but it works without a space too.

2018-10-08 10:09 UTC, BayoNet commented on docs/en/query_language/dicts/external_dicts_dict_sources.md
> +**Example of insecure use**
Amy answered that both variants are grammatically correct, but 'use' is  preferable in this case

2018-10-08 10:10 UTC, BayoNet commented on docs/en/query_language/dicts/external_dicts_dict_sources.md
> +then ODBC driver sends values of `USERNAME` and `PASSWORD` for `Servername = localhost` to `some-server.com`.
Use of future tenses not recommended for technical documentation.

2018-10-09 23:11 UTC, merged