DOCSUP-20065: Edit and translate to Russian (Window View Functions)
ClickHouse/ClickHouse pull request #33295
Opened 2021-12-29 14:39 UTC by karnevil13

Changelog category:

- Documentation for #32335 #32402

2021-12-29 14:50 UTC, kssenii commented
Please see https://github.com/ClickHouse/ClickHouse/pull/32498

2021-12-30 13:27 UTC, gyuton commented on docs/ru/sql-reference/statements/create/view.md
> +запрос `WATCH` должен отразить следующие результаты:
```suggestion
Запрос `WATCH` должен отразить следующие результаты:
```

2022-01-10 07:07 UTC, kssenii requested changes
Ok, but need to merge with master and remove accidentally changed files (see there are `contrib/` files added in the diff)

2022-01-10 07:07 UTC, kssenii commented on docs/ru/sql-reference/statements/create/view.md
> +Оконное представление может агрегировать данные к временному окну и выводить результаты, когда окно готово к запуску. Оно хранит результаты частичной агрегации во внутренней (или заявленной) таблице,
```suggestion
Оконное представление может агрегировать данные к временному окну и выводить результаты, когда окно готово к запуску. Оно хранит результаты частичной агрегации во внутренней (или заявленной) таблице, чтобы сократить время задержки. Результат обработки отправляется в заявленную таблицу и/или в виде уведомления с помощью запроса `WATCH`.
```

2022-04-24 22:23 UTC, closed without merging