Enable binary arithmetic between Decimal and Float
ClickHouse/ClickHouse pull request #33355
Opened 2022-01-01 09:08 UTC by ucasfl

Changelog category (leave one):

- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Enable binary arithmetic(plus, minus, multiply, division, least, greates) between Decimal and Float.

Detailed description / Documentation draft:
Convert both of them into Float64, and apply operation.

2022-01-06 04:07 UTC, ywqzzy commented on src/Functions/FunctionBinaryArithmetic.h
> +#include <Common/Arena.h>
remove useless header file.

2022-01-10 02:15 UTC, ucasfl commented
@alexey-milovidov Seems something wrong happend about the ci.

2022-01-10 02:47 UTC, ucasfl commented
@Mergifyio update

2022-01-10 07:14 UTC, ucasfl commented
@Mergifyio update

2022-01-11 12:04 UTC, novikd requested changes

2022-01-11 12:05 UTC, ucasfl commented on tests/queries/0_stateless/01603_decimal_mult_float.reference
> +299.41883695311844
Yes.

2022-01-11 12:09 UTC, ucasfl commented on src/Functions/FunctionBinaryArithmetic.h
> +            DataTypeFloat64>,
So, We should use Float32 for decimal op Float32?

2022-01-11 12:17 UTC, ucasfl commented on src/Functions/FunctionBinaryArithmetic.h
> +            DataTypeFloat64>,
But if we cast some decimal value into Float32, it may overflow, and in other systems like MySQL and Spark, they always cast decimal into float64.

2022-01-11 12:26 UTC, ucasfl commented on src/Functions/FunctionBinaryArithmetic.h
> +            DataTypeFloat64>,
In this way, we can compute:
```
select 0.1000000000000000055511151231257827021181583404541015625::Decimal256(70) + 0.1

SELECT CAST('0.1000000000000000055511151231257827021181583404541015625', 'Decimal256(70)') + 0.1

Query id: 08820334-4b12-4f50-8bf8-5f2b5a6022ae

┌─plus(CAST('0.1000000000000000055511151231257827021181583404541015625', 'Decimal256(70)'), 0.1)─┐
│                                                                                            0.2 │
└────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.009 sec. 
```

2022-01-16 05:12 UTC, ucasfl commented on src/Functions/FunctionBinaryArithmetic.h
> +            DataTypeFloat64>,
similar to #31966.

2022-01-18 10:57 UTC, novikd approved these changes

2022-01-18 11:04 UTC, novikd commented
>  Stateless tests (release, wide parts enabled, actions) — fail: 1, passed: 3725, skipped: 2 

Seems unrelated

> Stress test (address, actions) — Killed by signal (in clickhouse-server.log) 

Unrelated too

2022-01-18 11:04 UTC, merged