RangeHashedDictionary use interval tree
ClickHouse/ClickHouse pull request #33516
Opened 2022-01-11 10:16 UTC by kitaisreal

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve RangeHashedDictionary performance if for key there are a lot of intervals. Fixes #23821.

2022-01-11 18:05 UTC, serxa requested changes

2022-01-16 16:44 UTC, kitaisreal commented on src/Common/IntervalTree.h
> +template<typename IntervalStorageType>
Fixed.

2022-01-16 16:45 UTC, kitaisreal commented on src/Common/IntervalTree.h
> +    return std::tie(lhs.left, lhs.right) == std::tie(lhs.left, rhs.right);
Fixed.

2022-01-16 16:45 UTC, kitaisreal commented on src/Common/IntervalTree.h
> +    static constexpr bool is_nonempty_value = !std::is_same_v<Value, IntervalTreeVoidValue>;
Fixed.

2022-01-16 16:45 UTC, kitaisreal commented on src/Common/IntervalTree.h
> +        // Iterator operator++(int) {
Fixed.

2022-01-16 16:45 UTC, kitaisreal commented on src/Common/IntervalTree.h
> +        const IntervalWithValue *operator->()
Fixed.

2022-01-16 16:45 UTC, kitaisreal commented on src/Common/IntervalTree.h
> +        sorted_intervals.emplace_back(interval, Value(std::forward<Args>(args)...));
Fixed.

2022-01-19 10:18 UTC, kitaisreal commented on src/Common/IntervalTree.h
> +  * 4. Intervals that intersect node sorted by right ascending.
Fixed.

2022-01-19 10:18 UTC, kitaisreal commented on src/Common/IntervalTree.h
> +        sorted_intervals.emplace_back(std::piecewise_construct, interval, value);
Fixed.

2022-01-19 10:18 UTC, kitaisreal commented on src/Common/IntervalTree.h
> +    bool tree_is_build = false;
Fixed.

2022-01-19 14:41 UTC, serxa approved these changes

2022-01-19 15:30 UTC, merged