add h3 misc functions - part 2
ClickHouse/ClickHouse pull request #33621
Opened 2022-01-14 08:34 UTC by bharatnc

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
 
Add new h3 miscellaneous functions: `edgeLengthKm`,`exactEdgeLengthKm`,`exactEdgeLengthM`,`exactEdgeLengthRads`,`numHexagons`.

Detailed description / Documentation draft:

Add new h3 miscellaneous functions: `edgeLengthKm`,`exactEdgeLengthKm`,`exactEdgeLengthM`,`exactEdgeLengthRads`,`numHexagons`.
 as per: https://h3geo.org/docs/api/misc/

Splitting up adding the functions into smaller PRs so that it's easy to review.

2022-01-17 17:07 UTC, bharatnc commented
Failing tests don't seem to be related.

2022-01-21 15:22 UTC, kitaisreal requested changes
Need to make small fixes. Then ready to merge.

2022-01-21 16:44 UTC, bharatnc commented on src/Functions/h3HexAreaKm2.cpp
> +            const int resolution = data[row];
Changed to use `UInt8` everywhere.

2022-01-21 16:50 UTC, bharatnc commented on src/Functions/h3EdgeLengthM.cpp
> +            const int resolution = col_hindex->getUInt(row);
somehow missed this doing this here and in one other place. Fixed.

2022-01-21 19:30 UTC, kitaisreal approved these changes

2022-01-21 20:40 UTC, bharatnc commented
Fixed [build issues](https://s3.amazonaws.com/clickhouse-builds/33621/6f9b82dd2c98ef70ef053eda2602d33bc85d6eb9/clickhouse_build_check_(actions)/report.html), looks like fmtlib doesn't allow mixing int types while formatting the exception.
```
2022-01-21 17:32:46 In file included from ../src/Functions/h3HexAreaKm2.cpp:5:
2022-01-21 17:32:46 In file included from ../src/Columns/ColumnsNumber.h:4:
2022-01-21 17:32:46 In file included from ../src/Columns/ColumnVector.h:4:
2022-01-21 17:32:46 In file included from ../src/Columns/IColumn.h:5:
2022-01-21 17:32:46 In file included from ../src/Common/Exception.h:12:
2022-01-21 17:32:46 In file included from ../contrib/fmtlib-cmake/../fmtlib/include/fmt/format.h:44:
2022-01-21 17:32:46 /build/contrib/fmtlib/include/fmt/core.h:996:5: error: static_assert failed due to requirement 'std::is_same<char8_t, char>::value || std::is_same<char8_t, char>::value' "mixing character types is disallowed"
2022-01-21 17:32:46     static_assert(
2022-01-21 17:32:46     ^
2022-01-21 17:32:46 /build/contrib/fmtlib/include/fmt/core.h:1273:32: note: in instantiation of function template specialization 'fmt::detail::arg_mapper<fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>>::map<char8_t, 0>' requested here
2022-01-21 17:32:46   return arg_mapper<Context>().map(val);
...                   ^
```

2022-01-21 20:53 UTC, kitaisreal approved these changes

2022-01-22 11:20 UTC, merged