Add expire() in PoolBase
ClickHouse/ClickHouse pull request #34076
Opened 2022-01-28 06:06 UTC by lgbo-ustc

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add a new method `expire()` in PoolBase which is used to reallocate an invalid object in the pool.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

2022-01-28 10:56 UTC, tavplubix commented
But what is the purpose of this change? New method in never used as for now.

2022-01-28 11:51 UTC, lgbo-ustc commented
> But what is the purpose of this change? New method in never used as for now.

We use it in another developing feature. I want to  commit it alone

2022-01-28 19:15 UTC, kitaisreal requested changes
Seems that pull request is ok, it does not make any significant changes to interfaces.

2022-01-28 19:15 UTC, kitaisreal commented on src/Common/PoolBase.h
> +            data->data.is_expired = true;
Should this bool be atomic ?

2022-01-28 19:15 UTC, kitaisreal commented on src/Common/PoolBase.h
> +                    if (!item->is_expired)
Consider to wrap `for` loop in braces, because inner part not 2 lines now.

2022-01-28 19:15 UTC, kitaisreal commented on src/Common/PoolBase.h
> +                    if (!item->is_expired)
Please add `likely(!item->is_expired)`.

2022-01-28 19:15 UTC, kitaisreal commented on src/Common/PoolBase.h
> +    inline size_t aliveSize()
This returns just items size, consider to rename it into `size`.

2022-01-29 12:51 UTC, kitaisreal approved these changes

2022-01-29 12:51 UTC, merged