filtering shebang line from --queries-file
ClickHouse/ClickHouse pull request #34095
Opened 2022-01-28 12:27 UTC by egor-sivokhin2001

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Filtering `shebang` line from `--queries-file` to support shebang.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

2022-01-28 12:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=34095) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=34095) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=34095) it.</sub>

2022-01-28 13:20 UTC, qoega commented
@egor-sivokhin2001 please sign CLA.

Can you add a test case with this scenario?
What is the original idea? It is probably an SQL query passed in --query-file and what sort of shebang you encounter there?

2022-01-28 14:50 UTC, alexey-milovidov commented
@qoega This is for #33584.

2022-01-29 13:26 UTC, alexey-milovidov commented
@egor-sivokhin2001 Also please fix the style check:
https://s3.amazonaws.com/clickhouse-test-reports/34095/612f97f8e9240c0962fb314d4ae08f5ef70231c0/style_check__actions_.html

2022-01-29 13:55 UTC, alexey-milovidov commented
Alternative implementation is also considered: #34138

2022-01-31 12:46 UTC, alexey-milovidov commented on src/Client/ClientBase.cpp
> +            if (queries_from_file.starts_with("#!"))
Need to add a comment.

2022-01-31 12:46 UTC, alexey-milovidov requested changes
Also need to add a test, see tests/queries/0_stateless/ *.sh, *.reference

2022-02-03 00:34 UTC, alexey-milovidov commented
The task has been automatically solved by #34230.
I will add a test.

2022-02-03 10:20 UTC, closed without merging