Fix vulnerable code related to std::move and noexcept
ClickHouse/ClickHouse pull request #34691
Opened 2022-02-17 16:02 UTC by mreddy017

This commit fixes the vulnerable code related to std::move and noexcept identified by clangtidy tool.

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

2022-02-17 16:33 UTC, kitaisreal commented
@mreddy017 this is not `Improvement`, category should be `Not for changelog`. Also how do you run clang-tidy on .h files ?

2022-02-17 16:34 UTC, kitaisreal approved these changes
Marking `move` constructors `noexcept` is a good practice, because std containers can benefit from it.

2022-02-17 16:35 UTC, kitaisreal commented
@Mergifyio update

2022-02-17 18:29 UTC, kitaisreal commented
@mreddy017 need to rebase with master.

2022-02-17 18:44 UTC, mreddy017 commented on src/Interpreters/InterpreterCreateQuery.cpp
> +        DatabaseCatalog::instance().addLoadingDependencies(qualified_name, std::move(loading_dependencies));
It may not make difference in this case, this is to address the clang tidy warning because the std::move is eventually map to const references.

2022-02-17 21:52 UTC, alexey-milovidov commented
@kitaisreal Please make sure that the relevant diagnostics are enabled in the `.clang-tidy` file.
There is no point making these fixes without ensuring that the diagnostic is enabled in CI.

2022-02-18 18:43 UTC, kitaisreal requested changes

2022-02-21 10:57 UTC, kitaisreal approved these changes

2022-02-24 18:13 UTC, kitaisreal commented
Will merge into staging branch and try to update clang-tidy in project.

2022-02-24 18:13 UTC, merged