New Chinese translation for system.mutations
ClickHouse/ClickHouse pull request #34784
Opened 2022-02-21 06:48 UTC by lincion

Changelog category (leave one):
- Documentation (changelog entry is not required)

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/
Update zh translations for system.mutations

2022-02-21 06:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=34784) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=34784) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=34784) it.</sub>

2022-02-21 09:23 UTC, alesapin commented
@mergifyio update

2022-02-21 09:24 UTC, alesapin commented
@amosbird, please help :)

2022-02-21 10:27 UTC, ucasfl commented on docs/zh/operations/system-tables/mutations.md
> +该表包含关于MergeTree表的[突变](../../sql-reference/statements/alter.md#alter-mutations)及其进展的信息 。每条突变命令都用一行来表示。
mutation翻译成 突变 太奇怪了

2022-02-21 10:28 UTC, amosbird requested changes

2022-02-21 10:28 UTC, amosbird commented on docs/zh/operations/system-tables/mutations.md
> +- [ReplicatedMergeTree](../../engines/table-engines/mergetree-family/replication.md) 家族
家族 -> 族

2022-02-21 10:28 UTC, amosbird commented on docs/zh/operations/system-tables/mutations.md
> +该表包含关于MergeTree表的[突变](../../sql-reference/statements/alter.md#alter-mutations)及其进展的信息 。每条突变命令都用一行来表示。
突变 -> 变换

其他类似

2022-02-21 10:28 UTC, amosbird commented on docs/zh/operations/system-tables/mutations.md
> +该表包含关于MergeTree表的[突变](../../sql-reference/statements/alter.md#alter-mutations)及其进展的信息 。每条突变命令都用一行来表示。
进展的信息  -> 进度信息

2022-02-22 01:41 UTC, lincion commented on docs/zh/operations/system-tables/mutations.md
> +该表包含关于MergeTree表的[突变](../../sql-reference/statements/alter.md#alter-mutations)及其进展的信息 。每条突变命令都用一行来表示。
确实是这样，mutation无论怎么翻译都觉得不合适

2022-02-22 01:44 UTC, lincion commented on docs/zh/operations/system-tables/mutations.md
> +该表包含关于MergeTree表的[突变](../../sql-reference/statements/alter.md#alter-mutations)及其进展的信息 。每条突变命令都用一行来表示。
> 突变 -> 变换
> 
> 其他类似

我也认为突变这个翻译很奇怪，会不会直接保留mutation不翻译比较好一点

2022-02-22 02:07 UTC, cnmade commented
翻译是一项不简单的工作，鼓励所有有志者，一起翻译，不用拘泥于细节词语是否准确。因为参与的越多，翻译不佳的地方，终究会被修正到最合适的位置。你尽管翻译，自有更多的人来扶正，纠正翻译的不对的地方。LGTM。

2022-02-23 02:29 UTC, amosbird approved these changes

2022-02-23 10:08 UTC, merged