Support SQL compatible create/drop index syntax
ClickHouse/ClickHouse pull request #35166
Opened 2022-03-10 08:16 UTC by zhangjmruc

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support SQL standard create index and drop index syntax.

Description:
This is a prototype which try to support SQL compatible CREATE INDEX and DROP INDEX. In future, we would like to use separate parser files to parse the new syntax.

Examples:
Old syntax:
alter table tab add index i_b (b) TYPE minmax GRANULARITY 4;
New syntax:
create index i_b on tab(b) TYPE minmax GRANULARITY 4;

Old syntax:
alter table tab drop index i_b;
New syntax:
drop index i_b on tab;

2022-05-08 13:37 UTC, alexey-milovidov commented
@zhangjmruc The idea is good, we need this.
Let's continue?

2022-06-09 08:42 UTC, kitaisreal requested changes

2022-06-10 02:23 UTC, zhangjmruc commented on src/Parsers/ParserAlterQuery.h
> +  * CREATE INDEX [IF NOT EXISTS] name ON [db].name (expression) TYPE type GRANULARITY value
You think we should put the create/drop index in separate parser files? like ASTCreateIndexQuery and ASTDropIndexQuery?

2022-06-10 02:25 UTC, zhangjmruc commented on src/Parsers/ASTAlterQuery.cpp
> +        auto name = index_decl->as<ASTIndexDeclaration>()->name;
For ASTIndexDeclaration, if the name is empty, it represents sql standard syntax. otherwise, it's normal alter table.. add index syntax.

2022-06-10 09:49 UTC, kitaisreal commented on src/Parsers/ParserAlterQuery.h
> +  * CREATE INDEX [IF NOT EXISTS] name ON [db].name (expression) TYPE type GRANULARITY value
Yes. We should not mess up syntax and interpretation. `ParserAlterQuery` must parse only `ALTER` statements.

2022-06-21 08:05 UTC, zhangjmruc commented on src/Parsers/ParserAlterQuery.h
> +  * CREATE INDEX [IF NOT EXISTS] name ON [db].name (expression) TYPE type GRANULARITY value
@kitaisreal Please help to view the new code changes. The new InterpreterDropIndex/InterpreterCreateIndex is almost same as InterpreterAlterQuery, please give your advice if they are needed or not.

2022-06-28 10:11 UTC, zhangjmruc commented on src/Parsers/ParserAlterQuery.h
> +  * CREATE INDEX [IF NOT EXISTS] name ON [db].name (expression) TYPE type GRANULARITY value
> Yes. We should not mess up syntax and interpretation. `ParserAlterQuery` must parse only `ALTER` statements.

Hi Maksim, please let me know your opinion.

2022-06-29 10:29 UTC, kitaisreal approved these changes

2022-06-29 10:30 UTC, kitaisreal commented
@zhangjmruc great job. I will double check that everything work and maybe fix some minor style issues in follow up pull request.

2022-06-29 10:30 UTC, merged