fix clang tidy warning, add nullptr check
ClickHouse/ClickHouse pull request #35540
Opened 2022-03-23 15:17 UTC by SuzyWangIBMer

Changelog category (leave one):
- Not for changelog (changelog entry is not required)
> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

2022-03-23 16:15 UTC, vdimir commented
What error exactly is about? We have `NOLINTNEXTLINE` below. Also clang-tidy build in out CI is ok.

2022-03-23 16:15 UTC, vdimir reviewed
What error exactly is about? We have `NOLINTNEXTLINE` below. Also clang-tidy build in out CI is ok.

2022-03-23 22:47 UTC, alexey-milovidov commented
@SuzyWangIBMer you should also add this to `.clang-tidy` file in our source root to ensure it is covered by CI.

2022-03-23 22:48 UTC, alexey-milovidov commented
I'm not sure that this change is correct.
If a function does not expect nullptr, you should pass by reference, not by pointer.

2022-03-25 14:51 UTC, SuzyWangIBMer commented
> What error exactly is about? We have `NOLINTNEXTLINE` below. Also clang-tidy build in out CI is ok.

The error is about no check for ast nullptr, checking select nullptr does not guarantee ast to be valid. 
![image](https://user-images.githubusercontent.com/96189018/160144385-37f742d5-8de2-4b9f-9ddd-66f4d15b54ab.png)

2022-03-27 04:27 UTC, alexey-milovidov requested changes
Replace the calling code:

parsed_query.get() -> *parsed_query

2022-03-27 04:28 UTC, alexey-milovidov commented
You should add this check to `.clang-tidy` file, otherwise it does not make sense.

2022-03-30 20:22 UTC, SuzyWangIBMer commented
> You should add this check to `.clang-tidy` file, otherwise it does not make sense.
Since dereference of a null pointer is already in clang-tidy, hence just removed '//NOLINTNEXTLINE'

2022-03-30 20:22 UTC, SuzyWangIBMer commented
> You should add this check to `.clang-tidy` file, otherwise it does not make sense.
Since dereference of a null pointer is already in clang-tidy, hence just removed '//NOLINTNEXTLINE'

2022-04-03 03:04 UTC, alexey-milovidov commented
But now the code does not build.

2022-04-04 21:36 UTC, alexey-milovidov commented
@SuzyWangIBMer The idea is the following:
1. Use references instead of pointers if possible.
2. After replacing pointers to references you can check for nullptr earlier and in less number of places.

2022-04-06 13:32 UTC, SuzyWangIBMer commented
@alexey-milovidov  We do hold concern about this change. If we make it reference instead of pointer, then dynamic_cast for reference throws exception if it is not ASTSelectQuery, catching exception could become more expensive than the current design. Any suggestion you have based on this?

2022-04-07 22:26 UTC, alexey-milovidov commented
Take an address for dynamic_cast.

2022-04-11 17:17 UTC, vdimir commented on programs/client/Client.cpp
>      // nullptr, `ast` is also nullptr, and complains about nullptr dereference.
```suggestion
```

2022-04-12 09:44 UTC, vdimir approved these changes

2022-04-17 14:40 UTC, alexey-milovidov approved these changes
LGTM

2022-04-17 14:40 UTC, alexey-milovidov commented
Integration tests (asan, actions) [2/3] — fail: 1, passed: 615, flaky: 1
[Details](https://s3.amazonaws.com/clickhouse-test-reports/35540/5d2bd5b0c01ffbd60c79190e1ec941e3b3b8c4b9/integration_tests__asan__actions__[2/3].html)
@robot-clickhouse
Integration tests (release, actions) [1/2] — fail: 1, passed: 931, flaky: 0
[Details](https://s3.amazonaws.com/clickhouse-test-reports/35540/5d2bd5b0c01ffbd60c79190e1ec941e3b3b8c4b9/integration_tests__release__actions__[1/2].html)
@robot-clickhouse
Integration tests (thread, actions) [3/4] — fail: 3, passed: 426, flaky: 0
[Details](https://s3.amazonaws.com/clickhouse-test-reports/35540/5d2bd5b0c01ffbd60c79190e1ec941e3b3b8c4b9/integration_tests__thread__actions__[3/4].html)
@robot-ch-test-poll1
Stateful tests (thread, actions) — Timeout, fail: 1, passed: 115, skipped: 2
[Details](https://s3.amazonaws.com/clickhouse-test-reports/35540/5d2bd5b0c01ffbd60c79190e1ec941e3b3b8c4b9/stateful_tests__thread__actions_.html)

These tests have to be fixed before merging.

2022-04-18 00:51 UTC, alexey-milovidov commented
Waiting for #36361.

2022-04-18 04:01 UTC, alexey-milovidov commented
@mergifyio update

2022-04-18 04:09 UTC, alexey-milovidov commented
@SuzyWangIBMer I cannot merge your branch with master, you have to do it by yourself.

2022-04-19 18:58 UTC, SuzyWangIBMer commented
> @SuzyWangIBMer I cannot merge your branch with master, you have to do it by yourself.
I am going to close this PR and open a new one.

2022-04-20 09:26 UTC, merged