Avx512 memcpy small
ClickHouse/ClickHouse pull request #35983
Opened 2022-04-06 06:24 UTC by yaqi-zhao

### Changelog category (leave one):

- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add x86 avx512 support for memcpySmall functions to accelerate memory copy. It works only if you 
compile ClickHouse by yourself.

Detailed description / Documentation draft:
The changes is to implement the memCpy function in memcpySmall.h by using avx512 intrinsic '_mm512_storeu_si512'
and '_mm512_loadu_si512' when copied memory exceed 64bytes. Compared with the original version, functions in the avx512
version can have better performance(memcpySmallAllowReadWriteOverflow15Impl) or the same performance.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/yaqizhao/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/yaqizhao/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Case(byte) | memcpySmallAllowReadWriteOverflow15(SSE2) | memcpySmallAllowReadWriteOverflow15(AVX512)
-- | -- | --
8 | 20 | 20
16 | 27 | 26
32 | 30 | 24
64 | 39 | 33
128 | 49 | 37
256 | 66 | 44
512 | 75 | 70

</body>

</html>

test based on query:
Q1: SELECT encodeXMLComponent('clickse.com/docs/zh/getting-started/example-datasets/star-schema/8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=char*%20%20to%20string&fenlei=256&rsv_pq=8f61e3e900008628&rsv_t=db73wzdWMNRfgxJIW56as356jow533RiNh0G6Am%2FznQUZ6jGEJw34%2BVYK6o&rqlang=cn&rsv_enter=1&rsv_dl=tb&rsv_sug3=16&rsv_sug2=0&rsv_btype=i&inputT=3239&rsv_sug4=3239i8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=char*%20%2’);
Q2:40 sql of encodeXMLComponent different length url
Q3:  SELECT toFixedString('foo', 128); SELECT toFixedString('foo', 64); SELECT toFixedString('foo', 32); SELECT toFixedString('foo', 16);
Q4:SELECT toFixedString('foo', 128);
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/yaqizhao/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/yaqizhao/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Query | Baseline  (QPS) | avx512 optimized (QPS) | improvement
-- | -- | -- | --
Q1 | 1031 | 1234 | 19.40%
Q2 | 1117 | 1343 | 20%
Q3 | 2635 | 2700 | 2.80%
Q4 | 1910 | 2024 | 5.90%

</body>

</html>

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

2022-04-06 06:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=35983) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=35983) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=35983) it.</sub>

2022-04-07 09:59 UTC, kitaisreal commented
@Mergifyio update

2022-04-08 02:24 UTC, yaqi-zhao commented on src/Common/memcpySmall.h
> +            _mm512_loadu_si512(reinterpret_cast<const __m512i *>(src)));
comment

2022-05-08 13:40 UTC, alexey-milovidov commented on src/Common/memcpySmall.h
> +#if defined(__AVX512F__) && !defined(MEMORY_SANITIZER)
Missing comment, why `!defined(MEMORY_SANITIZER)` here?
And why it is not required below, in `#elif defined(__SSE2__)`?

2022-05-08 13:40 UTC, alexey-milovidov requested changes
I changed code formatting,
more changes required.

2022-05-08 13:49 UTC, alexey-milovidov commented
The improvement is only marginal.

But there are the following caveats:
1. This code path will be run only if ClickHouse is compiled with AVX-512 globally enabled. But we don't do that, because AVX-512 is rare. And we don't support any builds of ClickHouse except the single official build.
2. Implementing dynamic dispatching for this code will be difficult if not impossible.
3. The changes have been tested on unknown CPU model, but the performance of AVX-512 can vary a lot on different CPU models and on some models it can lead to performance degradation.
4. We add 15 byte padding to the columns, but with the introduction of AVX-512, it will be reasonable to change the padding to 63 bytes and simplify the code even more. It was not done in this PR.
5. It has been tested on TPC-H or Star Schema Benchmark dataset that is known to represent unrealistic workload with too many pseudorandom data with unnatural distributions. It may lead to excessive copying and overly-optimistic results on this benchmark.
6. Some prior work https://github.com/ClickHouse/ClickHouse/pull/21812 and https://presentations.clickhouse.com/zero_cost_conf/memcpy/ advices against this optimization.

2022-05-08 13:49 UTC, closed without merging

2022-05-08 13:50 UTC, alexey-milovidov commented
Please resubmit if we will come up to some other solution.

2022-05-10 08:17 UTC, yaqi-zhao commented
Thanks for your comments. @alexey-milovidov  It is useful and helps us provide more comprehensive solution in the future. But there are some confusions about the above caveats;
1.	I found that prior work on avx512 optimization have been merged, e.g.,,Avx512 memcmp small [#33706](https://github.com/ClickHouse/ClickHouse/pull/33706) && add x86 feature avx2/avx512 support for accelerating filter operation [#30014](https://github.com/ClickHouse/ClickHouse/pull/30014). But the comment said ck don't support any builds of ClickHouse except the single official build. I have doubt that if we have more avx512 optimization in the future, can these features be merged?
2.	Comments say “The improvement is only marginal” --=>  Is that means 5% performance improvement on function query tested by Star Schema Benchmark to small? Generally, how much the improvement made will the PR be accepted?

2022-05-14 02:50 UTC, alexey-milovidov commented
5% is good if it is available in the default build configuration and not good to motivate some code path that works only in custom builds.

2022-05-14 02:56 UTC, alexey-milovidov commented
I should better invite @nickitat here instead of closing :)

2022-05-16 08:38 UTC, yaqi-zhao commented
@alexey-milovidov  what if I add a cmake option to enable the code by default if build enviromnent supports AVX512?

2022-05-17 23:19 UTC, alexey-milovidov commented
It's not a good option, we can build on servers with AVX-512 but deploy on other servers.
Dynamic dispatch will be better if they can really work on memcpySmall (that's in question).