Description of VersionedCollapsingMergeTree
ClickHouse/ClickHouse pull request #3637
Opened 2018-11-22 10:11 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

2018-11-22 15:30 UTC, alexey-milovidov commented on docs/en/operations/table_engines/versionedcollapsingmergetree.md
> +`VersionedCollapsingMergeTree` asynchronously deletes (collapses) pairs of rows if all of the fields in a row are equivalent excepting the particular field `Sign` which can have `1` and `-1` values.
`if all of the fields in a row are equivalent`
Not true.

2018-11-22 15:32 UTC, alexey-milovidov commented on docs/en/operations/table_engines/versionedcollapsingmergetree.md
> +# VersionedCollapsingMergeTree
Cannot figure out the motivation for `VersionedCollapsingMergeTree` from this text.

2018-11-28 09:42 UTC, blinkov requested changes

2018-11-28 09:42 UTC, blinkov commented on docs/en/operations/table_engines/versionedcollapsingmergetree.md
> +The engine:
"This engine" would sound better I think

2018-11-28 09:42 UTC, blinkov commented on docs/en/operations/table_engines/versionedcollapsingmergetree.md
> +## Selecting data
**D**ata

2018-11-28 09:42 UTC, blinkov commented on docs/en/operations/table_engines/versionedcollapsingmergetree.md
> +## Example of use
**U**se

2018-11-28 09:42 UTC, blinkov commented on docs/en/operations/table_engines/versionedcollapsingmergetree.md
> +- Allows quick writing of continually changing states of objects.
It'd be useful to briefly mention Version right here as a mechanism to restore order of writes coming from concurrent writers.

2018-12-11 14:39 UTC, merged