add h3 unidirectional edge functions
ClickHouse/ClickHouse pull request #36843
Opened 2022-05-02 05:43 UTC by bharatnc

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Adds H3 unidirectional edge functions.

Adds all the H3 unidirectional edge functions as listed here: https://h3geo.org/docs/api/uniedge

Related to: #17708

2022-05-09 05:29 UTC, bharatnc commented
There are some errors due to AST fuzzer: https://s3.amazonaws.com/clickhouse-test-reports/36843/01ea1beee5f9c3907377a4c93a5898eebf7dff70/fuzzer_astfuzzerasan,actions//report.html

Mainly it looks like it's due to the following declarations in the h3 library:
- global variable 'NEW_ADJUSTMENT_III' defined in '../contrib/h3/src/h3lib/lib/algos.c:142:24
- global variable 'NEW_DIGIT_III' defined in '../contrib/h3/src/h3lib/lib/algos.c:121:24' 

I'm not sure of the best way to address this. Perhaps just tag it as no_sanitize ? Seems to be somewhat similar to this open issue: https://github.com/google/sanitizers/issues/1028

```
diff --git a/src/h3lib/lib/algos.c b/src/h3lib/lib/algos.c
index cf5f1d8..760a208 100644
--- a/src/h3lib/lib/algos.c
+++ b/src/h3lib/lib/algos.c
@@ -118,6 +118,7 @@ static const Direction NEW_ADJUSTMENT_II[7][7] = {
  *
  * Current digit -> direction -> new ap7 move (at coarser level).
  */
+__attribute__((no_sanitize("address")))
 static const Direction NEW_DIGIT_III[7][7] = {
     {CENTER_DIGIT, K_AXES_DIGIT, J_AXES_DIGIT, JK_AXES_DIGIT, I_AXES_DIGIT,
      IK_AXES_DIGIT, IJ_AXES_DIGIT},
@@ -139,6 +140,7 @@ static const Direction NEW_DIGIT_III[7][7] = {
  *
  * Current digit -> direction -> new ap7 move (at coarser level).
  */
+__attribute__((no_sanitize("address")))
 static const Direction NEW_ADJUSTMENT_III[7][7] = {
     {CENTER_DIGIT, CENTER_DIGIT, CENTER_DIGIT, CENTER_DIGIT, CENTER_DIGIT,
      CENTER_DIGIT, CENTER_DIGIT},
```

2022-05-11 16:37 UTC, kitaisreal requested changes
Need to fix minor issues and ready to merge.

2022-05-11 16:37 UTC, kitaisreal commented on src/Functions/h3GetIndexesFromUnidirectionalEdge.cpp
> +            std::vector<H3Index> res;
Allocate array with 2 elements on stack, instead of std::vector.

2022-05-11 16:37 UTC, kitaisreal commented on src/Functions/h3GetUnidirectionalEdgeBoundary.cpp
> +                latitude->insert(radsToDegs(boundary.verts[vert].lat));
IColumn insert will create temporary Field. Better to extract arrays from columns and use push_back method.

2022-05-11 16:37 UTC, kitaisreal commented on src/Functions/h3GetUnidirectionalEdgesFromHexagon.cpp
> +            res_vec.resize(6);
Also better to allocate array with 6 elements on stack.

2022-05-23 11:57 UTC, kitaisreal commented
@bharatnc need to fix fuzzer test failure https://s3.amazonaws.com/clickhouse-test-reports/36843/00d3bbc2e022cd843492215e653eac95cdc8725d/fuzzer_astfuzzerasan,actions//report.html.

2022-05-23 12:03 UTC, bharatnc commented
> There are some errors due to AST fuzzer: https://s3.amazonaws.com/clickhouse-test-reports/36843/01ea1beee5f9c3907377a4c93a5898eebf7dff70/fuzzer_astfuzzerasan,actions//report.html
> 
> Mainly it looks like it's due to the following declarations in the h3 library:
> 
> * global variable 'NEW_ADJUSTMENT_III' defined in '../contrib/h3/src/h3lib/lib/algos.c:142:24
> * global variable 'NEW_DIGIT_III' defined in '../contrib/h3/src/h3lib/lib/algos.c:121:24'
> 
> I'm not sure of the best way to address this. Perhaps just tag it as no_sanitize ? Seems to be somewhat similar to this open issue: [google/sanitizers#1028](https://github.com/google/sanitizers/issues/1028)
> 
> ```
> diff --git a/src/h3lib/lib/algos.c b/src/h3lib/lib/algos.c
> index cf5f1d8..760a208 100644
> --- a/src/h3lib/lib/algos.c
> +++ b/src/h3lib/lib/algos.c
> @@ -118,6 +118,7 @@ static const Direction NEW_ADJUSTMENT_II[7][7] = {
>   *
>   * Current digit -> direction -> new ap7 move (at coarser level).
>   */
> +__attribute__((no_sanitize("address")))
>  static const Direction NEW_DIGIT_III[7][7] = {
>      {CENTER_DIGIT, K_AXES_DIGIT, J_AXES_DIGIT, JK_AXES_DIGIT, I_AXES_DIGIT,
>       IK_AXES_DIGIT, IJ_AXES_DIGIT},
> @@ -139,6 +140,7 @@ static const Direction NEW_DIGIT_III[7][7] = {
>   *
>   * Current digit -> direction -> new ap7 move (at coarser level).
>   */
> +__attribute__((no_sanitize("address")))
>  static const Direction NEW_ADJUSTMENT_III[7][7] = {
>      {CENTER_DIGIT, CENTER_DIGIT, CENTER_DIGIT, CENTER_DIGIT, CENTER_DIGIT,
>       CENTER_DIGIT, CENTER_DIGIT},
> ```

@kitaisreal regarding the fuzzer. I think that might fix it, I'm not sure about a better way ?

2022-05-23 12:23 UTC, kitaisreal commented
@bharatnc yes, we can just disable sanitizer for this function.

2022-05-24 20:03 UTC, kitaisreal approved these changes

2022-05-24 20:05 UTC, kitaisreal commented
@bharatnc it seems for such query we get segmentation fault `SELECT h3GetUnidirectionalEdge(stringToH3('85283473ffffff\0'), stringToH3('852\03477fffffff')), NULL, NULL` from https://s3.amazonaws.com/clickhouse-test-reports/36843/6e49b76cfddbcf30467f17896227618e3b228faa/stress_test__undefined__actions_/bc_check_error_messages.txt.

2022-05-25 06:03 UTC, bharatnc commented
> @bharatnc it seems for such query we get segmentation fault `SELECT h3GetUnidirectionalEdge(stringToH3('85283473ffffff\0'), stringToH3('852\03477fffffff')), NULL, NULL` from https://s3.amazonaws.com/clickhouse-test-reports/36843/6e49b76cfddbcf30467f17896227618e3b228faa/stress_test__undefined__actions_/bc_check_error_messages.txt.

@kitaisreal added the necessary fixes, builds look better to me now.

2022-05-25 20:46 UTC, kitaisreal approved these changes

2022-05-25 20:46 UTC, merged