Fixed problem with infs in `quantileTDigest`
ClickHouse/ClickHouse pull request #37021
Opened 2022-05-08 17:32 UTC by excitoon

### Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed problem with infs in `quantileTDigest`.
Fixes #32107

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2022-05-09 09:44 UTC, Avogar commented on src/AggregateFunctions/QuantileTDigest.h
> +        if (cnt == 0 || std::isnan(vx) || std::isinf(vx))
Let's write a comment about it

2022-05-09 09:44 UTC, Avogar approved these changes

2022-05-09 09:45 UTC, Avogar commented
Can we write a test for it?

2022-05-09 11:43 UTC, Avogar requested changes
See https://github.com/ClickHouse/ClickHouse/issues/32107#issuecomment-1120954384

2022-05-16 13:21 UTC, Avogar approved these changes

2022-05-16 13:21 UTC, Avogar commented
LGTM

2022-05-16 13:21 UTC, merged

2022-05-18 20:40 UTC, den-crane commented
Can it be backported into 22.3 LTS ?