Support unaligned array join.
ClickHouse/ClickHouse pull request #3717
Opened 2018-11-30 14:38 UTC by amosbird

For left ARRAY JOIN, expand to the greatest size. If all sizes are zero,
resize to one which is the same as the old behavior, i.e. emptyArrayToSingle

For non-left ARRAY JOIN, expand to the greatest size but keep empty if all sizes are zero.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

2018-12-10 20:03 UTC, alexey-milovidov commented on dbms/src/Interpreters/ExpressionActions.cpp
> +    a.function_builder = FunctionFactory::instance().get("length", context);
Strange name.

2018-12-10 20:03 UTC, alexey-milovidov commented on dbms/src/Interpreters/ExpressionActions.cpp
> +                function_arrayResize->build({src_col, column_of_max_length})->execute(tmp_block, {0, 1}, 2, rows);
How it will affect performance?

2018-12-10 20:04 UTC, alexey-milovidov commented on dbms/src/Interpreters/ExpressionActions.cpp
> +    a.function_builder = FunctionFactory::instance().get("length", context);
Better to use separate variable.

2018-12-10 20:04 UTC, alexey-milovidov requested changes
Performance test is required.

2018-12-12 03:13 UTC, amosbird commented
The performance degrade badly for small arrays. It makes sense to add an option then.


```
Running: array_join
[
{
    "hostname": "201.nobida.cn",
    "main_metric": "max_rows_per_second",
    "num_cores": 20,
    "num_threads": 40,
    "ram": 134768111616,
    "runs": [
        {
            "max_rows_per_second": 67098782.000000,
            "query": "SELECT count() FROM (SELECT [number] a, [number * 2] b FROM system.numbers) AS t ARRAY JOIN a, b WHERE NOT ignore(a + b)"
        },
        {
            "max_rows_per_second": 33748463.000000,
            "query": "SELECT count() FROM (SELECT [number] a, [number * 2] b FROM system.numbers) AS t LEFT ARRAY JOIN a, b WHERE NOT ignore(a + b)"
        },
        {
            "max_rows_per_second": 21724193.000000,
            "query": "SELECT count() FROM (SELECT [number] a, [number * 2] b FROM system.numbers) AS t ARRAY JOIN a, b WHERE NOT ignore(a + b) SETTINGS enable_unaligned_array_join = 1"
        },
        {
            "max_rows_per_second": 21570510.000000,
            "query": "SELECT count() FROM (SELECT [number] a, [number * 2] b FROM system.numbers) AS t LEFT ARRAY JOIN a, b WHERE NOT ignore(a + b) SETTINGS enable_unaligned_array_join = 1"
        },
        {
            "max_rows_per_second": 16701070.000000,
            "query": "SELECT count() FROM (SELECT [number] a, [number * 2, number] b FROM system.numbers) AS t ARRAY JOIN a, b WHERE NOT ignore(a + b) SETTINGS enable_unaligned_array_join = 1"
        },
        {
            "max_rows_per_second": 16921843.000000,
            "query": "SELECT count() FROM (SELECT [number] a, [number * 2, number] b FROM system.numbers) AS t LEFT ARRAY JOIN a, b WHERE NOT ignore(a + b) SETTINGS enable_unaligned_array_join = 1"
        }
    ],
    "server_version": "18.14.9",
    "test_name": "array_join",
    "time": "2018-12-12 11:11:32"
}
]
```

2018-12-12 09:39 UTC, alexey-milovidov commented
Ok. A setting looks reasonable.

2018-12-14 18:12 UTC, merged