Fixed error with symbols in key name in S3
ClickHouse/ClickHouse pull request #37344
Opened 2022-05-19 08:03 UTC by excitoon

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed error with symbols in key name in S3.
Fixes #33009

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2022-05-20 00:22 UTC, alexey-milovidov commented on src/IO/S3/PocoHTTPClient.cpp
> +            const std::string reserved = "?#:;+@&="; /// Poco::URI::RESERVED_QUERY_PARAM without '/'.
Please provide an explanation about this change in the comments.

2022-05-20 00:22 UTC, alexey-milovidov requested changes
.

2022-05-20 00:23 UTC, alexey-milovidov commented
@excitoon it's not a bugfix but more like a new feature (support for GCP).

2022-05-20 07:11 UTC, excitoon commented
@alexey-milovidov Not quite. It actually fixes some cases for Amazon S3. Before the fix:

```
SELECT
    _path,
    *
FROM s3('https://s3.eu-central-1.amazonaws.com/testclickhouses3/test#test.txt', '...', '...', 'LineAsString', 's String')

Query id: 0b6476c0-00a0-4005-8b98-100b29484589

↙ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)                                                                                                              
0 rows in set. Elapsed: 1.590 sec. 

Received exception from server (version 22.5.1):
Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: The specified key does not exist.: While executing LineAsStringRowInputFormat: While executing S3. (S3_ERROR)
```

2022-05-20 12:49 UTC, excitoon commented
I would like to hold this PR for a while in order to run some tests.

2022-05-21 21:21 UTC, alexey-milovidov approved these changes
Thank you! Now it is more clear.

2022-05-25 02:34 UTC, alexey-milovidov commented
@excitoon How did your tests go?

2022-05-26 21:58 UTC, alexey-milovidov commented
No answer.

2022-05-26 21:58 UTC, merged