Memory Overcommit: update defaults, exception message and add ProfileEvent
ClickHouse/ClickHouse pull request #37460
Opened 2022-05-23 14:39 UTC by novikd

### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Set `global_memory_usage_overcommit_max_wait_microseconds` default value to 5 seconds. Add info about `OvercommitTracker` to OOM exception message. Add `MemoryOvercommitWaitTimeMicroseconds` profile event.

2022-05-23 14:57 UTC, evillique approved these changes

2022-05-24 23:16 UTC, alexey-milovidov commented on programs/server/Server.cpp
> +            UInt64 max_overcommit_wait_time = config->getUInt64("global_memory_usage_overcommit_max_wait_microseconds", 5'000'000);
Let's remove per-server global setting and rely only on the per-query setting `memory_usage_overcommit_max_wait_microseconds`.

By the way, you forgot to change it.

2022-05-24 23:16 UTC, alexey-milovidov requested changes
.

2022-05-29 05:02 UTC, alexey-milovidov commented on src/Core/Settings.h
> +    M(UInt64, memory_usage_overcommit_max_wait_microseconds, 5'000'000, "Maximum time thread will wait for memory to be freed in the case of memory overcommit on user level. If timeout is reached and
So, now it's not only for user level, but for server level as well? Need to change the description then.

2022-05-29 05:03 UTC, alexey-milovidov approved these changes

2022-06-01 15:06 UTC, merged