Function hasAll added dynamic dispatch
ClickHouse/ClickHouse pull request #37484
Opened 2022-05-24 15:07 UTC by kitaisreal

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve performance of `hasAll` function using dynamic dispatch infrastructure.

2022-05-24 19:58 UTC, kitaisreal commented
@Mergifyio update

2022-05-25 02:40 UTC, alexey-milovidov approved these changes

2022-05-25 02:42 UTC, alexey-milovidov commented
Some of the `hasAll` invocations improved a little but some others slowed down a lot.

2022-05-25 02:42 UTC, alexey-milovidov requested changes
We need to disable AVX-2 for the cases when it slows down the code.

2022-05-25 16:05 UTC, merged