Remove std::move from trivially-copyable object
ClickHouse/ClickHouse pull request #37609
Opened 2022-05-27 18:07 UTC by HeenaBansal2009

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
This PR fixed the medium severity Clang-Tidy error "std::move of the variable 'configuration' of the trivially-copyable type 'FlatDictionary::Configuration' has no effect; remove std::move()"

Refer: https://clang.llvm.org/extra/clang-tidy/checks/performance-move-const-arg.html

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2022-05-27 18:08 UTC, HeenaBansal2009 commented
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/86018844/170766721-020f226c-eb5e-4e90-b5d1-7ca98f301904.png">

2022-05-27 20:59 UTC, alexey-milovidov commented
@HeenaBansal2009 We already reviewed this check and @rschu1ze made the decision to not enable it: https://github.com/ClickHouse/ClickHouse/blob/master/.clang-tidy#L178

Nevertheless, if you change the code for this check, it should be also enabled in the same pull request.

2022-05-27 21:00 UTC, alexey-milovidov requested changes
.

2022-05-28 02:14 UTC, alexey-milovidov approved these changes
Ok to merge.

2022-05-28 17:00 UTC, rschu1ze commented
I support a merge of this PR.

(Side notes, just for completeness:
- The warning belongs to check "performance-move-const-arg" which is *on* by default and has been on already prior to my recent clang-tidy improvements. What is being disabled in https://github.com/ClickHouse/ClickHouse/blob/master/.clang-tidy#L178 is a specific "sub-warning" of the check about moving trivially copyable types.
- Fixing these warnings will *not* improve performance as for such types moving is as expensive as copying. It will merely no longer lure the reader into thinking that a move is cheaper.
- As the sub-check is disabled in our "official" clang-tidy definition (.clang-tidy), I assume @HeenaBansal2009 used another .clang-tidy file.
- It would certainly be nice to fix other warnings of this type and to finally to remove 'key: performance-move-const-arg.CheckTriviallyCopyableMove value: false' from our .clang-tidy file. It's just a bit of work. If @HeenaBansal2009 would like to work on this - the lazy option would be to do a push with 'key: performance-move-const-arg.CheckTriviallyCopyableMove value: false' removed to GitHub - the central clang-tidy (BuilderTidy) will then show all affected places ;-)

)

2022-05-28 18:27 UTC, merged

2022-05-30 11:01 UTC, HeenaBansal2009 commented
> I support a merge of this PR.
> 
> (Side notes, just for completeness:
> 
> * The warning belongs to check "performance-move-const-arg" which is _on_ by default and has been on already prior to my recent clang-tidy improvements. What is being disabled in https://github.com/ClickHouse/ClickHouse/blob/master/.clang-tidy#L178 is a specific "sub-warning" of the check about moving trivially copyable types.
> * Fixing these warnings will _not_ improve performance as for such types moving is as expensive as copying. It will merely no longer lure the reader into thinking that a move is cheaper.
> * As the sub-check is disabled in our "official" clang-tidy definition (.clang-tidy), I assume @HeenaBansal2009 used another .clang-tidy file.
> * It would certainly be nice to fix other warnings of this type and to finally to remove 'key: performance-move-const-arg.CheckTriviallyCopyableMove value: false' from our .clang-tidy file. It's just a bit of work. If @HeenaBansal2009 would like to work on this - the lazy option would be to do a push with 'key: performance-move-const-arg.CheckTriviallyCopyableMove value: false' removed to GitHub - the central clang-tidy (BuilderTidy) will then show all affected places ;-)
> 
> )

Thanks @rschu1ze for the clarification. Yes , I am using different setup than official .clang-candy definition. Fixing all other warnings of this type at once is better option. I can work on this.