Update of expression aliases syntax.
ClickHouse/ClickHouse pull request #3777
Opened 2018-12-07 09:25 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

2018-12-07 09:45 UTC, blinkov requested changes

2018-12-07 09:45 UTC, blinkov commented on docs/en/query_language/syntax.md
> +Alias is a developer defined name for expression in a query.
developer defined -> user defined

2018-12-07 09:45 UTC, blinkov commented on docs/en/query_language/syntax.md
> +- `AS` — keyword for defining aliases. You can define alias for table or a column name skipping `AS` keyword.
It's worth mentioning that in other context it might have different meaning, for instance in `CAST` call.

2018-12-07 09:45 UTC, blinkov commented on docs/en/query_language/syntax.md
> +Avoid aliases the same as column or table names. Let's consider the following example:
It's actually a pretty common practice which many people find convenient.

2018-12-07 09:45 UTC, blinkov commented on docs/en/query_language/syntax.md
> +    For example, `SELECT (1 AS n) + 2, n`.
This example shows unusual feature that's specific to ClickHouse, normally `AS` can be written only externally (after `2` in this example). So I'd start with more simple example and explain this separately.

2018-12-07 09:45 UTC, blinkov commented on docs/en/query_language/syntax.md
> +- `alias` — [string literal](#syntax-string_literal). If an alias contains spaces, enclose it in quotes.
1) **double** quotes (single won't work)
2) backticks are also supported

2018-12-07 09:45 UTC, blinkov commented on docs/en/query_language/syntax.md
> +## Expression aliases
**A**liases

2018-12-10 19:58 UTC, alexey-milovidov commented on docs/en/query_language/syntax.md
> +In this example, we declared table `t` with column `b`. Then, when selecting data, we defined the `sum(b) AS b` alias. As aliases are global, ClickHouse substituted the literal `b` in the expression
Semantic is not clear.

2018-12-10 19:58 UTC, merged