Clarify that match() & like() assume UTF-8
ClickHouse/ClickHouse pull request #37779
Opened 2022-06-02 10:00 UTC by rschu1ze

The previous sentence in the documentation of match() and like()

  "The regular expression works with the string as if it is a set of bytes."

suggested matching is based on Latin-1. Since we don't have separate methods matchUTF8() and likeUTF8(), we should state matching is based on UTF-8.

### Changelog category (leave one):
- Documentation (changelog entry is not required)

2022-06-02 17:37 UTC, rschu1ze commented
@Mergifyio update

(just to re-trigger "Docs Check" which failed with

```
++ git branch --show-current
+ GIT_BRANCH=main
+ '[' '' ']'
+ git pull
From https://github.com/ClickHouse/clickhouse-docs
   a7cebef..b1cdd27  main       -> origin/main
Updating a7cebef..b1cdd27
error: The following untracked working tree files would be overwritten by merge:
	yarn.lock
Please move or remove them before you merge.
Aborting
```
)

2022-06-02 17:52 UTC, rschu1ze commented
StyleCheck complains about trailing whitespaces in ReadFromRemote.cpp. Tried to fix it by myself but GitHub rejected my push because of missing permissions. Would you like to fix the whitespaces too? Thanks.

2022-06-02 17:54 UTC, rschu1ze commented
Meh, that didn't work.

2022-06-03 11:14 UTC, alexey-milovidov commented
Yes, you can say it's UTF-8, but there are many details:

```
ip-172-31-14-26.eu-central-1.compute.internal :) SELECT 'ё' AS yo1, normalizeUTF8NFKD('ё') AS yo2, upperUTF8(yo1) AS Yo1, upperUTF8(yo2) AS Yo2, yo1 LIKE '%' || yo2 || '%', match(yo1, yo2), match(yo1, '(?i)' || Yo1), yo2 LIKE '%\xB5\xCC%'

SELECT
    'ё' AS yo1,
    normalizeUTF8NFKD('ё') AS yo2,
    upperUTF8(yo1) AS Yo1,
    upperUTF8(yo2) AS Yo2,
    yo1 LIKE concat('%', yo2, '%'),
    match(yo1, yo2),
    match(yo1, concat('(?i)', Yo1)),
    yo2 LIKE '%��%'

Query id: 12e0d78f-0167-4b7c-b453-0b242e76e74e

┌─yo1─┬─yo2─┬─Yo1─┬─Yo2─┬─like('ё', concat('%', normalizeUTF8NFKD('ё'), '%'))─┬─match('ё', normalizeUTF8NFKD('ё'))─┬─match('ё', concat('(?i)', upperUTF8('ё')))─┬─like(normalizeUTF8NFKD('ё'), '%��%')─┐
│ ё   │ ё   │ Ё   │ Ё   │                                                   0 │                                  0 │                                          1 │                                  1 │
└─────┴─────┴─────┴─────┴─────────────────────────────────────────────────────┴────────────────────────────────────┴────────────────────────────────────────────┴────────────────────────────────────┘
```

1. Case-insensitive match with general collation algorithm (but not locale-aware algorithm like Turkish)
2. Unicode composition/normalization.
3. Some functions may work on invalid UTF-8 sequences in some cases, which is desirable behavior.

2022-06-15 02:05 UTC, alexey-milovidov commented on docs/en/sql-reference/functions/string-search-functions.md
> +Matching is based on UTF-8, e.g. `.` matches the two-codepoint symbol `¥`. The regular expression must not contain null bytes.
No, ¥ is one Unicode code point (U+00A5) that is encoded by two bytes in UTF-8.

2022-06-15 02:05 UTC, alexey-milovidov requested changes
.

2022-06-15 02:06 UTC, alexey-milovidov commented on docs/en/sql-reference/functions/string-search-functions.md
> +Matching is based on UTF-8, e.g. `.` matches the two-codepoint symbol `¥`. The regular expression must not contain null bytes.
grapheme cluster > code point > byte

2022-06-17 12:56 UTC, rschu1ze commented
Agree, that the devil is in the details. In fact, the complexity of Unicode is so high that a detailed specification of the exact behavior of each `*UTF8()` function variant in ClickHouse is not really realistic. We would need to mention besides the issues you mentioned the internally supported Unicode standard (the latest is 14.0), treatment of BOMs in UTF8, handling of private use code points, granularity of graphemes (e.g. flags) vs. code-point and probably a lot more.

But since ClickHouse comes with NF(K)(C/D) normalization and the general vs. locale-specific collation (Turkish i/İ vs i/I) is mentioned also elsewhere in the docs, let me add another sentence about these.

2022-06-18 02:43 UTC, alexey-milovidov approved these changes

2022-06-18 02:43 UTC, merged