Fix materialized view with column defaults.
ClickHouse/ClickHouse pull request #3796
Opened 2018-12-09 17:51 UTC by amosbird

https://github.com/yandex/ClickHouse/issues/448
https://github.com/yandex/ClickHouse/issues/3484
https://github.com/yandex/ClickHouse/issues/3450
https://github.com/yandex/ClickHouse/issues/2878
https://github.com/yandex/ClickHouse/issues/2285

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

2018-12-10 19:17 UTC, alexey-milovidov commented on dbms/src/DataStreams/PushingToViewsBlockOutputStream.cpp
> +        InterpreterSelectQuery select(view.query, local_context);
Non obvious, how it is guaranteed that it will read from external table
if full qualified name (db.table) is in `view.query`.

2018-12-10 19:20 UTC, alexey-milovidov commented on dbms/tests/queries/0_stateless/00794_materialized_view_with_column_defaults.reference
> +2018-12-10	1	1
Non deterministic result is not appropriate for test.

2018-12-10 19:20 UTC, alexey-milovidov commented on dbms/tests/queries/0_stateless/00794_materialized_view_with_column_defaults.sql
> +USE test;
Can we also test with qualified database?

2018-12-10 19:20 UTC, alexey-milovidov requested changes
.

2018-12-12 01:32 UTC, amosbird commented
Updated. It seems unavoidable to touch the context class.

2018-12-12 05:08 UTC, amosbird commented
Note, another reason for getDatabaseName in IStorage

2019-07-22 10:33 UTC, filimonov commented
> Note, another reason for getDatabaseName in IStorage

See https://github.com/yandex/ClickHouse/pull/5953

2019-07-22 16:42 UTC, alexey-milovidov commented
BTW, Why we are not using `InterpreterInsertQuery` while pushing to views?
It will allow both recursive materialized views and do defaults/materialized calculation automatically.

2019-08-04 00:06 UTC, merged