more consistent work with paths in object storages
ClickHouse/ClickHouse pull request #38436
Opened 2022-06-25 23:01 UTC by kssenii

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Extracted from https://github.com/ClickHouse/ClickHouse/pull/36171.

2022-06-26 13:14 UTC, alesapin requested changes

2022-06-26 13:14 UTC, alesapin commented on src/Disks/ObjectStorages/DiskObjectStorageMetadata.h
> +    std::vector<PathWithSize> storage_objects;
Let's avoid confusion and use different structure here:
```
RelativePathWithSize
{
    path,
    size
}
```

2022-06-26 13:14 UTC, alesapin commented on src/Disks/ObjectStorages/DiskObjectStorageMetadata.cpp
>  void DiskObjectStorageMetadata::addObject(const String & path, size_t size)
need to check in some way that this path is relative.

2022-06-26 13:18 UTC, alesapin commented on src/Disks/ObjectStorages/DiskObjectStorageMetadata.h
> +    std::vector<PathWithSize> getBlobs() const
getBlobsRelativePaths

2022-06-27 08:57 UTC, alesapin commented on src/Disks/IO/ReadBufferFromWebServer.h
>      explicit ReadBufferFromWebServer(
```suggestion
    ReadBufferFromWebServer(
```

2022-06-27 08:57 UTC, alesapin approved these changes

2022-06-27 08:58 UTC, merged

2022-06-30 04:26 UTC, excitoon commented
Guys @kssenii @alesapin I wonder what is the purpose having sizes in `removeObjects`?

2022-06-30 10:50 UTC, kssenii commented
> Guys @kssenii @alesapin I wonder what is the purpose having sizes in removeObjects?

Now there is no, but in another PR (https://github.com/ClickHouse/ClickHouse/pull/36171) it will be not just `PathsWithSize` but struct `StoredObject` and there it is needed.