Possibility to choose custom runner image in integration tests
ClickHouse/ClickHouse pull request #38459
Opened 2022-06-27 13:51 UTC by excitoon

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Possibility to choose custom runner image in integration tests. Can be useful for diagnostics.

2022-10-07 11:35 UTC, devcrafter commented on tests/integration/runner
> -DIND_INTEGRATION_TESTS_IMAGE_NAME = "clickhouse/integration-tests-runner"
Let's leave an ability to set default value via env variable.

2022-10-07 11:35 UTC, devcrafter commented on tests/integration/runner
> +        default="clickhouse/integration-tests-runner",
```suggestion
        default=DIND_INTEGRATION_TESTS_IMAGE_NAME,
```

2022-10-07 11:38 UTC, devcrafter requested changes
Thanks for PR. Please check the comments

2023-02-13 07:50 UTC, alexey-milovidov commented
Abandoned.

2023-02-13 07:50 UTC, closed without merging