add http_host and tls_sni fields to ClientInfo
ClickHouse/ClickHouse pull request #38581
Opened 2022-06-29 14:10 UTC by bharatnc

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add `http_host` and `tls_sni` fields to ClientInfo.

Adds `http_host` and `tls_sni` fields to ClientInfo and also populates the values into the relevant system tables:
```
➜  ~ curl 'http://localhost:8123/?query=SELECT%201'
:) select query, event_date, event_time, http_host, tls_sni from system.query_log where query_id = '2018213a-7129-400f-b133-01cf3a7d6a23' FORMAT Vertical;

Row 1:
──────
query:      SELECT 1
event_date: 2022-06-29
event_time: 2022-06-29 19:25:32
http_host:  localhost:8123
tls_sni:    127.0.0.1:58522
```

Related to: #38323

2022-07-01 22:29 UTC, alexey-milovidov commented on src/Interpreters/ClientInfo.cpp
> +        if (server_protocol_revision >= DBMS_MIN_REVISION_WITH_REFERER_IN_CLIENT_INFO)
A new macro should be used for compatibility.

2022-07-18 23:08 UTC, bharatnc commented
Related failures don't seem to be related, should be ready for review.

2022-08-04 13:38 UTC, CheSema commented on src/Core/ProtocolDefines.h
> +#define DBMS_MIN_REVISION_WITH_HTTP_HOST_IN_CLIENT_INFO 54450
I have concerns about that numbers. I see that VERSION_REVISION is defined as 54465 now.
I'm verifying that part right now. I'll return soon.

2023-09-07 22:31 UTC, CheSema requested changes
Please fix the flaws in the comments above.
You need to extract information from ssl layer for tls_sni.

2023-09-07 22:32 UTC, bharatnc commented
> Please fix the flaws in the comments above. You need to extract information from ssl layer for tls_sni.

Ok sure I will continue with this PR.

2023-11-29 02:31 UTC, bharatnc commented
> > Please fix the flaws in the comments above. You need to extract information from ssl layer for tls_sni.
> 
> Ok sure I will continue with this PR.

Sorry for the delay. I will get back to work on this.

2024-03-21 04:33 UTC, bharatnc commented
Sorry that this PR has been idle for a very long time. I'm going to close this PR for now since I've not had the time to work on the tls sni bit and the PR has been piling up merge conflicts. 

I've tried adding the sni support on the Poco secure socket implementation side, but was unsuccessful in writing a integration test using tls sni setup correctly. I will try reopening it or will open a new PR if I manage to get it working.

2024-03-21 04:33 UTC, closed without merging