Add SimpleCheck
ClickHouse/ClickHouse pull request #38744
Opened 2022-07-03 05:16 UTC by yakov-olkhovskiy

SimpleCheck will pass if either both StyleCheck and FastTest passed or pull request is labeled 'allow simple fail'

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

closes #38471

2022-07-03 05:19 UTC, yakov-olkhovskiy commented
@Felixoid I'm not sure how it will behave on adding/removing label though - I don't see on.pull_request.types contains [labeled,
unlabeled]

2022-07-03 13:43 UTC, alexey-milovidov commented
@yakov-olkhovskiy we have many pull requests where neither Fast Test nor Style Check are run.

It should be implemented in that way: https://github.com/ClickHouse/ClickHouse/issues/18507:
make SimpleCheck green at the start and turn it red if Fast Test or Style Check failed.

Otherwise, it cannot be enabled on GitHub.

2022-07-03 15:45 UTC, yakov-olkhovskiy commented
@alexey-milovidov my solution is to add complementary check for ignored paths - your proposed solution is impossible I think.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

2022-07-03 17:32 UTC, alexey-milovidov commented
Ok.

2022-07-03 17:33 UTC, alexey-milovidov commented
The approach to mark some checks as green and then update is possible if you are not using GitHub Actions and pushing updates to GitHub API directly. We used this approach before.

2022-07-03 17:35 UTC, alexey-milovidov commented on .github/workflows/pull_request.yml
> +        if: ${{ contains(github.event.pull_request.labels.*.name, 'allow simple fail') }}
The label should be named in a more neutral way.
Not "allow fail" but "skip check".

2022-07-04 08:25 UTC, Felixoid requested changes

2022-07-04 08:25 UTC, Felixoid commented on .github/workflows/pr-pass.yml
> +    paths:
no, it must not be any particular path. The check should work for everything

2022-07-04 08:25 UTC, Felixoid commented on .github/workflows/pull_request.yml
> +  SimpleCheck:
I don't get it. The plan is to create a commit status, like our other statuses, see the screenshot 
![image](https://user-images.githubusercontent.com/3025537/177113416-0ff7048d-1daa-43f5-9eb5-c15f361c09c2.png)

You'll slip into hell with solutions based on GH actions. Better add a status to something global like https://github.com/ClickHouse/ClickHouse/blob/master/tests/ci/run_check.py, and then to the checks we want blocking merge, like https://github.com/ClickHouse/ClickHouse/blob/master/tests/ci/fast_test_check.py and https://github.com/ClickHouse/ClickHouse/blob/master/tests/ci/build_check.py adding overwriting for the same status. See examples for https://github.com/ClickHouse/ClickHouse/blob/master/tests/ci/fast_test_check.py#L17

2022-07-08 08:16 UTC, alexey-milovidov approved these changes

2022-07-08 08:17 UTC, merged