Remove broken optimisation in Direct dictionary dictHas implementation
ClickHouse/ClickHouse pull request #39385
Opened 2022-07-19 12:18 UTC by jawm

I noticed this while working on another feature - if a set of keys being
passed to `hasKeys` contains duplicates, then only one of the result
slots for these keys will be populated.

My fix uses to a simpler implementation which is likely slower, but is
correct, which seems more important. No doubt faster approaches exist
which are also correct.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix behaviour of dictHas for direct dictionaries when multiple lookups to the same key are made in a single action

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2022-07-19 12:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=39385) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=39385) before we can accept your contribution.<br/><hr/>**James Morrison** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=39385) it.</sub>

2022-07-20 09:32 UTC, kitaisreal requested changes
Thanks for submission. I will fix slowdown later.
Please consider to change integration to stateless test, where Dictionary source will be ClickHouse.

2022-07-20 14:57 UTC, kitaisreal approved these changes

2022-07-21 09:43 UTC, merged

2022-07-21 10:09 UTC, jawm commented
Thanks for review + merge :)