Fix issues 39469
ClickHouse/ClickHouse pull request #39470
Opened 2022-07-21 15:54 UTC by nicelulu

### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix https://github.com/ClickHouse/ClickHouse/issues/39469

2022-08-03 06:17 UTC, alexey-milovidov commented
I've edited the changelog.

Was:
> https://github.com/ClickHouse/ClickHouse/issues/39469

Now:
> Fix possible "Not found column in block" exception when using projections. This closes #39469

2022-08-03 06:18 UTC, alexey-milovidov commented
@kssenii a test for PostgreSQL replica has failed: https://s3.amazonaws.com/clickhouse-test-reports/39470/c5d9a6c37c1e6fa5be6bfff332943cabb13242cb/integration_tests__asan__[3/3].html

2022-08-03 06:19 UTC, alexey-milovidov commented
@nicelulu flaky check shows that the new test is flaky: https://s3.amazonaws.com/clickhouse-test-reports/39470/c5d9a6c37c1e6fa5be6bfff332943cabb13242cb/stateless_tests_flaky_check__address_.html

PTAL.

2022-08-03 23:35 UTC, alexey-milovidov requested changes
.

2022-08-04 06:34 UTC, nicelulu commented
```
2022.07.25 11:38:44.753334 [ 892 ] {fe1d8acf-fc7c-4c12-ab27-1897ac551585} <Error> test_2m9u7n.video_log (321809a5-9194-4edf-a12f-04c201753597): Cannot quickly remove directory /var/lib/clickhouse/store/321/321809a5-9194-4edf-a12f-04c201753597/delete_tmp_tmp_mut_20220722_2_2_0_5 by removing files; fallback to recursive removal. Reason: Code: 458. DB::ErrnoException: Cannot unlink file /var/lib/clickhouse/store/321/321809a5-9194-4edf-a12f-04c201753597/delete_tmp_tmp_mut_20220722_2_2_0_5/checksums.txt, errno: 2, strerror: No such file or directory. (CANNOT_UNLINK) (version 22.8.1.1)
2
```
Strange, doesn't seem to have anything to do with the change.

2022-08-05 04:24 UTC, alexey-milovidov commented
Yes, looks strange. Need help from @tavplubix

2022-08-05 10:27 UTC, tavplubix commented
> Cannot quickly remove directory ... delete_tmp_tmp_mut_20220722_2_2_0_5 ... Cannot unlink file ... delete_tmp_tmp_mut_20220722_2_2_0_5/checksums.txt ...  No such file or directory

It's because part was not completely mutated and some files are absent (It's OK).
Part was not completely mutated because ALTERs in test are asynchronous.
So new test it not quite correct.

2022-08-05 10:30 UTC, tavplubix commented on tests/queries/0_stateless/02371_select_projection_normal_agg.sql
> +SELECT sleep(3);
There's no way it can work

2022-08-05 10:30 UTC, tavplubix commented on tests/queries/0_stateless/02371_select_projection_normal_agg.sql
> +GROUP BY hour;
Seems like this query does not actually check result of ALTERs

2022-08-08 04:44 UTC, nicelulu commented on tests/queries/0_stateless/02371_select_projection_normal_agg.sql
> +SELECT sleep(3);
Thanks

2022-08-11 01:45 UTC, alexey-milovidov approved these changes

2022-08-13 00:13 UTC, merged