Doc fix: add info about UUID
ClickHouse/ClickHouse pull request #3951
Opened 2018-12-28 12:10 UTC by ogorbacheva

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category:
- Doc fixes

Task:
- DOCAPI-5125

2018-12-28 17:52 UTC, blinkov requested changes

2018-12-28 17:52 UTC, blinkov commented on docs/en/query_language/functions/uuid_function.md
> +Generates [UUID](../../data_types/uuid.md) of version 4.
"version 4" could have been a link to https://tools.ietf.org/html/rfc4122#section-4.4

2018-12-28 17:52 UTC, blinkov commented on docs/en/data_types/uuid.md
> +The UUID format is represented below:
Actually it's just a human readable representation, physically it's 16 bytes.

2018-12-28 17:52 UTC, blinkov commented on docs/toc_en.yml
> +    - 'generateUUIDv4': 'query_language/functions/uuid_function.md'
There are multiple UUID-related functions, so the article should be named like others in plural (uuid_functions.md) with corresponding title.

See:
```
SELECT *
FROM system.functions
WHERE name LIKE '%UUID%'
FORMAT TSV

generateUUIDv4	0	0
toUUID	0	0
UUIDStringToNum	0	0
dictGetUUID	0	0
dictGetUUIDOrDefault	0	0
UUIDNumToString	0	0

6 rows in set. Elapsed: 0.003 sec.
```

2018-12-28 17:52 UTC, blinkov commented on docs/toc_en.yml
> +  - 'UUID': 'data_types/uuid.md'
I'd put it higher in TOC right after FixedString, because it's somewhat related

2019-01-11 21:15 UTC, blinkov requested changes
Current patch contains a lot of unrelated changes + uuid_function.md is not renamed to plural

2019-01-11 21:31 UTC, ogorbacheva commented
Yes, is in progress, tomorrow i ll do PR

2019-01-14 08:57 UTC, blinkov requested changes
+ the file is still not renamed to uuid_function**s**.md

2019-01-14 08:57 UTC, blinkov commented on docs/ru/query_language/misc.md
> +## CHECK TABLE
This is from other patch that was already merged to master, looks like you haven't done `git pull`.

2019-01-14 08:57 UTC, blinkov commented on docs/en/query_language/functions/uuid_function.md
>  ## dictGetUUID
I'm not sure if it's worth duplicating these functions here, there's a separate section with functions related to dictionaries and for other data types those are documented only once.

2019-01-14 08:57 UTC, blinkov commented on docs/en/query_language/functions/uuid_function.md
>  :) SELECT toUUID('61f0c4045cb3-11e7907ba6006ad3dba0') AS uuid
this example leads to `DB::Exception: Cannot parse uuid 61f0c4045cb3-11e7907ba6006ad3dba0: Cannot parse UUID from String.`

2019-01-15 10:07 UTC, closed without merging