WIP Add temporary databases  https://github.com/ClickHouse/ClickHouse/issues/31497
ClickHouse/ClickHouse pull request #41393
Opened 2022-09-15 23:29 UTC by Lirikl

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2022-09-15 23:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=41393) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=41393) before we can accept your contribution.<br/><hr/>**Kirill Akhmetshin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=41393) it.</sub>

2022-09-15 23:34 UTC, Lirikl commented
TemporaryDatabases are mainly working, TEMPORARY keyword allow creating databases that will be deleted upon ending session and could not be seen outside of it. TemporaryDatabases all use Atomic engine and therefore could contain tables of all engines that it could

2022-09-16 13:54 UTC, tavplubix requested changes
> TemporaryDatabases are mainly working

Tests are required to make sure that it actually works.

> will be deleted upon ending session

What happens if server is killed or power turned off before session destructor is called?

> TemporaryDatabases all use Atomic engine and therefore could contain tables of all engines that it could

This is questionable, because some table engines are complicated and were not supposed to be temporary. In particular, they may leave garbage on local filesystem and in ZooKeeper, so proper cleanup is required. 

Maybe we should start from the first step described in https://github.com/ClickHouse/ClickHouse/issues/31497: support more engines for temporary tables

And let's avoid copy-paste where possible

2022-09-16 13:54 UTC, tavplubix commented on src/Interpreters/InterpreterCreateQuery.cpp
> +        throw Exception("Temporary database must have Atomic engine", ErrorCodes::INCORRECT_QUERY); ///Probably needs new error code
`INCORRECT_QUERY` is fine (`NOT_IMPLEMENTED` is suitable too)

2022-09-16 13:54 UTC, tavplubix commented on src/Interpreters/InterpreterCreateQuery.cpp
> +        auto guard = DatabaseCatalog::instance().getDDLGuard(database_name, "");
Notice that it also locks non-temporary database with this name

2022-09-16 13:54 UTC, tavplubix commented on src/Interpreters/InterpreterCreateQuery.cpp
> +        //create.uuid = UUIDHelpers::generateV4();
Why not?

2022-09-16 13:54 UTC, tavplubix commented on src/Interpreters/InterpreterCreateQuery.cpp
>      auto guard = DatabaseCatalog::instance().getDDLGuard(database_name, "");
Seems like a race condition is possible

2022-09-16 13:54 UTC, tavplubix commented on src/Interpreters/InterpreterDropQuery.cpp
> +            res = executeToTemporaryDatabase(query);
Race condition is possible (executeToDatabaseImpl may be called for temporary database and vice versa)

2022-09-16 13:54 UTC, tavplubix commented on src/Interpreters/InterpreterDropQuery.cpp
> +            query.setDatabase(db_name);
What is the purpose of setting the database name after executing the query?

2022-09-16 13:54 UTC, tavplubix commented on src/Interpreters/TemporaryDatabaseHolder.cpp
> +        uuid_to_wait = table_id.uuid;
Copy-paste from `InterpreterDropQuery::executeToTableImpl`

2022-09-16 13:54 UTC, tavplubix commented on src/Interpreters/TemporaryDatabaseHolder.cpp
> +        DatabaseCatalog::instance().detachDatabase(getContext(), database_name, true /*drop*/, database->shouldBeEmptyOnDetach());
Copy-paste from `InterpreterDropQuery::executeToDatabaseImpl`

2022-10-20 14:42 UTC, closed without merging