ISSUES-3890 sync system functions to en document
ClickHouse/ClickHouse pull request #4168
Opened 2019-01-28 15:22 UTC by zhang2014

#3890 
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Other

Short description (up to few sentences):
Use system function tables to synchronize english documents. There are only a limited number of items that cannot be synchronized and may require assistance from @blinkov .
Later, I will complete the function state mark (#3890) and  function  Chinese document translation   based on this job.

- [ ] OSHierarchy
- [ ] OSIn
- [ ] OSToRoot
- [ ] SEHierarchy
- [ ] SEIn
- [ ] SEToRoot
- [ ] parseDateTimeBestEffort
- [ ] parseDateTimeBestEffortOrNull
- [ ] parseDateTimeBestEffortOrZero
- [ ] sumburConsistentHash
- [ ] toLowCardinality
- [ ]  lowCardinalityIndices
- [ ]  lowCardinalityKeys
- [ ]  trunc
- [ ] truncate
- [ ] yandexConsistentHash

2019-01-28 15:48 UTC, blinkov requested changes

2019-01-28 15:48 UTC, blinkov commented on docs/en/query_language/functions/string_functions.md
> +Returns a string that removes the left margin character.
it's not clear what's "margin character", I'd use the description from trimBoth with `s/either/left/g`

2019-01-28 15:48 UTC, blinkov commented on docs/en/query_language/functions/string_functions.md
> +Returns whether to end with the specified prefix, If return 1, the string ends with the specified prefix, otherwise it returns 0.
* `,` -> `.` before If
* Returns 1 if the string...

2019-01-28 15:48 UTC, blinkov commented on docs/en/query_language/functions/string_functions.md
> +Same as concat, the difference is that you need to ensure that concat(s1, s2, s3) -> s4 is injective, it will be used for optimization of GROUP BY
link to concat

2019-01-28 15:48 UTC, blinkov commented on docs/en/query_language/functions/rounding_functions.md
> +Accept a number, round it down to an element in the specified array. If the value is less than the minimum bound, the minimum bound is returned.
`s/minimum/lowest/g`?

2019-01-28 15:48 UTC, blinkov commented on docs/en/query_language/functions/other_functions.md
> +Returns the capacity information of the disk, in bytes. This information is evaluated using the configured by path
lost `.` at end

2019-01-28 15:48 UTC, blinkov commented on docs/en/query_language/functions/other_functions.md
> +Returns the ordinal number of the row in the data block. Different data blocks are always recalculated
lost `.` at end

2019-01-28 15:48 UTC, blinkov commented on docs/en/query_language/functions/ip_address_functions.md
> +## cutIPV6(x, cutIPv6, cutIPV4)
* "V" and "v" look weird together
* I'd rename the arguments to something like bitsToCutForIPv4

2019-01-28 15:48 UTC, blinkov commented on docs/en/query_language/functions/ip_address_functions.md
> +Accepts a FixedString(16) value containing the IPv6 address in binary format, Returns a string containing the address of the specified number of bits removed in text format. For example:
`s/,/./g`

2019-01-28 15:48 UTC, blinkov commented on docs/en/query_language/functions/hash_functions.md
> +For more information, see the link: <https://github.com/google/farmhash>
you could make name of hash a link to description instead of providing it separately

2019-01-28 15:48 UTC, blinkov commented on docs/en/query_language/functions/hash_functions.md
> +Calculates SipHash from a string.
SipHash doesn't match the header

2019-01-28 20:41 UTC, alexey-milovidov commented
```
OSHierarchy
OSIn
OSToRoot
SEHierarchy
SEIn
SEToRoot
```
These functions are deprecated and should not be listed in docs.

2019-01-29 11:39 UTC, zhang2014 commented
@blinkov Done.
`sumburConsistentHash`, `toLowCardinality`, `lowCardinalityIndices`, `lowCardinalityKeys`, `trunc`, `truncate`, `yandexConsistentHash` functions may require you to add.

2019-01-29 11:40 UTC, zhang2014 commented
@alexey-milovidov Have we considered deleting them?

2019-01-29 12:11 UTC, blinkov requested changes

2019-01-29 12:11 UTC, blinkov commented on docs/en/query_language/functions/hash_functions.md
> +For more information, see the link: [FarmHash64]<https://github.com/google/farmhash>
round brackets: `[FarmHash64](https://github.com/google/farmhash)`
here and in other similar places

2019-01-29 12:11 UTC, blinkov commented on docs/en/query_language/functions/string_replace_functions.md
> +For more information, see the link: [RE2]<https://github.com/google/re2/blob/master/re2/re2.cc>
shouldn't it lead to some specific line(s) of this file?

2019-01-30 10:39 UTC, merged

2019-01-30 12:17 UTC, zhang2014 commented
Maybe we can add version information for each function? for example, what version of the function to add? @blinkov

2019-01-30 13:09 UTC, blinkov commented
@zhang2014 no, we'll add documentation versioning later in a different manner.

2019-01-30 18:15 UTC, alexey-milovidov commented
> @alexey-milovidov Have we considered deleting them?

They're still used in production.