Read files in alphabetical order when file globbing
ClickHouse/ClickHouse pull request #42225
Opened 2022-10-10 16:12 UTC by Algunenano

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Read files in alphabetical order when file globbing

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

Closes https://github.com/ClickHouse/ClickHouse/issues/41934
Closes https://github.com/ClickHouse/ClickHouse/pull/41877

2022-10-10 23:16 UTC, alexey-milovidov commented
We don't have to read files in alphabetical order.

2022-10-10 23:16 UTC, alexey-milovidov commented on src/Storages/StorageFile.cpp
> +    std::sort(result.begin(), result.end()); /// Enforce the same order, independently of the order in the filesystem
We shouldn't pay for what we don't need.

2022-10-10 23:17 UTC, alexey-milovidov commented on tests/queries/0_stateless/02267_file_globs_schema_inference.sh
> +CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
If you're concerned about this test, @Avogar will fix it.

2022-10-10 23:17 UTC, alexey-milovidov requested changes
.

2022-10-10 23:18 UTC, alexey-milovidov commented on src/Storages/StorageFile.cpp
> +    std::sort(result.begin(), result.end()); /// Enforce the same order, independently of the order in the filesystem
The comment does not explain "why",

It reads like this:
```
/// Enforce the same order, independently of the order in the filesystem
```
so what?

2022-10-11 00:07 UTC, Algunenano commented
Well, the tests do seem to think that files are read in alphabetical order as it happens in bash or posix' glob; but if you think this isn't necessary we can keep it undefined.

2022-10-11 00:07 UTC, closed without merging