Disable concurrent parts removal
ClickHouse/ClickHouse pull request #42222
Opened 2022-10-10 12:11 UTC by alesapin

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

2022-10-10 12:13 UTC, tavplubix approved these changes

2022-10-10 23:20 UTC, alexey-milovidov commented on src/Storages/MergeTree/MergeTreeData.cpp
> +        && (!supportsReplication() || !settings->allow_remote_fs_zero_copy_replication)) /// parts must be removed in order for zero-copy replication
The comment does not explain "why".

It reads like this:
```
/// parts must be removed in order for zero-copy replication
```
what the heck is "zero-copy" replication and why it requires part removal in order? Is it a kludge and is the code of "zero-copy" replication trashy?

2022-10-10 23:20 UTC, alexey-milovidov requested changes
.

2022-10-10 23:22 UTC, alexey-milovidov commented
Related to https://github.com/ClickHouse/ClickHouse/pull/6438

2022-10-10 23:23 UTC, alexey-milovidov commented
Why "not for changelog"?

2022-10-11 21:53 UTC, alexey-milovidov approved these changes

2022-10-17 10:17 UTC, merged