Attempt to fix 'Local: No offset stored message' from Kafka
ClickHouse/ClickHouse pull request #42391
Opened 2022-10-17 12:45 UTC by filimonov

### Changelog category (leave one):
- Not for changelog

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Attempt to fix 'Local: No offset stored message' from Kafka
See https://github.com/ClickHouse/ClickHouse/issues/12295 

Test is needed

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-01-29 17:04 UTC, alexey-milovidov requested changes
The original exception should be saved for rethrowing.

Currently, the code is throwing a new exception and losing the context of the original.

2023-01-31 07:11 UTC, filimonov commented
That particular exception is for nothing what user can fix. It's rather assert / logical error.

There is a code around that should avoid doing any commits if there no offset stored. 

I think it's actually some internal issue in librdkafka (we have some offsets stored, but maybe not for every partition, and commit returns the exception from the partitions which had nothing to commit). 

Actually that needs a test...

2023-02-12 02:59 UTC, alexey-milovidov commented
> Or we need to refactor code to work with every partition isolately

This is what we should've done five years ago.

2023-02-12 03:01 UTC, alexey-milovidov approved these changes

2023-02-13 07:49 UTC, merged