use proper ErrorCode in table function Value
ClickHouse/ClickHouse pull request #43334
Opened 2022-11-17 15:54 UTC by ucasfl

### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Closes #43331.

2022-11-17 16:39 UTC, kssenii approved these changes

2022-11-17 19:46 UTC, tavplubix commented on src/TableFunctions/TableFunctionValues.cpp
> +        throw Exception("Table function '" + getName() + "' must have arguments", ErrorCodes::NUMBER_OF_ARGUMENTS_DOESNT_MATCH);
First of all, why not to replace it with formatted message like this?
```suggestion
        throw Exception(ErrorCodes::NUMBER_OF_ARGUMENTS_DOESNT_MATCH, "Table function '{}' must have arguments", getName());
```

2022-11-17 19:46 UTC, tavplubix commented on src/TableFunctions/TableFunctionValues.cpp
> -        throw Exception("Table function '" + getName() + "' must have arguments", ErrorCodes::LOGICAL_ERROR);
Second, it's not the only place where exception like this is thrown. Just grep `must have arguments", ErrorCodes::LOGICAL_ERROR` and you will find at least 2 more places. Should we fix other places as well?

2022-11-17 19:46 UTC, tavplubix requested changes
And third: what about adding some tests?

2022-11-17 20:05 UTC, tavplubix commented
And finally: why do you think that it's not a logical error?

Is it possible to have a function without arguments list? Of course it's possible to have a function with empty arguments list (like `func()`), but not without arguments list (`func` is an identifier, not a function). 

Seems like behavior of `ParserFunction` was changed recently (we can ask @evillique), so now the parser can produce invalid AST. I guess we have many places in code which assume that `ASTFunction` always has one child and it's `ASTExpressionList`. We have to either find all such places and fix them or fix `ParserFunction` and keep `LOGICAL_ERROR` here.

2022-11-18 01:21 UTC, evillique commented
There was a little [bug](https://github.com/ClickHouse/ClickHouse/pull/43350/files#diff-c9b1b8a9340030064ff0f78deb256c3d34608af5b2d4a5bd0a59eee7260733e8R923) in the ExpressionParser that allowed it to parse an unlimited amount of round brackets into one function, but the same error [occurs](https://fiddle.clickhouse.com/7384d943-3d73-4cfb-a5a5-dcf1e6942a56) on the 22.9 version (before the new parser) where there are two pairs of brackets.

The actual reason it happens is not that `args_func.size()` is 0, but because it actually equals 2. When we parse a function through ParserFunction we can specify if we want two pairs of brackets to be parsed as `parameters` and `arguments` in ASTFunction respectively. In this case, we will put both of them in the children of ASTFunction and get this error.

It is used in aggregate functions, but here I don't see any table functions that use it, so I tried to disable it in the previously mentioned PR as well.

2022-11-18 02:26 UTC, ucasfl commented
> And finally: why do you think that it's not a logical error?
> 
> Is it possible to have a function without arguments list? Of course it's possible to have a function with empty arguments list (like `func()`), but not without arguments list (`func` is an identifier, not a function).
> 
> Seems like behavior of `ParserFunction` was changed recently (we can ask @evillique), so now the parser can produce invalid AST. I guess we have many places in code which assume that `ASTFunction` always has one child and it's `ASTExpressionList`. We have to either find all such places and fix them or fix `ParserFunction` and keep `LOGICAL_ERROR` here.

It's ok to keep it and fix `ParserFunction`, and many other table functions also should fix it, because currently lot of them use `NUMBER_OF_ARGUMENTS_DOESNT_MATCH` as the ErrorCode.

2022-11-21 15:39 UTC, tavplubix commented
Closed in favor of https://github.com/ClickHouse/ClickHouse/pull/43350

2022-11-21 15:39 UTC, closed without merging