Support external source Redis WIP
ClickHouse/ClickHouse pull request #4361
Opened 2019-02-12 11:31 UTC by comunodi

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category:
- New Feature

Short description (up to few sentences):
Support Redis storage as external dictionary via Poco driver

2019-02-25 14:52 UTC, proller commented
Is this Still [WIP] ?

2019-03-10 16:13 UTC, alexey-milovidov commented
Tests must be converted to integration tests, because dictionary tests were deleted.

2019-03-10 16:14 UTC, alexey-milovidov commented
You have to tell your experience and performance testing results with Redis dictionaries.

2019-03-21 18:12 UTC, alesapin commented
I have added integration test, but Redis dictionary doesn't seems to be ok. https://github.com/yandex/ClickHouse/commit/22fc9a96b30721869724a0ce630ded701f5d3ede.

2019-03-21 18:20 UTC, alesapin requested changes

2019-03-21 18:20 UTC, alesapin commented on dbms/src/Dictionaries/RedisBlockInputStream.cpp
> +            if (cursor == keys.size())
Increment of index after comparison  == segmentation fault.

2019-03-21 18:20 UTC, alesapin commented on dbms/src/Dictionaries/RedisBlockInputStream.cpp
> +                insertValueByIdx(1, value);
Why do we insert in first column of block only?

2019-03-21 18:20 UTC, alesapin commented on dbms/src/Dictionaries/RedisBlockInputStream.cpp
> +        return description.sample_block.cloneWithColumns(std::move(columns));
Where is check, that columns consistent with sample block?

2019-03-21 18:20 UTC, alesapin commented on dbms/src/Dictionaries/RedisBlockInputStream.cpp
> +        assert(size == description.sample_block.columns());
What does it mean? Why only two columns?

2019-03-21 18:20 UTC, alesapin commented on dbms/src/Dictionaries/RedisDictionarySource.cpp
> +            (void)dict_struct;
Formating, style guide.

2019-03-21 18:20 UTC, alesapin commented on dbms/src/Dictionaries/RedisDictionarySource.cpp
> +        for (const UInt64 id : ids)
redundant const.

2019-03-21 18:20 UTC, alesapin commented on dbms/src/Dictionaries/RedisBlockInputStream.h
> +#include "ExternalResultDescription.h"
Doesn't compiles. This header in Common directory.

2019-03-21 18:20 UTC, alesapin commented on dbms/src/Dictionaries/RedisBlockInputStream.cpp
> +            const Poco::Redis::RedisType::Ptr & value = *(values.begin() + i);
Unsafe. Why we expect values size to be equals to num_rows?

2019-09-24 23:27 UTC, merged