DOCAPI-3820: EN review and RU translation for SELECT JOIN
ClickHouse/ClickHouse pull request #4422
Opened 2019-02-17 07:42 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation

2019-02-17 10:46 UTC, blinkov requested changes

2019-02-17 10:46 UTC, blinkov commented on docs/en/query_language/select.md
> +**`GLOBAL JOIN`**
** and ` are useless together

2019-02-17 10:46 UTC, blinkov commented on docs/en/query_language/select.md
> +Only one `JOIN` can be specified in a query (on a single level). To run multiple `JOIN` queries, you can put them in subqueries.
This limitation is (almost) gone by now, let's remove it.

2019-02-17 10:46 UTC, blinkov commented on docs/en/query_language/select.md
> +Each time a query is run with the same `JOIN`, the subquery is run again because the result is not cached. To avoid this, use the special 'Join' table engine, which is a prepared array for joining th
link to Join table engine?

2019-02-17 10:46 UTC, blinkov commented on docs/en/query_language/select.md
> +The `JOIN` behavior is affected by the [join_use_nulls](../operations/settings/settings.md#settings-join_use_nulls) setting. With `join_use_nulls=1`, `JOIN` works like in standard SQL.
We'd better start with describing the default behaviour.

2019-02-17 10:46 UTC, blinkov commented on docs/ru/query_language/select.md
> +    Не связана по функциональности с [ARRAY JOIN](#select-array-join-clause) .
не связана с функциональностью ARRAY JOIN

2019-02-17 10:46 UTC, blinkov commented on docs/ru/query_language/select.md
> +[GLOBAL] [ANY|ALL] INNER|LEFT|RIGHT|FULL|CROSS [OUTER] JOIN <right_subquery>
по идее INNER|LEFT|RIGHT|FULL|CROSS тоже уже опционально, при отсутствии должен быть INNER

2019-02-18 09:20 UTC, blinkov requested changes

2019-02-18 09:20 UTC, blinkov commented on docs/en/query_language/select.md
> +While merging tables with `JOIN`, the empty cells may appear. The setting [join_use_nulls](../operations/settings/settings.md#settings-join_use_nulls) define how ClickHouse fills these cells.
It's better to avoid "merge" in this context as it can be confused with background merges of MergeTree tables

2019-02-18 09:20 UTC, blinkov commented on docs/en/query_language/select.md
> +#### Processing of empty or NULL cells
Title Case

2019-02-18 09:20 UTC, blinkov commented on docs/en/query_language/select.md
>  **`ANY` or `ALL` strictness**
backticks inside bold

2019-02-18 09:20 UTC, blinkov commented on docs/en/query_language/select.md
> +You may skip the `OUTER` keyword because it is implied by default.
it's not clear what happens if you skip either INNER and OUTER simultaneously

2019-02-18 09:20 UTC, blinkov commented on docs/ru/query_language/select.md
> +Если `JOIN`  необходим для соединения с таблицами измерений (dimension tables - сравнительно небольшие таблицы, которые содержат свойства измерений - например, имена для рекламных кампаний), то испол
опять двойные пробелы...

2019-02-18 12:42 UTC, BayoNet commented on docs/ru/query_language/select.md
> +Если `JOIN`  необходим для соединения с таблицами измерений (dimension tables - сравнительно небольшие таблицы, которые содержат свойства измерений - например, имена для рекламных кампаний), то испол
Что-то я уже не знаю, что с ними делать, из всех щелей лезут :-(. Постараюсь ещё внимательнее отлавливать.

2019-02-18 13:55 UTC, blinkov commented on docs/en/query_language/select.md
> +You may skip the `INNER` and `OUTER` keywords because they are implied by default.
not exactly: if you skip all of them `INNER` is implied, but if you specify any of the alternatives to INNER (LEFT/RIGHT/FULL/etc.) `OUTER` is implied

I don't remember if we generate an error on `INNER OUTER JOIN`, but logically it's incorrect

2019-02-19 16:28 UTC, merged

2019-02-19 16:29 UTC, ogorbacheva commented on docs/ru/operations/settings/settings.md
> +Устанавливает тип поведения [JOIN](../../query_language/select.md). При присоединении таблиц могу появляться пустые ячейки. ClickHouse заполняет их по-разному в зависимости от настройки.
Опечатка - могуТ

2019-02-19 16:31 UTC, ogorbacheva commented on docs/ru/query_language/select.md
> +Вместо `<left_subquery>` и `<right_subquery>` можно указать имена таблиц. Это эквивалентно поздапросу `SELECT * FROM table`, за исключением особого случая таблицы с движком [Join](../operations/table
поздапросу -> подзапросу

2019-02-19 16:32 UTC, ogorbacheva commented on docs/ru/query_language/select.md
> +Если указано `ANY` , то при наличии в "правой" таблице нескольких соответствующих строк, будет присоединена только первая попавшаяся. Если известно, что в "правой" таблице есть не более одной подходя
опять пробел вылез лишний (после `ALL`)

2019-02-19 16:34 UTC, ogorbacheva commented on docs/ru/query_language/select.md
> +Будте аккуратны при использовании `GLOBAL` . За дополнительной информацией обращайтесь в раздел [Распределенные подзапросы](#select-distributed-subqueries).
Опечатка - будЬте

2019-02-19 16:37 UTC, ogorbacheva commented on docs/ru/query_language/select.md
> +Из подзапроса удаляются все столбцы ненужные для `JOIN` .
Запятая пропущена (перед ненужные)

2019-02-19 16:38 UTC, ogorbacheva commented on docs/ru/query_language/select.md
> +При запуске `JOIN`, отсутствует оптимизация порядка выполнения по отношению к другим стадиям запроса. Соединение (поиск в "правой" таблице) выполняется до фильтрации в `WHERE` и до агрегации. Чтобы я
и тут пробел

2019-02-19 16:39 UTC, ogorbacheva commented on docs/ru/query_language/select.md
> +Требуется, чтобы столбцы, указанные в `USING` , назывались одинаково в обоих подзапросах, а остальные столбцы - по-разному. Изменить имена столбцов в подзапросах можно с помощью алиасов (в примере ис
пробел после USING

2019-02-19 16:41 UTC, ogorbacheva commented on docs/ru/query_language/select.md
> +"Правая" таблица (результат подзапроса) располагается в оперативке. Если оперативки не хватает, вы не сможете выполнить `JOIN` .
Я бы заменила на "оперативная память"

2019-02-19 16:42 UTC, ogorbacheva commented on docs/ru/query_language/select.md
> +Если `JOIN` необходим для соединения с таблицами измерений (dimension tables - сравнительно небольшие таблицы, которые содержат свойства измерений - например, имена для рекламных кампаний), то исполь
правая таблица - где-то указана в кавычках, где-то без.