Fix reading bool value with CRLF in CSV format
ClickHouse/ClickHouse pull request #44442
Opened 2022-12-20 16:14 UTC by Avogar

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix reading bool value with CRLF in CSV format.
Closes https://github.com/ClickHouse/ClickHouse/issues/44401

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2022-12-20 18:03 UTC, nsweeting commented
The test doesn't seem to touch the broken behaviour right now:

```
❯ echo -ne "True\r\nFalse\r\n" | clickhouse local --input-format=CSV -q "select * from table";
True
False
```

vs

```
❯ echo -ne "True\r\nFalse\r\n" | clickhouse local --structure "a Boolean, b Boolean" --input-format=CSV -q "select * from table";
Code: 467. DB::Exception: Cannot parse boolean value here: 'True
Fals', should be 'true' or 'false' controlled by setting bool_true_representation and bool_false_representation or one of True/False/T/F/Y/N/Yes/No/On/Off/Enable/Disable/Enabled/Disabled/1/0: (at row 1)
:
Row 1:
Column 0,   name: a, type: Bool, ERROR: text "True<CARRIAGE RETURN><LINE FEED>Fals" is not like Bool

: While executing ParallelParsingBlockInputFormat: While executing File. (CANNOT_PARSE_BOOL)
```

2022-12-20 18:08 UTC, Avogar commented
I forgot to add `--structure='x Bool'` to the command:
```
echo -ne "True\r\nFalse\r\n" | clickhouse local --structure='a Boolean' --input-format=CSV -q "select * from table"
Code: 467. DB::Exception: Cannot parse boolean value here: 'True
Fals', should be 'true' or 'false' controlled by setting bool_true_representation and bool_false_representation or one of True/False/T/F/Y/N/Yes/No/On/Off/Enable/Disable/Enabled/Disabled/1/0: (at row 1)
:
Row 1:
Column 0,   name: x, type: Bool, ERROR: text "True<CARRIAGE RETURN><LINE FEED>Fals" is not like Bool
```

I'll fix that.

Your second example contains incorrect CSV data. `"True\r\nFalse\r\n"` cannot be parsed with structure `"a Boolean, b Boolean"`

2022-12-20 18:14 UTC, nsweeting requested changes

2022-12-20 18:14 UTC, nsweeting commented on tests/queries/0_stateless/02513_csv_bool_allow_crlf.sh
> +echo -ne "True\r\nFalse\r\n" | $CLICKHOUSE_LOCAL --stracture='x Bool' --input-format=CSV -q "select * from table";
```suggestion
echo -ne "True\r\nFalse\r\n" | $CLICKHOUSE_LOCAL --structure='x Bool' --input-format=CSV -q "select * from table";
```

2022-12-20 18:15 UTC, Avogar commented on tests/queries/0_stateless/02513_csv_bool_allow_crlf.sh
> +echo -ne "True\r\nFalse\r\n" | $CLICKHOUSE_LOCAL --stracture='x Bool' --input-format=CSV -q "select * from table";
Oups :)

2022-12-20 19:04 UTC, yakov-olkhovskiy approved these changes

2022-12-20 20:24 UTC, nsweeting requested changes

2022-12-20 20:24 UTC, nsweeting commented on tests/queries/0_stateless/02513_csv_bool_allow_crlf.reference
> +False
```suggestion
true
false
```

2022-12-26 18:25 UTC, alexey-milovidov approved these changes

2022-12-26 18:25 UTC, merged