Set pipeline type in join step description
ClickHouse/ClickHouse pull request #44545
Opened 2022-12-23 19:34 UTC by vdimir

### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2022-12-27 11:17 UTC, vdimir commented
Difference (running added test on current version):

<details>
<summary>Details</summary>



```
02514_analyzer_drop_join_on:                                            [ FAIL ] - result differs with reference: 
--- /home/ubuntu/ClickHouseA/tests/queries/0_stateless/02514_analyzer_drop_join_on.reference    2022-12-27 11:16:11.639907351 +0000
+++ /home/ubuntu/ClickHouseA/tests/queries/0_stateless/02514_analyzer_drop_join_on.stdout       2022-12-27 11:16:36.235829022 +0000
@@ -7,17 +7,23 @@
     Header: default.a.a2_4 String
       Join (JOIN FillRightFirst)
       Header: default.a.a2_4 String
+              default.a.a1_1 UInt64
+              default.b.b1_0 UInt64
               default.c.c1_2 UInt64
               default.d.d1_3 UInt64
         Expression ((JOIN actions + DROP unused columns after JOIN))
         Header: default.a.a2_4 String
+                default.a.a1_1 UInt64
+                default.b.b1_0 UInt64
                 default.c.c1_2 UInt64
           Join (JOIN FillRightFirst)
           Header: default.a.a2_4 String
+                  default.a.a1_1 UInt64
                   default.b.b1_0 UInt64
                   default.c.c1_2 UInt64
             Expression ((JOIN actions + DROP unused columns after JOIN))
             Header: default.a.a2_4 String
+                    default.a.a1_1 UInt64
                     default.b.b1_0 UInt64
               Join (JOIN FillRightFirst)
               Header: default.a.a2_4 String
@@ -47,18 +53,24 @@
   Join (JOIN FillRightFirst)
   Header: default.a.k_2 UInt64
           default.a.a2_0 String
+          default.b.k_3 UInt64
+          default.c.k_4 UInt64
           default.d.d2_1 String
           default.d.k_5 UInt64
     Expression (DROP unused columns after JOIN)
     Header: default.a.k_2 UInt64
             default.a.a2_0 String
+            default.b.k_3 UInt64
+            default.c.k_4 UInt64
       Join (JOIN FillRightFirst)
       Header: default.a.k_2 UInt64
               default.a.a2_0 String
+              default.b.k_3 UInt64
               default.c.k_4 UInt64
         Expression (DROP unused columns after JOIN)
         Header: default.a.k_2 UInt64
                 default.a.a2_0 String
+                default.b.k_3 UInt64
           Join (JOIN FillRightFirst)
           Header: default.a.k_2 UInt64
                   default.a.a2_0 String
@@ -93,23 +105,29 @@
             b.bx_0 String
       Join (JOIN FillRightFirst)
       Header: default.a.a2_6 String
+              default.a.a1_2 UInt64
               b.bx_0 String
+              b.b1_1 UInt64
               default.c.c2_5 String
               default.c.c1_3 UInt64
               d.d1_4 UInt64
         Filter (( + (JOIN actions + DROP unused columns after JOIN)))
         Header: default.a.a2_6 String
+                default.a.a1_2 UInt64
                 b.bx_0 String
+                b.b1_1 UInt64
                 default.c.c2_5 String
                 default.c.c1_3 UInt64
           Join (JOIN FillRightFirst)
           Header: default.a.a2_6 String
+                  default.a.a1_2 UInt64
                   b.bx_0 String
                   b.b1_1 UInt64
                   default.c.c2_5 String
                   default.c.c1_3 UInt64
             Expression ((JOIN actions + DROP unused columns after JOIN))
             Header: default.a.a2_6 String
+                    default.a.a1_2 UInt64
                     b.bx_0 String
                     b.b1_1 UInt64
               Join (JOIN FillRightFirst)
```



</details>

2023-01-03 10:49 UTC, kitaisreal requested changes
Looks good. Need to fix minor details and merge.

2023-01-03 10:49 UTC, kitaisreal commented on src/Planner/CollectColumnIndetifiers.h
> +#pragma once
Need to rename this file into `CollectColumnIdentifiers.h` from `CollectColumnIndetifiers.h`.

2023-01-03 10:49 UTC, kitaisreal commented on src/Planner/CollectColumnIndetifiers.h
> +/// Collect all top level column identifiers from query tree node.
Need to add in comment precondition that table expression data must be already collected in planner context.

2023-01-03 10:49 UTC, kitaisreal commented on src/Planner/PlannerJoinTree.h
> +using ColumnIdentifierSet = std::unordered_set<ColumnIdentifier>;
Need to move this into `TableExpressionData` and reuse in `CollectColumnIdentifiers`.

2023-01-03 10:49 UTC, kitaisreal commented on tests/queries/0_stateless/02514_analyzer_drop_join_on.sql
> +EXPLAIN PLAN header = 1
Consider to enable `echoOn` so test will be easier to verify.

2023-01-12 10:47 UTC, kitaisreal approved these changes

2023-01-12 10:51 UTC, kitaisreal approved these changes

2023-01-12 10:51 UTC, merged