Rewrite aggregate functions with if
ClickHouse/ClickHouse pull request #44730
Opened 2022-12-30 09:38 UTC by taiyang-li

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Rewrite aggregate functions with if expression as argument when logically equivalent. For example, avg(if(cond, col, null)) can be rewritten to avgIf(cond, col)

```
:) explain syntax select avg(if(number % 2, number, null)) from numbers(100);

EXPLAIN SYNTAX
SELECT avg(if(number % 2, number, NULL))
FROM numbers(100)

Query id: 59d1af55-b195-40db-b279-c31013d72ee2

┌─explain──────────────────────────┐
│ SELECT avgIf(number, number % 2) │
│ FROM numbers(100)                │
└──────────────────────────────────┘

2 rows in set. Elapsed: 0.001 sec. 

```

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2022-12-30 12:45 UTC, vdimir requested changes
@taiyang-li thank you for your effort!

Now we are migrating to the new infrastructure for query analysis and trying to avoid introducing AST-based optimizations because it's usually error-prone.
It's better to implement such optimization on top of _query tree_, it will work with `allow_experimental_analyzer`, which is not production-ready yet. But eventually, old infrastructure with AST-based optimizations will be removed, so it's better to go a bit ahead :)
Check out the _QueryTreePassManager_ section at https://github.com/ClickHouse/ClickHouse/issues/42648 for the examples.

2023-01-12 11:26 UTC, taiyang-li commented
> @taiyang-li thank you for your effort!
> 
> Now we are migrating to the new infrastructure for query analysis and trying to avoid introducing AST-based optimizations because it's usually error-prone. It's better to implement such optimization on top of _query tree_, it will work with `allow_experimental_analyzer`, which is not production-ready yet. But eventually, old infrastructure with AST-based optimizations will be removed, so it's better to go a bit ahead :) Check out the _QueryTreePassManager_ section at #42648 for the examples.

@vdimir  done.

2023-01-18 12:37 UTC, vdimir reviewed
I suggest not introducing AST optimization at all. It's deprecated due to error proneness. 

Code of pass lgtm, but need to fix build and.

@kitaisreal @novikd Do you want to take a look at the `RewriteAggregateFunctionWithIfPass` ?

2023-01-18 12:37 UTC, vdimir commented on tests/queries/0_stateless/02518_rewrite_aggregate_function_with_if.sql
> +explain syntax select sum(if(number % 2, number, 0)) from numbers(100);
`explain syntax` doesn't show the changes, it's visible in `EXPLAIN QUERY TREE run_passes = 1 SELECT ...`

2023-01-30 07:23 UTC, taiyang-li commented
> I suggest not introducing AST optimization at all. It's deprecated due to error proneness.
> 
> Code of pass lgtm, but need to fix build and.
> 
> @kitaisreal @novikd Do you want to take a look at the `RewriteAggregateFunctionWithIfPass` ?

Ast optimizer is already removed.

2023-01-30 12:48 UTC, taiyang-li commented
failed tests not related to this pr .

2023-01-31 10:24 UTC, vdimir approved these changes

2023-01-31 10:38 UTC, vdimir commented
@taiyang-li, could you please resolve a conflict (better rebase, but merge is also ok if there're too many conflicts)? I can't push to branch or resolve via web interface for unclear reasons.

2023-01-31 15:54 UTC, novikd approved these changes
LGTM, but requires adding documentation before merging.

2023-02-08 12:03 UTC, taiyang-li commented
@vdimir @novikd Sorry to bother you, do you think this pr is ok to merge now?

2023-02-08 14:26 UTC, merged