Feature: Optimize the replica delay api logic
ClickHouse/ClickHouse pull request #45148
Opened 2023-01-11 08:31 UTC by mateng0915

Description:
============
Currently if in the Whole CK instance has one table is read only status then the API  /replicas_status will throw error, xxx table is read only and can not get other normal ReplicatedMergeTree table's delay value

Solution:
=========
Return other normal table's delay value even if the CK instance has readonly Replicatedxxx table

Please enter the commit message for your changes. Lines starting

- Improvement

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-02-11 00:06 UTC, pufit requested changes

2023-02-11 00:06 UTC, pufit commented on src/Server/ReplicasStatusHandler.cpp
> +                if(!table_replicated->isTableReadOnly())
space before brackets

2023-02-11 00:06 UTC, pufit commented on src/Server/ReplicasStatusHandler.cpp
> +                } else {
`else` should be on a new line

2023-02-13 03:44 UTC, mateng0915 commented on src/Server/ReplicasStatusHandler.cpp
> +                if(!table_replicated->isTableReadOnly())
Thx comment,  Fixed it

2023-02-13 03:44 UTC, mateng0915 commented on src/Server/ReplicasStatusHandler.cpp
> +                } else {
Thx comment, Fixed it

2023-02-14 00:41 UTC, pufit approved these changes

2023-02-14 06:29 UTC, mateng0915 commented
@pufit  Hello pufit can you help merge this PR, thx

2023-02-14 15:09 UTC, pufit commented
> @pufit Hello pufit, can you help merge this PR, thx

Yes, sure. Just wanted to run CI before merging. It's not that I've expected any bug in your commit, just a good practice in general.

2023-02-14 18:44 UTC, merged