Remove PREALLOCATE for HASHED/SPARSE_HASHED dictionaries
ClickHouse/ClickHouse pull request #45388
Opened 2023-01-18 11:06 UTC by azat

### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove PREALLOCATE for HASHED/SPARSE_HASHED dictionaries

### Documentation entry for user-facing changes
It does not give significant benefit, but now, you hashed/sparse_hashed dictionaries can be filled in parallel (#40003), using sharded dictionaries, and this should be used instead of PREALLOCATE.

Note, that dictionaries, that had been created with PREALLOCATE will work, but simply ignore this attribute.

Fixes: #41985 (cc @alexey-milovidov)
Reverts: #23979 (cc @kitaisreal)

Note: I've marked this as `Backward Incompatible Change` since this removes functionality, however, unlikely that it was broadly used, and as written above dictionaries that had been created with `PREALLOCATE` will simply ignore this attribute.

2023-01-18 16:43 UTC, kitaisreal requested changes
LGMT. Need to add test that we can create dictionary with `PREALLOCATE` setting without exception for backward compatibility.

2023-01-18 16:43 UTC, kitaisreal commented on docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-layout.md
> +LAYOUT(SPARSE_HASHED([]))
Need to remove `[]`.

2023-01-18 16:43 UTC, kitaisreal commented on docs/ru/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-layout.md
> +LAYOUT(SPARSE_HASHED([]))
Need to remove `[]`.

2023-01-18 16:58 UTC, azat commented
> Need to add test that we can create dictionary with PREALLOCATE setting without exception for backward compatibility.

Ok, I've added the test (though right now this is how dictionary attributes works, unknown are simply ignored).
BTW what do you think, maybe it worth produce a warning if a dictionary with `PREALLOCATE` was created?

2023-01-18 17:48 UTC, kitaisreal commented
@azat I agree we can produce warning if we see PREALLOCATE.

2023-01-19 16:52 UTC, kitaisreal approved these changes

2023-01-19 16:53 UTC, kitaisreal commented
@azat need to fix docs check.

2023-01-19 18:06 UTC, azat commented
> need to fix docs check.

@kitaisreal is it a real problem? As far as I remember the difference between previous version of the patch (f5930d4d04ed5c9a790a324228dde562b8a30401) and current (4366f7fb3b02a0492def7d59e4abab570dba9738) does not contains docs changes:

```
$ git di f5930d4d04ed5c9a790a324228dde562b8a30401..4366f7fb3b02a0492def7d59e4abab570dba9738 --stat
 src/Dictionaries/HashedDictionary.cpp                            |  3 +++
 tests/queries/0_stateless/01509_dictionary_preallocate.reference |  2 +-
 tests/queries/0_stateless/01509_dictionary_preallocate.sh        | 40 ++++++++++++++++++++++++++++++++++++++++
 tests/queries/0_stateless/01509_dictionary_preallocate.sql       | 32 --------------------------------
 4 files changed, 44 insertions(+), 33 deletions(-)
```

While for previous patch docs check had been passed - https://s3.amazonaws.com/clickhouse-test-reports/45388/f5930d4d04ed5c9a790a324228dde562b8a30401/docs_check.html

Plus the check itself does not provide any details, or I'm missing something.

2023-01-20 11:51 UTC, merged