DOCAPI-5758: EN review and RU translation of the Kafka engine descrip…
ClickHouse/ClickHouse pull request #4660
Opened 2019-03-12 09:27 UTC by BayoNet

…tion.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation

2019-03-12 09:37 UTC, blinkov requested changes

2019-03-12 09:37 UTC, blinkov commented on docs/ru/operations/table_engines/kafka.md
> +Не используйте этот метод в новых проектах. По возможности переключите старые проекты на метод, описанный выше.
тут отступ похоже потерялся

2019-03-12 09:37 UTC, blinkov commented on docs/ru/operations/table_engines/kafka.md
> +- `kafka_skip_broken_messages` – режим парсинга сообщений Кафка. Если `kafka_skip_broken_messages = 1`, то движок отбрасывает сообщения Кафки, которые не получилось распарсить (одно сообщение в точно
* может не будем «Kafka» русскими буквами писать?
* двойной уровень вложенности скобок так себе смотрится
* не написано явно что происходит когда значение 0 + это скорее не режим парсинга, а режим обработки проблемных сообщений

2019-03-15 15:01 UTC, blinkov commented
сборка сломалась

2019-03-15 15:19 UTC, BayoNet commented
Починил вроде.

2019-03-15 16:39 UTC, merged