DOCAPI-5441- EN review and RU translation for the tcp_port_secure docs.
ClickHouse/ClickHouse pull request #4676
Opened 2019-03-13 11:38 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentaton

2019-03-14 14:07 UTC, blinkov requested changes

2019-03-15 14:59 UTC, blinkov commented on docs/en/operations/server_settings/settings.md
> +**Возможные значения**
это же английская версия?

2019-03-15 15:00 UTC, BayoNet commented on docs/en/operations/server_settings/settings.md
> +**Возможные значения**
Это я сгоряча, первым коммитом промахнулся. Во втором поправил.

2019-03-20 12:09 UTC, BayoNet commented
Сейчас специально попробовал собрать документацию локально полностью, сборщик проблем не выдал.

2019-03-20 12:57 UTC, merged