Fix crash in explain graph with StorageMerge
ClickHouse/ClickHouse pull request #48102
Opened 2023-03-28 11:04 UTC by vdimir

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fix crash in `EXPLAIN graph = 1 ...` with StorageMerge, close https://github.com/ClickHouse/ClickHouse/issues/48100

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-03-28 11:27 UTC, evillique approved these changes

2023-03-28 14:44 UTC, KochetovNicolai commented on src/Storages/StorageMerge.h
> +    std::vector<QueryPlan> child_plans;
No, it's not a good idea.
Storage may leave for a long time, but we don't clean these plans.

2023-03-28 14:56 UTC, KochetovNicolai approved these changes

2023-03-28 23:10 UTC, alexey-milovidov commented on src/Storages/StorageMerge.cpp
> +        QueryPlan & plan = child_plans.emplace_back();
Missing a comment.

2023-03-28 23:10 UTC, alexey-milovidov commented on src/Storages/StorageMerge.h
> +    std::vector<QueryPlan> child_plans;
Missing a comment.

2023-03-28 23:11 UTC, alexey-milovidov requested changes
.

2023-03-29 11:04 UTC, alexey-milovidov approved these changes

2023-03-30 10:54 UTC, merged