DOCAPI-5203: Direct I/O settings for MergeTree descriptions. EN review and RU translation.
ClickHouse/ClickHouse pull request #4848
Opened 2019-03-29 11:51 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Documentation

2019-03-29 12:56 UTC, blinkov requested changes

2019-03-29 12:56 UTC, blinkov commented on docs/ru/operations/settings/settings.md
> +ClickHouse использует этот параметр при чтении данных из таблиц. Если общий объем хранения всех данных для чтения превышает `min_bytes_to_use_direct_io` байт, тогда ClickHouse  использует флаг  `O_DI
удвоенный пробел

2019-03-29 12:56 UTC, blinkov commented on docs/ru/operations/settings/settings.md
> +0 — безбуфферный ввод-вывод отключен.
потерялась единичка, и в английской версии

2019-03-29 12:56 UTC, blinkov commented on docs/ru/operations/settings/settings.md
> +Минимальный объем данных, необходимый для безбуфферного чтения/записи (direct I/O) на диск.
* непонятно почему два ф, по-русски вроде правильно буфер
* сам перевод спорный, на мой вкус лучше было б хотя б «небуферизуемого», если «прямой» чем-то не нравится

2019-03-29 12:56 UTC, blinkov commented on docs/ru/operations/table_engines/mergetree.md
> +    - `min_merge_bytes_to_use_direct_io` — минимальный объем данных, необходимый для безбуфферного чтения/записи (direct I/O) на диск. При слиянии частей данных ClickHouse вычисляет общий объем хране
двойной пробел

2019-03-29 12:56 UTC, blinkov commented on docs/ru/operations/table_engines/mergetree.md
>  Пример
«пример» жирным вроде обычно сейчас?

2019-04-08 16:04 UTC, blinkov commented
не дает смерджить из-за конфликтов

2019-04-08 16:24 UTC, BayoNet commented
Вроде поправил.

2019-04-08 16:25 UTC, merged