Added flag toa avoid writing once per thread to query_views_log
ClickHouse/ClickHouse pull request #48626
Opened 2023-04-11 07:40 UTC by AlfVII

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Removed per-thread entries in query_views_log

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

When inserting data through a Null landing table with a Materialized View with multiple threads, several entries are stored in query_views_log, one per used thread. This PR adds a flag to write only one entry.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-04-11 13:22 UTC, qoega commented
Why do you want to suppress those records?

2023-04-11 13:53 UTC, Algunenano requested changes

2023-04-11 13:53 UTC, Algunenano commented on tests/queries/0_stateless/02713_repeated_entries_query_views_log.sh
> +rand_id=$RANDOM;
Why do you need random ids?

2023-06-27 09:35 UTC, Algunenano commented
This PR was bad all around and @AlfVII is no longer working on it. Please close it.

2023-10-09 01:49 UTC, closed without merging