distrubuted create [#CLICKHOUSE-5]
ClickHouse/ClickHouse pull request #491
Opened 2017-02-14 14:07 UTC by artpaul

2017-02-15 20:53 UTC, alexey-milovidov requested changes

2017-02-15 20:53 UTC, alexey-milovidov commented on dbms/include/DB/Parsers/ASTCreateQuery.h
> +	bool attach{false};	/// If true then it means what query is ATTACH TABLE.
Little typo.

2017-02-15 20:53 UTC, alexey-milovidov commented on dbms/src/Interpreters/DDLWorker.cpp
> +class Arguments final
"resharding" was left from copy-paste.

2017-02-15 20:53 UTC, alexey-milovidov commented on dbms/src/Interpreters/DDLWorker.cpp
> +				throw Exception{"Unknown parameter in resharding configuration", ErrorCodes::UNKNOWN_ELEMENT_IN_CONFIG};
.

2017-02-15 20:53 UTC, alexey-milovidov commented on dbms/src/Interpreters/DDLWorker.cpp
> +			throw Exception{"Resharding: missing parameter task_queue_path", ErrorCodes::INVALID_CONFIG_PARAMETER};
.

2017-02-15 20:53 UTC, alexey-milovidov commented on dbms/include/DB/Interpreters/DDLWorker.h
> +class DDLWorker
Need comment about what it is.
What is the structure of nodes in ZooKeeper. How they are processed.
And so on.

2017-02-15 20:53 UTC, alexey-milovidov commented on dbms/src/Interpreters/DDLWorker.cpp
> +		catch (const std::exception & ex)
Need to catch ... to extract more exception info.
See `tryLogCurrentException` across the code.

2017-02-15 20:53 UTC, alexey-milovidov commented on dbms/src/Interpreters/InterpreterCreateQuery.cpp
> +static void ExecuteQuery(const Cluster::Address & addr, const std::string & query)
Style.

2017-02-15 20:53 UTC, alexey-milovidov commented on dbms/src/Interpreters/InterpreterCreateQuery.cpp
> +	std::string table_name = create.database + "." + create.table;
See `backQuoteIfNeed` for quoting of identifiers.

2017-02-15 20:53 UTC, alexey-milovidov commented on dbms/src/Interpreters/InterpreterCreateQuery.cpp
> +		// TODO catch exceptions
You could create all required nodes in single transaction atomically.

2017-02-15 20:53 UTC, alexey-milovidov commented on dbms/src/Interpreters/InterpreterCreateQuery.cpp
> +				failed.push_back(addr);
Ok. But we also need to collect information from exceptions and then write log,
... and further we need to return a resultset for distributed create query, containing information, that following addresses was processed Ok, and following will be processed asynchronously.

2017-02-15 21:06 UTC, alexey-milovidov requested changes

2017-02-15 21:06 UTC, alexey-milovidov commented on dbms/include/DB/Interpreters/InterpreterCreateQuery.h
> +	void writeToZookeeper(ASTPtr query, const std::vector<Cluster::Address>& addrs);
Style.

2017-02-15 21:06 UTC, alexey-milovidov commented on dbms/src/Interpreters/InterpreterCreateQuery.cpp
> +			"/create/" + table_name;
It seems that `task_queue` is not actually a queue.
Queries are reordered. Need to mind that and don't forget to mention in doc.

2017-02-15 21:06 UTC, alexey-milovidov commented on dbms/src/Interpreters/DDLWorker.cpp
> +	}
I think, better to install watches.

2017-02-15 21:14 UTC, alexey-milovidov requested changes

2017-02-15 21:14 UTC, alexey-milovidov commented on dbms/src/Interpreters/InterpreterCreateQuery.cpp
> +		}
We must differentiate temporary failures (server unavailability, network issues) with incorrect queries.

2017-02-24 22:57 UTC, ludv1x commented on dbms/src/Parsers/formatAST.cpp
> +std::string formatASTToString(const IAST & ast)
Maybe, existing [queryToString](https://github.com/yandex/ClickHouse/blob/master/dbms/include/DB/Parsers/queryToString.h) will be better.

2017-04-25 04:39 UTC, alexey-milovidov commented
Waiting for new pull request.

2017-04-25 04:39 UTC, closed without merging