DOCAPI-6126: Clarification of the 'round' function description.
ClickHouse/ClickHouse pull request #4939
Opened 2019-04-08 14:56 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation

2019-04-08 15:38 UTC, blinkov requested changes

2019-04-08 15:38 UTC, blinkov commented on docs/ru/query_language/functions/rounding_functions.md
> +Реализует правило [округления к ближайшему целому](https://ru.wikipedia.org/wiki/%D0%9E%D0%BA%D1%80%D1%83%D0%B3%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5#%D0%9E%D0%B1%D1%89%D0%B8%D0%B9_%D0%BF%D0%BE%D1%80%D1%8F%D
не правило реализует, а само округление

2019-04-08 15:38 UTC, blinkov commented on docs/en/query_language/functions/rounding_functions.md
> +Implements the [rounding to the nearest integer](https://en.wikipedia.org/wiki/Rounding#Rounding_to_the_nearest_integer) rule. If `x` is exactly half-way between two numbers the function uses [banker
actually with N!=0 it's not rounding to an integer, it's more like https://en.wikipedia.org/wiki/Rounding#Floating-point_rounding

2019-04-10 06:01 UTC, blinkov commented
тесты не прошли, а так вроде норм

2019-04-10 06:57 UTC, BayoNet commented
Пофиксил ссылки. Локально собралось вроде.

2019-04-10 07:17 UTC, merged