Parallelize OPTIMIZE FINAL for non-replicated table
ClickHouse/ClickHouse pull request #49504
Opened 2023-05-04 12:29 UTC by aiven-sal

Close #46770

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
On  non-replicated tables, OPTIMIZE FINAL schedules merges for all partitions and waits for them to complete

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-08-08 03:14 UTC, al13n321 requested changes
IIUC, this makes the merge happen in context of a background thread rather than in query context. So, metrics aren't attributed to the query, memory limits are not taken from the query/session/user settings, and log messages won't include the query. Not ideal.

Let's at least propagate the metrics, then it'll be acceptable.

2023-08-08 03:14 UTC, al13n321 commented on tests/queries/0_stateless/02293_selected_rows_and_merges.sh
> +# Here for OPTIMIZE FINAL all values are 0, cause merges are executed in background.
The query still waits for the merges to complete, it just doesn't propagate the metrics to query_log. A whole new keyword wouldn't make sense for that.

We really should try to propagate the metrics, but I'm not sure what's a good way to do it.

I guess we should pass the thread group from `CurrentThread::getGroup()` in `merge()` to `MergePlainMergeTreeTask`, then make `transfer_profile_counters_to_initial_query()` add metrics to that thread group's `performance_counters`; either from `task_thread_group->performance_counters` (which I suspect won't work, but worth trying) or from `profile_counters` (like in `write_part_log`). I'm not sure if this should replace the `query_thread_group` or be a different thing.

@CheSema, any pointers?

2023-08-22 17:10 UTC, CheSema commented on tests/queries/0_stateless/02293_selected_rows_and_merges.sh
> +# Here for OPTIMIZE FINAL all values are 0, cause merges are executed in background.
That changes will break stats on the query.

Stats like this
https://github.com/ClickHouse/ClickHouse/blob/e708f0d9413a71cb788d3d23731fe379f44fd729/tests/queries/0_stateless/02293_selected_rows_and_merges.sh#L16-L20

@al13n321 is right, something has to be done to preserve it.

The most simple way I think is pass `transfer_profile_counters_to_initial_query calback` outside MergePlainMergeTreeTask. It has to add the stats to the query's thread group.

Be aware that this profile_counters does not account all metrics, the comment is actual.
https://github.com/ClickHouse/ClickHouse/blob/e708f0d9413a71cb788d3d23731fe379f44fd729/src/Storages/MergeTree/MergePlainMergeTreeTask.cpp#L34-36

The better approach is to account stats directly to the query's thread group. But I'm not sure that is safe to just reuse its thread group as a thread group for merge. That group consist query context, which has to have limited influence on merging. So for me this is an actual question how to do it elegant.

2023-08-22 17:11 UTC, CheSema requested changes
Query stats have to be preserved.

2023-08-22 18:13 UTC, CheSema commented on tests/queries/0_stateless/02293_selected_rows_and_merges.sh
> +# Here for OPTIMIZE FINAL all values are 0, cause merges are executed in background.
When `executeHere(task)` called thread group is not shared.

2023-08-22 19:35 UTC, al13n321 commented on tests/queries/0_stateless/02293_selected_rows_and_merges.sh
> +# Here for OPTIMIZE FINAL all values are 0, cause merges are executed in background.
Ah, so `executeHere()` also creates a new thread group, I see.

2023-08-22 19:39 UTC, al13n321 commented
Ok, I think this is how exactly to make the profile events propagate correctly:
```
src/Storages/MergeTree/MergePlainMergeTreeTask.h:
@@ -49,6 +49,11 @@ public:
         txn = std::move(txn_);
     }
 
+    void setQueryThreadGroup(ThreadGroupPtr g)
+    {
+        query_thread_group = g;
+    }
+
 private:
     void prepare();
     void finish();
@@ -89,6 +94,7 @@ private:
     MergeTreeTransactionPtr txn;
 
     ProfileEvents::Counters profile_counters;
+    ThreadGroupPtr query_thread_group;
 
     ContextMutablePtr task_context;
```
```
src/Storages/MergeTree/MergePlainMergeTreeTask.cpp:
@@ -108,7 +108,10 @@ void MergePlainMergeTreeTask::prepare()
             std::move(profile_counters_snapshot));
     };
 
-    transfer_profile_counters_to_initial_query = [this, query_thread_group = CurrentThread::getGroup()] ()
+    if (!query_thread_group)
+        query_thread_group = CurrentThread::getGroup();
+
+    transfer_profile_counters_to_initial_query = [this] ()
     {
         if (query_thread_group)
         {
```
Then call `task->setQueryThreadGroup(CurrentThread::getGroup())` in `StorageMergeTree::merge()` in the async case.

Please try it and see if it fixes the two tests.

2023-08-24 18:02 UTC, al13n321 approved these changes

2023-08-24 18:09 UTC, al13n321 commented
Test failures look related, need to investigate: `test_merge_canceled_by_s3_errors`, `test_memory_limit_success`, `01293_optimize_final_force`, `01825_replacing_vertical_merge`.

2023-12-27 15:07 UTC, alexey-milovidov commented
We have had many optimizations for FINAL recently - it will be nice to also have this one finished.

2024-03-24 20:17 UTC, alexey-milovidov commented
@aiven-sal Looks abandoned.

2024-10-28 06:20 UTC, closed without merging