Fix jemalloc per-cpu arena test for s390x
ClickHouse/ClickHouse pull request #49522
Opened 2023-05-04 19:40 UTC by HarryLeeIBM

Since s390x doesn't support jemalloc, functional test `01502_jemalloc_percpu_arena` fails on s390x.
The fix is to skip this test for s390x.

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Disabled 01502_jemalloc_percpu_arena functional test for s390x.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-05-04 21:18 UTC, alexey-milovidov approved these changes

2023-05-04 21:18 UTC, alexey-milovidov requested changes
There is no such tag in clickhouse-test.

2023-05-05 13:08 UTC, HarryLeeIBM commented
> There is no such tag in clickhouse-test.

`no-cpu-s390x` actually works. I think the failed reason is `Category 'Testing Improvement' is not valid`. I changed it to `Build/Testing/Packaging Improvement`.

> Fix jemalloc per-cpu arena test for s390x

2023-05-06 15:18 UTC, alexey-milovidov commented
We don't have support for this tag in clickhouse-test.

2023-05-06 15:18 UTC, closed without merging