Wrong table db name
ClickHouse/ClickHouse pull request #49610
Opened 2023-05-07 00:02 UTC by yariks5s

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added a hint for users when they write the name of db or table wrong 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-05-07 00:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=49610) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=49610) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=49610) it.</sub>

2023-05-11 15:14 UTC, CurtizJ requested changes
Please fix build and style check.

2023-05-11 15:14 UTC, CurtizJ commented on src/Interpreters/DatabaseCatalog.cpp
> +    }
Please add a reasonable limit to avoid complexity in case of many created tables or databases (e.g. 1000).

2023-05-11 15:14 UTC, CurtizJ commented on src/Interpreters/DatabaseCatalog.cpp
> +    }
Why not just use `getHints` or `appendHintsMessage` from `IHints`?

2023-05-11 15:14 UTC, CurtizJ commented on src/Interpreters/DatabaseCatalog.cpp
>      }
Actually this code should be executed later because if you have an empty `table_id` you cannot provide any hints.

2023-05-11 15:14 UTC, CurtizJ commented on src/Interpreters/DatabaseCatalog.cpp
> +                DatabaseNameHints hints(*this);
I think it's better to store an object with hints in `DatabaseCatalog` and reuse it.

2023-05-11 15:14 UTC, CurtizJ commented on src/Interpreters/DatabaseCatalog.cpp
> +                auto similarDb = hints.findMostSimilarWord(table_id.getAllRegisteredNames(), table_id.getDatabaseName());
`table_id.getAllRegisteredNames()` -- looks like it shouldn't compile.

2023-05-15 09:40 UTC, tavplubix commented
Continued in https://github.com/ClickHouse/ClickHouse/pull/49801

2023-05-15 09:40 UTC, closed without merging