DOCAPI-4177: HTTP compression settings. EN review. RU translation.
ClickHouse/ClickHouse pull request #4996
Opened 2019-04-12 15:51 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation

2019-04-13 06:38 UTC, blinkov requested changes

2019-04-13 06:38 UTC, blinkov commented on docs/ru/interfaces/http.md
> +Если вы указали `compress = 1` в URL, то сервер сжимает данные, которые он отправляет.
в url пробелы вокруг = не ставят

2019-04-13 06:38 UTC, blinkov commented on docs/ru/interfaces/http.md
> +Подробнее смотрите в разделе "Настройки".
ссылку?

2019-04-13 06:38 UTC, blinkov commented on docs/ru/interfaces/http.md
> +Имеется возможность получать информацию о прогрессе выполнения запроса в залоголвках X-ClickHouse-Progress. Для этого нужно включить настройку send_progress_in_http_headers.
ссылку на настройку?

2019-04-13 06:38 UTC, blinkov commented on docs/ru/operations/settings/settings.md
> +Включает или отключает fsync при записи .sql файлов. По умолчанию включено.
можно сослаться, например, на http://pubs.opengroup.org/onlinepubs/9699919799/functions/fsync.html

2019-04-15 10:51 UTC, BayoNet commented on docs/ru/interfaces/http.md
> +Имеется возможность получать информацию о прогрессе выполнения запроса в залоголвках X-ClickHouse-Progress. Для этого нужно включить настройку send_progress_in_http_headers.
Её сначала надо описать. Тикет поставил.

2019-04-15 11:47 UTC, merged