(WIP) Add DataTypeDomainBool
ClickHouse/ClickHouse pull request #5071
Opened 2019-04-22 05:20 UTC by hczhcz

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- New Feature

Short description (up to few sentences):

Add "Bool" using UInt8 as underlying type

Detailed description (optional):

```sql
CREATE TABLE test (a Bool) ENGINE = Memory;
INSERT INTO test VALUES ('false'), ('true');
SELECT * FROM test;
> false
> true
```

2019-04-22 14:30 UTC, alexey-milovidov commented
Missing test.

2019-04-22 14:31 UTC, alexey-milovidov commented on dbms/src/DataTypes/DataTypeDomainBool.cpp
> +                String(getName()) + " domain can only deserialize columns of type UInt32."
Error in comment.

2019-04-22 14:32 UTC, alexey-milovidov commented on dbms/src/DataTypes/DataTypeDomainBool.cpp
> +        istr.read(buffer, sizeof(buffer) - 1);
Extra data is eaten by this call.

2019-04-22 14:33 UTC, alexey-milovidov commented on dbms/src/DataTypes/DataTypeDomainBool.cpp
> +        istr.read(buffer, sizeof(buffer) - 1);
Look at `void DataTypeNumberBase<T>::deserializeTextJSON` for example.

2019-04-22 14:34 UTC, alexey-milovidov commented on dbms/src/DataTypes/DataTypeDomainBool.cpp
> +        if (strcmp(buffer, str_true) == 0)
Buffer overflow here.

2019-04-22 14:35 UTC, alexey-milovidov commented on dbms/src/DataTypes/DataTypeDomainBool.cpp
> +                "Invalid boolean value.",
Need to mention, what exactly value is invalid, in exception message.

2019-04-22 14:35 UTC, alexey-milovidov commented on dbms/src/DataTypes/DataTypeDomainBool.cpp
> +    void deserializeText(IColumn & column, ReadBuffer & istr, const FormatSettings &) const override
0 and 1 should be supported as well, for convenience.

2019-04-22 14:36 UTC, alexey-milovidov commented on dbms/src/DataTypes/DataTypeDomainBool.cpp
> +    factory.registerDataTypeDomain("UInt8", std::make_unique<DataTypeDomainBool>());
Mistake.

2019-04-22 14:37 UTC, alexey-milovidov commented on dbms/src/DataTypes/DataTypeDomainBool.cpp
> +class DataTypeDomainBool : public DataTypeDomainWithSimpleSerialization
`final`

For devirtualization in forwarded virtual calls like `serializeTextJSON`.

2019-04-22 14:37 UTC, alexey-milovidov requested changes
Some changes required.

2019-04-23 18:19 UTC, alexey-milovidov commented
Now it looks Ok.

BTW, Should we support case insensitive values: `TRUE`, `True`, etc?
It depends on the origin of the motivation for this data type.

Also please make some research about Bool type in other DBMS.
Maybe we should peek synonims for this data type, like BIT, Boolean?
But if we do, it can be incompatible due to different representation.

2019-04-23 18:21 UTC, alexey-milovidov commented
Should this type also represent a constraint
(what will happen if we write `INSERT INTO t SELECT 5 AS b`)

2019-04-23 18:23 UTC, alexey-milovidov commented
Don't you think that predefined `Enum8('false' = 0, 'true' = 1)` as a synonim for Bool type can be easier and better solution?

2019-04-24 03:02 UTC, hczhcz commented
@alexey-milovidov 

The motivation (and the implementation) is similar to IPv4/IPv6 domains in #3669 .

* Bool is useful when we match the type systems between ClickHouse and other systems like JSON, programming language bindings, etc.
* It is also good for documentation (in comparison to a raw UInt8)
* It is painful if we add a separate data type and make the type checking code more complex
* So, the approach in #3669 looks good: providing a "view" to an underlying type

> Should we support case insensitive values: TRUE, True, etc

For data exchanging, I would use one value.

> Should this type also represent a constraint?

To use 0 and 1 is more a "suggestion" considering things like `SELECT and(5, 6);` are legal now.

> Don't you think that predefined Enum8('false' = 0, 'true' = 1) as a synonim for Bool type can be easier and better solution?

The motivation should explain it. The reason I choose UInt8 is just because `SELECT toTypeName(1 = 1);` is UInt8.

2019-04-24 16:17 UTC, alexey-milovidov commented
Ok.

2019-04-24 18:24 UTC, alexey-milovidov commented
We have to check if `x = 'true'` works in SQL query.
BTW, does `x = '127.0.0.1'` works for IPv4 domain?

If not, it is the cause of major usability issues.

2019-04-24 19:52 UTC, orloffv commented
is nullable supported?

2019-04-25 15:01 UTC, hczhcz commented
@alexey-milovidov 

For now, both of them generate type errors.
We may use `select x;` for bool values and `select x = toIPv4('127.0.0.1')` for ipv4 values.

Two things might be useful:
1. Add a `toBool(x)` function to perform type conversions
2. Return bool type in comparison/logic functions

2019-04-25 15:03 UTC, hczhcz commented
@orloffv `Nullable(Bool)` works.

2019-04-25 23:16 UTC, geldot commented
In both MySQL and PostgreSQL, TRUE/FALSE are keywords, which makes sense independently of this PR. MySQL:

```
SELECT true, false, TRUE, FALSE, True, False;
-- 1 0 1 0 1 0
```

In MySQL it's a plain 1/0 bit, in PostgreSQL it's a special type similar to this patch with pretty formatting.

PostgreSQL accepts TRUE, FALSE, 1, 0, but also the strings 'true', 'false', 't', 'f', 'ON', 'OFF' and a bunch of other English-language strings.

I like "Bool" for the type name because it's consistent with the C++-style type naming scheme in Clickhouse.

Agree it'd be interesting to see how this plays with Bitmap, bit shifts, different input/output formats etc. a little more before landing the patch as there's no going back afterwards.

2019-05-05 15:55 UTC, alexey-milovidov commented
This PR looks Ok, but I'm not ready to

> Return bool type in comparison/logic functions

because it will introduce more complications.
It means, that `Bool` type will be not the first class citizen.
But it still makes sense. I need to discuss this feature with my collegues a bit more, and I think we will merge.

2020-01-22 15:53 UTC, abyss7 commented
We decided to close PR and postpone this feature for now.

2020-01-22 15:53 UTC, closed without merging

2021-11-20 04:36 UTC, alexey-milovidov commented
We decided to continue :) #30684