Implementing new commands for keeper-client
ClickHouse/ClickHouse pull request #51117
Opened 2023-06-17 03:28 UTC by pufit

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

Commands to add:
  - ~~getstat - returns the node's stat~~
  - ~~findsupernodes - finds nodes with number of children larger than some threshold for the given path~~
  - deletestalebackups - delete ClickHouse nodes used for backups that are now inactive
  - findbigfamily - return the top nodes which have the biggest family - the total number of nodes in the whole subtree
  - ...

2023-06-17 17:03 UTC, alexey-milovidov commented
Ok, but I don't like that these commands have all words together. What about `find_super_nodes`?

2023-07-21 12:16 UTC, yariks5s requested changes
Looks good, need to deal with the problems below and add info to docs: [here](https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/operations/utilities/clickhouse-keeper-client.md).
Also will be great to update tests to check how the new commands work: [here](https://github.com/ClickHouse/ClickHouse/tree/master/tests/integration/test_keeper_client).

2023-07-21 12:41 UTC, yariks5s commented on programs/keeper-client/Commands.h
> +    String getName() const override { return "getstat"; }
```suggestion
    String getName() const override { return "get_stat"; }
```
We have `find_super_nodes`, `delete_stable_backups`, `find_big_family`, but `getstat`😕. I think it's better to use `get_stat`.

2023-07-21 22:09 UTC, pufit commented on programs/keeper-client/KeeperClient.cpp
> +        std::make_shared<FindSupperNodes>(),
Yes, `FindSupperNodes` is a typo.

2023-07-26 10:23 UTC, yariks5s commented on tests/integration/test_keeper_client/test.py
> -def test_base_commands(started_cluster):
Tests are not running. I think we need to keep `started_cluster` as an argument.

2023-08-01 15:45 UTC, yariks5s approved these changes

2023-08-01 15:47 UTC, merged