Fix attaching gdb in stress tests
ClickHouse/ClickHouse pull request #51445
Opened 2023-06-26 19:14 UTC by Avogar

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Should fix
```
++ source attach_gdb.lib
/usr/share/clickhouse-test/ci/stress_tests.lib: line 12: attach_gdb.lib: No such file or directory
```

2023-06-27 10:53 UTC, devcrafter approved these changes

2023-06-27 11:19 UTC, devcrafter commented
Interesting what happened to performance tests - https://s3.amazonaws.com/clickhouse-test-reports/51445/f628cf185cb47d929fe7c30cdeb209009731e70c/performance_comparison_[3_4]/report.html

2023-07-03 10:50 UTC, tavplubix requested changes
https://s3.amazonaws.com/clickhouse-test-reports/51445/62b11a8d9fde642d75d02d5e012acee0b0f20f95/stress_test__debug_/run.log
```
++ source //attach_gdb.lib
/usr/share/clickhouse-test/ci/stress_tests.lib: line 12: //attach_gdb.lib: No such file or directory
```
```
+ attach_gdb_to_clickhouse
/usr/share/clickhouse-test/ci/stress_tests.lib: line 189: attach_gdb_to_clickhouse: command not found
```

2023-07-06 23:22 UTC, tavplubix commented
Style Check — Check mypy failed - some mess with docker images

2023-07-11 10:02 UTC, Avogar commented
I am confused with stress/upgrade tests failures, not obvious why it failed or I miss something

2023-07-11 12:15 UTC, tavplubix commented
I guess that's because we have `set +e` in `run_with_retry` that is called from `attach_gdb_to_clickhouse`, and it's not unset. So, after calling `attach_gdb_to_clickhouse` in `stress/run.sh`, any failed command will terminate the check

2023-07-11 12:41 UTC, Avogar commented
But it's unset if command succeded:
https://github.com/ClickHouse/ClickHouse/blob/49c1beb8705399dfb40ae5213ebca70ba31e3852/tests/ci/utils.lib#L14-L16

And if it didn't succed we should have this message I guess:
https://github.com/ClickHouse/ClickHouse/blob/49c1beb8705399dfb40ae5213ebca70ba31e3852/tests/ci/utils.lib#L23

But I dont see it

2023-07-11 12:43 UTC, Avogar commented
Yeah, we have `set -e` in run log

2023-07-19 13:55 UTC, Avogar commented
Well, removing `run_with_retry` helps

2023-07-19 14:04 UTC, tavplubix commented
> But it's unset if command succeded:

Hm, yes, but it appeared that bash is confusing sometimes :confused:  . `set -e` means "_enable_ exit-on-error mode" and `set +e` means "_disable_ exit-on-error mode". So `run_with_retry` enables it before returning, so the `run.sh` script exists on the first failed command after `run_with_retry`

2023-07-19 15:07 UTC, Avogar commented
> set -e means "enable exit-on-error mode" and set +e means "disable exit-on-error mode".

Ah, I was confused by this, yes. Thanks :)

2023-07-24 13:20 UTC, tavplubix commented on tests/ci/utils.lib
> +    fi
```suggestion
    if [[ $- =~e ]]; then
      set_e=true
    else
      set_e=false
    fi
    set +e
```

2023-07-26 09:53 UTC, tavplubix approved these changes

2023-07-26 09:53 UTC, merged

2023-07-26 10:03 UTC, tavplubix commented
SQLancer (release)  - https://github.com/ClickHouse/ClickHouse/issues/51722