DOCAPI-6181: Parquet format description
ClickHouse/ClickHouse pull request #5258
Opened 2019-05-13 15:41 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation for #4448

2019-05-13 15:55 UTC, blinkov requested changes

2019-05-13 15:55 UTC, blinkov commented on docs/en/interfaces/formats.md
> +ClickHouse supports some kinds of `Decimal` type. The `INSERT` query treats the Parquet `DECIMAL` type as the ClickHouse `Decimal128` type.
* some kinds -> configurable precision
* needs link to Decimal description in ClickHouse

2019-05-13 15:55 UTC, blinkov commented on docs/en/interfaces/formats.md
> +Some of the Parquet data types are not supported. The table below shows the supported data types and how they match ClickHouse [data types](../data_types/index.md) in `INSERT` and `SELECT` queries.
Remove first sentence + add unsupported types to table below (or as separate list)

2019-05-13 15:55 UTC, blinkov commented on docs/en/interfaces/formats.md
> +Data types of a ClickHouse table columns can be different then the corresponding fields of the Parquet data inserted. When inserting data, ClickHouse interprets data types according to the table abov
can differ from

2019-05-13 15:55 UTC, blinkov commented on docs/en/interfaces/formats.md
> +ClickHouse doesn't connect to [HDFS](https://en.wikipedia.org/wiki/Apache_Hadoop) to get data from it. You should take the Parquet data file and then you can insert Parquet data into some ClickHouse
* Sounds weird given there's no introduction. We should probably start from the fact that Parquet is a widespread format in Hadoop ecosystem.
* Actually it should work without intermediate files by replacing TSV with Parquet in this test case (and neighbouring ones): https://github.com/yandex/ClickHouse/blob/master/dbms/tests/integration/test_storage_hdfs/test.py#L47 If it doesn't work for some reason — this should be reported as bug and fixed.

2019-05-13 15:55 UTC, blinkov commented on docs/en/interfaces/formats.md
> +cat {filename} | clickhouse-client --query="INSERT INTO {some_table} FORMAT Parquet"
Given you've mentioned HDFS, these examples could use some CLI to read/write from HDFS instead of just `cat` and pipes.

2019-05-15 14:21 UTC, proller approved these changes

2019-05-25 13:06 UTC, merged