Revert "Revert "dateDiff: add support for plural units.""
ClickHouse/ClickHouse pull request #53803
Opened 2023-08-24 15:13 UTC by hanfei1991

Reverts ClickHouse/ClickHouse#53795 by fixing tests

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

2023-08-27 18:36 UTC, rschu1ze approved these changes

2023-08-27 20:35 UTC, alexey-milovidov commented on tests/queries/0_stateless/00538_datediff.sql
> +SELECT dateDiff('years', toDate('2017-12-31'), toDate('2016-01-01'));
We should add a new test for a new case instead of editing the existing test.

2023-08-27 20:35 UTC, alexey-milovidov commented on tests/queries/0_stateless/00538_datediff.sql
>  SELECT 'Additional test';
Btw, this suggests that you also needed to add a similar statement before the new test case.

2023-08-27 20:35 UTC, alexey-milovidov requested changes
.

2023-08-31 03:25 UTC, alexey-milovidov approved these changes

2023-09-03 01:36 UTC, merged