'from' is supported as a Expression and fix #53543
ClickHouse/ClickHouse pull request #53914
Opened 2023-08-29 07:33 UTC by Chen768959

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
'from' is supported as a Expression

fix #53543
If there is a comma after '`from`' then the first one was a name of a column

2023-08-29 15:24 UTC, CurtizJ requested changes
It looks too ad-hoc. Can be any problems if the next token is not comma? Can be any problems with other keywords? It's unclear because you cannot take into account all possible cases.

I suggest to always quote keywords like it's done now for some of them in [writeProbablyBackQuotedString](https://github.com/ClickHouse/ClickHouse/blob/17f37541935bce25e2b200f061baafa4dadb338e/src/IO/WriteHelpers.cpp#L87C1-L100C2). The problem is that we don't have explicit list of keywords now, but it will be implemented in #51808.

2023-08-29 15:35 UTC, CurtizJ approved these changes
Ok, I've seen that it's actually a degradation and it worked before. Let's merge this fix and when #51808 will be ready we can implement what I suggested.

2023-08-30 12:26 UTC, Chen768959 commented
> Ok, I've seen that it's actually a degradation and it worked before. Let's merge this fix and when #51808 will be ready we can implement what I suggested.

@CurtizJ Thank you very much for your feedback! Establishing an explicit list of keywords in #51808 is indeed a great idea. However, I apologize for not fully understanding your point. My fix mainly checks for the existence of a `comma`, and the `comma` is already part of the `TokenType` list. Therefore, it seems like this fix doesn't conflict with #51808.

2023-08-30 13:59 UTC, CurtizJ commented
My point was that your fix is too ad hoc and I suggested a more general solution that involves the list of keywords. As a hotfix you PR is ok.

2023-08-30 20:25 UTC, merged