dictGet and dictGetOrDefault for Decimals
ClickHouse/ClickHouse pull request #5394
Opened 2019-05-23 14:07 UTC by 4ertus2

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- New Feature

Short description (up to few sentences):
Implement dictGet and dictGetOrDefault functions for Decimal types. It extracts type arguments (precision and scale) from dictionary attributes described in XML.

2019-05-25 11:21 UTC, alexey-milovidov commented on dbms/src/Core/Types.h
> +    switch (idx)
BTW can be done with X macro.

2019-05-25 11:22 UTC, alexey-milovidov commented on dbms/src/Dictionaries/FlatDictionary.cpp
> +            setAttributeValueImpl<Decimal64>(attribute, id, value.get<Decimal64>());
A perfect case for PVS-Studio.

2019-05-25 12:06 UTC, alexey-milovidov commented
The only remaining is the integration test.

2019-05-25 12:06 UTC, alexey-milovidov requested changes
.

2019-05-27 18:45 UTC, alexey-milovidov commented
`clickhouse-test-server` script is not used in CI.
It is @proller's own script.

2019-05-29 11:06 UTC, alesapin commented
Temporary we can add this `.xml` files to docker images. After DDL for dictionaries will be merged we can write functional tests for dictionaries in simple way.

2019-05-29 20:28 UTC, merged