Perf test for linear regression
ClickHouse/ClickHouse pull request #5411
Opened 2019-05-24 22:43 UTC by Quid37

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Other

Short description (up to few sentences):

2019-05-25 15:47 UTC, alexey-milovidov commented on dbms/src/AggregateFunctions/AggregateFunctionMLMethod.cpp
> +void LinearModelData::return_weights(IColumn & to) const
Style.

2019-05-25 15:49 UTC, alexey-milovidov commented on dbms/tests/performance/linear_regression.xml
> +<!--    Проверяем, как работает fit-->
Comments must be only in english (both in code and in tests).

2019-05-25 15:50 UTC, alexey-milovidov commented on dbms/tests/performance/linear_regression.xml
> +    <fill_query>INSERT INTO train_dataset values (2.0, 1.0, 6.0), (3.0, -1.0, 6.0), (4.0, 2.0, 11.0), (-2.0, 1.0, -2.0)</fill_query>
Table is way too small. Better to reuse Taxi, Ontime or Metrica dataset
(look at the used tables across other performance tests).

There are many useful queries like "predict ride price according to time, distance and number of passengers".

2019-05-25 15:52 UTC, alexey-milovidov commented on dbms/src/AggregateFunctions/AggregateFunctionMLMethod.cpp
> +        column.getData().push_back(weight_value);
And this is totally incorrect. You're returning Float64 not Array(Float64).

2019-05-25 15:52 UTC, alexey-milovidov requested changes
.

2019-05-29 03:15 UTC, KochetovNicolai commented on dbms/src/AggregateFunctions/AggregateFunctionMLMethod.cpp
> +    while (i < weights.size())
Use for loop.

2019-05-29 03:17 UTC, KochetovNicolai commented on dbms/src/AggregateFunctions/AggregateFunctionMLMethod.h
> +    DataTypePtr getReturnTypeToPredict() const override
Comment is needed

2019-05-29 03:31 UTC, merged