[WIP] Support external source Aerospike
ClickHouse/ClickHouse pull request #5421
Opened 2019-05-26 20:16 UTC by Gleb-Tretyakov

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- New Feature

Short description (up to few sentences):

Support aerospike storage as external dictionary

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeBlockInputStream.cpp
> +                    String str{key->value.string.value, key->value.string.len};
no need to create String

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeBlockInputStream.cpp
> +                    static_cast<ColumnVector<UInt8> &>(column).getData().push_back(key->value.integer.value);
insertValue(...)

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeBlockInputStream.cpp
> +        uint32_t n_found = 0;
unused

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeBlockInputStream.cpp
> +                        ColumnNullable & column_nullable = static_cast<ColumnNullable &>(*(*columns)[idx]);
cast to ColumnNullable* to remove double dereferencing here

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeBlockInputStream.cpp
> +    class TemporaryName
naming

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeBlockInputStream.cpp
> +                    /*case AS_STRING:
remove or implement

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeBlockInputStream.cpp
> +                        insertValue(*(*columns)[idx], description.types[idx].first, &bin_value, name);
same here

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeBlockInputStream.cpp
> +                insertKey(*((*columns)[0]), description.types[0].first, key.get(),
same here

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeBlockInputStream.cpp
> +                        UInt16{DateLUT::instance().toDayNum(static_cast<Int64>(key->value.integer.value))});
parse LocalDate

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeBlockInputStream.cpp
> +                    throw Exception{"Type mismatch, expected String (UUID), got type id = " + invalid_type + " for column " + name,
change message

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeBlockInputStream.cpp
> +                    static_cast<ColumnString &>(column).insertDataWithTerminatingZero(str.data(), str.size() + 1);
parse String

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeBlockInputStream.h
> +/// Converts MongoDB Cursor to a stream of Blocks
remove comment

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeDictionarySource.cpp
> +        throw Exception{"Dictionary source of type `aerospike` is disabled because poco library was built without aerospike support.",
remove mention of poco

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeDictionarySource.cpp
> +const static char * default_namespace_name = "test";
move to config

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeDictionarySource.cpp
> +    return "Aerospike: "; // +  bla bla bla
more info

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeDictionarySource.h
> +    /* override {
remove commented

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeDictionarySource.h
> +    /// @todo: for Aerospike, modification date can somehow be determined from the `_id` object field
fix comment

2019-05-27 19:36 UTC, comunodi commented on dbms/src/Dictionaries/AerospikeDictionarySource.h
> +    bool supportsSelectiveLoad() const override { return true; }
false?

2019-05-29 01:36 UTC, comunodi commented on cmake/find_aerospike.cmake
> +message(STATUS "Using Aerospike=${USE_AEROSPIKE}: ${USE_POCO_REDIS}, ${AEROSPIKE_LIBRARY}, ${AEROSPIKE_INCLUDE_DIR}")
change vars

2019-05-29 01:38 UTC, comunodi commented on cmake/find_aerospike.cmake
> +    if (NOT EXISTS "${ClickHouse_SOURCE_DIR}/contrib/aerospike/src/main/aerospike/_bin.c")
+ ENABLE_AEROSPIKE

2019-06-04 13:17 UTC, 4ertus2 requested changes

2019-06-04 13:17 UTC, 4ertus2 commented on cmake/find_aerospike.cmake
> +    if(OS_FREEBSD AND SANITIZE STREQUAL "address")
Do not build on Linux. `else ()` block missing

2019-06-04 13:20 UTC, 4ertus2 commented on cmake/find_aerospike.cmake
> +    if(OS_FREEBSD AND SANITIZE STREQUAL "address")
Fails to build with Aerospike enabled
```
../dbms/src/Dictionaries/AerospikeDictionarySource.cpp:173:5: error: no matching function for call to 'printf'
    printf(stderr, "len %zu", strlen(keys[0]->value.string.value));
    ^~~~~~
/usr/include/stdio.h:318:12: note: candidate function not viable: no known conversion from 'struct _IO_FILE *' to 'const char *__restrict' for 1st argument
extern int printf (const char *__restrict __format, ...);
           ^
1 error generated.
```

2020-01-22 16:09 UTC, abyss7 commented
Continued in #5629

2020-01-22 16:09 UTC, closed without merging