Docapi 6427 settings for formats
ClickHouse/ClickHouse pull request #5423
Opened 2019-05-27 10:28 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Documentation for #5081

2019-06-03 12:04 UTC, blinkov requested changes

2019-06-03 12:04 UTC, blinkov commented on docs/en/operations/settings/settings.md
> +To improve ClickHouse performance, we recommend disabling this check if you are sure that the column order of the input data is the same as in the target table.
let's replace ClickHouse with insert here, "to improve insert performance"

2019-06-03 12:04 UTC, blinkov commented on docs/ru/operations/settings/settings.md
> +При записи данных, если входные данные содержат столбцы, которых нет в целевой таблице, ClickHouse генерирует исключение. Если пропускание вставки включено, ClickHouse не вставляет дополнительные дан
думаю стоит тут заменить «дополнительные» на «неизвестные»

2019-06-03 12:04 UTC, blinkov commented on docs/ru/operations/settings/settings.md
> +Поддерживаемые форматы: [JSONEachRow](../../interfaces/formats.md#jsoneachrow), [CSVWithNames](../../interfaces/formats.md#csvwithnames), [TabSeparatedWithNames](../../interfaces/formats.md#tabsepara
может лучше списком?

2019-06-03 12:04 UTC, blinkov commented on docs/ru/operations/settings/settings.md
> +Чтобы повысить производительность ClickHouse, рекомендуется отключить эту проверку, если вы уверены, что порядок столбцов входных данных такой же, как в целевой таблице.
производительность вставки

2019-06-03 12:04 UTC, blinkov commented on docs/ru/operations/settings/settings.md
> +Использование кэша несжатых блоков (только для таблиц семейства MergeTree) может существенно сократить задержку и увеличить пропускную способность при работе с большим количеством коротких запросов.
тут что-то странное с форматированием, как минимум про возможные значения отличается от других настроек

2019-06-03 12:04 UTC, blinkov commented on docs/ru/operations/settings/settings.md
> +
зачем эта пустая строка?

2019-06-04 13:37 UTC, BayoNet commented on docs/ru/operations/settings/settings.md
> +Использование кэша несжатых блоков (только для таблиц семейства MergeTree) может существенно сократить задержку и увеличить пропускную способность при работе с большим количеством коротких запросов.
Так это во всех настройках, которые не я описывал. Мы же их пока ещё не приводили к единому виду. Тут я то ли ссылку правил, то ли ещё какой мелкий косяк.

2019-06-04 13:38 UTC, BayoNet commented on docs/ru/operations/settings/settings.md
> +
Мне её Atom автоматически выставляет и ещё пробелы в конце строк убирает.

2019-06-04 14:09 UTC, merged