Update automated commit status comment
ClickHouse/ClickHouse pull request #54441
Opened 2023-09-08 09:57 UTC by vdimir

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-09-08 20:07 UTC, alexey-milovidov commented
Wow, it works! Wouldn't it be better if we put the status symbol in front of the title?
(Easier to scan the list of pull requests).

2023-09-11 10:45 UTC, vdimir commented
@alexey-milovidov 

Checked both options editing html and setting random badges.
Badge in the beginning indeed looks better imo.

<details>
<summary>Screenshots</summary>


<img width="1221" alt="Screenshot 2023-09-11 at 12 42 10" src="https://github.com/ClickHouse/ClickHouse/assets/7023786/dfd4204d-cdfc-43f7-a4e8-057b31c7059c">

---

<img width="1220" alt="Screenshot 2023-09-11 at 12 42 20" src="https://github.com/ClickHouse/ClickHouse/assets/7023786/586f1672-f9b1-4bdf-8313-20da61d036ac">


</details>

2023-09-11 10:48 UTC, vdimir commented on tests/ci/commit_status_helper.py
> +                status.context, status.state, log_urls=log_urls, raw_logs=raw_logs
Don't work yet (no expandable descriptions here https://s3.amazonaws.com/clickhouse-test-reports/54441/6a51d9fd7d2a373741f79ac7f9100225d79ef8bd/ci_running.html), going to check what's wrong

2023-09-11 10:49 UTC, Felixoid commented
Won't it be TOO annoying to have these strings for every update?..

![image](https://github.com/ClickHouse/ClickHouse/assets/3025537/ac3a4f9f-ab88-4642-9ce2-e7b3443e9d20)

2023-09-11 13:33 UTC, vdimir commented
> The mailboxes will have up to 4 different threads (original, and 3 with different statuses)

Let's check it

2023-09-11 13:39 UTC, vdimir commented
bump

2023-09-11 13:42 UTC, Felixoid commented
![image](https://github.com/ClickHouse/ClickHouse/assets/3025537/7ef758b6-a53d-4211-bc4e-67d2b05f03a5)

It looks strange..

2023-09-11 14:28 UTC, Felixoid commented
@alexey-milovidov Vladimir and came to a model where we'd use only two statuses, red and green, and change them only back and forth as labels `pr-status-🟢` and `pr-status-🔴`

Changing labels are sent to all subscribers, so it's the best balance we could think of.

2023-09-11 15:14 UTC, Felixoid commented on tests/ci/commit_status_helper.py
> +            raw_logs = status.description
```suggestion
        raw_logs = status.description or None
```

2023-09-11 16:57 UTC, Felixoid commented
![image](https://github.com/ClickHouse/ClickHouse/assets/3025537/b2a968c0-8369-4846-b6be-bb28a1800f52)

Just in case ¯\\\_(ツ)_/¯

2023-09-11 17:53 UTC, alexey-milovidov commented
Thanks, it looks like a good idea!

2023-09-11 19:08 UTC, Felixoid requested changes

2023-09-11 19:08 UTC, Felixoid commented on src/Storages/StorageReplicatedMergeTree.cpp
> -        {
Looks good. Let's revert it and run full checks to see the other reports

2023-09-11 21:54 UTC, Felixoid commented on src/Storages/StorageReplicatedMergeTree.cpp
> -        {
And there's a lost remaining in report.py: `if (classes.contains("failed-content") || classes.contains("failed-content.open"))`

2023-09-12 13:13 UTC, Felixoid approved these changes
![Schitts Creek Perfect](https://i.giphy.com/media/KEYbcgR8oKQzwpwvLU/giphy.webp)

2023-09-12 17:16 UTC, Felixoid commented on tests/ci/commit_status_helper.py
>              log_urls = [status.target_url]
Nice, it's fixed! https://s3.amazonaws.com/clickhouse-test-reports/54441/acb559ce8bd385d311c27aabb3e88fbf4a1cfa22/ci_running.html

2023-09-12 17:19 UTC, Felixoid approved these changes

2023-09-12 19:16 UTC, Felixoid commented
https://github.com/ClickHouse/ClickHouse/pull/54551 will address test_keeper_reconfig_remove_many/test.py::test_reconfig_remove_2_and_leader

2023-09-12 19:18 UTC, merged