Res-submit optimization uniq to count
ClickHouse/ClickHouse pull request #54568
Opened 2023-09-13 08:12 UTC by JackyWoo

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
This PR will fix UBsan test error [here](https://github.com/ClickHouse/ClickHouse/pull/54566)

2023-09-20 16:21 UTC, JackyWoo commented
@alexey-milovidov Please review the PR when you are free.

2023-09-22 02:43 UTC, JackyWoo commented
@alexey-milovidov The last commit will fix the UBsan test error https://github.com/ClickHouse/ClickHouse/pull/54566. 

There are some errors in CI, but maybe not caused by the PR.

2023-09-23 22:42 UTC, alexey-milovidov commented on src/Analyzer/Passes/UniqToCountPass.cpp
> +    return name == "uniq" || name == "uniqHLL12" || name == "uniqExact" || name == "uniqTheta" || name == "uniqCombined"
After we made function lowercase, there is no point comparing it to `uniqHLL12`, `uniqExact`, `uniqTheta`, `uniqCombined`

2023-09-25 19:36 UTC, alexey-milovidov commented on src/Interpreters/RewriteUniqToCountVisitor.cpp
> +    return name == "uniq" || name == "uniqHLL12" || name == "uniqExact" || name == "uniqTheta" || name == "uniqCombined"
?

2023-09-25 19:36 UTC, alexey-milovidov requested changes
.

2023-09-26 22:18 UTC, alexey-milovidov commented on src/Interpreters/RewriteUniqToCountVisitor.cpp
> +    return name == "uniq" || name == "uniqhll12" || name == "uniqexact" || name == "uniqtheta" || name == "uniqcombined"
I figured out that this is theoretically wrong.

The function `uniqCombined` is not case-insensitive.
A user could register a user-defined function with `uniqcombined` name, and the optimization will be applied incorrectly.

2023-10-30 00:33 UTC, alexey-milovidov approved these changes

2023-10-30 00:33 UTC, merged