DOCAPI-4293: MySQL table engine and function.  RU translation and EN review
ClickHouse/ClickHouse pull request #5487
Opened 2019-05-30 15:22 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Documentation

2019-05-30 16:47 UTC, alesapin approved these changes

2019-05-30 16:47 UTC, alesapin commented on docs/ru/query_language/table_functions/mysql.md
> +Выборка данных в ClickHouse:
Maybe 'Получение данных в ClickHouse'?

2019-05-30 16:47 UTC, alesapin commented on docs/en/operations/table_engines/mysql.md
> +    Example: `INSERT INTO t (c1,c2) VALUES ('a', 2) ON DUPLICATE KEY UPDATE c2 = c2 + 1`, where `on_duplicate_clause` is `UPDATE c2 = c2 + 1`. See the MySQL documentation to find which `on_duplicate_
`the MySQL`?

2019-06-03 13:29 UTC, blinkov requested changes

2019-06-03 13:29 UTC, blinkov commented on docs/en/operations/table_engines/mysql.md
> +- `replace_query` — Flag that converts `INSERT INTO` queries to `REPLACE INTO`. If `replace_query=1`, the query is replaced.
"query is **substituted**" would make it less confusing

2019-06-03 13:29 UTC, blinkov commented on docs/en/operations/table_engines/mysql.md
> +Simple `WHERE` clauses such as ` =, !=, >, >=, <, <=` are currently executed on the MySQL server.
I'm not sure what initial author was trying to say, but probably "currently" can also be dropped.

2019-06-03 13:29 UTC, blinkov commented on docs/ru/operations/table_engines/mysql.md
> +    Пример: `INSERT INTO t (c1,c2) VALUES ('a', 2) ON DUPLICATE KEY UPDATE c2 = c2 + 1`, где `on_duplicate_clause` это `UPDATE c2 = c2 + 1`. Чтобы узнать какие `on_duplicate_clause` можно использоват
может ссылку дать на эту документацию MySQL?

2019-06-03 13:29 UTC, blinkov commented on docs/ru/operations/table_engines/mysql.md
> +    Чтобы указать `'on_duplicate_clause'` необходимо передать `0` в параметр `replace_query`. Если одновременно передать `replace_query = 1` и `'on_duplicate_clause'`, то ClickHouse сгенерирует исклю
непонятно зачем кавычки удвоились

2019-06-03 13:29 UTC, blinkov commented on docs/ru/query_language/select.md
> +ClickHouse поддерживает использование в одном запросе секций `DISTINCT` и `ORDER BY` для разных столбцов. Секция `DISTINCT` исполняется перед секцией `ORDER BY`.
выглядит как какое-то несвязанное изменение

2019-06-05 15:27 UTC, BayoNet commented on docs/ru/query_language/select.md
> +ClickHouse поддерживает использование в одном запросе секций `DISTINCT` и `ORDER BY` для разных столбцов. Секция `DISTINCT` исполняется перед секцией `ORDER BY`.
Да, я в этот тикет засунул минорное изменение для спец. случая. MySQL действительно не касается, просто не хотелось делать отдельный тикет.

2019-06-15 19:35 UTC, BayoNet commented
Тут вроде всё хорошо, вмёржить бы :-).

2019-06-16 00:04 UTC, merged