Changelog for 19.7.3.9
ClickHouse/ClickHouse pull request #5502
Opened 2019-05-31 11:26 UTC by akuzm

This is for 19.7.3.9, not everything is backported yet.

2019-06-02 03:22 UTC, alexey-milovidov commented on CHANGELOG.md
> +* Allow setting constraints such as `max_memory_usage` in users.xml.
Not descriptive enough.

2019-06-02 03:23 UTC, alexey-milovidov commented on CHANGELOG.md
> +* Add a second version of the function `groupUniqArray` with an optional
is to -> is similar to

2019-06-02 03:23 UTC, alexey-milovidov commented on CHANGELOG.md
> +[#5026](https://github.com/yandex/ClickHouse/pull/5026) ([Guillaume
.

2019-06-02 03:23 UTC, alexey-milovidov commented on CHANGELOG.md
> +[#5081](https://github.com/yandex/ClickHouse/pull/5081)
.

2019-06-02 03:24 UTC, alexey-milovidov commented on CHANGELOG.md
> +* Implement radix sort for `ORDER BY`.
Duplicate of above.

2019-06-02 03:25 UTC, alexey-milovidov requested changes
.

2019-06-03 13:52 UTC, akuzm commented on CHANGELOG.md
> +[#5081](https://github.com/yandex/ClickHouse/pull/5081)
What's wrong here?

2019-06-05 05:08 UTC, merged