DOCAPI-6206: ODBC engine and table function. EN review. RU translation.
ClickHouse/ClickHouse pull request #5504
Opened 2019-05-31 12:57 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):

    Documentation for #3210

2019-06-15 14:36 UTC, blinkov requested changes

2019-06-15 14:36 UTC, blinkov commented on docs/ru/operations/table_engines/odbc.md
> +Чтобы использование ODBC было безопасным, ClickHouse использует отдельную программу `clickhouse-odbc-bridge`. Если драйвер ODBC подгружать непосредственно из  `clickhouse-server`, то проблемы с драйв
опять удвоенные пробелы

2019-06-15 14:36 UTC, blinkov commented on docs/ru/operations/table_engines/odbc.md
> +Этот пример проверялся в Ubuntu Linux 18.04 для MySQL server 5.7.
непонятно откуда взялось «проверялся в», по идее там просто «для» должно быть

2019-06-15 14:36 UTC, blinkov commented on docs/ru/operations/table_engines/odbc.md
> +[Оригинальная статья](https://clickhouse.yandex/docs/ru/operations/table_engines/jdbc/) <!--hide-->
odbc и jdbc похоже перепутано

2019-06-15 14:36 UTC, blinkov commented on docs/ru/query_language/table_functions/odbc.md
> +Возвращает таблицу, подключенную по [ODBC](https://en.wikipedia.org/wiki/Open_Database_Connectivity).
по -> через

2019-06-16 07:14 UTC, BayoNet commented on docs/ru/operations/table_engines/odbc.md
> +Этот пример проверялся в Ubuntu Linux 18.04 для MySQL server 5.7.
Я уверен, что пример сработает и во многих других конфигурациях, поэтому решил, что "проверялся в" более корректная формулировка, чем "для". В английском переделал.

2019-06-17 09:07 UTC, merged