Fix SIGSEGV in MergeSortingPartialResultTransform (due to zero chunks after remerge())
ClickHouse/ClickHouse pull request #55335
Opened 2023-10-08 13:17 UTC by azat

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix SIGSEGV in MergeSortingPartialResultTransform (due to zero chunks after remerge())

It is possible to have non zero input chunks before remerge() and zero after:

    2023.10.08 10:21:20.944928 [ 4321 ] {427df456-1400-4fbe-8bd7-c4de139f00ca} <Debug> MergeSortingTransform: Re-merging intermediate ORDER BY data (1 blocks with 0 rows) to save memory consumption
    2023.10.08 10:36:16.447001 [ 14466 ] {} <Fatal> BaseDaemon: (version 23.10.1.1, build id: 3E53B6B3A53FD562F44C88703BD88EB713881A44, git hash: 5ddfb170a1096cf88664b1a4b9b7bd2e7ef36c29) (from thread 4321) (query_id: 427df456-1400-4fbe-8bd7-c4de139f00ca) (query: SELECT CounterID FROM test.visits ARRAY JOIN Goals.ID WHERE CounterID = 942285 ORDER BY CounterID

CI: https://s3.amazonaws.com/clickhouse-test-reports/55276/099665478df3e77d1df0332dd705ca7209e903af/stress_test__debug_.html

2023-10-08 13:23 UTC, alexey-milovidov approved these changes

2023-10-08 13:24 UTC, alexey-milovidov commented
Need to add a test.

2023-10-08 13:24 UTC, alexey-milovidov requested changes
.

2023-10-08 20:22 UTC, azat commented
Indeed. Added. Actually the bug had been introduced by partial results - #48607, just wrong order...

2023-10-08 20:52 UTC, alexey-milovidov commented
https://github.com/ClickHouse/ClickHouse/pull/48607#issuecomment-1752159002

2023-10-09 00:48 UTC, merged

2023-10-11 12:21 UTC, azat commented
@alexey-milovidov I guess this PR should also be backported