DOCAPI-6213: Docs for send_progress_in_http_headers setting.
ClickHouse/ClickHouse pull request #5563
Opened 2019-06-08 15:27 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation

2019-06-13 05:32 UTC, blinkov requested changes

2019-06-13 05:32 UTC, blinkov commented on docs/en/interfaces/http.md
> +File [Progress.h](https://github.com/yandex/ClickHouse/blob/master/dbms/src/IO/Progress.h) contains structures `struct ProgressValues` and `struct Progress` which define fields that you see in the HT
why not just document them here?

2019-06-13 05:32 UTC, blinkov commented on docs/en/interfaces/http.md
> +You have the option to receive information about the progress of query execution in `X-ClickHouse-Progress` headers. To do this, enable the setting [send_progress_in_http_headers](../operations/setti
response headers

2019-06-13 05:32 UTC, blinkov commented on docs/en/interfaces/http.md
> +X-ClickHouse-Progress: {"read_rows":"393216","read_bytes":"28368934","total_rows":"8880128"}
probably the example could demonstrate how these values change over time for a single query

2019-06-13 05:32 UTC, blinkov commented on docs/en/operations/settings/settings.md
> +Enables or disables sending of the `X-ClickHouse-Progress` header in an answer from `clickhouse-server`.
header -> HTTP response headers

2019-06-15 19:35 UTC, BayoNet commented
Тут вроде всё хорошо. Вмёржить бы.

2019-06-16 00:05 UTC, merged