DOCAPI-6180: Syncronization between EN and RU versions of document.
ClickHouse/ClickHouse pull request #5566
Opened 2019-06-09 17:41 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation.

2019-06-13 05:28 UTC, blinkov requested changes

2019-06-13 05:28 UTC, blinkov commented on docs/ru/query_language/agg_functions/reference.md
>  Составляет массив из различных значений аргумента. Расход оперативки такой же, как у функции `uniqExact`.
оперативки -> оперативной памяти

2019-06-13 05:28 UTC, blinkov commented on docs/ru/query_language/agg_functions/reference.md
> +Функция `groupUniqArray(max_size)(x)` ограничивает размер результирующего массива до `max_size` элементов. Например, `groupUniqArray (1) (x)` равнозначно `[any (x)]`.
в примере убрать пробелы?

2019-06-13 05:28 UTC, blinkov commented on docs/ru/query_language/agg_functions/reference.md
> +Bitmap или агрегатные вычисления для столбца с типом данных `UInt*`, возвращают кардинальность в виде значения типа UInt64, если добавить суффикс -State, то возвращают [объект bitmap](../functions/bi
* из описания не ясно что оно вообще делает
* тут bitmap осталось по-английски, ниже транслит, а вообще кажется лучше б перевести и зафиксировать термин

2019-06-13 05:28 UTC, blinkov commented on docs/ru/query_language/functions/bitmap_functions.md
> +Создаёт битмап из массива целочисленных значений.
где-то есть описание по каким принципам это происходит?

2019-06-13 05:28 UTC, blinkov commented on docs/ru/query_language/functions/bitmap_functions.md
> +**Параметры**
а результат?

2019-06-13 05:28 UTC, blinkov commented on docs/ru/query_language/functions/bitmap_functions.md
> +Преобразует битмап в массив целочисленных значений.
как выбирается размер элемента массива в байтах?

2019-06-13 05:28 UTC, blinkov commented on docs/ru/query_language/functions/bitmap_functions.md
> +Аналогично функции `hasAny(array, array)` возвращает 1 если два битмапа содержат одинаковые элементы, 0 в противном случае.
* ссылка?
* «содержат одинаковые элементы» — не очевидно достаточно ли одного или все должны быть одинаковыми, а также важен ли порядок/позиции

2019-06-13 05:28 UTC, blinkov commented on docs/ru/query_language/functions/ip_address_functions.md
> +Принимает число типа UInt32. Интерпретирует его, как IPv4-адрес в big endian. Возвращает значение FixedString (16), содержащее адрес IPv6 в двоичном формате. Примеры:
* big endian — можно сослаться на википедию
* убрать пробел после FixedString и завернуть в бектики

2019-06-13 05:28 UTC, blinkov commented on docs/ru/query_language/functions/ip_address_functions.md
> +Принимает на вход IPv4 и значение `UInt8`, содержащее CIDR. Возвращает кортеж с двумя IPv4, содержащими нижний и более высокий диапазон подсети.
CIDR — ссылку на википедию

2019-06-14 08:17 UTC, BayoNet commented on docs/ru/query_language/agg_functions/reference.md
> +Bitmap или агрегатные вычисления для столбца с типом данных `UInt*`, возвращают кардинальность в виде значения типа UInt64, если добавить суффикс -State, то возвращают [объект bitmap](../functions/bi
А какой бы ты предложил термин?
Я сколько с битмапами встречался, всегда слышал только битмап. Думаю, что если мы употребим что-то типа "битовый массив" будет конечно понятно, но битмап тупо короче и кажется все понимают его как есть.

2019-06-14 09:08 UTC, blinkov commented on docs/ru/query_language/agg_functions/reference.md
> +Bitmap или агрегатные вычисления для столбца с типом данных `UInt*`, возвращают кардинальность в виде значения типа UInt64, если добавить суффикс -State, то возвращают [объект bitmap](../functions/bi
@BayoNet кандидаты есть вот тут: https://ru.wikipedia.org/wiki/Bitmap (там где структура данных)

2019-06-14 09:28 UTC, BayoNet commented on docs/ru/query_language/agg_functions/reference.md
> +Bitmap или агрегатные вычисления для столбца с типом данных `UInt*`, возвращают кардинальность в виде значения типа UInt64, если добавить суффикс -State, то возвращают [объект bitmap](../functions/bi
Кстати, если ты знаешь что это и можешь объяснить в двух словах, то лучше сделать это прямо сейчас. Если нет, то я лучше поставлю отдельный тикет. Висящие месяцами пуллы разъезжаются в конфликтах и портят психику.

2019-06-14 09:30 UTC, BayoNet commented on docs/ru/query_language/functions/bitmap_functions.md
> +Создаёт битмап из массива целочисленных значений.
Это перевод, Ваня. Что автор написал в английском, то и есть в русском. Если нужна переработка документации, я лучше отдельные тикеты буду ставить. У меня уже кажется ни одного пулла без конфликтов не проходит из-за того, что они висят неделями и месяцами.

2019-06-14 09:44 UTC, blinkov commented on docs/ru/query_language/functions/bitmap_functions.md
> +Создаёт битмап из массива целочисленных значений.
Вероятно биты по номерам из массива возводятся в единичку, но это лишь предположение, код/тесты не смотрел. Так или иначе если удобнее через тикет, то давай хоть так. @BayoNet

2019-06-14 10:23 UTC, BayoNet commented on docs/ru/query_language/functions/bitmap_functions.md
> +Преобразует битмап в массив целочисленных значений.
Минимальный UInt, в который влезет значение? Разве это не стандартная логика ClickHouse?

2019-06-14 10:31 UTC, blinkov commented on docs/ru/query_language/functions/bitmap_functions.md
> +Преобразует битмап в массив целочисленных значений.
только для литералов, а для результатов функций надо заранее знать тип данных результата не заглядывая в данные

2019-06-14 10:34 UTC, BayoNet commented
Тикет на переработку поставил DOCAPI-7046

2019-06-14 10:56 UTC, blinkov commented
@BayoNet тест на ссылки упал

2019-06-14 11:15 UTC, BayoNet commented
Да, я знаю. Сначала надо вмёржить https://github.com/yandex/ClickHouse/pull/5572, в котором я всё это правил, иначе падать будут абсолютно все пуллы в документацию.

2019-06-15 19:34 UTC, BayoNet commented
Тут вроде всё хорошо. Вмёржить бы :-).

2019-06-16 00:04 UTC, merged