Add aggregate function combinator -Resample
ClickHouse/ClickHouse pull request #5590
Opened 2019-06-12 08:08 UTC by hczhcz

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- New Feature

Short description (up to few sentences):

`-Resample` can be appended to an aggregate function.The aggregate function will have an extra `key` argument, and it will run separately for rows which have keys in each slot `[begin, begin + step), [begin + step, begin + 2 * step), ...`.

Detailed description (optional):

Example:
```
|uid   |age   |
|'A'   |16    |
|'B'   |30    |
|'C'   |35    |
|'D'   |48    |
|'E'   |62    |
```
```sql
SELECT groupArrayResample(0, 80, 10)(uid, age)
    = [[], ['A'], [], ['B', 'C'], ['D'], [], ['E'], []];
```

2019-06-12 08:11 UTC, hczhcz commented on dbms/src/AggregateFunctions/AggregateFunctionResample.h
> +                (end - begin + step - (step >= 0 ? 1 : -1)) / step
TODO: check zero-division manually

2019-06-18 06:28 UTC, hczhcz commented
TODO: Fix param handling

2019-06-24 11:33 UTC, alesapin commented
`select arrayReduce('sumResample(1, 1, 0)', [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);` leads to Floating point exception and server crash https://pastebin.com/3UzexYKW.

2019-06-24 12:07 UTC, alesapin commented on dbms/src/AggregateFunctions/AggregateFunctionResample.cpp
> +        return nullptr;
It's ok to throw an exception here.

2019-06-24 12:24 UTC, alesapin commented on dbms/src/AggregateFunctions/AggregateFunctionResample.h
> +                (end - begin + step - (step >= 0 ? 1 : -1)) / step
Yes, it's still have to be checked.

2019-06-24 12:31 UTC, alesapin commented
What is the main idea of the negative step and intervals? I don't understand how they work:
```
SELECT arrayReduce('sumResample(0, -1, -1)', [10], [0])

┌─arrayReduce('sumResample(0, -1, -1)', [10], [0])─┐
│ []                                               │
└──────────────────────────────────────────────────┘
SELECT arrayReduce('sumResample(0, -1, -1)', [10], [1])

┌─arrayReduce('sumResample(0, -1, -1)', [10], [1])─┐
│ []                                               │
└──────────────────────────────────────────────────┘
SELECT arrayReduce('sumResample(9, -1, -1)', [10], [0])                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                       
┌─arrayReduce('sumResample(9, -1, -1)', [10], [0])─┐                                                                                                                                                                                                                                                   
│ [0,0,0,0,0,0,0,0,0,10]                           │                                                                                                                                                                                                                                                   
└──────────────────────────────────────────────────┘   
SELECT arrayReduce('sumResample(0, -1, -1)', [10], [-0])                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                       
┌─arrayReduce('sumResample(0, -1, -1)', [10], [-0])─┐                                                                                                                                                                                                                                                   
│ [10]                                             │                                                                                                                                                                                                                                                   
└──────────────────────────────────────────────────┘   
```

2019-06-24 12:32 UTC, alesapin requested changes
.

2019-06-24 12:34 UTC, alesapin commented
Also error messages are unclear:
```
SELECT arrayReduce('sumResample(11, 10, 1)', [10], [0])

Received exception from server (version 19.9.1):
Code: 36. DB::Exception: Received from localhost:9000, ::1. DB::Exception: The range given in function sumResample contains too many elements. 
```

2019-06-25 12:14 UTC, merged

2020-11-25 10:22 UTC, YoannBuch commented
Hello @hczhcz, very nice addition :)

How would one use `-Resample` in combination of `quantileTimingWeighted`? (knowing that `quantileTimingWeighted` already returns an array) Thanks!