movingSum function for numeric and decimals
ClickHouse/ClickHouse pull request #5595
Opened 2019-06-12 14:08 UTC by inv2004

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- New Feature

Short description (up to few sentences):

Aggregate function movingSum(X)(v), which calculates moving sum with or without window-size limitation.

X - parameter for limit window size, if not set - it sums of all values.

Result: array of the same length and type as v rows.

Example:
```sql
CREATE TABLE t ENGINE = Memory AS SELECT number % 2 as k, 1+number v FROM system.numbers limit 10;

SELECT k, movingSum(3)(v) FROM t GROUP BY k;
┌─k─┬─movingSum(3)(v)─┐
│ 0 │ [1,4,9,15,21]   │
│ 1 │ [2,6,12,18,24]  │
└───┴─────────────────┘

SELECT k, movingSum(v) FROM t GROUP BY k;
┌─k─┬─movingSum(v)───┐
│ 0 │ [1,4,9,16,25]  │
│ 1 │ [2,6,12,20,30] │
└───┴────────────────┘
```

2019-06-14 13:09 UTC, alexey-milovidov commented on dbms/src/AggregateFunctions/AggregateFunctionMovingSum.cpp
> +	    // cumulative sum without parameter
Indent.

2019-06-14 13:17 UTC, alexey-milovidov commented on dbms/src/AggregateFunctions/AggregateFunctionMovingSum.h
> +#define AGGREGATE_FUNCTION_GROUP_ARRAY_MAX_ARRAY_SIZE 0xFFFFFF
Duplicate name of macro.

2019-06-14 13:22 UTC, alexey-milovidov requested changes
I have questions in https://t.me/joinchat/B44Vi1T-PQA97S02SBwXIw

2019-06-18 14:21 UTC, inv2004 commented
> I have questions in https://t.me/joinchat/B44Vi1T-PQA97S02SBwXIw

Functions created : groupArrayMovingSum and groupArrayMovingAvg

2019-06-24 16:13 UTC, merged