Fix mixing of send_timeout and receive_timeout
ClickHouse/ClickHouse pull request #56035
Opened 2023-10-26 06:47 UTC by azat

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix mixing of send_timeout and receive_timeout

2023-10-26 11:35 UTC, alexey-milovidov requested changes
> NOTE: We use send_timeout for the receive timeout and vice versa (change arguments ordering in TimeoutSetter),
            ///  because send_timeout is client-side setting which has opposite meaning on the server side.

2023-10-26 11:39 UTC, azat commented
I saw the comment, I just don't understand how it could be client-side setting in case of some driver (for c++, python, go...), none of drivers implement settings

2023-10-26 12:34 UTC, alexey-milovidov commented
Then, let's change it with the comment. It cannot be a "bug fix" because there is no bug.

2023-10-27 09:54 UTC, azat commented
>Then, let's change it with the comment. It cannot be a "bug fix" because there is no bug.

OK, I've changed to `Backward Incompatible Change`, since I guess  there is a little chance that somebody was relying on this.

2023-10-30 08:23 UTC, azat commented
All tests failures looks like due to https://github.com/ClickHouse/ClickHouse/issues/56108
And previous CI run passed - https://github.com/ClickHouse/ClickHouse/commit/6b90a3f6c6457fce458eb1e3b6aa442d23a98136

2023-10-30 19:59 UTC, alexey-milovidov approved these changes

2023-10-30 19:59 UTC, merged