Fix float to decimal convert overflow
ClickHouse/ClickHouse pull request #5607
Opened 2019-06-13 11:31 UTC by coraxster

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Bug Fix

Short description (up to few sentences):
```sql
select toDecimal32(10000.1, 6);
--2147.483648
select toDecimal64(10000.1, 18);
--9.223372036854775808
select toDecimal128(1000000000000000000000.1, 18);
0.000000000000000000
```

2019-06-13 12:25 UTC, 4ertus2 commented on dbms/tests/queries/0_stateless/00700_decimal_casts.sql
> +select toDecimal128(1000000000000000000000.1, 18); -- { serverError 407 }
no empty line at the end

2019-06-13 12:27 UTC, 4ertus2 approved these changes

2019-06-13 12:28 UTC, 4ertus2 commented on dbms/tests/queries/0_stateless/00700_decimal_casts.sql
> +select toDecimal128(1000000000000000000000.1, 18); -- { serverError 407 }
Need empty line at the end of file

2019-06-13 12:53 UTC, coraxster commented on dbms/tests/queries/0_stateless/00700_decimal_casts.sql
> +select toDecimal128(1000000000000000000000.1, 18); -- { serverError 407 }
done, thank you!

2019-06-13 16:07 UTC, 4ertus2 requested changes

2019-06-13 16:07 UTC, 4ertus2 commented on dbms/src/DataTypes/DataTypesDecimal.h
> +        if (converted_value == min_value || converted_value == max_value)
OK there's an error where we check isfinite(value) before multiplication and do not check the result. But why static_cast of INF returns min_value? Is it something documented in standard? If not we could just check the result.

```
auto out = value * ToDataType::getScaleMultiplier(scale);
if (!std::isfinite(value))
    throw Exception( ...
```

2019-06-13 18:54 UTC, 4ertus2 commented on dbms/src/DataTypes/DataTypesDecimal.h
> +        if (converted_value == min_value || converted_value == max_value)
This code works
```
    if constexpr (std::is_floating_point_v<FromFieldType>)
    {
        if (!std::isfinite(value))
            throw Exception("Decimal convert overflow. Cannot convert infinity or NaN to decimal", ErrorCodes::DECIMAL_OVERFLOW);

        auto out = value * ToDataType::getScaleMultiplier(scale);
        if constexpr (std::is_same_v<ToNativeType, Int128>)
        {
            static constexpr __int128 min_int128 = __int128(0x8000000000000000ll) << 64;
            static constexpr __int128 max_int128 = (__int128(0x7fffffffffffffffll) << 64) + 0xffffffffffffffffll;
            if (out < min_int128 || out > max_int128)
                throw Exception("Decimal convert overflow. Float is out of Decimal range", ErrorCodes::DECIMAL_OVERFLOW);
        }
        else
        {
            if (out < std::numeric_limits<ToNativeType>::min() || out > std::numeric_limits<ToNativeType>::max())
                throw Exception("Decimal convert overflow. Float is out of Decimal range", ErrorCodes::DECIMAL_OVERFLOW);
        }
        return out;
    }
```

2019-06-13 18:59 UTC, 4ertus2 commented on dbms/tests/queries/0_stateless/00700_decimal_casts.sql
> +select toDecimal128(1000000000000000000000.1, 18); -- { serverError 407 }
We need 3 more lines with negatives.
```
select toDecimal32(-10000.1, 6); -- { serverError 407 }
￼select toDecimal64(-10000.1, 18); -- { serverError 407 }
 select toDecimal128(-1000000000000000000000.1, 18); -- { serverError 407 }
```

2019-06-14 06:20 UTC, merged

2019-06-16 08:09 UTC, coraxster commented
Got some non-fixed boundary cases. Made a new PR.
https://github.com/yandex/ClickHouse/pull/5645