Add checks for conversion from Numbers to Enums
ClickHouse/ClickHouse pull request #56240
Opened 2023-11-02 06:44 UTC by evillique

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add a setting `input_format_numbers_enum_on_conversion_error` for conversion from Numbers to Enums to check whether the element exists. Closes: https://github.com/ClickHouse/ClickHouse/issues/56144

### Version info
- Merged into: `26.1.1.481`

2023-11-05 13:08 UTC, SaltTan commented
Please implement this under a setting.
People could leverage the existing behaviour to insert new values silently and then change the enum when selects start to fail.
I, for instance, always prefer a failed select over a failed insert. I have considered this behaviour a feature.

2023-11-24 12:36 UTC, Avogar commented on src/Functions/FunctionsConversion.h
> +                        if (!nullable_col->isNullAt(i))
`isNullAt` performs `assert_cast` on each call, better to use `null_map` from `ColumnNullable` directly. Also, we can avoid code duplication on nullable/non-nullable cases. For example, doing smth like:
```
const NullMap * null_map;
if (nullable_col)
    null_map = &nullable_col->getNullMapData();
for (size_t i = 0; i < size; ++i)
{
    if (null_map && (*null_map)[i])
        out_data[i] = default_enum_value;
    else
    {
    ...
    }
}
...
```

2023-11-24 12:41 UTC, Avogar commented on src/Core/Settings.h
> +    M(Bool, input_format_numbers_enum_on_conversion_error, false, "Throw an exception during Numbers to Enum conversion if the value does not exist in Enum.", 0) \
As I can see, this setting is used only in cast, not in input formats. Let's move it in common settings, remove `input_format` prefix and remove it from `FormatSettings`.
Or this settings should be also used in some input formats to validate number -> enum conversion?

2023-11-24 12:58 UTC, Avogar commented
We still can do bad convertion in some cases:
1) INSERT INTO ... SELECT ...
```
avogar-dev :) create table test(x Enum('a'=1, 'b'=2)) engine=Memory

CREATE TABLE test
(
    `x` Enum('a' = 1, 'b' = 2)
)
ENGINE = Memory

Query id: 2ea0f8bf-0f08-4b76-8d47-9be45173754a

Ok.

0 rows in set. Elapsed: 0.000 sec.

avogar-dev :) set input_format_numbers_enum_on_conversion_error=1

SET input_format_numbers_enum_on_conversion_error = 1

Query id: b4a75ac2-d759-4c5a-8909-ae40bb4fc2ee

Ok.

0 rows in set. Elapsed: 0.000 sec.

avogar-dev :) insert into test select 3

INSERT INTO test SELECT 3

Query id: 3953c80a-f451-41a8-87af-0bbad0a1a198

Ok.

0 rows in set. Elapsed: 0.001 sec.

avogar-dev :) select * from test

SELECT *
FROM test

Query id: cae5bae4-cc99-4cbc-b4b8-af4df3552e2d

Ok.
Exception on client:
Code: 36. DB::Exception: Code: 36. DB::Exception: Unexpected value 3 in enum. (BAD_ARGUMENTS) (version 23.11.1.1438). (BAD_ARGUMENTS)
```

I thought we do CAST in this case, but for some reason setting doesn't work.

2) We check if value is correct in EnumSerialization for text deserialization. But we don't check it in binary formats:
```
$ ./clickhouse client -q "select 42 format RowBinary" | ./clickhouse client -q "insert into test format RowBinary" --input_format_numbers_enum_on_conversion_error=1
$ ./clickhouse client -q "select * from test"
Code: 36. DB::Exception: Unexpected value 42 in enum: (in query: select * from test). (BAD_ARGUMENTS)
$ ./clickhouse client -q "truncate table test"
$ ./clickhouse client -q "select 42 as x format Arrow" | ./clickhouse client -q "insert into test format Arrow" --input_format_numbers_enum_on_conversion_error=1 # we use castColumn func in Arrow/Parquet/ORC, but we don't have context with settings there
$ ./clickhouse client -q "select * from test"
Code: 36. DB::Exception: Unexpected value 42 in enum: (in query: select * from test). (BAD_ARGUMENTS)
```
And other binary formats like BSON, Avro, even Native and some other.

2024-06-25 16:51 UTC, Avogar commented
@evillique do you have plans to continue this PR?

2026-01-11 21:04 UTC, alexey-milovidov commented on src/Core/FormatFactorySettings.h
> +    DECLARE(Bool, input_format_numbers_enum_on_conversion_error, false, R"(
This name does not read well.
Name it `input_format_check_conversion_from_numbers_to_enum`.

2026-01-11 21:06 UTC, alexey-milovidov commented on src/Functions/FunctionsConversion.h
> +                    if constexpr (is_signed)
This is strange... Enums can have gaps in numeric values, e.g., `Enum8('hello' = 10, 'world' = 100)`

2026-01-11 21:07 UTC, alexey-milovidov commented on src/Functions/FunctionsConversion.h
> +                    result_type.findByValue(static_cast<FieldType>(in_data[i]));
Missing a comment about this statement.

2026-01-11 21:09 UTC, alexey-milovidov commented on src/Core/FormatFactorySettings.h
> +    DECLARE(Bool, input_format_numbers_enum_on_conversion_error, false, R"(
I see it is not only about the input format. We should change it to

`check_conversion_from_numbers_to_enum`

2026-01-11 21:09 UTC, alexey-milovidov requested changes
.

2026-01-13 11:13 UTC, ahmadov commented on src/Functions/FunctionsConversion.h
> +                    if constexpr (is_signed)
I removed this check since `findByValue` should handle that properly with the correct error type `UNKNOWN_ELEMENT_OF_ENUM`. I added the tests for that case.

2026-01-13 11:15 UTC, ahmadov commented
Hi @evillique, I updated this PR since it was requested again by customers. Would you like to check it out?

2026-01-13 19:02 UTC, alexey-milovidov approved these changes

2026-01-13 19:02 UTC, merged

2026-01-23 21:01 UTC, alexey-milovidov commented
@ahmadov, unfortunately, your changes contain a bug: https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=fc44324e8274f017613310ab7aea13f2899e2f1a&name_0=MasterCI&name_1=BuzzHouse%20%28amd_ubsan%29&name_1=BuzzHouse%20%28amd_ubsan%29

I will try to revert or fix.