Add a table `system.symbols` and remove garbage.
ClickHouse/ClickHouse pull request #56350
Opened 2023-11-06 00:13 UTC by alexey-milovidov

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add `system.symbols` table useful for introspection of the binary.

2023-11-06 22:39 UTC, alexey-milovidov commented
You can see that I'm moving some code of aggregate functions, functions, and table functions to .cpp and removing header files. This makes the following sense:

1. These components are accessible only through a factory, and we don't want to include their header files from any other place than the implementation of the corresponding function.
2. We can put their code into an anonymous namespace to lower the binary size a little, but if we do it in a header file, it will be error-prone.
3. More clang-tidy checks are applied to .cpp files than to .h files.

2023-11-07 14:05 UTC, Algunenano requested changes
I'm scared of the changes to sumMap because some of the functions don't have enough tests and I see some changes in behaviour/states (which might or might not break compatibility). Left some other comments, some related to new code and some related to older code moved in the PR

2023-11-07 14:31 UTC, alexey-milovidov commented on src/AggregateFunctions/AggregateFunctionSumMap.cpp
> +    factory.registerFunction("sumMappedArrays", [](const std::string & name, const DataTypes & arguments, const Array & params, const Settings *) -> AggregateFunctionPtr
I checked - it is the same, as expected, because `sumMap` uses DataType for generic serialization. I will add a test.

2023-11-07 14:31 UTC, alexey-milovidov commented on src/AggregateFunctions/AggregateFunctionSumMap.cpp
> +    factory.registerFunction("sumMappedArrays", [](const std::string & name, const DataTypes & arguments, const Array & params, const Settings *) -> AggregateFunctionPtr
`0200000000010000000000000053542827302E312701000000020000000000000053542827312E3227`

2023-11-07 14:35 UTC, alexey-milovidov commented
Next offenders:
- RangeHashedDictionary;
- avgWeighted;
- deltaSumTimestamp;
- Stable versions of moment statistics;

2023-11-07 17:36 UTC, alexey-milovidov commented on src/Storages/System/StorageSystemSymbols.cpp
> +    }));
Yes, but we don't have it in the SymbolIndex, which serves a limited purpose.

2023-11-07 17:37 UTC, alexey-milovidov commented on src/Functions/castTypeToEither.h
> +static bool castTypeToEither(TypeList<Args...>, const auto * type, auto && f)
Yes, I didn't understand it, but it does not matter a lot.

2023-11-07 17:38 UTC, alexey-milovidov commented on src/AggregateFunctions/AggregateFunctionQuantile.h
> +    bool has_accuracy_parameter>
The previous behavior was dependent on std::is_same_v, which is less clear and was broken after moving the code to anonymous namespace.

2023-11-07 17:48 UTC, alexey-milovidov commented on src/AggregateFunctions/AggregateFunctionSumMap.cpp
> +    factory.registerFunction("sumMappedArrays", [](const std::string & name, const DataTypes & arguments, const Array & params, const Settings *) -> AggregateFunctionPtr
Hm, it differs in one byte... will take a look.

2023-11-08 02:45 UTC, alexey-milovidov commented
#56435

2023-11-08 09:44 UTC, Algunenano commented
> @alexey-milovidov
[Remove support of](https://github.com/ClickHouse/ClickHouse/pull/56350/commits/30bec95d111672c6d740a178e6208b5d186f0042) [Decimal](https://github.com/ClickHouse/ClickHouse/pull/56350/commits/30bec95d111672c6d740a178e6208b5d186f0042) [inside](https://github.com/ClickHouse/ClickHouse/pull/56350/commits/30bec95d111672c6d740a178e6208b5d186f0042) [avgWeighted](https://github.com/ClickHouse/ClickHouse/pull/56350/commits/30bec95d111672c6d740a178e6208b5d186f0042) https://github.com/ClickHouse/ClickHouse/issues/56435

This is a huge breaking change. It should probably be in a different PR (with a suggestion on how to migrate if you are using it / have -state's using it), and not mixed with the addition of system.symbols.

2023-11-08 19:56 UTC, alexey-milovidov commented
@Algunenano, it is hard to stop when I see so many problems in the code :)
But when it is finished, I will try to extract multiple PRs, or as a minimum - add all items into the changelog.

2023-11-12 04:53 UTC, alexey-milovidov commented
`sumMap` is utter garbage. It uses promoted Decimal type, e.g. Decimal128, for state serialization while using non-promoted Decimal type for the result.

2023-11-12 05:27 UTC, alexey-milovidov commented
@Algunenano, WTF? https://pastila.nl/?0003a09b/4d7bd2d352a396961eaf91dcdd69c3f3#NshzW/pAMeXr/GF9QxXfMA==

2023-11-12 06:47 UTC, alexey-milovidov commented
@Algunenano I've added a test, and it produces MSan error on master:
https://pastila.nl/?000b9ea7/0b76fa5d47173281f3f5160e7b4e9836#C3+cFjMNJwkTHcg28gAlEQ==

It means we have to merge this ASAP.

2023-11-12 07:12 UTC, alexey-milovidov commented
This PR will fix #54955 and #53134.

2023-11-12 07:14 UTC, alexey-milovidov commented
I regret that we let #7898 and #1250 into our codebase.

2023-11-13 03:09 UTC, alexey-milovidov commented
https://github.com/ClickHouse/ClickHouse/issues/56650

2023-11-13 11:25 UTC, merged

2023-11-13 11:58 UTC, Algunenano commented on src/AggregateFunctions/AggregateFunctionUniqCombined.h
> +AggregateFunctionPtr createAggregateFunctionWithK(const DataTypes & argument_types, const Array & params)
I wonder why K needs to be part of the template and force compiling the same functions over and over. It seems `HyperLogLogCounter` could just get k as a parameter

2023-11-15 15:38 UTC, tavplubix commented
@alexey-milovidov, you forgot to check the failed tests before merging:
Performance Comparison [3/4] — 2 errors - https://s3.amazonaws.com/clickhouse-test-reports/56350/c4de4045f15df2a835d7fb73793d75e3216e62bf/performance_comparison_[3_4]/report.html 
it was related, this PR breaks Performance tests in master. Should we revert this PR?

2023-11-15 15:42 UTC, tavplubix commented
Fix: https://github.com/ClickHouse/ClickHouse/pull/56797