allow ALTER for TEMPORARY tables
ClickHouse/ClickHouse pull request #56892
Opened 2023-11-16 22:14 UTC by icuken

### Changelog category:
- Improvement

### Changelog entry:
PR for #56336. Allow basic commands in ALTER for TEMPORARY tables.

2023-11-16 22:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=56892) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=56892) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=56892) it.</sub>

2023-11-27 19:56 UTC, jkartseva reviewed
Please update the documentation:

https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/sql-reference/statements/alter/column.md

2023-11-28 22:00 UTC, jkartseva requested changes
Asking to update the documentation, otherwise LGTM.

2023-11-28 22:12 UTC, icuken commented
Do I understand correctly that adding `[TEMPORARY]` to the syntax section will be enough?

2023-11-28 22:14 UTC, icuken commented on src/Storages/StorageMemory.h
> +    void checkAlterIsPossible(const AlterCommands & commands, ContextPtr local_context) const override;
It'll work on any temporary table, other engines will support all operations allowed for ALTER on non-temporary tables.

2023-11-28 22:20 UTC, tavplubix commented on src/Storages/StorageMemory.h
> +    void checkAlterIsPossible(const AlterCommands & commands, ContextPtr local_context) const override;
Could you please add a test with some other engine as well?

2023-11-29 21:16 UTC, jkartseva approved these changes
LGTM, thank you.

2023-11-30 18:29 UTC, jkartseva commented
@icuken 
Could you please rebase for the test pass?

2023-12-01 02:29 UTC, merged