DOCAPI-6425: EN review. RU Translation. User settings.
ClickHouse/ClickHouse pull request #5713
Opened 2019-06-21 14:37 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation #4792.

2019-06-21 14:48 UTC, blinkov requested changes

2019-06-21 14:48 UTC, blinkov commented on docs/en/operations/settings/settings_users.md
> +- To assign the SHA256 hash of a password, place it in a `password_sha256_hex` element.
To assign a password using SHA256 hash...

2019-06-21 14:48 UTC, blinkov commented on docs/en/operations/settings/settings_users.md
> +Quotas allow you to limit resource usage over a period of time or track resource usage. Quotas are configured in the `quotas`
Quotas allow you to track or limit resource usage over a period of time.

2019-06-21 14:48 UTC, blinkov commented on docs/en/operations/settings/settings_users.md
> +You can assign a quota for the user. For a detailed description of quota configuration, see [Quotas](../quotas.md#quotas).
why plural is dropped?

2019-06-21 14:48 UTC, blinkov commented on docs/en/operations/settings/settings_users.md
> +The following configuration establishes that user `user1` can only see the rows of `table1` as the result of `SELECT` queries, where the value of the `id` field is 1000.
establishes -> forces

2019-06-21 14:48 UTC, blinkov commented on docs/ru/operations/settings/settings_users.md
> +    <!-- If user name was not specified, 'default' user is used. -->
мы комментарии везде не переводим или только тут?

2019-06-21 14:48 UTC, blinkov commented on docs/ru/operations/settings/settings_users.md
> +    Первая строка результата — пароль. Вторая строка — соответствующий хэш SHA256.
соответствующий **ему**?

2019-06-21 14:48 UTC, blinkov commented on docs/ru/operations/settings/settings_users.md
> +    Для проверки доступа выполняется запрос [DNS PTR](https://en.wikipedia.org/wiki/Reverse_DNS_lookup) для адреса клиента, а затем применяется заданное регулярное выражение. Затем, для результатов з
DNS запрос PTR

2019-06-21 14:48 UTC, blinkov commented on docs/ru/operations/settings/settings_users.md
> +Все результаты DNS-запросов кэшируются до перезапуска сервера.
стоит сослаться на `system drop dns cache`

2019-06-21 14:48 UTC, blinkov commented on docs/ru/operations/settings/settings_users.md
> +    Открывать доступ из любой сети небезопасно, если у вас нет правильно настроенного брандмауэра или сервер не отключен от интернета.
Интернет разве не с заглавной буквы пишется?

2019-06-21 14:48 UTC, blinkov commented on docs/ru/operations/settings/settings_users.md
> +Квотирование позволяет ограничить использование ресурсов в течение определенного периода времени или отслеживать использование ресурсов. Квоты настраиваются в разделе `quotas` конфигурационного файла
тоже можно перефразировать как в английском

2019-06-21 14:56 UTC, spyros87 commented on docs/en/operations/settings/settings_users.md
> +List of networks that the user can connect to the ClickHouse server from.
I would replace to `List of networks from which the user can connect to the Clickhouse server.`

2019-06-21 14:58 UTC, spyros87 commented on docs/en/operations/settings/settings_users.md
> +Each element of the list has one of the following forms:
Looks a bit nicer as `Each element of the list can have one of the following forms`.

2019-06-21 15:11 UTC, spyros87 commented on docs/en/operations/settings/settings_users.md
> +    To check access, a [DNS PTR query](https://en.wikipedia.org/wiki/Reverse_DNS_lookup) is performed for the peer address and then regexp is applied. Then, for the results of PTR query, another DNS
Please correct to `and then the specified regexp is applied` in the first sentence.

For the second sentence can phrased as `Then, another DNS query is performed for the results of the PTR query and all the received addresses are compared with the peer address.`

2019-06-21 15:13 UTC, spyros87 commented on docs/en/operations/settings/settings_users.md
> +In this section, you can you can limit rows that are returned by ClickHouse for `SELECT` queries from the current user, thus implementing basic row-level security.
Change `queries from the current user` to `queries made by the current user`.

2019-06-21 15:14 UTC, spyros87 commented on docs/en/operations/settings/settings_users.md
> +The following configuration establishes that user `user1` can only see the rows of `table1` as the result of `SELECT` queries, where the value of the `id` field is 1000.
`defines` can be also an option.

2019-07-04 19:24 UTC, BayoNet commented on docs/ru/operations/settings/settings_users.md
> +    <!-- If user name was not specified, 'default' user is used. -->
Это хороший вопрос.
Мы в своё время договаривались, что кодблоки не переводим, поскольку на нашей стороне было техническое ограничение. Сейчас этого ограничения нет и в общем-то можно теперь их переводить, но не знаю надо ли. Согласно стайлгайду ClickHouse комментарии в коде должны быть на английском, а это кусок конфига, т.е. комментарии должны быть на английском. Вроде по логике так получается. Дальше по тексту же есть объяснение тегов на русском.

2019-07-04 19:29 UTC, BayoNet commented on docs/ru/operations/settings/settings_users.md
> +Все результаты DNS-запросов кэшируются до перезапуска сервера.
SYSTEM у нас вообще не описаны, но тикеты есть. Сейчас добавлю в тикет, что можно сослаться.

2019-07-04 19:32 UTC, BayoNet commented on docs/ru/operations/settings/settings_users.md
> +    Открывать доступ из любой сети небезопасно, если у вас нет правильно настроенного брандмауэра или сервер не отключен от интернета.
В гайде написано с маленькой буквы за исключением юридических текстов, где пишут "сеть Интернет"

2019-07-04 22:03 UTC, merged