T64
ClickHouse/ClickHouse pull request #5742
Opened 2019-06-25 14:12 UTC by 4ertus2

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Improvement

Short description (up to few sentences):
Full bit transpose variant for T64 codec. Could lead to better compression with zstd.

Detailed description (optional):
Continuation of #5557 and #5731. Allow to set option to T64 codec: T64('byte'), T64('bit'). So it would generate byte-transposed or bit-transposed data. By default it uses 'byte' variant.

2019-06-25 14:14 UTC, 4ertus2 commented
I've compressed some real data DateTime column with different variants:
```
lz4             833569732
zstd            515097904
t64(byte)+lz4   407128098
t64(bit)+lz4    472855596
t64(byte)+zstd  345330458
t64(bit)+zstd   318123008
```
It looks that full bit-transpose helps zstd and do not helps lz4.

2019-06-26 08:38 UTC, alexey-milovidov commented
You can also compare with different levels of ZSTD, because level 1 is used by default.
When comparing by compressed size, you should also mention compression and decompression speed.

2019-06-26 08:38 UTC, alexey-milovidov commented
PS. What's in stress test?

2019-06-26 09:55 UTC, 4ertus2 commented
> PS. What's in stress test?

Code: 202. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Too many simultaneous queries. Maximum: 100.

2019-06-28 11:53 UTC, alexey-milovidov commented
> Code: 202. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Too many simultaneous queries. Maximum: 100.

This message cannot relate to stress test failure. It fails only in case of sanitizer reports or server crash.

2019-06-28 11:55 UTC, alexey-milovidov commented on dbms/src/Compression/CompressionCodecT64.cpp
> +template <typename _T, bool _full = false>
`_Capital` is reserved for C++ language and standard library.

2019-06-28 11:55 UTC, alexey-milovidov requested changes
.

2019-06-28 11:56 UTC, alexey-milovidov commented on dbms/src/Compression/CompressionCodecT64.cpp
> +template <typename _T, bool _full = false>
Let's remove leading underscores at all.

2019-06-28 11:56 UTC, alexey-milovidov commented on dbms/src/Compression/CompressionCodecT64.cpp
>      UInt64 mx[64] = {};
Is `mx` an abbreviation for `matrix`?
I hate abbreviations.

2019-06-28 11:57 UTC, alexey-milovidov commented on dbms/src/Compression/CompressionCodecT64.cpp
> +        revTranspose64x8(mx_line);
rev -> reverse

2019-06-28 11:58 UTC, alexey-milovidov commented on dbms/src/Compression/CompressionCodecT64.h
> +    enum class Variant
Missing comment.

2019-07-02 22:56 UTC, merged