Support function getClientHTTPHeader
ClickHouse/ClickHouse pull request #57665
Opened 2023-12-08 11:34 UTC by lingtaolf

Resubmit: #54813

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add function `getClientHTTPHeader` for fetching values header values set in the HTTP request.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-12-13 03:36 UTC, lingtaolf commented
@alexey-milovidov Please help review my code when you have time.

2023-12-26 14:41 UTC, alexey-milovidov commented
Thank you! The linker shows duplicate symbols...

2023-12-28 00:25 UTC, alexey-milovidov commented
Still duplicate.

2023-12-28 00:26 UTC, alexey-milovidov commented on tests/config/config.d/forbidden_get_client_http_headers.xml
> +    <get_client_http_header_forbidden_headers>['FORBIDDEN-KEY1','FORBIDDEN-KEY2','FORBIDDEN-KEY,CONTAINS_COMMA']</get_client_http_header_forbidden_headers>
XML is a structured language, and array formatting is another structured language. We shouldn't mix both.

2023-12-28 00:28 UTC, alexey-milovidov commented on src/Functions/getClientHTTPHeader.cpp
> +            if (!headers.has(header_name))
Better if it will return the default value.

2023-12-28 00:28 UTC, alexey-milovidov commented on src/Functions/getClientHTTPHeader.cpp
> +                auto it = forbidden_header_list.find(header_name);
contains?

2023-12-28 00:29 UTC, alexey-milovidov requested changes
X-ClickHouse-Key should always be forbidden.

2024-03-23 19:12 UTC, alexey-milovidov commented on docs/en/sql-reference/functions/other-functions.md
> +┌─getClientHTTpHeader('test')─┐
The documentation is wrong, should be HTTP, not HTTp.

2024-03-23 20:51 UTC, alexey-milovidov commented
I'll continue and merge this PR in https://github.com/ClickHouse/ClickHouse/pull/61820.
Thank you! I will mention you as the author.

2024-03-23 20:51 UTC, closed without merging