Handle signed numeric literals in normalizeQuery
ClickHouse/ClickHouse pull request #58710
Opened 2024-01-11 10:22 UTC by aiven-sal

This solution is non-ideal, but it's difficult to achieve
better results using only the Lexer.

Close https://github.com/ClickHouse/ClickHouse/issues/57919

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improved handling of signed numeric literals in normalizeQuery

2024-01-11 18:04 UTC, yariks5s requested changes

2024-01-11 18:04 UTC, yariks5s commented on tests/queries/0_stateless/01451_normalize_query.sql
> +SELECT normalizeQuery('[+1, 2, 3]');
Can you please also add tests with addition/subtraction somewhere in the middle of the sequence and the end?

2024-01-13 12:00 UTC, yariks5s approved these changes

2024-01-15 13:40 UTC, merged

2026-04-28 17:57 UTC, clickgapai commented
Hi @aiven-sal @yariks5s — while reviewing this PR I found the following:

- **Bug (P2):** `normalizeQueryToPODArray` silently drops unary `+`/`-` before non-literal tokens after a comma — https://github.com/ClickHouse/ClickHouse/issues/103681

Happy to discuss — close anything that's wrong or already addressed.