DOCAPI-7129 Nested JSON in JSONEachRow description + date_time_input_format
ClickHouse/ClickHouse pull request #5889
Opened 2019-07-05 13:20 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Documentation for  #3144 and #5511 

Also so markup fixes.

2019-07-10 15:31 UTC, blinkov requested changes

2019-07-10 15:31 UTC, blinkov commented on docs/en/interfaces/formats.md
> +If you have a table with the [Nested](../data_types/nested_data_structures/nested.md) data type columns, you can insert JSON data, having the same structure. Enable this functionality with the [input
comma before "having" doesn't look necessary

2019-07-10 15:31 UTC, blinkov commented on docs/en/interfaces/formats.md
> +As you can find in the `Nested` data type description, ClickHouse treats each component of the nested structure as a separate column, `n.s` and `n.i` for our table. So you can insert the data by the
the data by the following way -> data the following way

2019-07-10 15:31 UTC, blinkov commented on docs/en/interfaces/formats.md
> +If you try to insert hierarchical JSON object, such as:
To insert data as hierarchical JSON object enable input_format_import_nested_json=1 setting... 
and make it a link

2019-07-10 15:31 UTC, blinkov commented on docs/en/interfaces/formats.md
> +Then ClickHouse returns an exception, unless the case, when `input_format_import_nested_json=1`.
Without this setting ClickHouse will throw an exception

2019-07-10 15:31 UTC, blinkov commented on docs/en/operations/settings/settings.md
> +Enables or disables inserting of JSON data with nested structures.
structures -> objects

2019-07-10 15:31 UTC, blinkov commented on docs/en/operations/settings/settings.md
> +The setting doesn't apply to date and time functions.
link to their reference?

2019-07-10 15:31 UTC, blinkov commented on docs/en/operations/settings/settings.md
> +    ClickHouse can parse only the basic format `YYYY-MM-DD HH:MM:SS`.
it's not clear if "best effort" supports basic format as well or not (space instead of T makes it non-ISO8601)

2019-07-10 15:31 UTC, blinkov commented
also there's a failing docs check

2019-07-16 09:21 UTC, merged

2019-10-10 23:24 UTC, 4ertus2 reviewed
.

2019-10-11 00:51 UTC, alexey-milovidov commented
@4ertus2 I don't understand what do you mean?