Display word-descriptive log level while enabling structured log formatting in json
ClickHouse/ClickHouse pull request #58936
Opened 2024-01-18 06:58 UTC by wheatdog

To address #57355

As example stated [here](https://github.com/ClickHouse/ClickHouse/blob/v23.10.6.60-stable/programs/server/config.xml#L66). ClickHouse should display word-descriptive log level value instead of numeric format.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Display word-descriptive log level while enabling structured log formatting in json

### Documentation entry for user-facing changes

no need

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2024-01-18 06:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=58936) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=58936) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=58936) it.</sub>

2024-01-18 07:14 UTC, wheatdog commented
I've tested this patch locally. It would spit out logs like following
```
> docker run --platform linux/amd64 --rm myclickhouse 
                                
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/99-my-settings.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Logging information to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
{"date_time":"1705559931.130354","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"SentryWriter","message":"Sending crash reports is disabled","source_file":"src\/Daemon\/SentryWriter.cpp; void SentryWriter::initialize(Poco::Util::LayeredConfiguration &)","source_line":"131"}
{"date_time":"1705559931.318622","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"Starting ClickHouse 24.1.1.1 (revision: 54482, git hash: 5775596c4f964523cfaf59a041d7807f98944f7f, build id: 1C2E6B09B3D7BF5D41CCB36B736825FA5C134F6B), PID 1","source_file":"","source_line":"0"}
{"date_time":"1705559931.320601","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"starting up","source_file":"","source_line":"0"}
{"date_time":"1705559931.321271","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"OS name: Linux, version: 6.5.13-orbstack-00121-ge428743e4e98, architecture: x86_64","source_file":"programs\/server\/Server.cpp; virtual void DB::Server::initialize(Poco::Util::Application &)","source_line":"425"}
{"date_time":"1705559931.493091","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"Available RAM: 7.75 GiB; physical cores: 8; logical cores: 8.","source_file":"programs\/server\/Server.cpp; virtual int DB::Server::main(const std::vector<std::string> &)","source_line":"712"}
```

2024-01-18 11:47 UTC, yariks5s requested changes
@wheatdog, can you please add some tests with different levels?

2024-01-18 12:40 UTC, wheatdog commented
@yariks5s, thanks for the review. Do you mean manually test it and check results with more logger levels?

Here are some more examples.

```
❯ docker run --platform linux/amd64 --rm myclickhouse                                 
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/99-my-settings.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Logging information to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
{"date_time":"1705559931.130354","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"SentryWriter","message":"Sending crash reports is disabled","source_file":"src\/Daemon\/SentryWriter.cpp; void SentryWriter::initialize(Poco::Util::LayeredConfiguration &)","source_line":"131"}
{"date_time":"1705559931.318622","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"Starting ClickHouse 24.1.1.1 (revision: 54482, git hash: 5775596c4f964523cfaf59a041d7807f98944f7f, build id: 1C2E6B09B3D7BF5D41CCB36B736825FA5C134F6B), PID 1","source_file":"","source_line":"0"}
{"date_time":"1705559931.320601","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"starting up","source_file":"","source_line":"0"}
{"date_time":"1705559931.321271","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"OS name: Linux, version: 6.5.13-orbstack-00121-ge428743e4e98, architecture: x86_64","source_file":"programs\/server\/Server.cpp; virtual void DB::Server::initialize(Poco::Util::Application &)","source_line":"425"}
{"date_time":"1705559931.493091","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"Available RAM: 7.75 GiB; physical cores: 8; logical cores: 8.","source_file":"programs\/server\/Server.cpp; virtual int DB::Server::main(const std::vector<std::string> &)","source_line":"712"}
{"date_time":"1705559931.503874","thread_name":"","thread_id":"1","level":"Warning","query_id":"","logger_name":"Context","message":"Delay accounting is not enabled, OSIOWaitMicroseconds will not be gathered. Check \/proc\/sys\/kernel\/task_delayacct","source_file":"","source_line":"0"}
{"date_time":"1705559931.563274","thread_name":"","thread_id":"1","level":"Warning","query_id":"","logger_name":"Application","message":"Integrity check of the executable skipped because the reference checksum could not be read.","source_file":"programs\/server\/Server.cpp; virtual int DB::Server::main(const std::vector<std::string> &)","source_line":"902"}
{"date_time":"1705559931.563733","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"It looks like the process has no CAP_IPC_LOCK capability, binary mlock will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_ipc_lock=+ep \/usr\/bin\/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.","source_file":"programs\/server\/Server.cpp; virtual int DB::Server::main(const std::vector<std::string> &)","source_line":"979"}
{"date_time":"1705559931.598976","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"Lowered uncompressed cache size to 3.87 GiB because the system has limited RAM","source_file":"programs\/server\/Server.cpp; virtual int DB::Server::main(const std::vector<std::string> &)","source_line":"1189"}
{"date_time":"1705559931.601272","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"Lowered mark cache size to 3.87 GiB because the system has limited RAM","source_file":"programs\/server\/Server.cpp; virtual int DB::Server::main(const std::vector<std::string> &)","source_line":"1199"}
{"date_time":"1705559931.602110","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"Lowered index mark cache size to 3.87 GiB because the system has limited RAM","source_file":"programs\/server\/Server.cpp; virtual int DB::Server::main(const std::vector<std::string> &)","source_line":"1219"}
{"date_time":"1705559931.643508","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"Setting max_server_memory_usage was set to 6.97 GiB (7.75 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)","source_file":"programs\/server\/Server.cpp; auto DB::Server::main(const std::vector<std::string> &)::(anonymous class)::operator()(ConfigurationPtr, bool) const","source_line":"1293"}
{"date_time":"1705559931.644882","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"Setting merges_mutations_memory_usage_soft_limit was set to 3.87 GiB (7.75 GiB available * 0.50 merges_mutations_memory_usage_to_ram_ratio)","source_file":"programs\/server\/Server.cpp; auto DB::Server::main(const std::vector<std::string> &)::(anonymous class)::operator()(ConfigurationPtr, bool) const","source_line":"1321"}
{"date_time":"1705559931.645166","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"Application","message":"Merges and mutations memory limit is set to 3.87 GiB","source_file":"programs\/server\/Server.cpp; auto DB::Server::main(const std::vector<std::string> &)::(anonymous class)::operator()(ConfigurationPtr, bool) const","source_line":"1334"}
{"date_time":"1705559931.688196","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"BackgroundSchedulePool\/BgBufSchPool","message":"Create BackgroundSchedulePool with 16 threads","source_file":"src\/Core\/BackgroundSchedulePool.cpp; DB::BackgroundSchedulePool::BackgroundSchedulePool(size_t, CurrentMetrics::Metric, CurrentMetrics::Metric, const char *)","source_line":"163"}
{"date_time":"1705559931.706573","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"BackgroundSchedulePool\/BgSchPool","message":"Create BackgroundSchedulePool with 512 threads","source_file":"src\/Core\/BackgroundSchedulePool.cpp; DB::BackgroundSchedulePool::BackgroundSchedulePool(size_t, CurrentMetrics::Metric, CurrentMetrics::Metric, const char *)","source_line":"163"}
{"date_time":"1705559931.887620","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"BackgroundSchedulePool\/BgMBSchPool","message":"Create BackgroundSchedulePool with 16 threads","source_file":"src\/Core\/BackgroundSchedulePool.cpp; DB::BackgroundSchedulePool::BackgroundSchedulePool(size_t, CurrentMetrics::Metric, CurrentMetrics::Metric, const char *)","source_line":"163"}
{"date_time":"1705559931.892537","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"BackgroundSchedulePool\/BgDistSchPool","message":"Create BackgroundSchedulePool with 16 threads","source_file":"src\/Core\/BackgroundSchedulePool.cpp; DB::BackgroundSchedulePool::BackgroundSchedulePool(size_t, CurrentMetrics::Metric, CurrentMetrics::Metric, const char *)","source_line":"163"}
{"date_time":"1705559931.904072","thread_name":"","thread_id":"1","level":"Information","query_id":"","logger_name":"CertificateReloader","message":"One of paths is empty. Cannot apply new configuration for certificates. Fill all paths and try again.","source_file":"src\/Server\/CertificateReloader.cpp; void DB::CertificateReloader::tryLoad(const Poco::Util::AbstractConfiguration &)","source_line":"72"}
{"date_time":"1705559931.923964","thread_name":"","thread_id":"1","level":"Warning","query_id":"","logger_name":"Application","message":"Listen [::]:9009 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname no [...]

2024-01-18 12:47 UTC, yariks5s commented
I mean automated testing (one similar example is located [here](https://github.com/yariks5s/ClickHouse/commit/03194eaeb92c6225112db68b26e24b2f03a8116d#diff-737eb62e000f437502a9dddf4ba2cc5388e013ff0186d3f6a9bb2b74a1681053)), So you can create a new test or enhance existing ones to check if `level` setting has correct data

2024-01-18 12:52 UTC, appier-timliou commented
Got it. Let me enhance that part.

2024-01-18 13:20 UTC, wheatdog commented
Got it. Let me enhance that part.

2024-01-18 15:00 UTC, wheatdog commented
@yariks5s I've enhance the related integration tests. 

I tried to follow [the guide](https://github.com/ClickHouse/ClickHouse/tree/master/tests/integration#running-with-runner-script) to run the corresponding integration test locally but I couldn't find `clickhouse-odbc-bridge`, which `runner` script required. It's not in my local build.

Could you guide me on how to properly do integration locally? Or could you review my test case and test it on CI. Thanks.

2024-01-18 15:31 UTC, yariks5s commented on tests/integration/test_structured_logging_json/test.py
> +    ) and validate_log_level(config, logs)
```suggestion
        and validate_log_level(config, logs)
    )

```

2024-01-18 15:31 UTC, yariks5s commented on tests/integration/test_structured_logging_json/test.py
>          config, logs, config_type
```suggestion
    return (
        validate_logs(logs)
        and validate_log_config_relation(config, logs, config_type)
```

2024-01-18 15:31 UTC, yariks5s commented on tests/integration/test_structured_logging_json/test.py
> +
```suggestion
    valid_level_values = {
        "Fatal",
        "Critical",
        "Error",
        "Warning",
        "Notice",
        "Information",
        "Debug",
        "Trace",
        "Test",
    }
```

2024-01-18 15:43 UTC, wheatdog commented
Thanks @yariks5s, I've run black locally to reformat the code.

2024-01-20 03:42 UTC, wheatdog commented
Hi @yariks5s, I noticed a several errors during CI. I'm not sure whether all of them are relevant to this PR. Could you guide me on how to proceed? Thanks.

The updated test case [test_structured_logging_json/test.py::test_structured_logging_json_format](https://s3.amazonaws.com/clickhouse-test-reports/58936/483bbaf14d16bb4b3871781c1bbc95eee7311a8f/integration_tests__release__[3_4]/integration_run_parallel5_0.log) is passed.

2024-01-22 11:47 UTC, yariks5s approved these changes

2024-01-22 12:03 UTC, yariks5s commented
Can you sync your branch with master? I don't have rights to do this by myself.

2024-01-23 14:30 UTC, wheatdog commented
Sure. I've merged the latest master branch into my feature branch.

2024-01-23 23:18 UTC, merged