Use scheduleOrThrow in MergeTree data selection and initialization to avoid deadlocks
ClickHouse/ClickHouse pull request #59427
Opened 2024-01-31 11:34 UTC by seandhaynes

At the moment, the use of `scheduleOrThrowOnError` means we don't currently have a timeout when waiting for threads to be allocated. So if you reach a point where you saturate all threads available in the global pool whilst in a loop or similar, ClickHouse can enter a deadlocked state as mentioned on https://github.com/ClickHouse/ClickHouse/issues/51820

Using `scheduleOrThrow` means rather that ClickHouse getting stuck/deadlocked, we get errors such as this in query threads:
```
2024.01.24 16:01:16.251258 [ 430 ] {787da7df-8198-414b-a367-747c96f053d3} <Error> DynamicQueryHandler: Code: 439. DB::Exception: Cannot schedule a task: cannot allocate thread 
```

Co-authored with @nikitamikhaylov - Thank you for the work on this once again, @nikitamikhaylov !

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...
Use scheduleOrThrow in MergeTree data selection and initialization to avoid deadlocks

2024-02-05 12:02 UTC, seandhaynes commented
Hm, this is related: https://s3.amazonaws.com/clickhouse-test-reports/59427/a93fb83cf618e1199527c9a8e59e67e6e69d8fd1/bugfix_validate_check.html

Weird, will take a look.

2024-02-05 18:30 UTC, CheSema commented on src/Databases/DatabaseOnDisk.cpp
> +    const std::chrono::microseconds lock_acquire_timeout_microseconds = std::chrono::seconds{getContext()->getSettingsRef().lock_acquire_timeout};
lets just do
`getContext()->getSettingsRef().lock_acquire_timeout.totalMicroseconds();`

it is a bit tangle how it is converted to std::chrono. `getContext()->getSettingsRef().lock_acquire_timeout` has a type as `SettingFieldTimespan`.

2024-02-05 18:37 UTC, CheSema commented on src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp
> +            SCOPE_EXIT({ pool.wait(); });
Here is an interesting case could be.

`pool.wait();` -- can throw an exception from other failed task. You dont what it when you already got some from `pool.scheduleOrThrow()`.

Just leave that as it was. Than d-tor ThreadPool will wait and mute other exception.

2024-02-08 16:55 UTC, CheSema requested changes
The comments above.

2024-03-21 11:27 UTC, CheSema commented
Any updates?

2024-03-22 13:09 UTC, seandhaynes commented
Thanks for the nudge, @CheSema  and sorry for the delay. I'm addressing your feedback today and will update the PR shortly.

2024-06-05 02:21 UTC, alexey-milovidov approved these changes

2024-06-05 02:24 UTC, alexey-milovidov approved these changes

2024-06-06 00:06 UTC, merged

2024-06-06 09:48 UTC, seandhaynes commented
Thank you for dealing with this, @alexey-milovidov ! Sorry for dropping off it.