Revert "Revert "Poco Logger small refactoring""
ClickHouse/ClickHouse pull request #59564
Opened 2024-02-05 09:33 UTC by kitaisreal

Reverts ClickHouse/ClickHouse#59509

2024-02-05 18:45 UTC, KochetovNicolai approved these changes

2024-02-06 16:39 UTC, Algunenano requested changes
Breaks GRPC with TSAN again (not sure why not other sanitizers):

```
2024.02.05 19:30:53.394507 [ 688 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.02.05 19:30:53.394590 [ 688 ] {} <Fatal> BaseDaemon: (version 24.2.1.1, build id: 9CECEA7C316F7D377B0BB24CD4239DB9D31745F2, git hash: ecee4b2968abe1f252fa4e35641edadb3a407be6) (from thread 687) Received signal 11
2024.02.05 19:30:53.394626 [ 688 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.02.05 19:30:53.394663 [ 688 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.02.05 19:30:53.394701 [ 688 ] {} <Fatal> BaseDaemon: Stack trace: 0x00005618d11a6662 0x00005618e42dfda5 0x00005618e42dd949 0x00005618d95ef0ef 0x00005618d95f4fb2 0x00005618d113480f 0x00007f8edecfdac3 0x00007f8eded8f850
2024.02.05 19:30:53.394761 [ 688 ] {} <Fatal> BaseDaemon: ########################################
2024.02.05 19:30:53.394788 [ 688 ] {} <Fatal> BaseDaemon: (version 24.2.1.1, build id: 9CECEA7C316F7D377B0BB24CD4239DB9D31745F2, git hash: ecee4b2968abe1f252fa4e35641edadb3a407be6) (from thread 687) (no query) Received signal Segmentation fault (11)
2024.02.05 19:30:53.394818 [ 688 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.02.05 19:30:53.394836 [ 688 ] {} <Fatal> BaseDaemon: Stack trace: 0x00005618d11a6662 0x00005618e42dfda5 0x00005618e42dd949 0x00005618d95ef0ef 0x00005618d95f4fb2 0x00005618d113480f 0x00007f8edecfdac3 0x00007f8eded8f850
2024.02.05 19:30:54.000148 [ 656 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 666.43 MiB, peak 666.43 MiB, free memory in arenas 0.00 B, will set to 809.68 MiB (RSS), difference: 143.25 MiB
2024.02.05 19:30:55.000167 [ 656 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 809.68 MiB, peak 809.68 MiB, free memory in arenas 0.00 B, will set to 1003.43 MiB (RSS), difference: 193.75 MiB
2024.02.05 19:30:56.000151 [ 656 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1003.43 MiB, peak 1003.43 MiB, free memory in arenas 0.00 B, will set to 1.21 GiB (RSS), difference: 234.38 MiB
2024.02.05 19:30:56.000257 [ 656 ] {} <Debug> MemoryTracker: Current memory usage (total): 1.21 GiB.
2024.02.05 19:30:57.000158 [ 656 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.21 GiB, peak 1.21 GiB, free memory in arenas 0.00 B, will set to 1.43 GiB (RSS), difference: 226.25 MiB
2024.02.05 19:30:58.000155 [ 656 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.43 GiB, peak 1.43 GiB, free memory in arenas 0.00 B, will set to 1.77 GiB (RSS), difference: 343.63 MiB
2024.02.05 19:30:58.168199 [ 688 ] {} <Fatal> BaseDaemon: 5. __tsan_read8 @ 0x000000000742b662 in /usr/bin/clickhouse
2024.02.05 19:30:58.432486 [ 688 ] {} <Fatal> BaseDaemon: 6.0. inlined from ./contrib/google-protobuf/src/google/protobuf/map.h:800: UntypedMapIterator
2024.02.05 19:30:58.432562 [ 688 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./contrib/google-protobuf/src/google/protobuf/map.h:1290: UntypedMapIterator
2024.02.05 19:30:58.432620 [ 688 ] {} <Fatal> BaseDaemon: 6.2. inlined from ./contrib/google-protobuf/src/google/protobuf/map.h:1343: google::protobuf::Map<String, String>::begin() const
2024.02.05 19:30:58.432648 [ 688 ] {} <Fatal> BaseDaemon: 6.3. inlined from ./build_docker/./src/Server/GRPCServer.cpp:834: DB::(anonymous namespace)::Call::executeQuery()
2024.02.05 19:30:58.432687 [ 688 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Server/GRPCServer.cpp:755: DB::(anonymous namespace)::Call::run() @ 0x000000001a564da5 in /usr/bin/clickhouse
2024.02.05 19:30:58.687610 [ 688 ] {} <Fatal> BaseDaemon: 7.0. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:848: ?
2024.02.05 19:30:58.687670 [ 688 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:1187: ?
2024.02.05 19:30:58.687692 [ 688 ] {} <Fatal> BaseDaemon: 7.2. inlined from ./build_docker/./src/Server/GRPCServer.cpp:744: operator()
2024.02.05 19:30:58.687711 [ 688 ] {} <Fatal> BaseDaemon: 7.3. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
2024.02.05 19:30:58.687781 [ 688 ] {} <Fatal> BaseDaemon: 7.4. inlined from ./contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__apply_tuple_impl[abi:v15000]<DB::(anonymous namespace)::Call::start(std::function<void ()> const&)::$_0&, std::tuple<>&>(DB::(anonymous namespace)::Call::start(std::function<void ()> const&)::$_0&, std::tuple<>&, std::__tuple_indices<>)
2024.02.05 19:30:58.687834 [ 688 ] {} <Fatal> BaseDaemon: 7.5. inlined from ./contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::apply[abi:v15000]<DB::(anonymous namespace)::Call::start(std::function<void ()> const&)::$_0&, std::tuple<>&>(DB::(anonymous namespace)::Call::start(std::function<void ()> const&)::$_0&, std::tuple<>&)
2024.02.05 19:30:58.687855 [ 688 ] {} <Fatal> BaseDaemon: 7.6. inlined from ./src/Common/ThreadPool.h:223: operator()
2024.02.05 19:30:58.687883 [ 688 ] {} <Fatal> BaseDaemon: 7.7. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
2024.02.05 19:30:58.687899 [ 688 ] {} <Fatal> BaseDaemon: 7.8. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: ?
2024.02.05 19:30:58.687916 [ 688 ] {} <Fatal> BaseDaemon: 7.9. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:235: ?
2024.02.05 19:30:58.687934 [ 688 ] {} <Fatal> BaseDaemon: 7. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001a562949 in /usr/bin/clickhouse
2024.02.05 19:30:58.737045 [ 688 ] {} <Fatal> BaseDaemon: 8.0. inlined from ./base/base/../base/wide_integer_impl.h:809: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2024.02.05 19:30:58.737124 [ 688 ] {} <Fatal> BaseDaemon: 8.1. inlined from ./base/base/../base/wide_integer_impl.h:1482: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2024.02.05 19:30:58.737157 [ 688 ] {} <Fatal> BaseDaemon: 8.2. inlined from ./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
2024.02.05 19:30:58.737186 [ 688 ] {} <Fatal> BaseDaemon: 8.3. inlined from ./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
2024.02.05 19:30:58.737213 [ 688 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Common/ThreadPool.cpp:457: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000f8740ef in /usr/bin/clickhouse
2024.02.05 19:30:58.800925 [ 688 ] {} <Fatal> BaseDaemon: 9.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>::reset[abi:v15000](std::__thread_struct*)
2024.02.05 19:30:58.800989 [ 688 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2024.02.05 19:30:58.801009 [ 688 ] {} <Fatal> BaseDaemon: 9.2. inlined from ./contrib/llvm-project/libcxx/include/tuple:265: ~__tuple_leaf
2024.02.05 19:30:58.801027 [ 688 ] {} <Fatal> BaseDaemon: 9.3. inlined from ./contrib/llvm-project/libcxx/include/tuple:538: ~tuple
2024.02.05 19:30:58.801107 [ 688 ] {} <Fatal> BaseDaemon: 9.4. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>::operator()[abi:v15000](std::tuple<std::unique_ptr<std::__thread_struct, std::default_dele [...]

2024-02-10 11:16 UTC, KochetovNicolai commented
02981_vertical_merges_memory_usage is flaky

2024-02-10 11:17 UTC, KochetovNicolai approved these changes

2024-02-10 11:52 UTC, Algunenano approved these changes

2024-02-10 11:53 UTC, merged