Trivial optimize of function coalesce.
ClickHouse/ClickHouse pull request #59627
Opened 2024-02-06 07:06 UTC by taiyang-li

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Reuse the result of `FunctionFactory::instance().get("isNotNull", context)` and `FunctionFactory::instance().get("assumeNotNull", context)`. Make sure it is called once during the lifetime of `FunctionCoalesce`

``` sql 
select coalesce(materialize(null), -1) from numbers(1000000000) format Null settings max_block_size = 8192;  
Old: 0 rows in set. Elapsed: 2.478 sec. Processed 1.00 billion rows, 8.00 GB (403.61 million rows/s., 3.23 GB/s.)
New: 0 rows in set. Elapsed: 2.321 sec. Processed 1.00 billion rows, 8.00 GB (430.86 million rows/s., 3.45 GB/s.)
```

2024-02-06 09:49 UTC, antaljanosbenjamin requested changes

2024-02-06 09:49 UTC, antaljanosbenjamin commented on src/Functions/coalesce.cpp
> +
```suggestion
```

2024-02-06 14:18 UTC, CurtizJ reviewed
You can also optimize https://github.com/ClickHouse/ClickHouse/blob/5a789f5387fd5d81166431e46be81970021101bd/src/Functions/coalesce.cpp#L154-L156

2024-02-07 09:17 UTC, antaljanosbenjamin approved these changes

2024-02-08 02:36 UTC, alexey-milovidov approved these changes

2024-02-14 10:29 UTC, antaljanosbenjamin commented
The test failures are not related, I will merge the PR.

2024-02-14 10:29 UTC, merged