Support sql created named collections in Kafka Storage for librdkafka settings
ClickHouse/ClickHouse pull request #59710
Opened 2024-02-07 12:57 UTC by GrigoryPervakov

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Unify xml and sql created named collection behaviour in kafka storage.

Kafka storage have two types of parameters: storage parameters iteself and settings that would be passed to librdkafka.
Before changes storage paramets applied in both cases, but kafka settings loaded only if named collection was created with xml config.
Changes unifies named collection access and as a bonus allows use new xml named collection without server restart.

Example:
Consider following config
`<clickhouse>
    <named_collections>
        <kafka_config_xml>
            <kafka_broker_list>kafka:19092</broker_list>
            <kafka_topic_list>topic_name</kafka_topic_list>
            <kafka_group_name>group</kafka_group_name>
            <kafka_format>JSONAsString</kafka_format>
            <kafka>
                <security_protocol>SASL_SSL</security_protocol>
                <sasl_mechanisms>'SCRAM-SHA-512</sasl_mechanisms>
                <sasl_username>username</sasl_username>
                <sasl_password>primary_secret_password</sasl_password>
            </kafka>
        </kafka_config_xml>
    </named_collections>
</clickhouse>
`

And queries like
`
CREATE NAMED COLLECTION kafka_config_sql AS
    kafka_security_protocol = 'SASL_SSL',
    kafka_sasl_mechanism = 'SCRAM-SHA-512',
    kafka_sasl_password = 'pswd',
    kafka_sasl_username = 'username
            
    kafka_broker_list = 'kafka:19092',
    kafka_topic_list = 'topic_name',
    kafka_group_name = 'group',
    kafka_format = 'JSONAsString'

CREATE TABLE test.kafka_sql (field String) ENGINE = Kafka(kafka_config_sql);
CREATE TABLE test.kafka_xml (field String) ENGINE = Kafka(kafka_config_xml);
`

Before changes table kafka_sql would not apply first 4 settings and would be unable to auth.
And also it wouldn't read default config, because of specified named collection, so right now kafka storage with sql created named collection is almost not configurable.

2024-02-07 12:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=59710) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=59710) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=59710) it.</sub>

2024-02-12 13:40 UTC, myrrc requested changes

2024-02-12 13:40 UTC, myrrc commented on src/Storages/Kafka/StorageKafka.cpp
> +    void setKafkaConfigValue(LoggerPtr log, cppkafka::Configuration & kafka_config, String key, String value) {
const String& or std::string_view ?

2024-02-12 13:40 UTC, myrrc commented on src/Storages/Kafka/StorageKafka.cpp
> +    void loadFromConfig(LoggerPtr log, cppkafka::Configuration & kafka_config, const Poco::Util::AbstractConfiguration & config, String collection_name, const String & config_prefix)
const String & collection_name ?
Or std::string_view

2024-02-12 13:40 UTC, myrrc commented on src/Storages/Kafka/StorageKafka.cpp
> +                const String setting_path = config_prefix + "." + tag;
`fmt::format("{}.{}", config_prefix, tag)`

2024-02-21 17:04 UTC, myrrc reviewed
LGTM

2024-02-21 17:04 UTC, myrrc commented on src/Storages/Kafka/StorageKafka.cpp
> +        }
`return` and deindent else block.

2024-02-21 17:04 UTC, myrrc commented on src/Storages/Kafka/StorageKafka.cpp
> +                if (!key.starts_with(fmt::format("{}.{}", config_prefix, CONFIG_KAFKA_TOPIC_TAG)))
fmt::format expression can be calculated before for loop

2024-02-26 16:11 UTC, kssenii commented on src/Storages/Kafka/StorageKafka.cpp
> +            for (const auto & key : collection->getKeys(-1, config_prefix)) {
```suggestion
            for (const auto & key : collection->getKeys(-1, config_prefix)) 
            {
```

2024-02-26 16:11 UTC, kssenii commented on src/Storages/Kafka/StorageKafka.cpp
> +                const String kafpa_topic_name_path = kafka_topic_path + "." + CONFIG_NAME_TAG;
```suggestion
                const String kafka_topic_name_path = kafka_topic_path + "." + CONFIG_NAME_TAG;
```

2024-02-27 02:59 UTC, kssenii approved these changes

2024-02-28 15:38 UTC, merged