DOCAPI-7415: Docs for the -Resample aggregate function combinator.
ClickHouse/ClickHouse pull request #5972
Opened 2019-07-11 10:37 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation for #5590.

2019-07-31 18:45 UTC, BayoNet commented
@blinkov Do you have any comments?

2019-08-12 09:12 UTC, blinkov requested changes

2019-08-12 09:12 UTC, blinkov commented on docs/en/query_language/agg_functions/combinators.md
> +Allows to aggregate data, separating them into intervals.
this sentence sounds confusing and hardly makes it possible to understand the feature without reading further, let's make it more detailed?

2019-08-12 09:12 UTC, blinkov commented on docs/en/query_language/agg_functions/combinators.md
> +- `start` — Starting value of the whole required interval for the values of `resampling_key`.
* Starting/ending or start/end
* We need to mention whether those borders are inclusive or not

2019-08-12 09:12 UTC, blinkov commented on docs/en/query_language/agg_functions/combinators.md
> +- `step` — Step for separating the whole interval by subintervals. The `aggFunction` is executed over these subintervals.
...over each of those subintervals independently?

2019-08-12 09:12 UTC, blinkov commented on docs/en/query_language/agg_functions/combinators.md
> +What do we see in the result?
do we use this question style in docs?

2019-08-12 09:12 UTC, blinkov commented on docs/en/query_language/agg_functions/combinators.md
> +`Jonh` is out of the sample because he is too young. Other persons are distributed according to the specified age intervals.
persons -> people?

2019-08-15 10:09 UTC, merged