DOCAPI-3933: EN review and RU translation of hash functions doc
ClickHouse/ClickHouse pull request #5980
Opened 2019-07-11 15:49 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation

2019-07-12 12:02 UTC, blinkov requested changes

2019-07-12 12:02 UTC, blinkov commented on docs/ru/query_language/functions/hash_functions.md
> +Генерирует 64-х битный хэш.
в других функциях ссылка на алгоритм и его упоминание прямо в первом предложении, а тут слишком получилось

2019-07-12 12:02 UTC, blinkov commented on docs/ru/query_language/functions/hash_functions.md
> +Дополнительную информацию смотрите по ссылке: [JavaHash](http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/478a4add975b/src/share/classes/java/lang/String.java#l1452)
непонятно почему не сделать ссылкой JavaHash двумя строками выше

2019-07-12 12:02 UTC, blinkov commented on docs/ru/query_language/functions/hash_functions.md
> +Работает аналогично [JavaHash](#hash_functions-javahash), за исключением того, что возвращаемое значение не может быть отрицательным.
нужно уточнение почему оно называется HiveHash

2019-07-25 08:23 UTC, KochetovNicolai commented on docs/ru/query_language/functions/hash_functions.md
> +SELECT sum(cityHash64(*)) FROM table
`SELECT groupBitXor(cityHash64(*)) FROM table`

2019-07-25 10:14 UTC, merged