L10n/docapi 6889 dict get
ClickHouse/ClickHouse pull request #5989
Opened 2019-07-12 05:32 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation for #5394

2019-07-12 12:23 UTC, blinkov requested changes

2019-07-12 12:23 UTC, blinkov commented on docs/en/query_language/functions/ext_dict_functions.md
> +All these functions take the `OrDefault` modifier. For example, `dictGetDateOrDefault`.
"have" sounded better

2019-07-12 12:23 UTC, blinkov commented on docs/ru/query_language/functions/ext_dict_functions.md
> +- Если ClickHouse успешно обработал атрибут в соответствии с  [заданным типом данных](../dicts/external_dicts_dict_structure.md#ext_dict_structure-attributes), то функции возвращают значение атрибута
* двойной пробел
* «успешно обработал атрибут» коряво звучит

2019-07-12 12:23 UTC, blinkov commented on docs/ru/query_language/functions/ext_dict_functions.md
> +- Если запрошенного `id_expr` в словаре нет, то:
кажется, тут не особо хорошо ссылаться на id_expr, т.к. речь не о самом выражении, а о его результате (ключе)

2019-07-12 12:23 UTC, blinkov commented on docs/ru/query_language/functions/ext_dict_functions.md
> +Иерархия ключей словаря.
думаю стоит уточнить в каком порядке ключи оказываются в массиве

2019-07-12 12:23 UTC, blinkov commented on docs/ru/query_language/functions/ext_dict_functions.md
> +Проверяет предка ключа в иерархическом словаре.
не очевидно речь только о непосредственном предке или о нахождении в цепочке родителей

2019-07-26 06:36 UTC, BayoNet commented on docs/ru/query_language/functions/ext_dict_functions.md
> +Иерархия ключей словаря.
Это в описании самой функции есть.

2019-07-26 06:38 UTC, BayoNet commented on docs/ru/query_language/functions/ext_dict_functions.md
> +Проверяет предка ключа в иерархическом словаре.
@4ertus2 ?

2019-07-31 14:45 UTC, merged