docs: add ckman to gui documents
ClickHouse/ClickHouse pull request #60394
Opened 2024-02-26 06:28 UTC by YenchangChan

### Changelog category (leave one):
- New Feature
- Improvement
- Performance Improvement
- Backward Incompatible Change
- Build/Testing/Packaging Improvement
- Documentation (changelog entry is not required)
- Bug Fix (user-visible misbehavior in an official stable release)
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2024-02-26 06:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=60394) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=60394) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=60394) it.</sub>

2024-02-27 09:31 UTC, mshustov approved these changes

2024-02-27 11:38 UTC, Algunenano commented on docs/en/interfaces/third-party/gui.md
> +
Missing header to differentiate from the tool above

2024-02-27 15:44 UTC, Algunenano approved these changes

2024-02-27 18:46 UTC, Algunenano requested changes
https://s3.amazonaws.com/clickhouse-test-reports/60394/dfe56297867065ba7f96af37cad291132eaaa201/style_check/docs_spelling_output.txt

```
====== /ClickHouse/docs/en/interfaces/third-party/gui.md ======
ckman
CKMAN
====== Errors found ======
To exclude some words add them to the dictionary file "/ClickHouse/utils/check-style/aspell-ignore/en/aspell-dict.txt"
You can also run ./check-doc-aspell -i to see the errors interactively and fix them or add to the dictionary file
```

2024-02-28 15:09 UTC, Algunenano approved these changes

2024-02-28 15:17 UTC, merged