Add test that validates attach partition fails if structure differs because of materialized column
ClickHouse/ClickHouse pull request #60418
Opened 2024-02-26 14:24 UTC by arthurpassos

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add test that validates attach partition fails if structure differs because of materialized column

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2024-02-27 18:49 UTC, Algunenano requested changes
Please create a new file to add new tests. It makes it simpler to track and test them individually.

2024-02-27 18:49 UTC, Algunenano commented on tests/queries/0_stateless/02888_attach_partition_from_different_tables.sql
> +ALTER TABLE attach_partition_t8 ATTACH PARTITION ID '1' FROM attach_partition_t7; -- {serverError 122};
```suggestion
ALTER TABLE attach_partition_t8 ATTACH PARTITION ID '1' FROM attach_partition_t7; -- {serverError INCOMPATIBLE_COLUMNS};
```

2024-02-27 19:02 UTC, arthurpassos commented on tests/queries/0_stateless/02888_attach_partition_from_different_tables.sql
> +ALTER TABLE attach_partition_t8 ATTACH PARTITION ID '1' FROM attach_partition_t7; -- {serverError 122};
Done

2024-02-29 15:46 UTC, Algunenano approved these changes

2024-02-29 15:47 UTC, merged