Fix boundRatio incorrect merge
ClickHouse/ClickHouse pull request #60532
Opened 2024-02-29 04:02 UTC by wangtZJU

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2024-02-29 08:07 UTC, alexey-milovidov commented
Missing tests. Missing comments.

2024-02-29 10:24 UTC, wangtZJU commented
Hi @alexey-milovidov , the problem is that when `other.empty` = true, the original code will still use the `other.left.x`(which may be any arbitrary value) to update self's state.

I can reproduce it in a 2-nodes cluster,
```sql
-- this case mimic CI test 00715_bounding_ratio 
--
-- in node 1, run below queries
create table rate_test on cluster my_cluster (timestamp UInt32, event UInt32) engine=Memory;
insert into rate_test values (0,1000),(1,1001),(2,1002),(3,1003),(4,1004),(5,1005),(6,1006),(7,1007),(8,1008);
create table rate_test_dist (timestamp UInt32, event UInt32) engine=Distributed(my_cluster, currentDatabase(), 'rate_test');

select boundingRatio(timestamp, event) from rate_test;  -- output: 1
select boundingRatio(timestamp, event) from rate_test_dist; -- output: 126
```
but i don't know how to implement this in CI

2024-03-02 10:37 UTC, UnamedRus commented
Probably, even more "interesting" output
https://fiddle.clickhouse.com/f42759d4-6cbd-4a3d-9261-da6fe6e654a7

2024-03-02 17:09 UTC, alexey-milovidov commented
@wangtZJU, Write tests. Write comments. Write changelog entry.

2024-03-04 14:24 UTC, wangtZJU commented
tests and changelog entry are added

2024-03-05 04:42 UTC, alexey-milovidov approved these changes

2024-03-05 04:42 UTC, alexey-milovidov commented
Thank you!

2024-03-21 22:28 UTC, alexey-milovidov requested changes

2024-03-21 22:28 UTC, alexey-milovidov commented on src/AggregateFunctions/AggregateFunctionBoundingRatio.cpp
> +        {
It still lacks comments.

2024-03-21 22:28 UTC, alexey-milovidov commented on tests/queries/0_stateless/00715_bounding_ratio.sql
> +create table rate_test2 (timestamp UInt32, event UInt32) engine=Memory;
It should be added as a new test. The old test should remain untouched.

2024-03-21 22:28 UTC, alexey-milovidov commented
@wangtZJU,
> tests and changelog entry are added

But we also need comments in the code.
Writing code without comments is a crime.

2024-04-08 06:40 UTC, wangtZJU commented
@alexey-milovidov fixed

2024-04-27 21:55 UTC, alexey-milovidov approved these changes

2024-05-03 01:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=60532) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=60532) before we can accept your contribution.<br/>**15** out of **16** committers have signed the CLA.<br/><br/>:white_check_mark: larry-cdn77<br/>:white_check_mark: alesapin<br/>:white_check_mark: SmitaRKulkarni<br/>:white_check_mark: alexey-milovidov<br/>:white_check_mark: rschu1ze<br/>:white_check_mark: antaljanosbenjamin<br/>:white_check_mark: Algunenano<br/>:white_check_mark: yariks5s<br/>:white_check_mark: jrdi<br/>:white_check_mark: davenger<br/>:white_check_mark: CheSema<br/>:white_check_mark: kssenii<br/>:white_check_mark: thevar1able<br/>:white_check_mark: vdimir<br/>:white_check_mark: evillique<br/>:x: Naartti<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=60532) it.</sub>

2024-05-03 02:13 UTC, merged