Russian documentation about functions for working with external dictionaries
ClickHouse/ClickHouse pull request #6059
Opened 2019-07-18 21:19 UTC by izebit

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

It is a translation of an English version

2019-07-18 21:30 UTC, blinkov requested changes

2019-07-18 21:30 UTC, blinkov commented on docs/ru/query_language/functions/ext_dict_functions.md
> +                <Тип>UInt32</Тип>
зря переведено

2019-07-18 21:30 UTC, blinkov commented on docs/ru/query_language/functions/ext_dict_functions.md
> +    toТипName(val) AS Тип
лишний перевод

2019-07-18 21:30 UTC, blinkov commented on docs/ru/query_language/functions/ext_dict_functions.md
> +┌─val─┬─Тип───┐
лишний перевод

2019-07-18 21:30 UTC, blinkov commented on docs/ru/query_language/functions/ext_dict_functions.md
> +Проверяет наличие строки с заданным ключом в словаре.
строки -> записи?

2019-07-18 21:30 UTC, blinkov commented on docs/ru/query_language/functions/ext_dict_functions.md
> +Для иерархических словарей, возвращает массив ключей, содержащий ключ `id_expr` и все ключи родительских элементов по цепочке.
кажется, первая запятая лишняя

2019-07-18 21:30 UTC, blinkov commented on docs/ru/query_language/functions/ext_dict_functions.md
> +Осуществляет проверку - является ли ключ родительским в иерархии словаря.
не понятно речь только о прямом родителе или о всей цепочке родителей

2019-07-18 21:30 UTC, blinkov commented on docs/ru/query_language/functions/ext_dict_functions.md
> +[Оригинальная статья](https://clickhouse.yandex/docs/en/query_language/functions/ext_dict_functions/) <!--hide-->
.../docs/**ru**/...

2019-07-18 21:37 UTC, izebit commented on docs/ru/query_language/functions/ext_dict_functions.md
> +    toТипName(val) AS Тип
Упс, надо было поаккуратнее заменой)

2019-07-18 22:08 UTC, merged

2019-07-22 19:22 UTC, BayoNet commented
Этот пулл решает ту же задачу, что и более ранний https://github.com/yandex/ClickHouse/pull/5989/. Я разрешу конфликты и возьму лучшее из обоих.