Make csv write string in quote configurable
ClickHouse/ClickHouse pull request #60737
Opened 2024-03-04 04:10 UTC by shuai-xu

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add a config to control whether write string in quote for CSV format

### Documentation entry for user-facing changes

This pr add a config to control whether write string in quote for CSV format. Now CSV will write string in quote, this is conflicing with hive, and we hope it is configurable. 

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2024-03-04 04:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=60737) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=60737) before we can accept your contribution.<br/><hr/>**shuai-xu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=60737) it.</sub>

2024-03-04 05:01 UTC, alexey-milovidov commented
Need to sign a CLA.
Need to write a test.

2024-03-05 01:56 UTC, alexey-milovidov commented
^

2024-03-07 10:04 UTC, shuai-xu commented
@alexey-milovidov In fact, this issue is that clickhouse output csv in format such like `"20240305",1,"['s','d']","{'a':2}","(123567,'e01001',{'action':33333})"`, but hive write csv like 
<img width="641" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/20960838/fced26a4-30ce-4249-831a-8440e77cc460">
, we need to let clickhouse compatiable with hive in our production. But I see it needs a lot to do as now clickhouse hard code the delimiters and so on. So will the clickhouse community consider let csv format support compatiable with hive? If so, I will continue working on it.

2024-03-09 08:00 UTC, alexey-milovidov commented
@shuai-xu, It looks like the `CustomSeparated` format.

2024-03-11 07:14 UTC, shuai-xu commented
> @shuai-xu, It looks like the `CustomSeparated` format.

Yes, it looks like CustomSeparated, but not fully supported since map has to in the '{}', and so do array/tuple.

2024-03-21 22:24 UTC, alexey-milovidov commented on tests/queries/0_stateless/00300_csv.reference
> +"Hello, ""World""",123,"[1,2,3]","(456,['abc','def'])","Newline
Old tests should not be modified.

2024-03-21 22:24 UTC, alexey-milovidov requested changes
Maybe better to add it as a new format? What is the name for it?

2024-03-28 07:48 UTC, shuai-xu commented
> Maybe better to add it as a new format? What is the name for it?

Maybe HiveTextOutputFormat?

2024-04-11 09:55 UTC, shuai-xu commented
I added the HiveTextRowOutputFormat to support write as hive

2024-04-24 02:20 UTC, shuai-xu commented
@alexey-milovidov can you help to review this pr?

2024-05-09 01:06 UTC, shuai-xu commented
@alexey-milovidov Tests have passed, the failed one seems not related to this pr.

2025-10-25 13:08 UTC, alexey-milovidov commented on src/DataTypes/Serializations/SerializationVariant.cpp
> +    throw Exception(ErrorCodes::NOT_IMPLEMENTED, "Method serializeTextHive is not implemented for Variant");
It could be.

2025-10-25 13:10 UTC, alexey-milovidov commented
@shuai-xu, please allow edits in your branch.

2026-06-29 03:39 UTC, alexey-milovidov commented
Continued in https://github.com/ClickHouse/ClickHouse/pull/107582

2026-06-29 03:39 UTC, closed without merging