L10n/docapi 7063
ClickHouse/ClickHouse pull request #6142
Opened 2019-07-24 17:33 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation for #5535.

2019-07-24 18:34 UTC, blinkov requested changes

2019-07-24 18:34 UTC, blinkov commented on docs/ru/query_language/functions/bitmap_functions.md
> +Проверяет вхождение элемента в битовый массив.
кажется ни к чему тут пытаться вводить синонимы, если делать битовый массив, то везде

2019-07-24 18:34 UTC, blinkov commented on docs/ru/query_language/functions/bitmap_functions.md
> +Если вы уверены, что `bitmap2` содержит строго один элемент, используйте функцию  [bitmapContains](#bitmap_functions-bitmapcontains). Она работает эффективнее.
давайте всё же исправим то место, откуда берутся двойные пробелы? надоело через раз о них писать...

2019-07-30 06:45 UTC, BayoNet commented on docs/ru/query_language/functions/bitmap_functions.md
> +Проверяет вхождение элемента в битовый массив.
Поправил по всему файлу.

2019-07-30 06:45 UTC, BayoNet commented on docs/ru/query_language/functions/bitmap_functions.md
> +Если вы уверены, что `bitmap2` содержит строго один элемент, используйте функцию  [bitmapContains](#bitmap_functions-bitmapcontains). Она работает эффективнее.
Место поправится не скоро, к сожалению. Я постараюсь за ними повнимательнее следить.

2019-07-30 06:47 UTC, merged