T64 codec description
ClickHouse/ClickHouse pull request #6149
Opened 2019-07-25 11:13 UTC by 4ertus2

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Other

Short description (up to few sentences):

2019-07-25 11:24 UTC, blinkov requested changes

2019-07-25 11:24 UTC, blinkov commented on docs/en/query_language/create.md
> +- `T64` — compression approach that croppes unused most significant bits in numeric data (including Enums, Date and DateTime). Bits that are not differs between min and max value in part are cropped.
* cropped -> crops
* are not differs -> do not differ

2019-07-25 11:24 UTC, blinkov commented on docs/en/query_language/create.md
>  - `Delta(delta_bytes)` — compression approach, when raw values are replaced with the difference of two neighbour values. Up to `delta_bytes` are used for storing delta value, so `delta_bytes` is a ma
Maybe indeed let's rename them from "compression approach" to "data preparation approach" like you did in Russian version? And explicitly say that such preprocessed sequences then often compress better using general purpose compression.

2019-07-25 11:24 UTC, blinkov commented on docs/ru/query_language/create.md
> +Алгоритм сжатия берет 64 входных значения, записывает их в битовую матрицу 64х64, транспонирует ее и выдает обрезанную на незначащие биты последовательность.
эта часть потерялась в английской версии

2019-07-25 12:03 UTC, 4ertus2 commented
@BayoNet Предлагаю взять этот PR за основу, закрыть его и сделать правильный. Готов проконсультировать в чатике или лично.

2019-07-26 12:40 UTC, BayoNet commented
Да. Давай так и сделаем.

2019-08-05 16:27 UTC, 4ertus2 commented
Continuation #6347

2019-08-05 16:27 UTC, closed without merging