Fix addDays cause an error when used datetime64
ClickHouse/ClickHouse pull request #61561
Opened 2024-03-19 05:53 UTC by loneylee

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the issue where the function `addDays` reports an error when the first parameter is datetime64.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

Not needed.

2024-03-19 11:19 UTC, antaljanosbenjamin requested changes

2024-03-19 11:19 UTC, antaljanosbenjamin commented on tests/queries/0_stateless/03013_addDays_with_timezone.sql
> +select addDays(toDateTime64('2024-01-01', 6), 10, 'Asia/Shanghai');
```suggestion
select addDays(toDateTime64('2024-01-01', 6), 10, 'Asia/Shanghai');

```

Just a trailing new line.

2024-03-20 11:01 UTC, antaljanosbenjamin approved these changes

2024-03-21 13:47 UTC, merged

2026-05-03 07:04 UTC, clickgapai commented
Hi @loneylee @antaljanosbenjamin — while reviewing this PR I found the following:

- **Coverage gap:** `addMilliseconds`/`addMicroseconds`/`addNanoseconds` (and subtract counterparts) untested with `DateTime64` + timezone (3-arg form) — https://github.com/ClickHouse/ClickHouse/pull/103934

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.