Improve json earch row read by ignore key case
ClickHouse/ClickHouse pull request #61750
Opened 2024-03-22 07:38 UTC by KevinyhZou

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Somethimes we insert data to a table from json file, if the table's column name is not match the field name of json because of letter case problem,  then the column can not be read, such as we have a json file that schema is (id UInt32, reqId UInt64, name String),  and the table schema is (id UInt32, reqid UInt64, name String), then the field `reqId` can not be read.

So we introduce a config to ignore the case problem in such suitation.
 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Set desired options before CI starts or re-push after updates

#### Run only:
- [ ]  Integration tests
- [ ]  Integration tests (arm64)
- [ ]  Stateless tests (release)
- [ ]  Stateless tests (asan)
- [ ]  Stateful tests (release)
- [ ]  Stateful tests (asan)
- [ ]  No sanitizers
- [ ]  Tests with analyzer
- [ ]  Fast tests
- [ ]  Only package_debug build
- [ ]  Add your CI variant description here

#### CI options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

2024-03-22 17:53 UTC, divanik requested changes

2024-03-22 17:53 UTC, divanik commented on src/Processors/Formats/Impl/JSONEachRowRowInputFormat.cpp
> +            transformFieldNameToLowerCase(key);
As it seems to me, you try to mutate key of a hash table while iterating on it. Usually mutating of a key breaks insides of an iterator of a data structure

2024-03-22 17:53 UTC, divanik commented on src/Processors/Formats/Impl/JSONEachRowRowInputFormat.h
> +        char * name_data = const_cast<char*>(field_name.data);
I think that const_cast is a not good idea when you are trying to mutate sth that you don't own. I suggest the following: if key ignore_key_case is set to True, we will create map from the lower_case versions names to the actual names, and make more profound check while finding the column_name in our set

2024-03-25 12:35 UTC, divanik approved these changes

2024-03-26 01:01 UTC, alexey-milovidov commented
I like the idea, but I'd prefer a few things differently:

1. It should apply to all data formats with names, such as CSVWithNames, Protobuf, Avro, Parquet, and even Native.
2. The modes should be match case, ignore case, and auto. The auto mode will search for a matching column case insensitive if the direct match isn't found. In contrast, the case insensitive mode should throw an exception if the data contain ambiguous names.

2024-03-26 11:22 UTC, Avogar commented on src/Core/Settings.h
> +    M(Bool, input_format_json_ignore_key_case, false, "Ignore json key case while read json field from string", 0) \
Please, add this new setting to SettingsChangesHistory.h

2024-03-26 11:29 UTC, Avogar commented on tests/queries/0_stateless/02995_baseline_23_12_1.tsv
> +input_format_json_ignore_key_case	0
That's not right, this setting didn't exist in 23.12 version, please, don't change this file and add new setting to SettingsChangesHistory.h

2024-03-26 11:52 UTC, KevinyhZou commented
done @Avogar

2024-03-29 01:53 UTC, KevinyhZou commented
Could this pr be merged ? and support for other formats and modes can be later @divanik @alexey-milovidov

2024-04-03 05:09 UTC, alexey-milovidov commented
It does not build, and the tests don't pass.

> Could this pr be merged ? and support for other formats and modes can be later

Not later. The code should be complete and consistent. The user experience should be flawless.

2024-04-03 06:37 UTC, KevinyhZou commented
OK

2024-06-26 01:28 UTC, alexey-milovidov commented
This is a good change - please resolve conflicts and merge.

2024-06-27 23:38 UTC, al13n321 commented
Test failures look unrelated:
 * 01158_zookeeper_log_long - flaky [1]
 * 02931_rewrite_sum_column_and_constant - https://github.com/ClickHouse/ClickHouse/pull/65800
 * performance comparison - shows lots of weird errors, it does that often these days, didn't investigate

[1] https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcHVsbF9yZXF1ZXN0X251bWJlciwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIElOVEVSVkFMIDcgZGF5CiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgYW5kIHRlc3RfbmFtZSBsaWtlICclMDExNThfem9va2VlcGVyX2xvZ19sb25nJScKT1JERVIgQlkgYWxs

2024-06-28 00:36 UTC, merged

2024-07-01 18:08 UTC, Algunenano commented on src/Core/SettingsChangesHistory.h
> +              {"input_format_json_ignore_key_case", false, false, "Ignore json key case while read json field from string."},
This should be 24.7

2024-07-30 09:35 UTC, alexey-milovidov commented
It is implemented not like we needed. Let's revert.

2024-07-30 09:38 UTC, alexey-milovidov commented on src/Processors/Formats/Impl/JSONEachRowRowInputFormat.h
> +    std::unordered_map<String, StringRef> lower_case_name_map;
This is very bad.

2024-07-30 09:38 UTC, alexey-milovidov commented on src/Processors/Formats/Impl/JSONEachRowRowInputFormat.h
> +            [](unsigned char c) { return std::tolower(c); });
This is wrong.

2024-07-30 09:40 UTC, alexey-milovidov commented
This will be reverted, because the review is not addressed: https://github.com/ClickHouse/ClickHouse/pull/61750#issuecomment-2019201049

2024-08-08 12:42 UTC, KevinyhZou commented
would you open another pr to slove this problem? @alexey-milovidov

2024-08-08 17:19 UTC, alexey-milovidov commented
We should do it, but I didn't plan it for the next days. It will be very helpful if you resumbit.