New analyzer pass to simplify case when
ClickHouse/ClickHouse pull request #61919
Opened 2024-03-26 08:06 UTC by liuneng1994

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Simply case when clause to get better performance

In some case we can simplify case when to use primary key index.
example:
```
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) = 1
```
=>
```
select * from test where x = 'a'
```

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2024-03-27 07:51 UTC, liuneng1994 commented
There are too many bugs and I need to reconsider the implementation method.

2024-05-06 11:06 UTC, novikd requested changes
The provided test doesn't use the new infrastructure. Please, fix it. Also, I think it's useful to add a performance test.
The implementation requires to have more comments because it's hard to read now.

2024-05-06 11:06 UTC, novikd commented on src/Analyzer/Passes/CaseWhenSimplifyPass.cpp
> +                has_else = false;
Why?

2024-05-15 02:07 UTC, liuneng1994 commented
Sorry, this optimization still requires a lot of work to be perfect. I don’t have more energy to spend on it at the moment.

2024-05-15 02:07 UTC, closed without merging