Fix queries with FINAL give wrong result when table does not use adaptive granularity
ClickHouse/ClickHouse pull request #62432
Opened 2024-04-09 09:57 UTC by canhld94

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix queries with FINAL give wrong result when table does not use adaptive granularity

Close #62426

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

2024-04-09 10:15 UTC, kitaisreal requested changes

2024-04-09 10:15 UTC, kitaisreal commented on tests/queries/0_stateless/03033_final_undefined_last_mark.sql
> +SELECT 'GOOD', * FROM account_test FINAL WHERE id = 11338881281426660955 SETTINGS split_parts_ranges_into_intersecting_and_non_intersecting_final = 1;
It is better to add another query in test:
```
SELECT 'GOOD', * FROM account_test FINAL WHERE id = 11338881281426660955 SETTINGS split_parts_ranges_into_intersecting_and_non_intersecting_final = 0;
```
So it is easier to compare outputs.

2024-04-10 16:39 UTC, kitaisreal approved these changes

2024-04-18 02:47 UTC, canhld94 commented
AST Fuzzer test is failing, but I think it doesn't relates to the change this PR. Can reproduce in upstream `HEAD` even when turning off splitting parts https://fiddle.clickhouse.com/d5c476f8-9fb9-4ee1-bf10-0491e173bafb

2024-04-18 02:52 UTC, canhld94 commented
> AST Fuzzer test is failing, but I think it doesn't relates to the change this PR. Can reproduce in upstream `HEAD` even when turning off splitting parts https://fiddle.clickhouse.com/d5c476f8-9fb9-4ee1-bf10-0491e173bafb
> 
> Update: even without `FINAL`

#62741

2024-04-18 02:56 UTC, canhld94 commented
Stress test failure relates to  database replicated #62742

2024-04-28 00:49 UTC, canhld94 commented
Ping @Algunenano I think this PR is ready to merge

2024-04-28 02:12 UTC, alexey-milovidov commented
@canhld94, what is with these logical errors detected by our fuzzers?

2024-04-28 02:36 UTC, canhld94 commented
> @canhld94, what is with these logical errors detected by our fuzzers?

@alexey-milovidov this is a known bug, I opened an issue for it https://github.com/ClickHouse/ClickHouse/pull/62432 and have an attempt to fix in https://github.com/ClickHouse/ClickHouse/pull/62776 but not yet found  a good approach.

2024-05-22 15:34 UTC, Algunenano commented
Sorry for the delay reviewing this. Initially it slipped through the cracks and then I got sidetracked by bugs in related code (but not in this PR). I've simplified the test so it doesn't depend on generateRandom and updated with master to make sure things are still ok.

2024-05-23 09:20 UTC, canhld94 commented
> Sorry for the delay reviewing this. Initially it slipped through the cracks and then I got sidetracked by bugs in related code (but not in this PR). I've simplified the test so it doesn't depend on generateRandom and updated with master to make sure things are still ok.

Thanks! Nevertheless, the AST fuzzer failure is still there, not causing by this PR but merging this PR will reproduce the failure in master. May be we need to push to fix this bug soon.

2024-05-23 09:29 UTC, merged