try test hualloc
ClickHouse/ClickHouse pull request #62942
Opened 2024-04-25 00:48 UTC by no-1dea

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Trying to use hualloc instead of jemalloc, measuring perf.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2024-04-25 00:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=62942) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=62942) before we can accept your contribution.<br/><hr/>**n0-1dea** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=62942) it.</sub>

2024-04-25 12:57 UTC, Algunenano requested changes
Seems like you forgot to push the submodule (`contrib/oneTBB`)

2024-04-25 14:44 UTC, no-1dea commented
> Seems like you forgot to push the submodule (`contrib/oneTBB`)

I think there is another problem. This PR for hualloc, so no need for oneTBB, I just have forgotten to delete it.

2024-06-17 17:20 UTC, Algunenano commented
It never built

2024-06-17 17:20 UTC, closed without merging