[feature]: allow to attach parts from a different disk (v2.0)
ClickHouse/ClickHouse pull request #63087
Opened 2024-04-28 13:30 UTC by Unalian

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow to attach parts from a different disk
*  attach partition from the table on other disks using copy instead of hard link (such as instant table)
*  attach partition using copy when the hard link fails even on the same disk

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)
- Motivation: 
Allow to attach parts from a different disk: 
attach partition from the table on other disks using copy instead of hard link (such as instant table)
attach partition using copy when the hard link fails even on the same disk
mergetree and replicatedMergeTree Engineer can both support this feature

- Example use: 
The source table can be an instant table like here: https://github.com/ClickHouse/web-tables-demo 
Create a destination table with the same structure with source table. Then we can run:
```sql
ALTER TABLE destination ATTACH PARTITION tuple() FROM source
```
The destination table can attach the partition from source table even though the source table is an instant table.

### Test
1. The integration test is written in test_attach_partition_using_copy:
* test_both_mergtree: Attach data from source table(instant table) on replica1 to destination table on replica1. Both are mergetree engine tables.
* test_all_replicated: Attach data from source table(instant table) on replica1 to destination table on replica1, verify whether destination table on replica2 and source table on replica1 are the same. The three tables are all ReplicatedMergetree tables.
* test_only_destination_replicated: Attach data from source table(instant table) on replica1 to destination table on replica2, verify whether destination table on replica2 and source table on replica1 are the same. The destination tables are ReplicatedMergetree tables.
* test_not_work_on_different_disk : Replace and move partition don't work when on different disks.

2/ The integration test tests/integration/test_multiple_disks/test.py::test_move_across_policies_not_work shows attach fail when on the different disks. Change this case.

### Additional information
This PR used to be merged in https://github.com/ClickHouse/ClickHouse/pull/60112. However, there are some problems after merged: 
https://github.com/ClickHouse/ClickHouse/issues/62283
<img width="954" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/54164389/1d96e3eb-6f09-4a82-8f4d-ce3cda251a10">

<img width="1030" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/54164389/b83f3f78-962e-4a78-ba84-39a1a22dac7e">
These problems have been fixed in this pr.

2024-04-30 03:35 UTC, Unalian commented
I have no idea why this stateless test case failed. It seems like it has nothing to do with my codes. 
029920.sql: 
```sql
SYSTEM FLUSH LOGS;
SELECT 'Column ' || name || ' from table ' || concat(database, '.', table) || ' should have a comment'
FROM system.columns
WHERE (database = 'system') AND (comment = '') AND (table NOT ILIKE '%_log_%') AND (table NOT IN ('numbers', 'numbers_mt', 'one', 'generate_series', 'generateSeries')) AND (default_kind != 'ALIAS');
```
<img width="1727" alt="企业微信截图_55d31be6-47a0-41f0-991c-613995ff37e1" src="https://github.com/ClickHouse/ClickHouse/assets/54164389/04054719-affb-484e-8b85-866bdd9a59f6">

2024-05-07 15:41 UTC, tavplubix requested changes

2024-05-07 15:41 UTC, tavplubix commented on src/Storages/MergeTree/remoteBackup.cpp
It's 90% copy-paste from `localBackup.cpp`. Let's avoid copy-paste and make `localBackup.cpp` work with two disks. We can pass src and dst disks to `localBackup` as 2 separate arguments, so it will be able to check if it's the same disk or not. And if it's not the same, it will copy from one disk to another.

2024-05-07 15:41 UTC, tavplubix commented on src/Storages/MergeTree/MergeTreeData.cpp
> +    const WriteSettings & write_settings)
Smae, let's avoid copy-paste

2024-05-07 15:43 UTC, tavplubix commented
> I have no idea why this stateless test case failed. It seems like it has nothing to do with my codes.

Yes, it was broken in master for a while

2024-05-24 02:35 UTC, Unalian commented
@tavplubix @alexey-milovidov  Is there anything else that needs to be modified in this PR? Please let me know if you still have any questions.

2024-05-28 21:15 UTC, tavplubix approved these changes

2024-05-28 21:15 UTC, tavplubix commented on src/Storages/MergeTree/DataPartStorageOnDiskBase.cpp
> +        {},
Please add comments with the argument names (like `/* max_level= */ {}`)

2024-06-03 18:20 UTC, tavplubix commented
Integration tests (aarch64) [5/6] - https://github.com/ClickHouse/ClickHouse/issues/64451
Stateless tests (debug, s3 storage) [1/6] - https://github.com/ClickHouse/ClickHouse/issues/50911
Stateless tests (msan) [6/6] - https://github.com/ClickHouse/ClickHouse/pull/64765
Stress test (tsan) - timeout in `DistributedAsyncInsertDirectoryQueue` is too big
Upgrade check - was broken by new release

2024-06-04 14:20 UTC, merged

2024-07-03 14:08 UTC, Algunenano commented
> Hi, will this be backported to 24.3+ where the feature was originally added?

No, features are not backported. Even if it's reintroducing a feature that was removed