Added optional message argument in throwIf (#5772)
ClickHouse/ClickHouse pull request #6329
Opened 2019-08-04 23:28 UTC by Vdimir

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Improvement

New optional argument added to `throwIf`. It must be constant string and shown instead of standard exception message

2019-08-04 23:40 UTC, alexey-milovidov commented on dbms/src/Functions/throwIf.cpp
>          return 1;
Please change to zero.

2019-08-04 23:41 UTC, alexey-milovidov commented on dbms/src/Functions/throwIf.cpp
>      bool useDefaultImplementationForConstants() const override { return true; }
Add getArgumentsThatAreAlwaysConstant returning {1}

2019-08-04 23:42 UTC, alexey-milovidov requested changes
Ok. Only a few changes remain.

2019-08-05 07:40 UTC, Vdimir commented
I made one excess commit and decide to squash it to one to keep history clean. But changes have been already pushed and it requires force-push. I hope it is not a big problem.

2019-08-06 14:26 UTC, alexey-milovidov approved these changes

2019-08-06 14:27 UTC, merged