[Docs] add missing `showCertificate`
ClickHouse/ClickHouse pull request #63379
Opened 2024-05-05 01:57 UTC by Blargian

Closes [#2009](https://github.com/ClickHouse/clickhouse-docs/issues/2009) as part of [#1833](https://github.com/ClickHouse/clickhouse-docs/issues/1833) to document missing functions.

Adds missing
- `showCertificates`

I chose not to include an example here as it depends on user configuration and is fairly straightforward to understand without one.

### Changelog category (leave one):
- Documentation (changelog entry is not required)

2024-05-05 17:21 UTC, alexey-milovidov commented
This documentation is not sufficient. It does not provide more info than the function name.
It does not explain the function behavior and logic. It does not explain corner cases.
It does not explain what "server's certificate" means.

2024-05-05 17:21 UTC, alexey-milovidov requested changes
.

2024-05-15 02:15 UTC, Blargian commented
@alexey-milovidov better now, or still needs some work?

2024-05-15 03:13 UTC, alexey-milovidov approved these changes

2024-05-15 03:30 UTC, merged