Fix filter pushdown for Parquet and maybe StorageMerge
ClickHouse/ClickHouse pull request #63642
Opened 2024-05-11 01:00 UTC by al13n321

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed Parquet filter pushdown not working with Analyzer.

Situation:
```
/// Analyzer generates unique ColumnIdentifiers like __table1.__partition_id in filter nodes,
/// while key analysis still requires unqualified column names.
```
MergeTree had code to specifically correct for that, but other storages didn't, for some reason. So filter pushdown wasn't working for Parquet and probably ORC and maybe Merge.

Most of the PR is one find-replace. Non-mechanical changes are in `ReadFromMergeTree.cpp`, `SelectQueryInfo.{h,cpp}`, `SourceStepWithFilter.cpp`, and `02841_parquet_filter_pushdown.sql`

2024-05-11 01:05 UTC, alexey-milovidov approved these changes

2024-05-11 01:07 UTC, alexey-milovidov requested changes

2024-05-11 01:07 UTC, alexey-milovidov commented on tests/queries/0_stateless/02841_parquet_filter_pushdown.sql
See also `orc_filter_pushdown`

2024-05-11 01:40 UTC, alexey-milovidov approved these changes

2024-05-17 00:50 UTC, al13n321 commented
The test failures about `system.zookeeper` are clearly related, but I couldn't reproduce them locally so far. Maybe it needs fast-test-like build with reduced dependencies? Maybe something's different in server config? Maybe fast test passes some important arguments to clickhouse-test?

2024-05-17 02:58 UTC, al13n321 commented
> Maybe it needs fast-test-like build with reduced dependencies?

Didn't help.

> Maybe fast test passes some important arguments to clickhouse-test?

Didn't help.

> Maybe something's different in server config?

I tried to use tests/config/install.sh to create configs similar to CI, but getting it to work seems hopeless, I ran into a few different errors, the configs seem to be missing things, and it would take a while to follow the code and configs to figure out how exactly CI sets everything up to try to reproduce.

Is there a way to get CI to deploy everything, then pause and let me SSH to it?

2024-05-17 03:35 UTC, al13n321 commented
In https://github.com/ClickHouse/ClickHouse/pull/58061 is another example where the server takes very different code paths in CI vs locally.

2024-05-21 00:34 UTC, al13n321 commented
(Ok, reproduced the CI setup by copying the commands from the log in CI (thanks to whoever put a `set +x` there!), found the dumb bug in my code.)

2024-05-21 03:37 UTC, merged