toFloat() monotonicity fixed
ClickHouse/ClickHouse pull request #6374
Opened 2019-08-07 09:25 UTC by dimarub2000

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Bug Fix

Short description (up to few sentences):
Fixes #6248

2019-08-07 09:53 UTC, alexey-milovidov requested changes
Not enough.

2019-08-07 09:55 UTC, alexey-milovidov commented
Need to add a test:
- for the issue;
- to check that the index by integer or decimal continue to work if you convert toFloat64.

2019-08-07 09:57 UTC, dimarub2000 commented
Tests will be added soon.

2019-08-07 18:23 UTC, alexey-milovidov commented
Still not ready.

2019-08-07 18:24 UTC, alexey-milovidov commented on dbms/src/Functions/FunctionsConversion.h
> +using FunctionToFloat32 = FunctionConvert<DataTypeFloat32, NameToFloat32, ToIntMonotonicity<Float32>>;
But now the template name is idiosyncratic.

2019-08-08 16:11 UTC, alexey-milovidov approved these changes

2019-08-08 16:11 UTC, merged