Test for #6371
ClickHouse/ClickHouse pull request #6378
Opened 2019-08-07 12:28 UTC by 4ertus2

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Build/Testing/Packaging Improvement

Short description (up to few sentences):
Test for probably fixed crash

2019-08-07 18:05 UTC, 4ertus2 commented
There's no alignment in AllocatorWithStackMemory. It leads to crash in attepmt to push_back __int128 into PODArrayWithStackMemory

2019-08-07 18:23 UTC, alexey-milovidov commented
Also we can replace `__int128` to more portable `boost::cpp_int`. It may lead to performance degradation, but most likely not.

2019-08-08 00:08 UTC, alexey-milovidov requested changes
Asked a question in Telegram chat.

2019-08-08 16:06 UTC, alexey-milovidov commented on dbms/src/Common/PODArray.h
> +    AllocatorWithStackMemory<Allocator<false>, rounded_bytes, ((sizeof(T) < 16) ? sizeof(T) : 16)>>;
There is also `alignof` keyword.

2019-08-08 16:06 UTC, alexey-milovidov commented on dbms/src/Common/PODArray.h
> +    AllocatorWithStackMemory<Allocator<false>, rounded_bytes, ((sizeof(T) < 16) ? sizeof(T) : 16)>>;
I'll change.

2019-08-08 19:32 UTC, merged