write last rows in PrettyMonoBlock
ClickHouse/ClickHouse pull request #64200
Opened 2024-05-21 15:26 UTC by Volodyachan

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Outputs the last 10 rows if `output_format_pretty_max_rows` is exceeded
If `output_format_pretty_max_rows < 10`, outputs `output_format_pretty_max_rows / 2` last rows

Example:
```
SELECT *
FROM system.numbers
LIMIT 10000
FORMAT PrettyMonoBlock
SETTINGS output_format_pretty_max_rows = 9

Query id: 958bc7a4-d926-4946-a56a-dcc94f699e06

       ┏━━━━━━━━┓
       ┃ number ┃
       ┡━━━━━━━━┩
    1. │      0 │
       ├────────┤
    2. │      1 │
       ├────────┤
    3. │      2 │
       ├────────┤
    4. │      3 │
       ├────────┤
    5. │      4 │

       ⋮

 9997. │   9996 │
       ├────────┤
 9998. │   9997 │
       ├────────┤
 9999. │   9998 │
       ├────────┤
10000. │   9999 │
       └────────┘
  Showed 9.
```

2024-05-24 01:00 UTC, jkartseva requested changes

2024-05-28 23:39 UTC, jkartseva commented on src/Processors/Formats/Impl/PrettyBlockOutputFormat.cpp
> +            if (mono_chunk.getNumRows() > 10)
Please name the constant, e.g. `constexpr size_t last_rows_num = 10`
Alternatively, `auto last_rows_num = std::min(format_settings.pretty.max_rows / 2, 10)`

2024-05-28 23:39 UTC, jkartseva commented on src/Processors/Formats/Impl/PrettyBlockOutputFormat.cpp
>      if (total_rows >= format_settings.pretty.max_rows)
When `output_format_pretty_max_rows` equal to `LIMIT` it writes "Showed first":
```
SELECT *
FROM system.numbers
LIMIT 3
FORMAT PrettyMonoBlock
SETTINGS output_format_pretty_max_rows = 3

Query id: 7f513247-acf0-4f01-95d0-de705b1a90ea

   ┏━━━━━━━━┓
   ┃ number ┃
   ┡━━━━━━━━┩
1. │      0 │
   ├────────┤
2. │      1 │
   ├────────┤
3. │      2 │
   └────────┘
  Showed first 3.

3 rows in set. Elapsed: 0.002 sec.
```

It seems the condition should be `total_rows > format_settings.pretty.max_rows`

2024-06-06 22:39 UTC, jkartseva commented
@Volodyachan please take a look at the review comments. Build failure ought to be fixed: https://github.com/ClickHouse/ClickHouse/actions/runs/9224891757/job/25387973912#step:8:11008

2024-12-27 22:08 UTC, alexey-milovidov commented
I thought about implementing it in a simpler way. I will submit another PR.

2024-12-27 22:08 UTC, closed without merging