Skip adding x-amz-server-side-encryption headers to HeadObject requests
ClickHouse/ClickHouse pull request #64577
Opened 2024-05-29 12:16 UTC by Beetelbrox

Issue: #64570

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`x-amz-server-side-encryption` headers are not added to `HeadObject` requests as they're not supported. 

### Documentation entry for user-facing changes

N/A

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

<details>
    <summary>CI Settings</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step
- [ ]  Allow: Integration Tests
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Unit tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All with aarch64
- [ ]  Allow: All with ASAN
- [ ]  Allow: All with TSAN
- [ ]  Allow: All with Analyzer
- [ ]  Allow: All with Azure
- [ ]  Allow: Add your option here
---
- [ ]  Exclude: Fast test
- [ ]  Exclude: Integration Tests
- [ ]  Exclude: Stateless tests
- [ ]  Exclude: Stateful tests
- [ ]  Exclude: Performance tests
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN
- [ ]  Exclude: All with MSAN
- [ ]  Exclude: All with UBSAN
- [ ]  Exclude: All with Coverage
- [ ]  Exclude: All with Aarch64
---
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)
- [ ]  allow: batch 1 for multi-batch jobs
- [ ]  allow: batch 2
- [ ]  allow: batch 3
- [ ]  allow: batch 4, 5 and 6
</details>

2024-05-29 14:44 UTC, Beetelbrox commented
With the changes applied here, trying to write with a bucket without policy passing the `x-amz-server-side-encryption` header:
```
INSERT INTO FUNCTION s3('https://test-fjjm-no-encryption.s3.eu-north-1.amazonaws.com/sql.csv', 'REDACTED', 'REDACTED', 'CSV', headers('x-amz-server-side-encryption' = 'AES256'))
SETTINGS s3_create_new_file_on_insert = 1
SELECT number
FROM numbers(10)
SETTINGS s3_create_new_file_on_insert = 1

Query id: cf0d1527-c444-4534-ac32-650dfcf53a8b

Ok.

0 rows in set. Elapsed: 0.672 sec. 
```

Then, for a bucket with the following permission policy:
```
{
    "Version": "2012-10-17",
    "Id": "PutObjectPolicy",
    "Statement": [
        {
            "Sid": "DenyObjectsThatAreNotSSES3",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::test-fjjm-encryption/*",
            "Condition": {
                "StringNotEquals": {
                    "s3:x-amz-server-side-encryption": "AES256"
                }
            }
        }
    ]
}
```

If we try to write without passing the header it fails with an `Access Denied` error as expected:
```
INSERT INTO FUNCTION s3('https://test-fjjm-encryption.s3.eu-north-1.amazonaws.com/sql.csv', 'REDACTED', 'REDACTED', 'CSV')
SETTINGS s3_create_new_file_on_insert = 1
SELECT number
FROM numbers(10)
SETTINGS s3_create_new_file_on_insert = 1

Query id: cc3a73c5-0d30-41ae-8e8b-c25a84f6f888


Elapsed: 0.974 sec. 

Received exception:
Code: 499. DB::Exception: Message: Access Denied, bucket test-fjjm-encryption, key sql.5.csv, object size 20. (S3_ERROR)
```

While if we pass the header it works:
```
INSERT INTO FUNCTION s3('https://test-fjjm-encryption.s3.eu-north-1.amazonaws.com/sql.csv', 'REDACTED', 'REDACTED', 'CSV', headers('x-amz-server-side-encryption' = 'AES256'))
SETTINGS s3_create_new_file_on_insert = 1
SELECT number
FROM numbers(10)
SETTINGS s3_create_new_file_on_insert = 1

Query id: b4da97c1-c9d5-4f16-8892-23debf3d2b34

Ok.

0 rows in set. Elapsed: 0.706 sec. 
```

2024-05-29 14:46 UTC, Beetelbrox commented
I am not sure if how we can test this, if we can at all, as it requires an S3 bucket with the appropriate policy and AFAIK for testing the S3 function we're using MinIO. Any guidance is more than welcome.

2024-05-29 15:06 UTC, Beetelbrox commented
I've found out that this happens too for `UploadPart` & `CompleteMultipartUpload` requests (see issue for traces) so I've added skip to them too, now files uploaded with multipart and the SSE header are uploaded properly:

```
INSERT INTO FUNCTION s3('https://test-fjjm-encryption.s3.eu-north-1.amazonaws.com/sql.csv', 'REDACTED', 'REDACTED', 'CSV', headers('x-amz-server-side-encryption' = 'AES256'))
SETTINGS s3_create_new_file_on_insert = 1
SELECT number
FROM numbers(10000000)
SETTINGS s3_create_new_file_on_insert = 1

Query id: 15e54563-6b73-4dac-8af0-d2f1c9f7bb18

Ok.

0 rows in set. Elapsed: 10.883 sec. Processed 10.00 million rows, 80.00 MB (918.87 thousand rows/s., 7.35 MB/s.)
Peak memory usage: 99.57 MiB.
```

The above produces a 75 MB file.

2024-05-30 17:12 UTC, alexkats commented
Thanks for the changes, I'd like to double-check them, but one thing from the top of my head. I see that there are more requests that don't support this header as well, at least `DeleteObject` and `DeleteObjects`, can you please check the remaining requests as well?

2024-06-17 15:49 UTC, CheSema commented
> I am not sure if how we can test this, if we can at all, as it requires an S3 bucket with the appropriate policy and AFAIK for testing the S3 function we're using MinIO. Any guidance is more than welcome.

In integration tests you could create new or alter existed bucket. Here is an example https://github.com/ClickHouse/ClickHouse/blob/bbe3a9f78e24e2e7c82e5358530c239cd2e9a463/tests/integration/test_storage_s3_queue/test.py#L18

Also you could run s3-mock between clickhouse and minio and just check headers in it.

2024-07-11 15:29 UTC, alexkats requested changes
In general, the changes are ok, but like I said, let's cover other requests as well. Also it would be nice to have some test for the changes

2025-08-05 18:01 UTC, iamsudip commented
I am facing this too. I don't see any traction on this PR, can we get this PR moving. I can raise another PR if the original author isn't available anymore. But I would like to get it moving as I am blocked on this. All of our buckets where I want to put data are encrypted by customer managed KMS keys (SSE-KMS).

2025-12-30 20:41 UTC, alexey-milovidov commented
This makes sense. It's sad that no one was able to write tests. Let's check that the existing tests pass and merge.

2026-01-01 23:17 UTC, merged