Let's Encrypt integration
ClickHouse/ClickHouse pull request #66315
Opened 2024-07-10 09:45 UTC by thevar1able

Continuation of https://github.com/ClickHouse/ClickHouse/pull/48661

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
TODO

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-09-06 00:39 UTC, thevar1able commented on src/Common/Base64.h
> +std::string base64Encode(const std::string & decoded, bool url_encoding = false, bool no_padding = false);
`padding = true`

2024-09-06 00:42 UTC, thevar1able commented on src/Server/ACMEClient.cpp
> +    return csr;
Don't forget to free OpenSSL objects memory.

2025-04-04 19:07 UTC, GrigoryPervakov commented on tests/integration/test_acme_tls/test.py
> +import logging
Why not Pebble?

https://github.com/letsencrypt/Pebble

2025-04-05 11:38 UTC, thevar1able commented on tests/integration/test_acme_tls/test.py
> +import logging
Thank you, I was looking at it at some point and honestly forgot about it; let's try to use it in tests.

One thing that might be tricky is hooking functions to add counters for the tests.

2025-04-05 14:24 UTC, GrigoryPervakov commented on tests/integration/test_acme_tls/test.py
> +import logging
There are some additional api to track the internal status, it could be useful for that

2025-06-09 19:39 UTC, azat requested changes, later dismissed
Great feature! Please take a look at the comments

Also:

- it cannot start with embedded keeper - https://pastila.nl/?0035423d/19f2f9a1672f14ccb625260010d02eeb#bOQjWFKlV2e+9XX53PROrQ==
  - it is from config reload, we need to wait for zk and a mode w/o zk would be nice for single node setup (but let's do this on top)

- `ACME::Client: Certificate order is in progress by another replica, skipping` with only one replica, (likely this is due to I have very huge `session_timeout` of 1 hour, for better debugger experience), we can fix this by putting server UUID there and using `deleteEphemeralNodeIfContentMatches` method

- After first request and restarting the server I broken let's encrypt - `ACME::Client: Order https://acme-staging-v02.api.letsencrypt.org/acme/order/204855314/25226075894 is invalid, retrying`, have you seen such behavior? And hence I cannot test it properly

- There can be some issues in ZK interraction, conflicts between replicas, though it should not be possible I guess, since the replica that is working on it acquires lock, but it will be nice to add version checks and remove `IfExists` whenever it is not required

_P.S. I did not looked at the test (yet)_

2025-06-09 19:39 UTC, azat commented on programs/server/Server.cpp
> +        auto stop_acme_instance = []{
Maybe it will be better to avoid using callback just for this and write this code in place?

2025-06-09 19:39 UTC, azat commented on programs/server/config.xml
> +    -->
Should we update doc somewhere?

2025-06-09 19:39 UTC, azat commented on src/Common/Crypto/X509Certificate.cpp
> +    }
This looks like a copy-paste from `fromFile`

2025-06-09 19:39 UTC, azat commented on src/Common/JSONWebKey.h
> +struct JSONWebKey
Let's add a brief comment what it is

2025-06-09 19:39 UTC, azat commented on src/Common/JSONWebKey.h
> +    std::string e;
```suggestion
    /// Public exponent
    std::string e;
```

2025-06-09 19:39 UTC, azat commented on src/Common/JSONWebKey.h
> +    std::string n;
```suggestion
    /// modulus
    std::string n;
```

2025-06-09 19:39 UTC, azat commented on src/Common/JSONWebKey.h
> +    std::string kty;
```suggestion
    /// Key TYpe
    std::string kty;
```

2025-06-09 19:39 UTC, azat commented on src/Common/OpenSSLHelpers.h
> +/// FIXME
?

2025-06-09 19:39 UTC, azat commented on src/Common/OpenSSLHelpers.h
> +std::string calculateHMACwithSHA256(std::string to_sign, EVP_PKEY * pkey);
```suggestion
std::string calculateHMACWithSHA256(std::string to_sign, EVP_PKEY * pkey);
```

2025-06-09 19:39 UTC, azat commented on src/Common/OpenSSLHelpers.h
> +std::string generateCSR(std::vector<std::string>, std::string);
```suggestion
std::string generateCSR(const std::vector<std::string> & domain_names, const std::string & pkey);
```

Also why here we accept private key as string and above as `EVP_PKEY`?

2025-06-09 19:39 UTC, azat commented on src/Common/OpenSSLHelpers.cpp
> +            throw Exception(ErrorCodes::OPENSSL_ERROR, "Unable to add Subject Alternative Names to CSR {}", getOpenSSLErrors());
Looks like `extensions` can be leaked? Consider wrapping raw C objects into `std::unique_ptr` with proper deleter

2025-06-09 19:39 UTC, azat commented on src/Common/OpenSSLHelpers.cpp
> +    X509_REQ * req(X509_REQ_new());
Shouldn't we free it properly? Also leak in case of exception

2025-06-09 19:39 UTC, azat commented on src/Common/OpenSSLHelpers.cpp
> +    EVP_PKEY * key = EVP_PKEY_new();
Can leak?

2025-06-09 19:39 UTC, azat commented on src/Common/OpenSSLHelpers.cpp
> +    X509_NAME * cn = X509_REQ_get_subject_name(req);
Leak?

2025-06-09 19:39 UTC, azat commented on src/Common/OpenSSLHelpers.cpp
> +            other_domain_names += fmt::format("DNS:{}, ", *it);
```suggestion
            other_domain_names += fmt::format("DNS:{}, ", *it);
```

Is trailing `,` OK? I guess, but looks clumsy

Consider using some thing like this:

```cpp
fmt::format("{}",
    fmt::join(domains | std::views::drop(1) | std::views::transform([](const std::string &d) {
        return fmt::format("DNS:{}", d);
    }), ",")
);
```

2025-06-09 19:39 UTC, azat commented on src/Common/OpenSSLHelpers.cpp
> +    return csr;
Please don't forget to verify all raw C objects

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/API.cpp
> +        auto *log = &Poco::Logger::get("ACME::API");
```suggestion
        auto * log = &Poco::Logger::get("ACME::API");
```

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/API.h
> +    static constexpr auto STAGING_DIRECTORY_URL = "https://acme-staging-v02.api.letsencrypt.org/directory";
I guess we should move this into the `config.xml` as an example, so that users will see that there is staging out of the box.

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/API.h
> +    }
Consider hide the implementation in .cpp.

2025-06-09 19:39 UTC, azat commented on src/Server/CertificateReloader.h
> +        Data(KeyPair, X509Certificate::List, std::string hash);
```suggestion
        Data(KeyPair, X509Certificate::List, std::string hash);
```

Can you please add the name of the variables in the header as well (and I guess this is not the only place), it is easier to read the code that way

2025-06-09 19:39 UTC, azat commented on src/Server/CertificateReloader.cpp
> +    : certs_chain(std::move(_certs_chain)), key(std::move(_pkey)), hash(_hash)
Either `hash(std::move(hash))` or `const std::string & _hash`

2025-06-09 19:39 UTC, azat commented on src/Server/WebUIRequestHandler.cpp
> +void ACMERequestHandler::handleRequest(HTTPServerRequest & request, HTTPServerResponse & response, const ProfileEvents::Event &)
Interesting, why it is here? It does not have UI AFAIU?

2025-06-09 19:39 UTC, azat commented on src/Server/CertificateReloader.cpp
> +            throw Exception(ErrorCodes::LOGICAL_ERROR, "Static TLS keys and ACME provider are enabled at the same time.");
```suggestion
            throw Exception(ErrorCodes::INVALID_CONFIG_PARAMETER, "Static TLS keys and ACME provider are enabled at the same time.");
```

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.cpp
> +    if (initialized)
This variable has never been set.

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.cpp
> +        LOG_WARNING(log, "For ACME HTTP challenge HTTP port must be 80, but is {}", http_port);
I guess this is for let's encrypt `/.well-known/acme-challenge/`?

From https://letsencrypt.org/docs/challenge-types/

>Our implementation of the HTTP-01 challenge follows redirects, up to 10 redirects deep. It only accepts redirects to “http:” or “https:”, and only to ports 80 or 443

But then we need to check `https_port` as well and we can also add a note about let's encrypt

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.h
> +    std::mutex private_acme_key_mutex;
Consider adding TSA annotations

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.cpp
> +    std::lock_guard key_lock(private_acme_key_mutex);
Can we release lock while we are interacting with ZK?

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.cpp
> +void Client::refresh_certificates_fn(const Poco::Util::AbstractConfiguration & config)
Why it has `under_score` notation?

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.h
> +static constexpr auto REFRESH_TASK_IN_A_SECOND = 1000;
This can be hidden

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.cpp
> +            zk->createIfNotExists(fs::path(ZOOKEEPER_BASE_PATH) / acme_hostname / "account_private_key", private_key);
It should be `create` or `set` with version check I suppose to avoid conflicts

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.cpp
> +            return;
Can't we just continue execution?

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.cpp
> +    LOG_TEST(log, "ACME private key successfully loaded");
I guess these logs are not that frequent so it is OK to make the `TRACE`?

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.cpp
> +        LOG_WARNING(log, "Private key is not initialized, retrying in 1 second. This is a bug.");
```suggestion
        LOG_FATAL(log, "Private key is not initialized, retrying in 1 second. This is a bug.");
```

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.cpp
> +                .private_key = private_acme_key,
If it has private key, shouldn't we update it in case it has been changed? I believe it is not possible, then I would replace `Private key is not initialized, retrying in 1 second. This is a bug.` with proper `LOGICAL_ERROR`

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.cpp
> +                need_refresh = true;
```suggestion
                need_refresh = true;
                break;
```

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.cpp
> +
Don't we need to reset `active_order` and unlock and reset the lock here?

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/API.cpp
> +        payload = R"({"termsOfServiceAgreed":true})";
This should use `terms_of_service_agreed` from config

2025-06-09 19:39 UTC, azat commented on src/Server/ACME/Client.h
> +static constexpr auto ZOOKEEPER_BASE_PATH = "/clickhouse/acme";
I guess we need make this configurable to avoid possible interfier with i.e. `ReplicatedMergeTree('/clickhouse/acme', 'r1')`

2025-06-13 02:28 UTC, thevar1able commented on programs/server/Server.cpp
> +        auto stop_acme_instance = []{
Can't put `#if USE_SSL` in `STOP_EXIT_SAFE` macro.
>Embedding a directive within macro arguments has undefined behavior

2025-06-13 02:31 UTC, thevar1able commented on programs/server/config.xml
> +    -->
We definitely should, but maybe after testing thoroughly on Alexey's instance?

2025-06-13 02:37 UTC, thevar1able commented on src/Server/WebUIRequestHandler.cpp
> +void ACMERequestHandler::handleRequest(HTTPServerRequest & request, HTTPServerResponse & response, const ProfileEvents::Event &)
For serving verification challenge.

2025-06-13 02:54 UTC, thevar1able commented on src/Common/OpenSSLHelpers.h
> +/// FIXME
It looked similar to `hmacSHA256`, I wanted to recheck if we really need another one.

2025-06-13 04:10 UTC, thevar1able commented on src/Server/ACME/Client.cpp
> +                need_refresh = true;
Why?

2025-06-16 16:06 UTC, azat commented on src/Server/ACME/Client.cpp
> +                need_refresh = true;
At least one expired certificate is enough AFAICS

2025-11-11 15:40 UTC, thevar1able commented on src/Server/ACME/Client.cpp
> +
No, we should hold the lock until we have a certificate.

2025-11-12 14:19 UTC, thevar1able commented
>BuzzHouse (amd_debug)

https://github.com/ClickHouse/ClickHouse/issues/89924

2025-11-12 18:47 UTC, thevar1able commented
Intentionally merging without approval.

2025-11-12 19:15 UTC, merged

2025-11-13 16:37 UTC, rschu1ze commented on programs/server/config.xml
> +    -->
Yes, please let's add docs for this PR :-)

2025-11-13 16:41 UTC, thevar1able commented on programs/server/config.xml
> +    -->
I'll merge docs by the end of the year in the worst case.