Limit number of linker jobs on arm to avoid OOM during build
ClickHouse/ClickHouse pull request #66435
Opened 2024-07-12 12:10 UTC by nickitat

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-07-12 12:22 UTC, tavplubix approved these changes

2024-07-12 15:28 UTC, alexey-milovidov requested changes

2024-07-12 15:28 UTC, alexey-milovidov commented on cmake/limit_jobs.cmake
> +    if (ARCH_AARCH64)
Missing explanation.

2024-07-13 20:50 UTC, alexey-milovidov approved these changes

2024-07-13 21:21 UTC, merged

2024-07-15 08:59 UTC, antonio2368 commented
Seems like it didn't help https://github.com/ClickHouse/ClickHouse/actions/runs/9935217428/job/27441008909

2024-07-15 15:46 UTC, alexey-milovidov commented
@antonio2368 Let's disable LTO on ARM.

2024-07-15 15:51 UTC, nickitat commented
Let's try another fix first

https://github.com/ClickHouse/ClickHouse/pull/66530