Rename FileSegmentKind::Ephemeral and other changes
ClickHouse/ClickHouse pull request #66606
Opened 2024-07-16 16:37 UTC by vdimir

### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-10-25 08:47 UTC, vdimir commented on src/Storages/MergeTree/MergeTask.cpp
> +            (is_vertical_merge ? ctx->rows_sources_temporary_file : nullptr),  /// rows_sources temporaty file is used only for vertical merge
```suggestion
            (is_vertical_merge ? ctx->rows_sources_temporary_file : nullptr),  /// rows_sources' temporary file is used only for vertical merge
```

2024-11-04 09:25 UTC, vdimir commented
> Integration tests (aarch64) [5/6] — fail: 1, passed: 472 [Details](https://s3.amazonaws.com/clickhouse-test-reports/66606/60fa4be570f78b935d47f9cc6ed88fbd2b0b1440/integration_tests__aarch64__[5_6].html)
> Integration tests (asan, old analyzer) [6/6] — fail: 1, passed: 517 [Details](https://s3.amazonaws.com/clickhouse-test-reports/66606/60fa4be570f78b935d47f9cc6ed88fbd2b0b1440/integration_tests__asan__old_analyzer__[6_6].html)
> Integration tests (tsan) [6/6] — fail: 1, passed: 511 [Details](https://s3.amazonaws.com/clickhouse-test-reports/66606/60fa4be570f78b935d47f9cc6ed88fbd2b0b1440/integration_tests__tsan__[6_6].html)


https://github.com/ClickHouse/ClickHouse/issues/67604
https://github.com/ClickHouse/ClickHouse/issues/71237

2024-11-04 09:27 UTC, vdimir commented
@davenger I've updated the code to revert the excess changes around MergeTask that we discussed, please take a look

2024-11-12 16:11 UTC, davenger requested changes

2024-11-13 13:20 UTC, vdimir commented
Investigating failure https://s3.amazonaws.com/clickhouse-test-reports/66606/6917a37d5c978e20bbc4dbfea48c8460a3cea0da/stateless_tests__release_.html

2024-11-13 13:24 UTC, vdimir commented on src/Interpreters/Aggregator.cpp
> +}
I suppose we can move ownership of `std::list<TemporaryBlockStreamHolder>` to `AggregatingTransform` in `initGenerate`

2024-11-15 09:38 UTC, vdimir commented
One like and I'll merge this PR

2024-11-15 13:22 UTC, davenger approved these changes

2024-11-15 13:57 UTC, merged