Build LLVM from sources
ClickHouse/ClickHouse pull request #66793
Opened 2024-07-20 00:03 UTC by alexey-milovidov

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Pin the compiler and tools version by building LLVM from sources. This eliminates a fragile supply-chain dependency. This closes #66493. See https://github.com/llvm/llvm-project/issues/99453

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-07-20 01:27 UTC, thevar1able commented on docker/test/util/Dockerfile
> +RUN curl -s https://apt.kitware.com/keys/kitware-archive-latest.asc | gpg --dearmor - > /etc/apt/trusted.gpg.d/kitware.gpg \
We may merge this in one big `RUN` so that we don't have intermediate layers with unnecessary dependencies.

2024-07-22 10:58 UTC, alesapin requested changes
I'm strongly against building such complex tools as clang or llvm at docker build stage. It's very unclear, implicit, and slow down these jobs. All other CI jobs depend on them.

`docker build` command shouldn't take hours if your laptop is not powerful enough. 

 Let's introduce a separate job for it which will publish artifacts to S3. We can even introduce fancy URLs for them and it will be available for every clickhouse developer.

2024-07-22 14:28 UTC, thevar1able commented
I somewhat agree with @alesapin, this approach will work, but is very inefficient and will slow down CI significantly. Would be much nicer to make something like `FROM clickhouse/llvm:<llvm-hash>`, then that image could be rebuilt only on LLVM commit hash update.

2024-07-22 14:37 UTC, alexey-milovidov commented
The `base` Docker image is rebuild only when it's changed, so it isn't a problem.

2024-07-23 13:27 UTC, alesapin commented
It's a huge problem. What if I want to use locally exactly the same compiler/llvm which CI uses? I have to rebuild it (what if my PC is slow), or execute weird commands to extract it from docker image. Separate job with artifacts is much better than this solution.

2024-07-24 01:40 UTC, alexey-milovidov commented
Ok, but this PR is still a step forward. Today you have a difficult way to get exactly the same compiler, either on your machine or in CI. After this pull request, it becomes easier.

2024-08-15 23:16 UTC, alexey-milovidov commented
Reopen if needed.

2024-08-15 23:16 UTC, closed without merging