Ensure COMMENT clause works for all table engines
ClickHouse/ClickHouse pull request #66832
Opened 2024-07-21 18:07 UTC by joelynch

### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Ensure COMMENT clause works for all table engines

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-07-22 03:50 UTC, alexey-milovidov commented
Does not sound like a bug fix. Change the category accordingly.

2024-07-22 03:50 UTC, alexey-milovidov requested changes
Needs tests.

2024-07-22 17:17 UTC, joelynch commented
I added tests for all the table engines that don't need an external process running to `tests/queries/0_stateless/01821_table_comment.sql`.  Is this enough or should I write some integration tests for the remaining table engines that were affected by this PR?

Also I fixed up the docs a bit.

2024-07-26 09:35 UTC, alexey-milovidov approved these changes

2024-07-26 10:07 UTC, merged