Revert "Keep subscriptions for all enabled roles."
ClickHouse/ClickHouse pull request #66845
Opened 2024-07-22 06:54 UTC by ilejn

This reverts commit 31b7e6edc64689d1d682506530a426c8f06ae1b6.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Reasons:

1. The code contains an error and does not work 
1.1.  new_subscriptions_on_roles are intact here https://github.com/ClickHouse/ClickHouse/blob/5611ef0d387e7c18a76dbcb1d1619d19ac60b501/src/Access/RoleCache.cpp#L121-L134
1. The code is not needed
1. 1. The original motivation  https://github.com/ClickHouse/ClickHouse/pull/46772#discussion_r1116832141 _Because if a role expires from the cache not only it got deleted from the cache but the subscription got deleted too. And that's bad because some EnabledRoles might still depend on that role. Apparently we need to store subscriptions in EnabledRoles and not in this role cache_ is probably wrong, `collectEnabledRoles` that is called in context of `roleChanged` / `roleRemoved` provides this guarantee .

Another reason for this PR is we definitely have issues with roles, it is common knowledge that roles should be avoided, e.g. https://t.me/clickhouse_ru/383357?thread=383348
Wood be exceedingly splendid to sort these issues out.

attn @vitlibar

2024-07-22 07:11 UTC, alexey-milovidov commented
What was the wrong pull request, and when it was merged?
What issues with roles remain?

2024-07-22 07:11 UTC, alexey-milovidov requested changes
A test is required.

2024-07-22 07:12 UTC, alexey-milovidov commented
If it is a bug fix, please provide an example of a wrong behavior and change the category.

2024-07-22 07:21 UTC, alexey-milovidov approved these changes

2024-07-22 07:21 UTC, alexey-milovidov commented
Ok. As long as all tests are green, we can merge it.

2024-07-22 07:22 UTC, ilejn commented
@alexey-milovidov , sorry, could we wait for @vitlibar , please?

2024-07-24 05:59 UTC, alexey-milovidov commented
@ilejn We found a failed test, and you are the author. Let's fix it before merging this PR: #66998

2024-07-26 19:40 UTC, vitlibar commented
I don't really understand that. Mostly we revert changes if they break something. What exactly was broken by that commit?

2024-07-27 00:01 UTC, ilejn commented
> I don't really understand that. Mostly we revert changes if they break something. What exactly was broken by that commit?

@vitlibar  see code in 1.1 of the description of the PR. 
As far as I can see, it contains error and does not work.

It would be cool if you can
- confirm that it does not work indeed
- confirm that no misbehavior is expected

2024-08-04 12:31 UTC, vitlibar commented
> @vitlibar see code in 1.1 of the description of the PR.
As far as I can see, it contains error - new_subscriptions_on_roles is always empty.

You're right, the code contains error. But this code is necessary and removing it doesn't help anything. This code should be fixed, and not removed.

2024-08-04 12:40 UTC, vitlibar commented
@ilejn I've fixed the error you found in https://github.com/ClickHouse/ClickHouse/pull/67748.

Also I managed to write a real test there to be sure this time that the issue won't come back again.

2024-08-04 12:40 UTC, closed without merging