DOCAPI-7745: optimize_throw_if_noop docs.
ClickHouse/ClickHouse pull request #6848
Opened 2019-09-06 15:24 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation

2019-09-06 16:20 UTC, blinkov requested changes

2019-09-06 16:20 UTC, blinkov commented on docs/en/interfaces/formats.md
> +To exchange data with the Hadoop, you can use [`HDFS` table engine](../operations/table_engines/hdfs.md).
why it's in backticks?

2019-09-06 16:20 UTC, blinkov commented on docs/en/operations/settings/settings.md
> +If the `OPTIMIZE` query doesn't perform a merge of data parts for any reason (for example, nothing to merge or lack of resources) it finishes and the client cann't know why. To know when and why the
```suggestion
By default `OPTIMIZE` returns successfully even if it haven't done anything. This setting allows to distinguish this situation and get the reason in exception message.
```

2019-09-06 16:20 UTC, blinkov commented on docs/en/query_language/misc.md
> +Supported only by `MergeTree` family of table engines, in which this query initializes a non-scheduled merge of data parts.
```suggestion
This query tries to initialize an unscheduled merge of data parts for tables with a table engine of [MergeTree](../operations/table_engines/mergetree.md) family. Other kinds of table engines are not supported.
```

2019-09-06 16:20 UTC, blinkov commented on docs/en/query_language/misc.md
> +When used with [MergeTree](../operations/table_engines/mergetree.md) family of table engines `OPTIMIZE` forces data parts merges. ClickHouse tries to find data parts for merging and then merge them.
I'd just drop this paragraph

2019-09-06 16:20 UTC, blinkov commented on docs/en/query_language/misc.md
> +When `OPTIMIZE` used with [ReplicatedMergeTree](../operations/table_engines/replication.md) family of table engines, ClickHouse creates a task for merging and waits for execution on all nodes (if the
link to setting?

2019-09-06 16:20 UTC, blinkov commented on docs/en/query_language/misc.md
> +If you specify a `PARTITION`, only the specified partition is optimized.
Group this if's in some bullet point list?

2019-09-09 15:55 UTC, BayoNet commented on docs/en/query_language/misc.md
> +When `OPTIMIZE` used with [ReplicatedMergeTree](../operations/table_engines/replication.md) family of table engines, ClickHouse creates a task for merging and waits for execution on all nodes (if the
It's not documented, but it will be.

2019-09-10 08:06 UTC, merged