repeat field is also compound types, ignore it.
ClickHouse/ClickHouse pull request #68494
Opened 2024-08-17 10:43 UTC by baibaichen

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

Minor patch for https://github.com/ClickHouse/ClickHouse/pull/68131

For parquet written by spark,  `repeat` type is used for `Array`,  for example:

```thrift
message 68131_scheme {
    repeated int32 f
}
```

We also need ignore it.  otherwise excepion is thrown at `convertFieldToType`

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-08-17 10:57 UTC, baibaichen commented
@al13n321 please review it.

2024-08-18 08:25 UTC, alexey-milovidov commented
The changelog entry has to be rewritten for better clarity.

2024-08-18 08:26 UTC, alexey-milovidov commented on src/Processors/Formats/Impl/ParquetBlockInputFormat.cpp
> +        if(s->descr()->schema_node()->is_repeated())
Missing whitespace.

2024-08-18 08:26 UTC, alexey-milovidov requested changes
Needs a test.

2024-08-18 11:12 UTC, baibaichen commented on src/Processors/Formats/Impl/ParquetBlockInputFormat.cpp
> +        if(s->descr()->schema_node()->is_repeated())
fix

2024-08-18 11:12 UTC, baibaichen commented
> Needs a test.

@alexey-milovidov test is added.

2024-08-19 16:13 UTC, baibaichen commented
@alexey-milovidov @al13n321 would you please review this PR? 
Thanks

2024-08-19 20:38 UTC, al13n321 approved these changes
Thanks!

2024-08-20 17:10 UTC, al13n321 commented
@alexey-milovidov , please approve.

2024-08-21 13:48 UTC, alexey-milovidov approved these changes

2024-08-21 19:30 UTC, merged