Fix empty TZ error
ClickHouse/ClickHouse pull request #68921
Opened 2024-08-27 01:57 UTC by cangyin

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-08-27 08:22 UTC, antaljanosbenjamin requested changes

2024-08-27 08:22 UTC, antaljanosbenjamin commented on src/Common/DateLUT.cpp
> +    if (!tz_env_var.empty())
I don't think you can call `empty()` on a `const char *`.

2024-08-27 08:27 UTC, antaljanosbenjamin commented
Please also take a loot at the description of [this issue](https://github.com/ogham/exa/issues/856) about how the content of TZ should be handled.

2024-08-31 06:38 UTC, cangyin commented
@antaljanosbenjamin 

Most tests passed. But look like I messed up with the reviews.

2024-08-31 10:17 UTC, cangyin commented
Should I close this PR and open another?

2024-09-02 06:53 UTC, antaljanosbenjamin commented
> But look like I messed up with the reviews.

What do you mean? I think nothing is bad here.

2024-09-02 07:12 UTC, antaljanosbenjamin commented on src/Common/DateLUT.cpp
> +            tz_env_var = "UTC";
Why not just return "UTC"?

2024-09-02 07:20 UTC, antaljanosbenjamin commented on src/Common/DateLUT.cpp
> +                return relative_path.string();
Ohh, I see now after playing with the code. Maybe do the same change on line 104.

2024-11-18 14:44 UTC, antaljanosbenjamin commented
I had an unanswered [question](https://github.com/ClickHouse/ClickHouse/pull/68921#discussion_r1773305391):

> Do you think it makes sense to do the same changes on line 104 to be consistent?

What do you think @cangyin ?

2024-12-05 15:40 UTC, antaljanosbenjamin approved these changes

2024-12-05 15:41 UTC, antaljanosbenjamin commented
@cangyin sorry for the late answer. Could you please merge a recent master? After that I think we can merge this.

2024-12-09 17:05 UTC, cangyin commented
> @cangyin sorry for the late answer. Could you please merge a recent master? After that I think we can merge this.

Thks for guiding, I will do it ASAP

2025-04-12 07:46 UTC, cangyin commented
@antaljanosbenjamin Check failures seems unrelated. The 'CH Inc sync' check is marked as required. Could you please have a look ?

2025-04-15 06:47 UTC, antaljanosbenjamin commented
The integration tests is not related, but I have to check the stress test failure. I will do it either today or tomorrow. If I don't manage, feel free to ping me.

2026-06-17 19:36 UTC, alexey-milovidov approved these changes
The change is good.

2026-06-18 16:18 UTC, alexey-milovidov commented
@groeneai, fix the failure in `test_checking_s3_blobs_paranoid` and send a PR.

2026-06-18 17:35 UTC, groeneai commented
@alexey-milovidov The `test_checking_s3_blobs_paranoid` failure on this PR is unrelated to your TZ change. Fix sent: #107895.

Root cause: every subtest ERRORs at setup in `init_broken_s3.reset()` -> `assert response == "OK"`. The tests flood the `broken_s3` mock with thousands of retried/slow requests; on slow builds (coverage/MSan/TSan) the mock briefly stops accepting connections while draining the backlog. `MockControl` sent each control request as one no-retry `curl`, so a single transient empty response cascaded the whole file to ERROR. The mock's `broken_s3.err.log` stops mid-flood right after `test_when_error_is_retried[connection_refused]` (count=1000), and the next test errors at `reset()`. It never fails on master, only on the heaviest builds.

The fix routes all `MockControl` requests through a retry helper (~10s) so a momentary stall no longer aborts the suite; a truly dead mock still fails the assert.

2026-06-20 07:40 UTC, alexey-milovidov commented
Merged the latest `master` into this branch (it was 851 commits behind and red) and renumbered the new functional test from `04356_timezone_env` to `04401_timezone_env`.

Reason for the renumber: while this PR sat, `master` accumulated five tests sharing the `04356_` prefix (`04356_compatibility_skips_obsolete_settings`, `04356_geojson_geometry_values`, `04356_key_condition_ifnull_coalesce_boolean_entry_points`, `04356_nullable_tuple_beta`, `04356_packed_skip_indices_vertical_merge`), so the test now lives at the next free number `04401`. The test content and the one-line `determineDefaultTimeZone` fix in `DateLUT.cpp` are unchanged.

The only red on the previous run was `test_checking_s3_blobs_paranoid` in `Integration tests (amd_llvm_coverage, 3/5)` — confirmed unrelated to this `TZ` change (a flaky mock-control stall on the heaviest coverage build) and already addressed by #107895.

2026-06-20 15:46 UTC, alexey-milovidov commented
@groeneai, provide a fix for `Logical error: 'Inconsistent AST formatting: the original AST: (STID: 1941-1bfa)`.

2026-06-20 16:42 UTC, groeneai commented
@alexey-milovidov The BuzzHouse `1941-1bfa` failure on this PR is the `kql_array_sort` subscript-then-operator subvariant, already fixed by my open PR #107634. It is not related to the TZ change.

The diverging node in the report (BuzzHouse amd_debug, SHA 953dd4294198) is `arrayElement(kql_array_sort_asc(...), i)` followed by an outer access operator, which re-parses back as `tupleElement`. The CTE/WITH wrapping in the fuzzed query is incidental. `kql_array_sort_asc`/`kql_array_sort_desc` return `Tuple(Array, ...)`, so a `[i]` subscript on their result is tuple-element access; the parser rewrites `arrayElement` to `tupleElement` only in `Layer::mergeElement`. When the subscript is immediately followed by another operator, the node is built by the operator-merge loop in `ParserExpressionImpl::tryParseOperator`, which had no rewrite, so a raw `arrayElement(kql_array_sort_*, i)` survived and the format-parse-format round-trip diverged by one node.

Minimal reproducer (aborts on master, clean type error with #107634):
```sql
SELECT kql_array_sort_desc([3, 1, 2])[0].4;
```

Verified locally on the #107634 branch (debug): both the minimal reproducer and the exact failing fragment from this report (`kql_array_sort_asc([10,20,30])[-3].(-3.) - 5`) abort on master and return a clean type error with the fix. #107634 is open and awaiting review.

2026-06-30 04:50 UTC, alexey-milovidov commented
Merged the latest `master` into this branch (it was 1801 commits behind and red) and re-triggered CI (run `28421074221` on `136bd2a7f16`). No conflicts; the net diff is unchanged — the one-line `determineDefaultTimeZone` fix in `DateLUT.cpp` plus the `04401_timezone_env` functional test (24 insertions across 3 files). No renumber needed: `04401_` is now shared by ~22 tests on `master`, and only the full filename must be unique.

Both reds on the previous run (`b533ade1`) are unrelated flakes, not reachable from a one-line empty-`TZ`→`UTC` change:

- `Stress test (amd_asan_ubsan)` — `Hung check failed, possible deadlock found`: the chronic, master-wide hung-check flake tracked by https://github.com/ClickHouse/ClickHouse/issues/107941 (the CI bot already links its CIDB query).
- `AST fuzzer (amd_debug)` — `Logical error: Unexpected column in sample block: A (STID: 3400-40ae)`, aborting inside `StorageFileSource::generate`. CIDB history shows this message is a sporadic AST-fuzzer-internal-path flake: over the last 90 days it appears exactly once each on unrelated PRs (#101526, #107694, #106028) and once here, never reproducibly. It is not one of the 5 sites already consolidated in https://github.com/ClickHouse/ClickHouse/issues/107951, but it fits the same class (the executor asserts on a fuzzer-constructed AST that the analyzer would normally reject with a clean exception).

@groeneai, investigate the `AST fuzzer (amd_debug)` failure `Unexpected column in sample block: A (STID: 3400-40ae)` — report: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=68921&sha=b533ade1afe97d34d9abf3a9772ae897b4e25f15&name_0=PR&name_1=AST%20fuzzer%20%28amd_debug%29 — and provide a fix in a separate PR (likely belongs under the #107951 umbrella). If a fix is already in progress, please link it here.

2026-06-30 05:22 UTC, groeneai commented
@alexey-milovidov This one is already covered by my open PR #107059. It is the ParquetV3 reader, not a distinct `StorageFileSource` site, and it is deterministic rather than a flake.

`StorageFileSource::generate` (`StorageFile.cpp:1744`, frame 23) is only the outer pipeline driver for the `file()` read. The `LOGICAL_ERROR` is one frame deeper, in `Parquet::Reader::preparePrewhere()` (`Reader.cpp:785`):

```
12. Reader.cpp:785                     Parquet::Reader::preparePrewhere()   <-- abort
13. ReadManager.cpp:65                 Parquet::ReadManager::init()
14. ParquetV3BlockInputFormat.cpp:102  ParquetV3BlockInputFormat::initializeIfNeeded()
 ...
23. StorageFile.cpp:1744               StorageFileSource::generate()
```

Root cause is a #93542 regression in `preparePrewhere`'s `add_step` lambda. It reuses the MergeTree prewhere splitter, but when the kept `and(...)` PREWHERE needs no row filtering (`need_filter == false && remove_prewhere_column == false`) the kept output column lands in neither `output_columns` nor `prewhere_output_column_idxs`, so the sample-block bookkeeping check throws. The fuzzed query here hits exactly that shape: `file(...)` Parquet + a multi-condition `PREWHERE (x > 1) AND (...)` kept in the output, plus a `WHERE`, under `enable_analyzer = 0` (per the run's settings dump). #107059 commit `60bea00a` fixes it by not splitting when no filtering is needed; regression test `04340_parquet_native_reader_prewhere_and_no_filter` (before = SIGABRT, after = passes).

So you are right that it fits the #107951 class (the executor asserting on a fuzzer-built AST the analyzer would otherwise reject), but it does not need a separate fix. One correction to the "sporadic flake" reading: it is a deterministic trunk bug. It aborts every time that PREWHERE / WHERE / old-analyzer shape is built over a Parquet `file()` read; the fuzzer just rarely constructs that exact shape, which is why it lands only once each on the three unrelated PRs you listed and on master.

Report: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=68921&sha=b533ade1afe97d34d9abf3a9772ae897b4e25f15&name_0=PR&name_1=AST%20fuzzer%20%28amd_debug%29

2026-06-30 09:47 UTC, alexey-milovidov commented
CI for the latest run (`136bd2a7`) is complete and fully green except for two reds, both the chronic master-wide hung-check flake [#107941](https://github.com/ClickHouse/ClickHouse/issues/107941) (already bot-linked in the summary table):

- `Stress test (amd_tsan)` — `Hung check failed, possible deadlock found`: the hung thread is in query-pipeline execution (`PipelineExecutor::executeStepImpl` on a `ThreadPool` worker).
- `Stress test (arm_tsan)` — `Hung check failed, possible deadlock found`: the hung thread is an AST-fuzzer query under stress (`executeASTFuzzerQueries` → `executeQuery` → `TCPHandler::runImpl`).

Neither stack touches `determineDefaultTimeZone`, which runs once at process init and has nothing to do with query execution. The net diff is unchanged — the one-line empty-`TZ`→`UTC` fix in `DateLUT.cpp` plus the `04401_timezone_env` functional test (changed lines 5/5 covered). Everything else is green: all builds, all Stateless/Integration/Stress (other than the two `tsan` hung-checks), AST fuzzer, BuzzHouse, Bugfix validation (functional, amd64 + aarch64), and Performance.

@groeneai, the two `tsan` hung-checks here are [#107941](https://github.com/ClickHouse/ClickHouse/issues/107941); flagging in case they should fold into that umbrella. The PR is otherwise ready to merge.

2026-07-02 16:50 UTC, merged