Allow empty arguments for arrayZip/arrayZipUnaligned
ClickHouse/ClickHouse pull request #69576
Opened 2024-09-13 02:48 UTC by taiyang-li

### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow empty arguments for arrayZip/arrayZipUnaligned, as concat did in https://github.com/ClickHouse/ClickHouse/pull/65887

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-09-13 10:13 UTC, alexkats requested changes
In general lgtm

2024-09-13 10:13 UTC, alexkats commented on tests/queries/0_stateless/01045_array_zip.reference
> +[()]
It actually returns `[]` and that's why FastTest has failed, and it makes sense to me that there shouldn't be an empty tuple when there are no arrays at all

2024-09-13 10:13 UTC, alexkats commented on tests/queries/0_stateless/03230_array_zip_unaligned.reference
> +[()]
Same

2024-09-13 10:23 UTC, alexkats approved these changes

2024-09-14 02:10 UTC, taiyang-li commented
failed test in https://s3.amazonaws.com/clickhouse-test-reports/69576/71553022e0c36b7740445d1806f132613a394066/stateless_tests__release__old_analyzer__s3__databasereplicated__[1_2].html seems not related to this pr.

2024-09-17 21:22 UTC, alexkats commented
Stateless tests (release, old analyzer, s3, DatabaseReplicated) [1/2]: #69624

2024-09-17 21:53 UTC, merged