DOCAPI-7459: EN review, RU translation for skip_unavailable_shards docs
ClickHouse/ClickHouse pull request #6996
Opened 2019-09-19 14:24 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation for #5924

2019-09-24 00:49 UTC, alexey-milovidov requested changes

2019-09-24 00:49 UTC, alexey-milovidov commented on docs/en/operations/settings/settings.md
> +- Nodes, if their name can't be resolved through DNS.
It's only a special case of unavailable replica.
And these replicas are always skipped.

2019-09-27 13:44 UTC, blinkov commented on docs/ru/operations/settings/settings.md
> +Включает или выключает тихий пропуск:
пропуск по время чего?

2019-10-21 13:29 UTC, BayoNet commented
@alexey-milovidov  Look at this one more time, please.

2019-10-31 09:28 UTC, blinkov requested changes

2019-11-05 19:15 UTC, merged