Support write orc file by custom time zone
ClickHouse/ClickHouse pull request #70615
Opened 2024-10-14 09:02 UTC by KevinyhZou

ORC format file write always use the default `GMT` time zone, which we write a `dateTime64` type field in a local time zone (like `Asia/Shanghai`), it will make the write value wrong.

In my case, when write a value with local timezone `2024-10-09 20:00:00`, but it written the value as `2024-10-09 12:00:00`

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support write orc file by custom time zone, not always by `GMT` time zone

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-10-14 21:13 UTC, alexey-milovidov commented on src/Core/SettingsChangesHistory.cpp
> +            {"input_format_orc_writer_time_zone_name", "GMT", "GMT", "The time zone name for ORC writer, the default ORC writer's time zone is GMT."},
It's output, not input.

2024-10-14 21:13 UTC, alexey-milovidov requested changes
.

2024-10-15 02:12 UTC, KevinyhZou commented on src/Core/SettingsChangesHistory.cpp
> +            {"input_format_orc_writer_time_zone_name", "GMT", "GMT", "The time zone name for ORC writer, the default ORC writer's time zone is GMT."},
fixed

2024-10-21 13:51 UTC, alexey-milovidov approved these changes

2024-10-30 02:05 UTC, KevinyhZou commented
could you help to merge this pr @alexey-milovidov

2024-10-30 03:04 UTC, alexey-milovidov commented
Yes, this is approved, but a few unrelated tests have failed. We need to resolve it...

2024-12-25 10:23 UTC, alexey-milovidov commented
@KevinyhZou, are you sure it is GMT, not UTC?
Let's check in the ORC docs.

2024-12-25 11:56 UTC, KevinyhZou commented
> @KevinyhZou, are you sure it is GMT, not UTC? Let's check in the ORC docs.

Yes, orc writer time zone default value is `GMT`, and this can be found at the code of orc `Writer.cpp`: https://github.com/apache/orc/blob/d812403d5590c377d486589a9172bb56e5dff54d/c%2B%2B/src/Writer.cc#L68 @alexey-milovidov

2024-12-25 16:18 UTC, merged

2026-05-11 21:33 UTC, clickgapai commented
Hi @KevinyhZou @alexey-milovidov — while reviewing this PR I found the following:

- **Bug (P1):** `output_format_orc_writer_time_zone_name` causes DateTime64 timestamp corruption due to double UTC conversion — https://github.com/ClickHouse/ClickHouse/issues/104641

Happy to discuss — close anything that's wrong or already addressed.