Fix header for now
ClickHouse/ClickHouse pull request #7156
Opened 2019-09-30 17:54 UTC by KochetovNicolai

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- New Feature
- Bug Fix
- Improvement
- Performance Improvement
- Backward Incompatible Change
- Build/Testing/Packaging Improvement
- Other

Short description (up to few sentences):

...

Detailed description (optional):

...

2019-09-30 19:01 UTC, alexey-milovidov commented
We have more than one such function. What about today(), yesterday(), randConstant()...

2019-09-30 19:01 UTC, alexey-milovidov requested changes
.

2019-10-01 10:40 UTC, KochetovNicolai commented
Still doesn't fix :(

2019-10-01 11:02 UTC, KochetovNicolai commented
Now won't fail.
Can't solve it better for now.

2019-10-01 21:53 UTC, alexey-milovidov commented
Missing test.

2019-10-01 21:54 UTC, alexey-milovidov commented on dbms/src/DataStreams/ConvertingBlockInputStream.cpp
> +    bool allow_different_constant_values_)
A huge complication. Better to find other way to fix.

2019-10-01 21:54 UTC, alexey-milovidov commented on dbms/src/DataStreams/ConvertingBlockInputStream.h
> +    bool allow_different_constant_values;
You have not explained it in code.

2019-10-01 21:55 UTC, alexey-milovidov commented
> today(), yesterday(), randConstant()

I don't think I have listed all the relevant functions.

2019-10-04 18:05 UTC, KochetovNicolai commented
Now actions from header are reused. Should fix for all functions.

2019-10-05 19:35 UTC, alexey-milovidov approved these changes

2019-10-05 19:35 UTC, merged