Parallel freeze of data parts
ClickHouse/ClickHouse pull request #71743
Opened 2024-11-11 13:52 UTC by kirillgarbar

`FREEZE` queries for large tables can take several hours, while the process itself parallels well, so it makes sense to do this.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added parallelism for `ALTER TABLE ... FREEZE` queries

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-11-12 22:42 UTC, geldot commented on programs/local/LocalServer.cpp
> +    const size_t drop_tables_threas = server_settings[ServerSetting::database_catalog_drop_table_concurrency];
typo -> "threads"

2024-11-22 09:40 UTC, pufit commented
We need a setting to control this behavior (e.g., in some tests, we want to run `FREEZE` sequentially).

Also, I'm not sure that we need a separate thread pool because this operation should be quite rare

2024-11-25 17:22 UTC, kirillgarbar commented
> Also, I'm not sure that we need a separate thread pool because this operation should be quite rare
Can you please clarify what you meant by not using a separate thread pool? I can create a local thread pool, or use another shared or global thread pool.

2024-12-03 03:43 UTC, pufit commented
Sorry for the late response, I missed your message. I suppose we can use a local thread pool here. This way, it will be easier to adjust the number of threads via query settings (it will also be an easy fix for broken tests).

2024-12-06 04:09 UTC, pufit approved these changes
LGTM

2025-08-27 10:04 UTC, Slach commented
@kirillgarbar maybe need to add separate test which test FREEZE/UNFREEZE with `max_threads = 3' ?

2025-10-17 21:26 UTC, alexey-milovidov approved these changes

2025-10-17 21:28 UTC, alexey-milovidov requested changes

2025-10-17 21:28 UTC, alexey-milovidov commented on tests/queries/0_stateless/01417_freeze_partition_verbose_zookeeper.sh
> -# setup
Let's copy-paste this test while not changing the old one. This will help if the new test or the new feature has problems.

2025-10-17 21:28 UTC, alexey-milovidov commented on tests/queries/0_stateless/01417_freeze_partition_verbose.sh
> -
And this test as well. Just add a new one without touching the old test.

2025-10-20 14:19 UTC, alexey-milovidov approved these changes

2025-10-20 22:13 UTC, alexey-milovidov commented
@kirillgarbar, ok, now let's check the fast test result.

2025-10-26 03:06 UTC, alexey-milovidov commented
@kirillgarbar, evertything is ok, but the docs check has failed. Either it was an unfortunate moment, and the PR needs an update, or something has to be fixed.

2025-10-27 18:16 UTC, alexey-milovidov commented
@kirillgarbar, I'm not entirely confident when I see these backup tests failing. Could you please either reconfirm or rerun?

2025-10-28 16:56 UTC, kirillgarbar commented
Judging by the logs, the backup tests have failed due to ZooKeeper failure, I guess restart will help

2025-11-02 17:46 UTC, merged