fix typo in ontime.md
ClickHouse/ClickHouse pull request #7285
Opened 2019-10-11 19:02 UTC by bi122

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

2019-10-11 20:28 UTC, blinkov requested changes

2019-10-11 20:28 UTC, blinkov commented on docs/en/getting_started/example_datasets/ontime.md
> +FROM ontime
```suggestion
FROM ontime
```

2019-10-11 20:28 UTC, blinkov commented on docs/en/getting_started/example_datasets/ontime.md
> +GROUP BY DestCityName
```suggestion
GROUP BY DestCityName
```

2019-10-11 20:28 UTC, blinkov commented on docs/en/getting_started/example_datasets/ontime.md
> +WHERE Year >= 2000 and Year <= 2010
```suggestion
WHERE Year >= 2000 and Year <= 2010
```

2019-10-15 08:43 UTC, blinkov commented
@bi122 those extra spaces were not removed

2019-10-17 11:56 UTC, blinkov approved these changes

2019-10-23 04:41 UTC, alexey-milovidov commented on docs/en/getting_started/example_datasets/ontime.md
> +``` sql
This whitespace - it is ok?

2019-10-23 15:32 UTC, merged