Feature: Highlight trailing whitespace in Pretty formats
ClickHouse/ClickHouse pull request #72996
Opened 2024-12-10 04:07 UTC by bradenburns

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add highlighting and underscoring to trailing whitespace in Pretty formats when colors is enabled - enabled with `output_format_pretty_highlight_trailing_whitespace` setting, which is false by default

Potentially closes #71590 

<!---
Directly edit documentation source files in the "docs" folder with the same pull-request as code changes

or

Add a user-readable short description of the changes that should be added to docs.clickhouse.com below.

2024-12-10 04:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=72996) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=72996) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: bdnburns<br/>:x: bradenburns<br/><hr/>**bdnburns** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=72996) it.</sub>

2024-12-10 15:52 UTC, alexkats requested changes
Thanks for the changes, from the first look the idea looks good, but there are some unnecessary changes here

2024-12-10 15:52 UTC, alexkats commented on preprocessed_configs/config.xml
Please, remove this file from changelist

2024-12-10 15:52 UTC, alexkats commented on contrib/NuRaft
What is the reason for updating this and other submodules (especially in this PR)?

2024-12-10 15:57 UTC, alexkats commented
I also believe that you used 2 different emails for commits, and one of those isn't tied to the GitHub account and as a result the CLA check has failed

2024-12-26 11:43 UTC, alexey-milovidov commented
Thanks, this is a great work! The PR contains a few minor problems with the code - I will resubmit it as another PR and acknowledge your authorship.

2024-12-26 12:24 UTC, alexey-milovidov commented
#73847

2024-12-26 12:24 UTC, closed without merging