Server: Special mode with empty listen_host : try listen v4 and v6
ClickHouse/ClickHouse pull request #730
Opened 2017-04-26 01:18 UTC by proller

without fatal error if protocol not supported (for docker and freebsd)

2017-04-26 01:18 UTC, proller commented
will auto-reformat after merge

2017-04-26 02:51 UTC, alexey-milovidov commented on dbms/src/Server/Server.cpp
> +            } catch (const std::exception & e) {
Need to catch only relevant exceptions.

2017-04-26 02:51 UTC, alexey-milovidov requested changes
.

2017-04-27 05:48 UTC, alexey-milovidov commented
You need to check exception code.
Now the behaviour is wrong for case of "Address already in use" error: half of server interfaces could be started.

2017-04-27 21:51 UTC, merged