[WIP] Speed up greatCircleDistance function with test
ClickHouse/ClickHouse pull request #7307
Opened 2019-10-14 10:17 UTC by stavrolia

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.
Speedup greatCircleDistance function with the code from Andrey Aksenov (for issue #5739)

Category (leave one):
    Performance Improvement

Short description (up to few sentences):
Speedup and test correctness of current function. Add perf test.

This PR made instead of #7254

2019-10-17 12:14 UTC, stavrolia commented
Functional test for greatCircleDistance now look only on distance ~340 km. It is sad, because on such distance using haversine formula (old version) we don't know what exact amount of meters it is. I checked the pair of coordinates from test in more precise and slow formula - vincenty, and the distance was 344.480489697 km. With haversine formula (in test) it is 343417 m, with formula of this PR it is 344579 m. So new version is better in this case, and current test is awfull.

2019-10-23 10:41 UTC, akuzm commented on dbms/src/Functions/greatCircleDistance.cpp
> +    static FunctionPtr create(const Context &) { GeodistInit(); return std::make_shared<FunctionGreatCircleDistance>(); }
`create()` is called in a query context, so calling `GeodistInit()` here might introduce a ThreadSanitizer warning, if two queries with this functions are executed simultaneously. A good place to do the initialization of global constants would be `registerFunction`, which is called at server startup in a single-threaded context.

2019-10-29 13:31 UTC, akuzm commented on dbms/src/Functions/greatCircleDistance.cpp
> +    static FunctionPtr create(const Context &) {  return std::make_shared<FunctionGreatCircleDistance>(); }
```suggestion
    static FunctionPtr create(const Context &) { return std::make_shared<FunctionGreatCircleDistance>(); }
```

2019-10-29 13:33 UTC, akuzm commented on dbms/src/Functions/greatCircleDistance.cpp
> +    while (f > 360)
fmodf()?

2019-10-29 13:35 UTC, akuzm commented
Let's merge the test first, so that we can see the performance improvement.

2019-11-02 21:50 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +static const double PI = 3.14159265358979323846;
Authorship and license must be specified.

(Andrey Aksenov, the author of original code, permitted to use this code in ClickHouse under the Apache 2.0 license.)

2019-11-02 21:51 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +const int GEODIST_TABLE_COS = 1024; // maxerr 0.00063%
static

2019-11-02 21:51 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +const int GEODIST_TABLE_ASIN = 512;
or anonymous namespace

2019-11-02 21:51 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +const int GEODIST_TABLE_K = 1024;
The name is not descriptive enough.

2019-11-02 21:51 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +static float g_GeoCos[GEODIST_TABLE_COS + 1];        ///< cos(x) table
Style.

2019-11-02 21:51 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +inline double sqr(double v)
static

2019-11-02 21:51 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +    return v*v;
Style.

2019-11-02 21:52 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +    return v*v;
We can unify both methods.

2019-11-02 21:52 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +    for (int i = 0; i <= GEODIST_TABLE_COS; i++)
++i

2019-11-02 21:52 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +    for (int i = 0; i <= GEODIST_TABLE_ASIN; i++)
int -> size_t

2019-11-02 21:54 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +void GeodistInit()
Style.

2019-11-02 21:55 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +static inline float GeodistFastCos(float x)
Style.

2019-11-02 21:56 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +static const double PI = 3.14159265358979323846;
The link to presentation from HighLoad++ Siberia an a video is also valuable.

2019-11-02 21:56 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +static const double PI = 3.14159265358979323846;
Also add a link to the original code.

2019-11-02 21:58 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +            float kk1 = g_GeoFlatK[i][0] + (g_GeoFlatK[i + 1][0] - g_GeoFlatK[i][0]) * (m - i);
If you have some explanation on algorithm, please provide it here (and rename variables accordingly).

2019-11-02 21:59 UTC, alexey-milovidov commented on dbms/src/Functions/greatCircleDistance.cpp
> +        static const float D = 2 * 6371000;
Constants should be also explained even if it's obvious for you.

2019-11-02 21:59 UTC, alexey-milovidov commented on dbms/tests/performance/great_circle_dist.xml
> +
And what is the improvement?

2019-11-02 21:59 UTC, alexey-milovidov requested changes
.

2019-12-03 01:34 UTC, merged

2019-12-03 01:34 UTC, alexey-milovidov commented
@stavrolia You did not answered what was the improvement.

2019-12-03 10:19 UTC, stavrolia commented
@alexey-milovidov I have seen smth like 35x but maybe it was on my laptop, I don't remember

2019-12-09 01:25 UTC, alexey-milovidov commented
Now it's about three times.