Fixing timezone option of formatDateTime
ClickHouse/ClickHouse pull request #73091
Opened 2024-12-11 03:52 UTC by ollidraese

The mysqlTimezoneOffset function, called for the formatDateTime(ts, '%W%z') scalar function only stores the '-' for negative timezone offsets but no '+' for positive offsets. The memory that is passed into this function is not necessarily initialized, so the function skips the character for the +/- and only writes the offset value. This leads to the corrupted output as described in the following issue:

https://github.com/ClickHouse/ClickHouse/issues/72877

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixing positive timezone formatting of formatDateTime scalar function.

### Documentation entry for user-facing changes

n/a

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-12-11 03:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=73091) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=73091) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=73091) it.</sub>

2024-12-11 13:26 UTC, alexkats commented
Thanks for the change, please add a test for it

2024-12-11 13:27 UTC, alexkats requested changes
Thanks for the change, please add a test for it. You can use something similar to reproduction in the issue and put you test in `tests/queries/0_stateless`

2024-12-11 13:29 UTC, alexkats commented
Also style check has failed because of trailing spaces

2024-12-13 11:03 UTC, alexkats commented on tests/queries/0_stateless/00718_format_datetime_1.sql
> +select formatDateTime(toDateTime64('2024-12-11 12:34:56.000', 3, 'UTC'), '%W%z');
In general new test cases should be created in a new file. Let's do it and add a couple more tests with different time zones (both negative and positive), so we'll have this check for all the cases in the future

2024-12-13 22:10 UTC, ollidraese commented
@alexkats I moved the tests (now multiple timezones) into a new file. The `clickhouse-test` script is failing for me (across different macos machines), so, this might be a script regression. I opened https://github.com/ClickHouse/ClickHouse/issues/73310 for this. Thx.

2024-12-13 22:49 UTC, alexkats approved these changes
LGTM, thanks again for the changes. Waiting for CI to finish.

2024-12-13 22:49 UTC, alexkats commented
> @alexkats I moved the tests (now multiple timezones) into a new file. The `clickhouse-test` script is failing for me (across different macos machines), so, this might be a script regression. I opened https://github.com/ClickHouse/ClickHouse/issues/73310 for this. Thx.

I'll try to take a look at the script later on.

2024-12-14 10:21 UTC, alexkats commented
Taking a brief look, all CI failures seem unrelated to the changes. Will take a closer look later

2024-12-17 21:09 UTC, merged