Decimal hex function
ClickHouse/ClickHouse pull request #7355
Opened 2019-10-16 15:35 UTC by millb

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- New Feature

Short description (up to few sentences):

Created function hex for Decimal numbers. It works like hex(reinterpretAsString()), but doesn't delete last zero bytes. 

Detailed description (optional):

...

2019-10-28 18:51 UTC, stavrolia commented
Could you please add docs?

2019-10-30 17:13 UTC, alexey-milovidov requested changes
I don't like code duplication with `tryExecuteFloat`.

2019-11-06 09:20 UTC, alexey-milovidov requested changes

2019-11-06 09:20 UTC, alexey-milovidov commented on docs/ru/query_language/functions/encoding_functions.md
> +Принимает аргументы типов: `String`, `unsigned integer`, `float`, `decimal`, `Date`, or `DateTime`. Возвращает строку, содержащую шестнадцатеричное представление аргумента. Используются заглавные бук
шетснадцатеричное - typo

2019-11-07 21:57 UTC, merged