Add parquet reading support of fixed_size_list
ClickHouse/ClickHouse pull request #73654
Opened 2024-12-20 02:29 UTC by J-Meyers

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Adds reading arrow fixed_size_list as an Array instead of treating it as an unsupported type

Closes #68209

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-12-20 02:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=73654) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/ClickHouse?pullRequest=73654) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/ClickHouse?pullRequest=73654) it.</sub>

2024-12-28 22:32 UTC, alexey-milovidov requested changes
Needs a test.

2025-01-07 01:00 UTC, alexey-milovidov approved these changes

2025-01-09 21:11 UTC, J-Meyers commented
@alexey-milovidov The AST failure of Null 128 test seems unrelated and I am unable to replicate the error on the stateless test, not sure if you understand what's going on with it, running it locally with the UTC timezone and diff the output with the reference I see no output

2025-01-09 21:58 UTC, alexey-milovidov commented
Let's check the failure of the test for Parquet under UBSan: https://s3.amazonaws.com/clickhouse-test-reports/73654/f08cf3f175a40c54dccac8fcbaeb0f793f6482d4/stateless_tests__ubsan__[2_2].html

2025-01-16 17:48 UTC, J-Meyers commented
> Let's check the failure of the test for Parquet under UBSan: [https://s3.amazonaws.com/clickhouse-test-reports/73654/f08cf3f175a40c54dccac8fcbaeb0f793f6482d4/stateless_tests__ubsan__[2_2].html](https://s3.amazonaws.com/clickhouse-test-reports/73654/f08cf3f175a40c54dccac8fcbaeb0f793f6482d4/stateless_tests__ubsan__%5B2_2%5D.html)

I think it was due to the issue https://github.com/ClickHouse/ClickHouse/issues/74512 not related to this PR it seems to be resolved after merging now that that has been fixed

2025-01-23 18:51 UTC, J-Meyers commented
@alexey-milovidov just a ping, also that other failing test 02125 looking at this issue #65589 also seems to have issues

2025-01-23 20:00 UTC, merged