Ensure that a valid utf8 string is used for the serialization json.
ClickHouse/ClickHouse pull request #73668
Opened 2024-12-20 09:43 UTC by MikhailBurdukov

### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Ensure that a valid utf8 string is used for serialization json.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Motivation

By now if the user used non-utf8 characters in the column name (with `Create` or `Alter`) then after restart, all parts with such column in `serialization.json` file will be `broken_on_start`,  so user should manually recover these parts by removing columns and moving parts from detached.

As @aalexfvk suggested (#72281), we got 2 options: prevent using non-utf8 characters or support other encodings with escaping methods. I believe that the first option is preferable, because
https://clickhouse.com/docs/en/install#launch
```
The terminal must use UTF-8 encoding.
```
https://clickhouse.com/docs/en/development/style#how-to-write-code
```
Use UTF-8 everywhere. Use std::string and char *. Do not use std::wstring and wchar_t. 
```

Actually the PR won't resolve the problem fully. But it should protect from creating the parts that will be broken after restarting the server and make the issue visible for users. 
We will also make a separate with validating column names for other entities,  but it seems that at the moment the problem can only occur with objects that use json files inside.

Related issues: https://github.com/ClickHouse/ClickHouse/issues/69329 https://github.com/ClickHouse/ClickHouse/issues/72281

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-12-23 14:05 UTC, divanik commented
Hi, @MikhailBurdukov. Could you please consider additional JSON string requirements for column_name validation? While UTF-8 validation is important, we should also handle control characters (0x00-0x1F) and proper escaping of quotes and backslashes to ensure proper JSON serialization. This would help prevent potential issues down the line.

2024-12-23 15:49 UTC, divanik commented
@MikhailBurdukov, we discussed your PR in our reliability meeting and reached the following conclusions:

We'll focus first on UTF-8 encoding validation and address escape characters later
We agree with forbidding non-UTF-8 encoding at table creation time
This will be a forward-only change (I've removed the backport tags and marked it as backward-incompatible)
The setting should be internal and not exposed to users. @nikitamikhaylov, @Algunenano - could you please advise on the best way to implement this?

The PR is ready to merge once we resolve the setting visibility issue, as all other issues are already addressed.

2024-12-23 16:35 UTC, divanik reviewed
Minor issues

2024-12-23 16:35 UTC, divanik commented on src/Core/Settings.cpp
> +    DECLARE(Bool, use_non_utf8_chars_in_schema, false, R"(
This setting should be unavailable for cloud users

2024-12-24 01:13 UTC, alexey-milovidov commented
ClickHouse is always charset-agnostic - we allow arbitrary binary data in the String data type; - there is no special distinction for UTF-8. Compared to other programming languages (Python, Java, JavaScript, Perl, PHP, Rust), this is the right decision. But there is a problem - somehow, we let JSON for certain metadata files, and because it does not support arbitrary binary data, this is a mistake. We should not have used JSON in the first place.

The solution should be to allow arbitrary binary data in the JSON files.
For example, if you want to write a string containing two 0x80 bytes in JSON, followed by `"`, it will be serialized as follows:

```
milovidov@milovidov-pc:~/Photo/Iceland$ ch -q "SELECT '\x80\x80\"' AS x FORMAT JSONEachRow" | xxd
00000000: 7b22 7822 3a22 8080 5c22 227d 0a         {"x":"..\""}.
```

It should be able to deserialize back transparently.

2024-12-24 01:15 UTC, alexey-milovidov requested changes
.

2024-12-24 01:16 UTC, alexey-milovidov commented
The first step should be - to change JSON parsers for all internal metadata files so they will support arbitrary binary data.
The second step should be - to forbid creating columns with invalid UTF-8, because it will be a good restriction anyway.

2024-12-24 09:58 UTC, divanik commented
> The first step should be - to change JSON parsers for all internal metadata files so they will support arbitrary binary data.
The second step should be - to forbid creating columns with invalid UTF-8, because it will be a good restriction anyway.

I don't think that this PR is about changing json metadata parsers. If done, this should be done in another one

2024-12-25 09:30 UTC, alexey-milovidov commented
Yes.

2024-12-25 10:03 UTC, MikhailBurdukov commented
> I do not understand how this is a blocker for the current PR, tbh

I guess my vision is close to @divanik 's one

>The first step should be - to change JSON parsers for all internal metadata files so they will support arbitrary binary data.
The second step should be - to forbid creating columns with invalid UTF-8, because it will be a good restriction anyway.

don't understand why we have to do in this particular order. In my opinion, these improvements don't really block each other.
Moreover changing the metadata format can be a long-term task, but the problem can be really critical:  without restrictions, the user will lose all their data in cases where an encoding other than utf 8 is used. And all this time, while we are json is used for serialization, there will be a critical bug in the code.
@alexey-milovidov 
Could you please share why we can't merge pr until the first step is completed?

2025-02-14 16:15 UTC, closed without merging