DOCS-8799: EN review, RU translation. SHOW TABLES update and toc restructurization.
ClickHouse/ClickHouse pull request #7367
Opened 2019-10-17 10:20 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Docs for #6944.

2019-10-26 13:09 UTC, blinkov requested changes

2019-10-26 13:09 UTC, blinkov commented on docs/ru/query_language/show.md
> +Возвращает один столбец statement типа `String`, содержащий одно значение - запрос `CREATE`, с помощью которого создана указанная таблица.
```suggestion
Возвращает один столбец типа `String` с именем statement, содержащий одно значение — запрос `CREATE TABLE`, с помощью которого была создана указанная таблица.
```

2019-10-26 13:09 UTC, blinkov commented on docs/ru/query_language/show.md
> +Смотрите также раздел "Форматы".
ссылка? и при чем тут вообще форматы?

2019-10-26 13:09 UTC, blinkov commented on docs/ru/query_language/show.md
> +Выдаёт таблицу, содержащую столбцы:
какие у них типы данных? может таблицей это оформить, а не плоским списком?

2019-10-26 13:09 UTC, blinkov commented on docs/ru/query_language/show.md
> +**user** - пользователь, под которым был задан запрос. Следует иметь ввиду, что при распределённой обработке запроса на удалённые серверы запросы отправляются под пользователем 'default'. И SHOW PROC
почему одинарные кавычки вокруг default, а show processlist не в backtick?

2019-10-26 13:09 UTC, blinkov commented on docs/ru/query_language/show.md
> +**address** - имя хоста, с которого был отправлен запрос. При распределённой обработке запроса на удалённых серверах — это имя хоста-инициатора запроса. Чтобы проследить, откуда был задан распределён
хост-инициатор и сервер-инициатор — по идее одно и то же, да и вообще имхо так не пишется через дефис , когда слева одно слово, а справа два.

2019-10-26 13:09 UTC, blinkov commented on docs/ru/query_language/show.md
> +**rows_read**, **bytes_read** - сколько было прочитано строк, байт несжатых данных при обработке запроса. При распределённой обработке запроса суммируются данные со всех удалённых серверов. Именно эт
имхо лучше не объединять их, можно запутаться

2019-10-26 13:09 UTC, blinkov commented on docs/ru/query_language/show.md
> +**memory_usage** - текущее потребление оперативки в байтах. Смотрите настройку 'max_memory_usage'.
ссылка?

2019-10-26 13:09 UTC, blinkov commented on docs/ru/query_language/show.md
> +**query** - сам запрос. В запросах INSERT данные для вставки не выводятся.
```suggestion
**query** - текст запроса. В запросах INSERT данные для вставки не выводятся.
```

2019-10-26 13:09 UTC, blinkov commented on docs/ru/query_language/show.md
> +**query_id** - идентификатор запроса. Непустой, только если был явно задан пользователем. При распределённой обработке запроса идентификатор запроса не передаётся на удалённые серверы.
```suggestion
**query_id** - идентификатор запроса. Задается пользователем явно, по умолчанию пустая строка. При распределённой обработке запроса идентификатор запроса не передаётся на удалённые серверы.
```

2019-10-31 13:43 UTC, BayoNet commented
Я удалил описание полей из запроса из SHOW PROCESS и обновил их в system.processes.

2019-11-01 14:20 UTC, merged