DOCS-7719: EN review, RU translation. Columns matcher
ClickHouse/ClickHouse pull request #7373
Opened 2019-10-17 14:58 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation for #6038

2019-10-26 13:42 UTC, blinkov requested changes

2019-10-26 13:42 UTC, blinkov commented on docs/en/query_language/select.md
> +[Expressions](syntax.md#syntax-expressions) specified in the `SELECT` clause are analyzed after the calculations for all the clauses listed above are completed. More specifically, expressions above t
we'd better rewrite it, because it's not really obvious what "above" and "below" means here

2019-10-26 13:42 UTC, blinkov commented on docs/ru/query_language/select.md
> +Чтобы включить в результат несколько стоблцов, выбрав их имена с помощью регулярных выражений [re2](https://en.wikipedia.org/wiki/RE2_(software)), используйте выражение `COLUMNS`.
ссылки на русском не было?

2019-10-26 13:42 UTC, blinkov commented on docs/ru/query_language/select.md
> +Аккуратно используйте функции, поскольку выражение `COLUMNS` возвращает переменное число столбцов и если функция не поддерживает результирующее число аргументов, то ClickHouse генерирует исключение.
```suggestion
Аккуратно используйте функции, поскольку выражение `COLUMNS` возвращает переменное число столбцов и если функция не поддерживает получившееся число аргументов, то ClickHouse генерирует исключение.
```

2019-10-26 13:42 UTC, blinkov commented on docs/en/query_language/select.md
> +You can use multiple `COLUMNS` expressions in a query and apply functions to them.
needs clarifications:
* how actually applying functions works: columns are passed as separate arguments, what happens with additional arguments, etc
* whether an order of columns is guaranteed to be alphabetical or not

2019-10-26 13:42 UTC, blinkov commented on docs/en/query_language/select.md
> +Columns that matched the `COLUMNS` expression can be different types. If `COLUMNS` doesn't match any columns and is the only expression in `SELECT`, ClickHouse throws an exception.
why these sentences are in same paragraph? sounds completely unrelated

```suggestion
Columns that matched the `COLUMNS` expression can have different data types. If `COLUMNS` doesn't match any columns and is the only expression in `SELECT`, ClickHouse throws an exception.
```

2019-11-06 06:08 UTC, BayoNet commented on docs/ru/query_language/select.md
> +Чтобы включить в результат несколько стоблцов, выбрав их имена с помощью регулярных выражений [re2](https://en.wikipedia.org/wiki/RE2_(software)), используйте выражение `COLUMNS`.
Честно поискал ещё раз, не нашел.

2019-11-07 14:08 UTC, merged