fix setting materialized_views_ignore_errors
ClickHouse/ClickHouse pull request #73802
Opened 2024-12-24 15:45 UTC by CheSema

Fixes https://github.com/ClickHouse/ClickHouse/issues/73015

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory
and will run independently of the checks below:

- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64
- [ ]  Exclude: All with release
- [ ]  Exclude: All with debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

2024-12-27 17:16 UTC, Michicosun requested changes

2024-12-30 11:40 UTC, CheSema commented on src/Processors/Transforms/ExceptionKeepingTransform.cpp
> +            cancel();
Let me do it in separate PR. Because it is not right that `onException` behaves as `onFinish` in `MessageQueueueSink`

2024-12-30 11:49 UTC, CheSema commented on src/Processors/Transforms/buildPushingToViewsChain.cpp
> +        IProcessor * finalizing_processor = nullptr;
I missed the idea not to wrap exception in each level of materialized view, in that idea I need to distinguish wrapped exceptions on `FinalizingViewsTransform`. 
But lets remove it and wrap each time, in that case there is less code to write and read.

2024-12-30 13:04 UTC, CheSema commented on src/Processors/Transforms/buildPushingToViewsChain.cpp
>      for (auto & view : views_data->views)
I like it. But we have to wait c++23.

2025-02-17 09:35 UTC, Michicosun commented
The errors seem to be related

2025-05-23 11:13 UTC, closed without merging