Add syntax "query1 PARALLEL WITH query2".
ClickHouse/ClickHouse pull request #73983
Opened 2024-12-30 14:32 UTC by vitlibar

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add syntax `query1 PARALLEL WITH query2 PARALLEL WITH query3 ... PARALLEL WITH queryN`
That means subqueries `{query1, query2, ... queryN}` are allowed to run in parallel with each other (and it's preferable).

Query `query1 PARALLEL WITH query2 PARALLEL WITH query3 ... PARALLEL WITH queryN` is expected to be faster than just a sequence of queries `query1; query2; query3; ... queryN` in many cases.

2024-12-30 15:05 UTC, alexey-milovidov commented
Sounds interesting!

There is one potential source of confusion:

1. When you do UNION ALL for SELECTs, it is parallel by default.
2. We have a task for allowing sequential UNION ALL, either with a setting or with a new syntax - it is needed for certain rare scenarios.
3. When someone notes the existence of `IN PARALLEL WITH` syntax, one might think that it could be applicable for SELECT, or that UNION ALL is not parallel by default.
4. However, we cannot reuse the UNION ALL syntax for CREATE or INSERT SELECT, which justifies the need for a separate syntax.

Does the proposed syntax correspond to anything in other database systems?

Taking into account all considerations, the syntax looks ok to me.

2025-01-02 12:33 UTC, vitlibar commented
In a separate PR later I'll add a special processing for `ON CLUSTER` queries and also for queries related to a replicated database. For example, the following query
```
CREATE TABLE replicated_db.table1 (a Int32) ENGINE=ReplicatedMergeTree() SETTINGS ...
    PARALLEL WITH
CREATE TABLE replicated_db.table2 (b Int32) ENGINE=ReplicatedMergeTree() SETTINGS ...
    PARALLEL WITH
CREATE TABLE replicated_db.table3 (c Int32) ENGINE=ReplicatedMergeTree() SETTINGS ...
```
will be executed as one DDLWorker's task and thus it can be faster than just a sequence of three CREATE TABLE queries.

2025-01-02 14:32 UTC, vitlibar commented
> Does the proposed syntax correspond to anything in other database systems?

No.

I've done more investigations today and found that MySQL has a bit similar [syntax](https://dev.mysql.com/doc/refman/8.4/en/do.html):

```
DO expr [, expr] ...
```

This statement executes all `exprs` and discards the results. MySQL executes `exprs` not in parallel, but I think we could take this syntax as a basis and thus instead of `IN PARALLEL WITH` or `PARALLEL WITH` we can implement syntax

```
DO [PARALLEL] expr [, expr]
```

Perhaps it's better.

2025-01-02 14:45 UTC, alexey-milovidov commented
I like your syntax, no need to follow MySQL's `DO` (also because comma will lead to ambiguity)

2025-01-03 11:27 UTC, Michicosun commented on src/Interpreters/InterpreterParallelWithQuery.cpp
> +    }
Maybe it would be better to build 1 big pipeline using https://github.com/ClickHouse/ClickHouse/blob/fe35e6d3def4c73755e7bd20b65ebe2a2e0a52a4/src/QueryPipeline/QueryPipeline.h#L133, which already run with max_threads setting? Because right not this can spawn a lot of threads.

In general, it seems to be accurate to allow any queries if the completed pipelines are built for them. For example, it will be possible to run many SELECT INTO OUTFILE.

What do you think?

2025-01-03 15:47 UTC, vitlibar commented on src/Interpreters/InterpreterParallelWithQuery.cpp
> +    }
I implemented using 1 big pipeline.

Also I changed the code to allow any queries if the completed pipelines are built for them.

However it doesn't work for `SELECT INTO OUTFILE` because the server executes `SELECT INTO OUTFILE` just as a regular `SELECT`, i.e. with generating an output, and then the client writes that output into a file.

2025-01-06 12:12 UTC, vitlibar commented
CI failures are unrelated:
- [test_async_insert_adaptive_busy_timeout/test.py::test_compare_parallel_inserts_durations_for_adaptive_and_fixed_async_timeouts](https://s3.amazonaws.com/clickhouse-test-reports/73983/c13827be9a38265a08ed0e648c8996463bfe204c/integration_tests__asan__old_analyzer__[1_6].html) - see https://github.com/ClickHouse/ClickHouse/issues/74185

2025-01-06 12:49 UTC, Michicosun requested changes

2025-01-06 12:49 UTC, Michicosun commented on src/Interpreters/InterpreterParallelWithQuery.cpp
> +    }
Why do you need to parallel plan creation? It should be fast.

2025-01-06 12:49 UTC, Michicosun commented on src/Interpreters/InterpreterParallelWithQuery.h
> +    QueryPipeline big_pipeline TSA_GUARDED_BY(mutex);
```suggestion
    QueryPipeline combined_pipeline TSA_GUARDED_BY(mutex);
```

2025-01-06 12:49 UTC, Michicosun commented on src/Interpreters/InterpreterParallelWithQuery.h
> +    void waitBigPipeline();
```suggestion
    void executeCombinedPipeline();
```

2025-01-06 12:49 UTC, Michicosun commented on src/Interpreters/InterpreterParallelWithQuery.cpp
> +        schedule = threadPoolCallbackRunnerUnsafe<void>(*thread_pool, "ParallelWithQry");
Better to use ThreadPoolCallbackRunnerLocal<void>

2025-01-06 12:49 UTC, Michicosun commented on src/Parsers/ASTParallelWithQuery.cpp
> +            ostr << settings.nl_or_ws << indent_str;
If I understand correctly it will be formatted like

```
query1     PARALLEL WITH query2     PARALLEL WITH query3
```

if one_line

2025-01-06 12:49 UTC, Michicosun commented on tests/queries/0_stateless/03305_parallel_with.sql
Can you also add an error handling test?

2025-01-06 13:24 UTC, vitlibar commented on src/Interpreters/InterpreterParallelWithQuery.cpp
> +    }
There can be statements which do all the work in their interpreter without using any plan at all. For example, `CREATE TABLE`. It's better to execute such things in parallel.

2025-01-06 13:34 UTC, vitlibar commented on src/Parsers/ASTParallelWithQuery.cpp
> +            ostr << settings.nl_or_ws << indent_str;
```
settings.one_line = true
indent_str = ""
settings.nl_or_ws = ' '

if (i != 0)
{
    ostr << ' ' << "";
    ostr << "PARALLEL WITH"
    ostr << ' ';
}
```

2025-01-06 19:44 UTC, vitlibar commented on src/Interpreters/InterpreterParallelWithQuery.h
> +    QueryPipeline big_pipeline TSA_GUARDED_BY(mutex);
done

2025-01-06 19:44 UTC, vitlibar commented on src/Interpreters/InterpreterParallelWithQuery.cpp
> +        schedule = threadPoolCallbackRunnerUnsafe<void>(*thread_pool, "ParallelWithQry");
done

2025-01-06 19:45 UTC, vitlibar commented on src/Interpreters/InterpreterParallelWithQuery.h
> +    void waitBigPipeline();
done

2025-01-07 16:02 UTC, vitlibar commented
CI failures are unrelated:
- [01700_deltasum](https://s3.amazonaws.com/clickhouse-test-reports/73983/a3bcd4952b5089487ebb6947d74ca4a70a2cf993/stateless_tests__debug__[2_2].html) - flaky test, see https://github.com/ClickHouse/ClickHouse/pull/74240
- [00814_replicated_minimalistic_part_header_zookeeper](https://s3.amazonaws.com/clickhouse-test-reports/73983/a3bcd4952b5089487ebb6947d74ca4a70a2cf993/stateless_tests__debug__s3_storage_.html) - flaky test, see https://github.com/ClickHouse/ClickHouse/issues/70339
- [Logical error: 'RangeReader read 4 rows, but 16 expected.'](https://s3.amazonaws.com/clickhouse-test-reports/73983/a3bcd4952b5089487ebb6947d74ca4a70a2cf993/ast_fuzzer__debug_.html) - known issue, see https://github.com/ClickHouse/ClickHouse/issues/62741

2025-01-07 16:09 UTC, Michicosun requested changes
In general lgtm, left some simple comments.

2025-01-07 16:09 UTC, Michicosun commented on src/Interpreters/InterpreterParallelWithQuery.h
> +    std::unique_ptr<ThreadPool> thread_pool;
This thread pool is only needed during the plan build phase, but lives the entire time of the query, while not using the running threads. Perhaps it is better to move it and runner to executeSubqueries and remove from class fields.

2025-01-07 16:09 UTC, Michicosun commented on src/Interpreters/InterpreterParallelWithQuery.h
> +    std::atomic<bool> error_found = false;
same

2025-01-07 17:08 UTC, vitlibar commented on src/Interpreters/InterpreterParallelWithQuery.h
> +    std::atomic<bool> error_found = false;
I made `error_found` a local variable in `executeSubqueries()`.

2025-01-07 17:13 UTC, vitlibar commented on src/Interpreters/InterpreterParallelWithQuery.h
> +    std::unique_ptr<ThreadPool> thread_pool;
I added dropping of the thread pool immediately after it stopped being used.
I'd like to keep the thread pool and the runner as class fields though because it doesn't seem very convenient to add two more arguments to `executeSubqueries()`.

2025-01-07 17:19 UTC, Michicosun approved these changes

2025-01-08 17:33 UTC, vitlibar commented
CI failures are unrelated:
- [test_storage_s3/test_invalid_env_credentials.py::test_with_invalid_environment_credentials](https://s3.amazonaws.com/clickhouse-test-reports/73983/3f1181a6a1d390302d0e4dd57cd10cfbd611701d/integration_tests__tsan__[6_6].html)

2025-01-08 18:19 UTC, merged