Description of distributed_product_mode was added.
ClickHouse/ClickHouse pull request #740
Opened 2017-04-28 16:31 UTC by BayoNet

2017-04-28 22:59 UTC, Tri0L commented on docs/ru/query_language/queries.rst
> +::
Не совсем верно убирать code-block, в некоторых рендерах мы теряем подсветку SQL синтаксиса.

2017-04-29 03:18 UTC, alexey-milovidov requested changes

2017-04-29 03:18 UTC, alexey-milovidov commented on docs/ru/settings/settings.rst
> +ClickHouse применяет настройку в том случае, когда в подзапросах на любом уровне встретилась распределенная таблица, которая существует на локальном сервере и имеет больше одного шарда.
Только подзапросы для IN, JOIN.

Только если в секции FROM используется распределённая таблица.
Именно поэтому настройка называется distributed_**product**_mode - настройка поведения в случае, если запрос содержит произведение распределённых таблиц.

Не используется в случае табличной функции remote.

2017-05-04 12:20 UTC, BayoNet commented on docs/ru/query_language/queries.rst
> +::
А я как раз таки потому и убрал, что у меня подсветки не было :-).
Строка  ":) CREATE TABLE arrays_test (s String, arr Array(UInt8)) ENGINE = Memory" не распознается Сфинксовским хайлайтером как sql даже несмотря на прямое указание code-block:: sql. Видимо это происходит из-за символов ":)" в начале строки. Я предпочел убрать code-block, чем менять оригинальный текст.

2017-05-16 18:44 UTC, merged