Implement changing collapsing sign column table constraint
ClickHouse/ClickHouse pull request #74014
Opened 2024-12-31 14:55 UTC by cwurm

Moved the implementation of the table setting `add_implicit_sign_column_constraint_for_collapsing_engine` to make it changeable and apply it automatically during insert. The previous implementation did not allow changing the setting after table creation and also led to some metadata inconsistency.

I originally tried to keep the current implementation as is with https://github.com/ClickHouse/ClickHouse/pull/73606 but ran into some issues caused by a table setting changing the table definition (adding/removing a constraint). A standard constraint can also be inadvertently changed by the user. See https://github.com/ClickHouse/ClickHouse/pull/73606#issuecomment-2561227887.

Moving the implementation into `InterpreterInsertQuery` also has the advantage of making it easy to implement a query setting in the future. This would likely be needed if we wanted to change the default of `optimize_on_insert` to `false` (since it heavily slows down inserts into non-standard *MergeTree tables).

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow changing `add_implicit_sign_column_constraint_for_collapsing_engine` after table creation.

2025-01-01 09:54 UTC, cwurm commented
Test failures seem unrelated:
- https://github.com/ClickHouse/ClickHouse/issues/72458
- https://github.com/ClickHouse/ClickHouse/issues/59114

2025-01-02 19:18 UTC, Michicosun requested changes
LGTM, just a few remarks.

BTW: I also think it's better to check this setting in Insert Interpreter

2025-01-02 19:18 UTC, Michicosun commented on tests/queries/0_stateless/02918_implicit_sign_column_constraints_for_collapsing_engine.sh
I think it is worth including the queries from your comment https://github.com/ClickHouse/ClickHouse/pull/73606#issuecomment-2561227887 into the tests to check for invalid results.

2025-01-02 19:18 UTC, Michicosun commented on docs/en/operations/settings/merge-tree-settings.md
> +If true, add an implicit constraint for the `sign` column of CollapsingMergeTree tables so only valid values (`1` and `-1`) are allowed.
```suggestion
If true, adds an implicit constraint for the `sign` column of CollapsingMergeTree table to allow only valid values (`1` and `-1`).
```

2025-01-03 13:32 UTC, cwurm commented on docs/en/operations/settings/merge-tree-settings.md
> +If true, add an implicit constraint for the `sign` column of CollapsingMergeTree tables so only valid values (`1` and `-1`) are allowed.
Thanks, I've changed it and also included that this covers VersionedCollapsingMergeTree as well.

2025-01-03 13:34 UTC, cwurm commented on tests/queries/0_stateless/02918_implicit_sign_column_constraints_for_collapsing_engine.sh
Add some `SHOW CREATE TABLE` statements and check the output for a constraint definition? I can do it, but the code that added the constraint to the table definition was completely removed in this PR, so I'm not sure what it would be testing for.

2025-01-03 13:41 UTC, Michicosun commented on tests/queries/0_stateless/02918_implicit_sign_column_constraints_for_collapsing_engine.sh
Actually I was talking about EXPLAIN PIPELINE, but yeah, it won't add more checks, let's leave it as it is.

2025-01-03 13:43 UTC, Michicosun approved these changes
LGTM

2025-01-04 11:00 UTC, cwurm commented
The test failure seems unrelated, a timeout during JSON deserialization.

2025-01-06 13:27 UTC, Michicosun commented
@cwurm Could you please merge master to restart CI?

2025-01-06 19:14 UTC, merged