Docs dateDiff
ClickHouse/ClickHouse pull request #7478
Opened 2019-10-24 15:19 UTC by godfreyd

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation

2019-10-26 13:22 UTC, blinkov requested changes

2019-10-26 13:22 UTC, blinkov commented on docs/en/query_language/functions/date_time_functions.md
> +    | unit   |
why not just plain list?

2019-10-26 13:22 UTC, blinkov commented on docs/en/query_language/functions/date_time_functions.md
> +Returns the difference between two time values.
```suggestion
Returns the difference between two Date or DateTime values.
```

2019-10-26 13:22 UTC, blinkov commented on docs/en/query_language/functions/date_time_functions.md
> +Difference between `startdate` and `enddate` expressed in `unit`.
Needs clarifications:
* What is the data time of the result?
* How fractional results are handled? Rounding?
* What happens if startdate is later than enddate. Negative result? Absolute difference? Error?

2019-10-26 13:22 UTC, blinkov commented on docs/en/query_language/functions/date_time_functions.md
> +- `timezone` — Optional parameter. If specified, it is applied to both `startdate` and `enddate`. If not specified, timezones of `startdate` and `enddate` are used. If they are not the same, the resu
needs separate example, if timezones are forced to be the same, why do they affect the result?

2019-10-26 13:22 UTC, blinkov commented on docs/en/query_language/functions/date_time_functions.md
> +    |month   |
Needs detailed explanation on how exactly does the months and beyond work.
For example, difference between December 31 and January 1 is one month or zero?

2020-02-02 21:49 UTC, alexey-milovidov commented
No chance this PR will be finished.

2020-02-02 21:49 UTC, merged