add easy diff for document tracking
ClickHouse/ClickHouse pull request #7498
Opened 2019-10-27 18:24 UTC by zhang2014

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category :
- Documentation

Detailed description (optional):

for example:
```
☁  tools [docs/diff_script] ⚡ ./easy_diff.py zh/data_types
```
use stdout print : 
```
Need Transaction document:/Users/coswde/Source/ClickHouse/docs/tools/../../docs/en/data_types/uuid.md
```
use git pager print: 
````
diff --git a/docs/en/data_types/domains/ipv6.md b/docs/en/data_types/domains/ipv6.md
index 1bfbe3400b..e2abaff017 100644
--- a/docs/en/data_types/domains/ipv6.md
+++ b/docs/en/data_types/domains/ipv6.md
@@ -4,13 +4,13 @@
 
 ### Basic Usage
 
-``` sql
+```sql
 CREATE TABLE hits (url String, from IPv6) ENGINE = MergeTree() ORDER BY url;
 
 DESCRIBE TABLE hits;
 ```
 
-```
+```text
 ┌─name─┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┐
 │ url  │ String │              │                    │         │                  │
 │ from │ IPv6   │              │                    │         │                  │
@@ -19,19 +19,19 @@ DESCRIBE TABLE hits;
 
 OR you can use `IPv6` domain as a key:
 
-``` sql
+```sql
 CREATE TABLE hits (url String, from IPv6) ENGINE = MergeTree() ORDER BY from;
... MORE
````

2019-10-27 18:40 UTC, zhang2014 commented
This script is based on the assumption that documents in other languages are fully synchronized with the en document at a commit.

2019-10-28 12:58 UTC, blinkov requested changes

2019-10-28 12:58 UTC, blinkov commented on docs/tools/easy_diff.py
> +def diffFile(reference_file, working_file, git, temp_diff):
```suggestion
def diff_file(reference_file, working_file, git, temp_diff):
```
snake_case style is more common in python for function names and as far as I remember nearby scripts use it, let's change this? (here and below)

2019-10-28 12:58 UTC, blinkov commented on docs/tools/easy_diff.py
> +CLICK_HOUSE_REPO_HOME = os.path.join(os.path.dirname(SCRIPT_PATH), '../../')
not so important, but I think:
*  it's better to write `CLICKHOUSE` in one word
* `os.path.join(os.path.dirname(SCRIPT_PATH), '..', '..')` looks better

2019-10-28 12:58 UTC, blinkov commented on docs/tools/easy_diff.py
> +            return 1
shouldn't we use this number as exit code below where we call these functions?

2019-10-28 12:58 UTC, blinkov commented on docs/tools/easy_diff.py
> +    working_language = os.path.join(CLICK_HOUSE_REPO_HOME, 'docs', sys.argv[1])
We'd better start using `argparse` module right away to make it more flexible and extendable. For example there could be an option to skip the git pager part.

2019-10-28 12:59 UTC, blinkov commented
> This script is based on the assumption that documents in other languages are fully synchronized with the en document at a commit.

@zhang2014 it's better to add this comment to `--help` output or at least in code comments

2019-11-01 15:33 UTC, alexey-milovidov approved these changes

2019-11-01 15:34 UTC, merged