Docs(bitmapSubsetLimit): Added bitmapSubsetLimit description
ClickHouse/ClickHouse pull request #7525
Opened 2019-10-29 11:23 UTC by godfreyd

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Documentation

2019-10-30 21:12 UTC, alexey-milovidov commented on docs/en/query_language/functions/bitmap_functions.md
> +Returns a subset of a bitmap. The subset values are sorted in ascending order and its cardinality and starting point do not exceed the corresponding input values.
Don't understand.

2019-10-30 21:13 UTC, alexey-milovidov commented on docs/ru/query_language/functions/bitmap_functions.md
> +Возвращает подмножество битового массива. Значения подмножества сортируются в порядке возрастания, а его верхний предел и начальная точка не превышают соответствующие входные значения.
That's a bitmap, not a bit array.

2019-10-30 21:13 UTC, alexey-milovidov commented on docs/ru/query_language/functions/bitmap_functions.md
> +Возвращает подмножество битового массива. Значения подмножества сортируются в порядке возрастания, а его верхний предел и начальная точка не превышают соответствующие входные значения.
Don't understand the logic of this function.

2019-10-30 21:14 UTC, alexey-milovidov requested changes
This documentation does not make sense for me.

2019-11-27 09:14 UTC, godfreyd commented
Fixed

2020-02-02 21:50 UTC, merged

2020-02-02 21:50 UTC, alexey-milovidov commented
Ok.