Fix "create as select" parsing
ClickHouse/ClickHouse pull request #7542
Opened 2019-10-30 13:08 UTC by hczhcz

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Bug Fix

Short description (up to few sentences):

Fix the parsing of queries like `CREATE TABLE ... AS (SELECT (1, 2))`

2019-10-30 17:33 UTC, alexey-milovidov approved these changes

2019-10-30 17:34 UTC, alexey-milovidov requested changes
Missing functional test.

2019-10-31 08:30 UTC, alexey-milovidov approved these changes

2019-11-01 21:58 UTC, merged

2019-11-11 09:23 UTC, alesapin commented
conflicts in 19.15