Check column for __getScalar() (avoids assertion)
ClickHouse/ClickHouse pull request #7599
Opened 2019-11-03 18:46 UTC by azat

Category (leave one):
-non-significant

Can be triggered using the following query:

      CREATE TABLE foo (key String, macro String MATERIALIZED __getScalar(key)) Engine=Null();

Trace:
```
    3. 0x00007ffff6d5d526 __assert_fail (libc.so.6)
    4. 0x00007ffff41fd931 boost::intrusive_ptr<DB::IColumn const>::operator*() const (libclickhouse_functionsd.so)
    5. 0x00007ffff41fcd64 COW<DB::IColumn>::IntrusivePtr<DB::IColumn const>::operator*() const & (libclickhouse_functionsd.so)
    6. 0x00007ffff4dc5944 DB::FunctionGetScalar::getReturnTypeImpl() const (libclickhouse_functionsd.so)
```

*(Even though it is internal I guess it is better to fix it)*

Refs: #7392
Cc: @amosbird

2019-11-03 21:25 UTC, alexey-milovidov approved these changes

2019-11-03 21:27 UTC, alexey-milovidov requested changes
Missing functional test.

2019-11-03 21:31 UTC, azat commented
I thought that since it is internal, tests is not needed, anyway added.

2019-11-03 23:28 UTC, merged

2019-11-04 00:44 UTC, amosbird commented
Thanks!