Storage dictionary
ClickHouse/ClickHouse pull request #763
Opened 2017-05-04 19:33 UTC by KochetovNicolai

Added:
* **StorageDictionary** storage
* **DictionaryBlockInputStream** and **RangeDictionaryBlockInputStream** implementation of the `IBlockInputStream` representing in-memry stored dictionary data

Changed:
`ComplexKeyHashDictionary` and `ComplexKeyCacheDictionary` key serialization format

2017-05-05 14:53 UTC, alexey-milovidov commented on dbms/src/Dictionaries/IDictionary.h
> +    virtual BlockInputStreamPtr getBlockInputStream(const Names & column_names) const = 0;
Please add a comment.

2017-05-05 14:53 UTC, alexey-milovidov commented on dbms/src/Dictionaries/ComplexKeyCacheDictionary.cpp
> +    Arena arena;
Temporary Arena for every row is very expensive.
Better to implement overload `IColumn::serializeValueIntoArena` for `ArenaWithFreeLists`.
(or call it `IColumn::serializeValueIntoArenaWithFreeLists` and provide a wrapper here.)

2017-05-05 16:35 UTC, alexey-milovidov requested changes

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/ComplexKeyHashedDictionary.cpp
> +    std::vector<StringRef> keys;
We should reserve space for vector.
In other places too.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/ComplexKeyHashedDictionary.cpp
> +    return std::move(std::make_unique<BlockInputStreamType>(*this, getKeys(), column_names));
See prev. comment.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/DictionaryBlockInputStream.h
> + * read() returns single block consisting of the in-memory contents of the dictionaries
Single block will be too large for some dictionaries. It's better to generate blocks of max_block_size.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/DictionaryBlockInputStream.h
> +    logger = &Poco::Logger::get("DictionaryBlockInputStream");
It's more easy to use in-class member initialization. Few lines above.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/DictionaryBlockInputStream.h
> +    return ColumnPtr(std::move(column_string));
No need for std::move, you could create shared_ptr instead.
No need for explicit cast to ColumnPtr.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/DictionaryBlockInputStream.h
> +                    std::move(std::make_unique<ColumnString>()), attribute.type, attribute.name));
`std::move` is useless, because its argument is already an rvalue.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/DictionaryBlockInputStream.h
> +    for (const DictionaryAttribute & attribute: *dictionary_structure.key)
Inconsistent use of whitespace before `:`.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/DictionaryBlockInputStream.h
> +            throw Exception("DictionaryBlockInputStream: unable to deserialize data");
No error code.
Better to totally remove this check, because it is in inner loop.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/DictionaryBlockInputStreamBase.h
> +class DictionaryBlockInputStreamBase : public IProfilingBlockInputStream
Missing comment.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/DictionaryBlockInputStreamBase.h
> +    void readPrefixImpl() override { was_read = false; }
I am sure, that we don't need this.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/IDictionary.h
> +#include <Dictionaries/IDictionarySource.h>
?

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/IDictionary.h
> +#include <DataStreams/IBlockInputStream.h>
You could forward declare IBlockInputStream and add `using BlockInputStreamPtr = ...`.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/RangeDictionaryBlockInputStream.h
> +template <class DictionaryType, class Key>
We only use `typename` for all class/struct/type template parameters.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/RangeDictionaryBlockInputStream.h
> +        const DictionaryType& dictionary, const Names & column_names, const PaddedPODArray<Key> & ids,
Please add whitespaces before `&` according to the style.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/RangeDictionaryBlockInputStream.h
> +    if (column_names.find(name) != column_names.end()) {
Style.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Dictionaries/RangeDictionaryBlockInputStream.h
> +    block = Block(columns);
Now `std::move` will be appropriate.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Storages/StorageFactory.cpp
> +        return StorageView::create(
You should setup your IDE to trim trailing whitespaces.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Storages/StorageFactory.cpp
> -/// Some types are only for intermediate values of expressions and cannot be used in tables.
Bad merge. You have deleted my changes.

2017-05-05 16:35 UTC, alexey-milovidov commented on dbms/src/Storages/StorageDictionary.h
> +}
Better to setup your IDE to add newlines at end of file. This does not matter a lot (for C++11), but will be more consistent.

2017-06-05 09:03 UTC, KochetovNicolai commented on dbms/src/Dictionaries/CacheDictionary.h
> +    PaddedPODArray<Key> getCachedIds() const;
moved to private

2017-06-05 09:04 UTC, KochetovNicolai commented on dbms/src/Dictionaries/ComplexKeyHashedDictionary.cpp
> +    std::vector<StringRef> keys;
added reserve call

2017-06-05 09:05 UTC, KochetovNicolai commented on dbms/src/Storages/StorageDictionary.h
> +}
done

2017-06-13 04:20 UTC, merged