Add simhash, minhash, and hammingdistance function
ClickHouse/ClickHouse pull request #7649
Opened 2019-11-06 10:45 UTC by ucasFL

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (up to few sentences, not needed for non-significant PRs):

...

Detailed description (optional):

Implementation of Simhash and Minhash.
Simhash: String->UInt64
Minhash: String->(UInt64, UInt64)

Parameters and variations:
- Case sensitive, case insensitive ASCII, case insensitive UTF8
- Extracting String: ngram or word shingles(parameter n)
- Minhash: take K minimum values and K maximum value. 

Usage:
```sql
SELECT ngramSimhash('what a cute cat.');                                                                                                         
SELECT ngramSimhashCaseInsensitive('what a cute cat.');                                                                                          
SELECT ngramSimhashUTF8('what a cute cat.');                                                                                                     
SELECT ngramSimhashCaseInsensitiveUTF8('what a cute cat.');                                                                                      
SELECT wordShingleSimhash('what a cute cat.');                                                                                                   
SELECT wordShingleSimhashCaseInsensitive('what a cute cat.');                                                                                    
SELECT wordShingleSimhashUTF8('what a cute cat.');                                                                                               
SELECT wordShingleSimhashCaseInsensitiveUTF8('what a cute cat.');                                                                                
                                                                                                                                                 
SELECT ngramMinhash('what a cute cat.');                                                                                                         
SELECT ngramMinhashCaseInsensitive('what a cute cat.');                                                                                          
SELECT ngramMinhashUTF8('what a cute cat.');                                                                                                     
SELECT ngramMinhashCaseInsensitiveUTF8('what a cute cat.');                                                                                      
SELECT wordShingleMinhash('what a cute cat.');                                                                                                   
SELECT wordShingleMinhashCaseInsensitive('what a cute cat.');
SELECT wordShingleMinhashUTF8('what a cute cat.');
SELECT wordShingleMinhashCaseInsensitiveUTF8('what a cute cat.');

DROP TABLE IF EXISTS defaults;
CREATE TABLE defaults
(
   s String
)ENGINE = Memory();
INSERT INTO defaults values ('It is the latest occurrence of the Southeast European haze, the issue that occurs in constant intensity during ever$ wet season. It has mainly been caused by forest fires resulting from illegal slash-and-burn clearing performed on behalf of the palm oil industry in Kazakhstan, principally on the islands, which then spread quickly in the dry season.') ('It is the latest occurrence of the Southeast Asian ha
ze, the issue that occurs in constant intensity during every wet season. It has mainly been caused by forest fires resulting from illegal slash-an
d-burn clearing performed on behalf of the palm oil industry in Kazakhstan, principally on the islands, which then spread quickly in the dry seaso
n.');

SELECT ngramSimhash(s) FROM defaults;
SELECT ngramSimhashCaseInsensitive(s) FROM defaults;
SELECT ngramSimhashUTF8(s) FROM defaults;
SELECT ngramSimhashCaseInsensitiveUTF8(s) FROM defaults;
SELECT wordShingleSimhash(s) FROM defaults;
SELECT wordShingleSimhashCaseInsensitive(s) FROM defaults;
SELECT wordShingleSimhashUTF8(s) FROM defaults;
SELECT wordShingleSimhashCaseInsensitiveUTF8(s) FROM defaults;

SELECT ngramMinhash(s) FROM defaults;
SELECT ngramMinhashCaseInsensitive(s) FROM defaults;
SELECT ngramMinhashUTF8(s) FROM defaults;
SELECT ngramMinhashCaseInsensitiveUTF8(s) FROM defaults;
SELECT wordShingleMinhash(s) FROM defaults;
SELECT wordShingleMinhashCaseInsensitive(s) FROM defaults;
SELECT wordShingleMinhashUTF8(s) FROM defaults;
SELECT wordShingleMinhashCaseInsensitiveUTF8(s) FROM defaults;
``` 

Function `bitHammingDistance`: (Integer, Integer) -> UInt8
For example
```sql
SELECT bitHammingDistance(1, 5);
SELECT bitHammingDistance(100, 100000);
SELECT bitHammingDistance(-1, 1);

DROP TABLE IF EXISTS defaults;
CREATE TABLE defaults
(
	n1 UInt8,
	n2 UInt16,
	n3 UInt32,
	n4 UInt64
)ENGINE = Memory();

INSERT INTO defaults VALUES (1, 2, 3, 4) (12, 4345, 435, 1233) (45, 675, 32343, 54566) (90, 784, 9034, 778752);

SELECT bitHammingDistance(4, n1) FROM defaults;
SELECT bitHammingDistance(n2, 100) FROM defaults;
SELECT bitHammingDistance(n3, n4) FROM defaults;
```
Function `tupleHammingDistancec`: (tuple(Integer, Integer), tuple(Integer, integer)) -> UInt8
For example:
```sql
SELECT tupleHammingDistance((1, 2), (3, 4));
SELECT tupleHammingDistance((120, 2434), (123, 434));
SELECT tupleHammingDistance((-12, 434), (987, 432));

DROP TABLE IF EXISTS defaults;
CREATE TABLE defaults
(
	t1 Tuple(UInt8, UInt16),
	t2 Tuple(UInt32, UInt64),
	t3 Tuple(Int32, Int64)
)ENGINE = Memory();

INSERT INTO defaults VALUES ((12, 43), (12312, 43453) ,(-10, 32)) ((1, 4), (546, 12345), (123, 456)) ((90, 9875), (43456, 234203), (1231, -123)) ((87, 987), (545645, 768354634), (9123, 909));

SELECT tupleHammingDistance((1, 3), t1) FROM defaults;
SELECT tupleHammingDistance(t2, (-1, 1)) FROM defaults;
SELECT tupleHammingDistance(t2, t3) FROM defaults;
```

2019-12-05 03:36 UTC, alexey-milovidov commented on dbms/src/Functions/bitHammingDistance.cpp
> +        UInt8 count = 0;
`__builtin_popcountll`

2019-12-05 03:40 UTC, alexey-milovidov commented on dbms/src/Functions/bitHammingDistance.cpp
> +class FunctionBitHammingDistance : public IFunction
Maybe use `FunctionBinaryArithmetic`?

2019-12-05 03:43 UTC, alexey-milovidov commented on dbms/src/Functions/bitHammingDistance.cpp
> +                    auto res = OpImpl::constant_constant(col_left->template getValue<T0>(), col_right->template getValue<T1>());
useDefaultImplementationForConstants?

2019-12-05 03:53 UTC, alexey-milovidov commented on dbms/src/Functions/ExtractString.h
> +    static ALWAYS_INLINE inline bool isAlphaNum(const UInt8 c)
`isAlphaNumericASCII`

2019-12-05 03:55 UTC, alexey-milovidov commented on dbms/src/Functions/ExtractString.h
> +    static ALWAYS_INLINE inline size_t readOneASCIIWord(UInt8 * word, const char *& pos, const char * end, const size_t & max_word_size)
`const size_t & max_word_size` - don't need to pass by reference.

2019-12-05 03:56 UTC, alexey-milovidov commented on dbms/src/Functions/ExtractString.h
> +        size_t word_size = (static_cast<size_t>(pos - word_start) <= max_word_size) ? pos - word_start : max_word_size;
Ok, we can also use std::min.

2019-12-05 03:59 UTC, alexey-milovidov commented on dbms/src/Functions/ExtractString.h
> +    static ALWAYS_INLINE size_t readASCIICodePointsNoPadding(UInt8 * code_points, const char *& pos, const char * end)
We can avoid this function (and use the same as above) if we will pass internal ColumnString of ColumnConst instead of std::string.

2019-12-05 04:04 UTC, alexey-milovidov commented on dbms/src/Functions/FunctionsStringHash.cpp
> +                res &= intHashCRC32(hashes[i]);
Not a good hash function. Better to calculate CRC32 (_mm_crc32_u64) by chain (starting with -1 as initial value).
Look at `UInt256HashCRC32` as an example.

2019-12-05 04:05 UTC, alexey-milovidov commented on dbms/src/Functions/FunctionsStringHash.cpp
> +        return (intHashCRC32(even) ^ intHashCRC32(odd));
Not a good way to combine hashes.

2019-12-05 04:07 UTC, alexey-milovidov commented on dbms/src/Functions/FunctionsStringHash.cpp
> +    static ALWAYS_INLINE inline UInt64 wordShinglesHash(const UInt64 * hashes, const size_t & size, const size_t & offset)
Don't need to pass offset by reference.

2019-12-05 04:07 UTC, alexey-milovidov commented on dbms/src/Functions/FunctionsStringHash.cpp
> +    static ALWAYS_INLINE inline UInt64 hashSum(const CodePoint * hashes, const size_t & K)
Don't need to pass K by reference.

2020-05-29 14:20 UTC, KochetovNicolai requested changes

2020-06-04 08:21 UTC, ucasFL commented on src/Functions/FunctionsStringHash.cpp
> +template <size_t N, typename CodePoint, bool UTF8, bool Ngram, bool CaseInsensitive>
`N` means the length of ngram or words shingle
`CodePoint` means ascii(UInt8) or UTF8(UInt32)
`UTF8` means ascii or UTF8, these two parameters can only be (UInt8, false) or (UInt32, true)
`Ngram` means ngram(true) or words shingle(false)
`CaseInsensitive` means should we consider about letter case or not

2020-06-04 08:29 UTC, ucasFL commented on src/Functions/FunctionsStringHash.cpp
> +    static constexpr size_t max_word_size = 1u << 7;
Maybe max string size can be a safety threshold, I saw it in `FunctionsStringSimilarity.h`。As to max word size, when calculate hash values, i allocate a fixed size buffer to read one word each time, the buffer size is the max word size, maybe these is better solution.

2020-06-04 08:46 UTC, ucasFL commented on src/Functions/ExtractString.h
> +        while (num < default_padding && pos < end)
yes. it is.

2020-06-04 08:50 UTC, ucasFL commented on src/Functions/ExtractString.h
> +        }
This is not a really true case insensitive utf8. For ASCII it works https://catonmat.net/ascii-case-conversion-trick. For most cyrrilic letters also does.

2020-06-04 14:36 UTC, ucasFL commented on src/Functions/FunctionsStringHash.cpp
> +            for (; iter + N <= found; ++iter)
if we use condition `iter < found`, so we need copy the last three bytes to the beginning. using `iter + N <= found` is depends on the readASCIICodePoints function, the position of `pos` only go forward `padding_offset` bytes each time, so the last `N-1` bytes in the buffer copied twice. in fact, the implementation of this function refers to the `FunctionsStringSimilarity`, so i don't understand some details as well......

2020-06-04 14:40 UTC, ucasFL commented on src/Functions/FunctionsStringHash.cpp
> +        return (intHashCRC32(combined) ^ intHashCRC32(code_points[2]));
the combining method is refers to `UInt256HashCRC32`

2020-06-04 15:35 UTC, KochetovNicolai commented on src/Functions/FunctionsStringHash.cpp
> +template <size_t N, typename CodePoint, bool UTF8, bool Ngram, bool CaseInsensitive>
Yes, thank you!
Could you, please, add this comment into code?

2020-06-04 15:38 UTC, KochetovNicolai commented on src/Functions/FunctionsStringHash.cpp
> +    static constexpr size_t max_word_size = 1u << 7;
I suppose it is not very difficult to use `PodArray` instead of fixed buffer, and reallocate it inside functions when needed.

2020-06-05 04:23 UTC, ucasFL commented on src/Functions/FunctionsStringHash.cpp
> +    static ALWAYS_INLINE inline void insertMinValue(UInt64 * hashes, UInt64 v)
in fact, `K` is always small, never more than 10 usually, so do we need to use other more complex object?

2020-12-23 09:22 UTC, merged

2020-12-24 21:08 UTC, deripas commented
Hi!
Thank you very much, very useful!
In what release will this be seen?

2020-12-25 01:34 UTC, alexey-milovidov commented
@deripas 

It is going to be released in 21.1.

This feature is experimental and we have to apply some changes before the release:
- make the number of hashes and the size of shingles configurable (e.g. I want to calculate 10 min hashes of 5-word shingles);
- maybe make a threshold on word size for word shingles;
- maybe implement `shinglesDistance*` function similar to `ngramDistance*`;
- provide debug version of functions that will return Arrays of min ngrams/shingles instead of their hashes.

Provide recommendation on parameters that will work reasonable well for:
- searching semi-duplicate comments/messages from HN, Reddit, Telegram with examples for western alphabets and CJK;
- searching semi-duplicate source files in C++ codebase;
- searching semi-duplicate HTML pages.

Note that efficient search by min-hash (tuple of two hashes) will also require #6286.

2020-12-25 06:30 UTC, alexey-milovidov commented
Check for performance of ngram min hashes:
```
  42.93%  clickhouse               [.] DB::FixedHeap<std::__1::greater<unsigned long>, 6ul, 0ul>::insertAndReplace
  39.55%  clickhouse               [.] DB::FixedHeap<std::__1::less<unsigned long>, 6ul, 18446744073709551615ul>::insertAndReplace
   7.63%  clickhouse               [.] DB::MinhashImpl<4ul, 6ul, char8_t, false, true, true>::apply
```

2020-12-25 11:26 UTC, deripas commented
Another small question.
In the example, the functions work with raw text. Will it be possible to calculate shingles it yourself, using for example Lucene?
That is, I want to have functions that accept not only raw text, but also shingles as argument.

We are currently using 10-word shingles (EN language) after clearing the text (remove short world and etc.).
But the rules for preprocessing strings may differ in different languages (for example a different "stop word" dictionary).
I planned to solve the problem of supporting different languages with the help of Lucene.

Thank you very much!

2021-01-06 21:22 UTC, alexey-milovidov commented
@deripas We are not going to add custom function to calculate shingles, but there is another way to go:

First preprocess text by extracting meaningful words with normalization and write them separated by whitespaces. This has to be done before loading data into ClickHouse. Then save the preprocessed text to a separate column and calculate shingles as usual.

Another option is to calculate shingles outside of ClickHouse, hash them to single artificial words and then use them as 1-word shingles.

2021-04-14 12:12 UTC, ccaapton commented
When I use conventional minhash for string similarity measure, like [datasketch](https://github.com/ekzhu/datasketch/) , I can use multiple permutation of the hash function to generate a fixed-length vector, and estimate the jaccard distance of two strings using hamming_distance/total_length.

But in clickhouse implementation, it gives only a vector of length 2, one for min and another for max.

Is there anyway to generate a 128-length tuple and compare their hamming distance in clickhouse?

2025-01-13 03:28 UTC, serega commented
The minhash function has a strange [implementation](https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionsStringHash.cpp#L351), and I am not sure what it does. The [documentation](https://clickhouse.com/docs/en/sql-reference/functions/hash-functions#ngramminhash) says to use `tupleHammingDistance` to calculate the distance between two strings, but the output is always 2 for any two different strings. 

```
SELECT tupleHammingDistance(ngramMinHash(string1, 3, 25), ngramMinHash(string2, 3, 25)) AS HammingDistance
FROM
(
    SELECT
        'Clickhouse' AS string1,
        'Clickhouse1' AS string2
)

Query id: 492397fa-240e-43f1-983c-8d3e6c36c3e9

   ┌─HammingDistance─┐
1. │               2 │
   └─────────────────┘

1 row in set. Elapsed: 0.002 sec. 
```
I would expect ngramMinHash to return an array of numbers and a corresponding function something like `minHashJaccardSimilarity`. This does not look like a correct minhash implementation.