Docs: fix bitmapSubsetInRange function
ClickHouse/ClickHouse pull request #7654
Opened 2019-11-06 12:31 UTC by godfreyd

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation

2020-01-21 14:44 UTC, blinkov requested changes

2020-01-21 14:44 UTC, blinkov commented on docs/en/query_language/functions/bitmap_functions.md
> +Converts a bitmap into an integer array. Returns values from given range not including the range_end.
* range_end is referenced before it was introduced in example
* "Converts a bitmap into an integer array" sounds misleading, following explanation demonstrates different behaviour

2020-01-21 14:44 UTC, blinkov commented on docs/en/query_language/functions/bitmap_functions.md
> +Returns subset of the values in set which greater or equal than `range_start` and less than `range_end`.
greater by value or by position?

2020-02-02 21:52 UTC, alexey-milovidov commented
Conflicted.

2020-02-02 21:52 UTC, closed without merging