Docs: fix joinGet function
ClickHouse/ClickHouse pull request #7719
Opened 2019-11-11 15:03 UTC by godfreyd

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation

2019-12-09 20:50 UTC, blinkov requested changes
also there's a broken docs test

2019-12-09 20:50 UTC, blinkov commented on docs/en/query_language/functions/other_functions.md
> +The function lets you extract data from the table the same way as from a [dictionary](https://clickhouse.yandex/docs/en/query_language/dicts/).
internal links have to be relative and point to markdown files

2019-12-09 20:50 UTC, blinkov commented on docs/en/query_language/functions/other_functions.md
> +If certain doesn't exist in source table then `0` or `null` will be returned based on [join_use_nulls](https://clickhouse.yandex/docs/en/operations/settings/settings/#settings-join_use_nulls) setting
```suggestion
If some keys doesn't exist in source table then default value or `NULL` will be returned (depending on [join_use_nulls](https://clickhouse.yandex/docs/en/operations/settings/settings/#settings-join_use_nulls) setting). 
```

2020-02-02 22:03 UTC, alexey-milovidov commented
Was documented in newer PR.

2020-02-02 22:03 UTC, closed without merging