Docs: fixes for if conditional function
ClickHouse/ClickHouse pull request #7770
Opened 2019-11-14 08:25 UTC by godfreyd

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation

2019-11-17 20:31 UTC, alexey-milovidov commented on docs/en/query_language/functions/conditional_functions.md
> +- `then` - The expression executed if condition is met. Any [data type](https://clickhouse.yandex/docs/en/data_types/).
Incorrect. Both expressions are executed.

2019-11-17 20:31 UTC, alexey-milovidov requested changes
.

2019-11-17 20:32 UTC, alexey-milovidov commented on docs/en/query_language/functions/conditional_functions.md
> +Expressions `then` and `else` can be `NULL`, any expressions or have an explicit values.
cond also can be NULL.

2019-11-17 20:32 UTC, alexey-milovidov commented on docs/en/query_language/functions/conditional_functions.md
> +Returns any [data type](https://clickhouse.yandex/docs/en/data_types/).
What?

2019-12-02 13:40 UTC, blinkov requested changes

2019-12-02 13:40 UTC, blinkov commented on docs/en/query_language/functions/conditional_functions.md
> +- `else` - The expression executed if condition is not met. Any [data type](https://clickhouse.yandex/docs/en/data_types/).
Not really any data type, there must be a supertype between `then` and `else` types.

2019-12-02 13:40 UTC, blinkov commented on docs/en/query_language/functions/conditional_functions.md
> +- `then` - The expression executed if condition is met. Any [data type](https://clickhouse.yandex/docs/en/data_types/).
```suggestion
- `then` - The expression to return if condition is met. Any [data type](https://clickhouse.yandex/docs/en/data_types/).
```

2019-12-02 13:40 UTC, blinkov commented on docs/en/query_language/functions/conditional_functions.md
> +- `else` - The expression executed if condition is not met. Any [data type](https://clickhouse.yandex/docs/en/data_types/).
```suggestion
- `else` - The expression to return if condition is not met. Any [data type](https://clickhouse.yandex/docs/en/data_types/).
```

2019-12-02 13:40 UTC, blinkov commented on docs/en/query_language/functions/conditional_functions.md
> +The function executes `then` or `else` expression and returns its result, depending on the condition `cond`.
```suggestion
The function executes `then` and `else` expressions and returns its result, depending on whether the condition `cond` ended up being zero or not.
```

2019-12-02 13:40 UTC, blinkov commented on docs/en/query_language/functions/conditional_functions.md
> +- `else` - The expression executed if condition is not met. Any [data type](https://clickhouse.yandex/docs/en/data_types/).
All internal links should point to markdown files instead of pages where they are published

2019-12-02 13:40 UTC, blinkov commented on docs/en/query_language/functions/conditional_functions.md
> +## if {#if}
ternary operator seems to be just removed without replacement

2020-02-02 22:09 UTC, merged