DOCS-466: Query profiler settings docs
ClickHouse/ClickHouse pull request #7860
Opened 2019-11-20 10:08 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation

Documented #6283

2019-12-02 15:24 UTC, blinkov requested changes

2019-12-02 15:24 UTC, blinkov commented on docs/en/operations/settings/settings.md
> +        - 10000000 (100 times a second) nanosecods and more for for single queries.
```suggestion
        - 10000000 (100 times a second) nanoseconds and less for single queries.
```

2019-12-02 15:24 UTC, blinkov commented on docs/en/operations/settings/settings.md
> +- Positive integer number of nanoseconds.
```suggestion
- Positive integer number, in nanoseconds.
```

2019-12-02 15:24 UTC, blinkov commented on docs/en/operations/settings/settings.md
> +Default value: 1000000000 nanoseconds.
```suggestion
Default value: 1000000000 nanoseconds (once a second).
```

2019-12-02 15:24 UTC, blinkov commented on docs/en/operations/settings/settings.md
> +Sets the period for a CPU clock timer of the query profiler. Real clock timer counts CPU time.
```suggestion
Sets the period for a CPU clock timer of the query profiler. This timer counts only CPU time.
```

2019-12-06 05:24 UTC, merged

2019-12-06 09:12 UTC, nikitamikhaylov commented
No need to change submodule in documentation PR.