Moved developer instruction
ClickHouse/ClickHouse pull request #7879
Opened 2019-11-21 15:09 UTC by Akazz

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Moved developer instruction from `dbms/tests/instructions` to the more appropriate path - `docs/{ru|en}/development`

2019-11-21 21:57 UTC, alexey-milovidov requested changes
Could you please also update ToC and create symlinks from zh, fa languages to en?

2019-11-22 10:03 UTC, Akazz commented
> Could you please also update ToC and create symlinks from zh, fa languages to en?

Thanks for pointing this out! I somehow took it for granted that ToC would update itself automatically

2019-11-22 10:51 UTC, zhang2014 commented on docs/toc_zh.yml
> +  - 'The Beginner ClickHouse Developer Instruction': 'development/developer_instruction.md'
开发者指南

2019-11-22 10:53 UTC, zhang2014 commented on docs/toc_zh.yml
>    - 'How to Build ClickHouse on Linux for Mac OS X': 'development/build_cross.md'
如何在Linux中编译Mac OS X ClickHouse

2019-11-22 11:20 UTC, Akazz commented on docs/toc_zh.yml
>    - 'How to Build ClickHouse on Linux for Mac OS X': 'development/build_cross.md'
Thanks, Zhang! Your help with Chinese is always appreciated!

2019-11-23 16:20 UTC, merged