Fix bug in check table for tables without primary key
ClickHouse/ClickHouse pull request #7979
Opened 2019-12-02 10:31 UTC by alesapin

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Fix `CHECK TABLE` query for `*MergeTree` tables without key. Fixes [#7543](https://github.com/ClickHouse/ClickHouse/issues/7543).

2019-12-02 11:37 UTC, tavplubix approved these changes

2019-12-02 23:35 UTC, alexey-milovidov commented on dbms/src/Storages/MergeTree/checkDataPart.cpp
> +    if (Poco::File(path + "primary.idx").exists())
Looks like incorrect change. What if primary key must exist but the file was removed.

Why don't just move `if (!primary_key_data_types.empty())` upper?

2019-12-02 23:35 UTC, alexey-milovidov requested changes
.

2019-12-02 23:42 UTC, alexey-milovidov commented on dbms/src/Storages/MergeTree/checkDataPart.cpp
> +    if (Poco::File(path + "primary.idx").exists())
Ok.
`primary_key_data_types` can be empty to skip check of the primary key.
But it's needed only for `part_checker` tool. I'd better remove `part_checker` tool.

2019-12-02 23:46 UTC, alexey-milovidov approved these changes

2019-12-02 23:52 UTC, merged

2019-12-05 10:39 UTC, nikitamikhaylov commented
Conflicts with 19.17