Add docs for predefined_http
ClickHouse/ClickHouse pull request #8161
Opened 2019-12-12 10:03 UTC by TCeason

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Documentation

Detailed description (optional):
#7572

2019-12-13 13:30 UTC, blinkov requested changes

2019-12-13 13:30 UTC, blinkov commented on docs/en/interfaces/index.md
> +* [Predefined HTTP](predefined_http.md), which is more easy integration with third-party tools.
let's put all this into same `http.md` as additional sections

2019-12-13 13:30 UTC, blinkov commented on docs/en/interfaces/predefined_http.md
> +Now ClickHouse supports Predefined HTTP Interface which can help you more easy integration with third party tools. For example, the following example describes how to by Prometheus with Predefined HT
we shouldn't use any reference to time in documentation (now, already, etc.), here and in other places

2019-12-13 13:30 UTC, blinkov commented on docs/en/interfaces/predefined_http.md
> +> Example:
some formatting issues, there should be no mass `>`

2019-12-13 13:30 UTC, blinkov commented on docs/en/interfaces/predefined_http.md
> +> * First, add these configurations to the configuration file:
```suggestion
> * First of all, add this section to server configuration file:
```

2019-12-13 13:30 UTC, blinkov commented on docs/en/interfaces/predefined_http.md
> +> * You can now request the url directly for data in the Prometheus format:
* link to format description and/or to Prometheus itself
* we should explain in the very beginning that this example is about exporting metrics in Prometheus format, not in the middle of it

2019-12-13 13:30 UTC, blinkov commented on docs/en/interfaces/predefined_http.md
> +As you can see from the example, if  `<http_handlers>` is configured in the configuration file, ClickHouse will match the HTTP requests received to the predefined type in  `<http_handlers>`, then Cli
* double spaces
* "configured in configuration file" needs to be said differently to avoid duplicate word

2019-12-13 13:30 UTC, blinkov commented on docs/en/interfaces/predefined_http.md
> +`<ping_handler>` can be used to probe the health of the current ClickHouse Server. When the ClickHouse HTTP interface is normal, accessing ClickHouse through `<ping_handler>` will return **Ok.**.
what exactly does it mean that "HTTP interface is normal"?

2019-12-13 13:30 UTC, blinkov commented on docs/en/interfaces/predefined_http.md
> +$ curl 'http://localhost:8123/replicas_status'
add example for when there's some delay?

2019-12-13 13:30 UTC, blinkov commented on docs/en/interfaces/predefined_http.md
> +`<method>` is responsible for matching the method part of the HTTP request. `<method>` fully conforms to the definition of method in the HTTP protocol. It is an optional configuration.
some link to proper definition of "method"

2019-12-13 13:30 UTC, blinkov commented on docs/en/interfaces/predefined_http.md
> +`<url>`  is responsible for matching the url part of the HTTP request. It is compatible with RE2's regular expressions. It is an optional configuration.
* what happens if it's omitted?
* link to re2 docs

2019-12-13 13:30 UTC, blinkov commented on docs/en/interfaces/predefined_http.md
> +To experiment with this functionality, the example defines the values of max_threads and max_alter_threads and queries whether the Settings were set successfully.
```suggestion
The following example defines the values of `max_threads` and `max_alter_threads` settings, then queries the system table to check whether these settings were set successfully.
```

2019-12-13 13:30 UTC, blinkov commented on docs/en/interfaces/predefined_http.md
> +> Note:
Proper syntax for notes:
```
!!! note "Note"
   My note text
```

2019-12-13 13:30 UTC, blinkov commented on docs/en/interfaces/predefined_http.md
> +To experiment with this functionality, the example defines the values of max_threads and max_alter_threads and queries whether the Settings were set successfully.
* same issue as above
* also it doesn't explain the specifics of this example comparing to previous one

2020-02-26 21:14 UTC, blinkov approved these changes

2020-04-01 18:16 UTC, merged

2020-04-01 19:35 UTC, alexey-milovidov commented
But the feature is not merged yet. It is in the queue and I hope will be merged very soon!