Fixed ALTER TTL for replicated tables
ClickHouse/ClickHouse pull request #8318
Opened 2019-12-20 12:25 UTC by excitoon

Co-authored-by: Vitaliy Zakaznikov <vzakaznikov@protonmail.com>

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):

Fixed ALTER TTL for replicated tables.

2019-12-26 19:00 UTC, alexey-milovidov requested changes
> ready for review

but

> I hereby not agree to the terms of the CLA

2019-12-26 19:01 UTC, alexey-milovidov approved these changes

2019-12-26 19:52 UTC, alexey-milovidov approved these changes

2019-12-28 03:49 UTC, merged

2020-01-21 10:13 UTC, alesapin commented
Fix cannot be applied to 19.17.