added marks_size column in system.parts
ClickHouse/ClickHouse pull request #832
Opened 2017-05-30 14:05 UTC by KochetovNicolai

2017-05-30 15:35 UTC, alexey-milovidov requested changes

2017-05-30 15:35 UTC, alexey-milovidov commented on dbms/src/Storages/System/StorageSystemParts.cpp
> +#include <Storages/StorageLog.h>
Double include.

2017-05-30 15:35 UTC, alexey-milovidov commented on dbms/src/Storages/System/StorageSystemParts.cpp
> +#include <Storages/StorageLog.h>
This is not the right one. Look at `MarkInCompressedFile.h`.
(You could consider the implementation of StorageMergeTree.)

2017-05-30 15:37 UTC, alexey-milovidov commented on dbms/src/Storages/System/StorageSystemParts.cpp
> +            block.getByPosition(i++).column->insert(part->size * part->columns.size() * sizeof(Mark));
Also look at `MergeTreeDataPartChecksums` and it's usage across the codebase.

2017-05-31 09:36 UTC, KochetovNicolai commented on dbms/src/Storages/System/StorageSystemParts.cpp
> +            block.getByPosition(i++).column->insert(part->size * part->columns.size() * sizeof(Mark));
Do you mean that I need to add checksums size for primary.idx file?

2017-05-31 16:54 UTC, merged