New configuration for abilities to raise the priority of mutations.
ClickHouse/ClickHouse pull request #8559
Opened 2020-01-07 12:09 UTC by sunadm

In some scenarios, a lots of mutations in an busy cluster will affect
the server normal operation due to blocking the queue.
We may want increase the process speed of mutations.

But in current design, mutation seems has the lowest priority.

So we add a new configuration item to separate mutation and merge.

* for merge. `max_bytes_to_merge_at_max_space_in_pool`
* for mutations. `max_bytes_to_mutate_at_max_space_in_pool`

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
New configuration for abilities to raise the priority of mutations.

In some scenarios, a lots of mutations in an busy cluster will affect
the server normal operation due to blocking the queue.
We may want increase the process speed of mutations.

But in current design, mutation seems has the lowest priority.

So we add a new configuration item to separate mutation and merge.

* for merge. `max_bytes_to_merge_at_max_space_in_pool`
* for mutations. `max_bytes_to_mutate_at_max_space_in_pool`
...

Detailed description (optional):

...

2020-01-13 14:30 UTC, alexey-milovidov commented
Could you please take a look to `ClickHouse build check — 0/14 builds are OK`

2020-01-15 08:12 UTC, sunadm commented
> Could you please take a look to `ClickHouse build check — 0/14 builds are OK`?

My fault. Already fixed.

Could u pls tell me how to fix the failed of "Style check" ?

2020-01-15 17:48 UTC, tavplubix requested changes

2020-01-15 17:48 UTC, tavplubix commented on dbms/src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp
> +        bool ignore_max_size_for_mutate = (entry.type == LogEntry::MUTATE_PART) && (max_source_parts_size == data_settings->max_bytes_to_mutate_at_max_space_in_pool);
Please take a look at `MergeTreeDataMergerMutator::getMaxSourcePartSizeForMutation()`. It calculates `max_source_parts_size` as `disk_space / DISK_USAGE_COEFFICIENT_TO_RESERVE`, so it almost never equals to `max_bytes_to_mutate_at_max_space_in_pool` and `ignore_max_size_for_mutate` is false

2020-05-15 15:03 UTC, alesapin commented
Actually your idea (give mutations higher priority) is already implemented. First of all, you can tune `max_replicated_mutations_in_queue` and `max_replicated_merges_in_queue`. It allows you to have as many mutations in the queue as you want. Another setting is `number_of_free_entries_in_pool_to_execute_mutation`. It has quite a big value by default, but if you choose the smaller one, your mutations will take up more threads in background pool. And if you want to execute them as fast as possible you should also enlarge `background_pool_size setting`.

You can see an example of tuning of these settings in my test https://github.com/clickhouse/ClickHouse/blob/master/tests/queries/0_stateless/01079_parallel_alter_modify_zookeeper.sh#L13. 

Your implementation in this PR is not correct, because part size for mutations is unlimited (the only limit is available disk space). Such a setting doesn't make sense. 

If I understood your idea incorrectly fill free to reopen this pull request. Thank you, for your contribution, new ideas are welcome.

2020-05-15 15:03 UTC, closed without merging

2020-05-16 05:57 UTC, silviucpp commented
@alesapin I think https://github.com/ClickHouse/ClickHouse/issues/10897 is related to this problem as well. In case number_of_free_entries_in_pool_to_execute_mutationis > than background_pool_size the mutations will block forever. So at least some alerts should be added in logs.