Allow data in square brackets in JSONEachRowFormat.
ClickHouse/ClickHouse pull request #8860
Opened 2020-01-27 18:34 UTC by Avogar

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
JSONEachRowFormat: support special case when objects enclosed in [array.[](url)](url). There is an example:

```
air :) INSERT INTO students FORMAT JSONEachRow [{"id": 1, "name": "name1" }, {"id" : 2, "name": "name2"}]

INSERT INTO students FORMAT JSONEachRow

Ok.

2 rows in set. Elapsed: 0.015 sec.
```

2020-01-27 19:00 UTC, alexey-milovidov commented on dbms/src/Processors/Formats/Impl/JSONEachRowRowInputFormat.cpp
> +    if (!in.eof() && in.position() == in.buffer().begin()) {
That's slightly incorrect. Because buffer is constantly refilled with new data and cursor is moved from the end of buffer to begin.

2020-01-27 19:02 UTC, alexey-milovidov commented on dbms/src/Processors/Formats/Impl/JSONEachRowRowInputFormat.cpp
> +        throw Exception("Unexpected data after ']' while parsing JSONEachRow format.", ErrorCodes::INCORRECT_DATA);
Just stop parsing is Ok. The user may continue to read from this ReadBuffer in another format.

2020-01-30 13:30 UTC, alexey-milovidov requested changes
Ok but please add functional test.
They are inside `dbms/tests/queries`.

2020-01-31 01:06 UTC, alexey-milovidov commented
Difference in perf test: unrelated.

2020-01-31 01:06 UTC, merged

2020-01-31 23:12 UTC, den-crane commented
it fails on long sets [.....] https://github.com/ClickHouse/ClickHouse/issues/8948