draft implementation of key and timestamp in Kafka producet
ClickHouse/ClickHouse pull request #8969
Opened 2020-02-03 11:42 UTC by filimonov

Draft

2020-02-04 06:01 UTC, Enmk requested changes
Some minor tweaks here and there.

2020-02-04 16:21 UTC, filimonov commented on dbms/src/Storages/Kafka/StorageKafka.cpp
> +        producer, topics[0], row_delimiter ? std::optional<char>{row_delimiter} : std::optional<char>(), 1, 1024, std::chrono::milliseconds(poll_timeout), header);
+1

2020-02-04 16:23 UTC, filimonov commented on dbms/src/Storages/Kafka/WriteBufferToKafkaProducer.cpp
> +    for (size_t i = 0; i < header.columns(); ++i)
Yes, a bit clearer, but in that case I need to extract type once again, should not be to much difference.

2020-02-04 16:25 UTC, filimonov commented on dbms/src/Storages/Kafka/StorageKafka.cpp
> +ProducerBufferPtr StorageKafka::createWriteBuffer(Block header)
+1

2020-02-04 16:26 UTC, filimonov commented on dbms/src/Storages/Kafka/WriteBufferToKafkaProducer.h
> +        Block header);
+1

2020-02-05 07:08 UTC, filimonov commented on dbms/src/Storages/Kafka/WriteBufferToKafkaProducer.cpp
> +    for (size_t i = 0; i < header.columns(); ++i)
Oh, there is index_by_name map inside. I've changed code to your variant.

2020-02-11 19:03 UTC, merged

2021-11-03 16:09 UTC, mafiore commented
Is this feature available?  I cannot get this to work. That is exactly what I need