Fixing PerformanceTest: table_exists condition, move getMemoryAmount function to file. Add more debug helpers
ClickHouse/ClickHouse pull request #905
Opened 2017-06-21 17:51 UTC by proller

table_exists condition, move getMemoryAmount function to file. Add more debug helpers

2017-06-21 18:15 UTC, alexey-milovidov requested changes

2017-06-21 18:15 UTC, alexey-milovidov commented on dbms/src/Common/getMemoryAmount.h
> +size_t getMemoryAmount();
No comments. No comment that function returns zero on unsupported platform.

2017-06-21 18:15 UTC, alexey-milovidov commented on dbms/src/Common/getMemoryAmount.h
> +namespace DB {
Style.

2017-06-21 18:15 UTC, alexey-milovidov commented on dbms/src/Common/getMemoryAmount.cpp
> +        return 0;
You should throw an exception.

2017-06-21 18:15 UTC, alexey-milovidov commented on dbms/src/Common/iostream_debug_helpers.cpp
> +        << ") {"
Inconsistent style of whitespaces. See above.

2017-06-21 18:15 UTC, alexey-milovidov commented on dbms/src/Server/PerformanceTest.cpp
> +                if (ram_size_needed > actual_ram_mb)
Inconsistent style of sizes in configuration. All sizes should be in number of bytes.

2017-06-21 18:15 UTC, alexey-milovidov commented on dbms/src/Server/PerformanceTest.cpp
> +                    std::cerr << "Not enough RAM: need=" << ram_size_needed << " present=" << actual_ram_mb << std::endl;
No whitespaces around `=`.
No units.

2017-06-21 18:15 UTC, alexey-milovidov commented on dbms/src/Server/PerformanceTest.cpp
> +                                column.column->get(0, field);
So, why previous code was incorrect?

2017-06-21 20:41 UTC, proller commented on dbms/src/Server/PerformanceTest.cpp
> +                                column.column->get(0, field);
it was fixed here - https://github.com/yandex/ClickHouse/commit/8c9aa37318c87cb0d226721e74fc450d50b03fb3

2017-06-21 21:36 UTC, alexey-milovidov requested changes

2017-06-21 21:36 UTC, alexey-milovidov commented on dbms/src/Common/getMemoryAmount.h
> +int64_t getMemoryAmount();
Why not unsigned?

2017-06-21 21:36 UTC, alexey-milovidov commented on dbms/src/Server/PerformanceTest.cpp
> +                size_t ram_size_needed = config->getUInt64("preconditions.ram_size");
RAM size should be configured in bytes.

2017-06-22 14:25 UTC, alexey-milovidov commented on dbms/src/Server/PerformanceTest.cpp
> +                    std::cerr << "Not enough RAM: need =" << ram_size_needed << " present=" << actual_ram << std::endl;
Inconsistent whitespaces.

2017-06-22 15:57 UTC, merged