DOCS-545: Yandex Datalens data analytics and visualization tool
ClickHouse/ClickHouse pull request #9190
Opened 2020-02-18 10:33 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Documentation

2020-02-18 11:12 UTC, qoega commented on docs/en/interfaces/third-party/gui.md
> +- Creation of simple visualizations and complex dashboards.
```suggestion
- Supports simple visualizations and complex dashboards.
```
But I don't like both. First point should be more descriptive...

2020-02-18 11:27 UTC, blinkov requested changes

2020-02-18 11:27 UTC, blinkov commented on docs/en/interfaces/third-party/gui.md
> +- Support for multiple data sources.
```suggestion
- Support for multiple data sources including ClickHouse.
```

2020-02-18 11:27 UTC, blinkov commented on docs/en/interfaces/third-party/gui.md
> +- Storage for materialized data.
```suggestion
- Storage for materialized data based on ClickHouse.
```

2020-02-18 11:27 UTC, blinkov commented on docs/en/interfaces/third-party/gui.md
> +- Creation of simple visualizations and complex dashboards.
```suggestion
- Wide range of available visualisations, from simple bar charts to complex dashboards.
```

2020-02-18 11:27 UTC, blinkov commented on docs/en/interfaces/third-party/gui.md
> +- Public dashboards.
```suggestion
- Dashboards could be made publicly available.
```

2020-02-18 11:27 UTC, blinkov commented on docs/en/interfaces/third-party/gui.md
> +For low-load projects, DataLens is [available for free](https://cloud.yandex.com/docs/datalens/pricing), including for commercial use.
```suggestion
DataLens is [available for free](https://cloud.yandex.com/docs/datalens/pricing) for low-load projects, even for commercial use.
```

2020-02-18 11:27 UTC, blinkov commented on docs/en/interfaces/third-party/gui.md
> +- [Visualizing data from a ClickHouse database](https://cloud.yandex.com/docs/datalens/solutions/data-from-db-visualization) tutorial.
```suggestion
- [Tutorial](https://cloud.yandex.com/docs/datalens/solutions/data-from-db-visualization) on visualizing data from a ClickHouse database.
```

2020-02-19 16:57 UTC, alexey-milovidov approved these changes

2020-02-19 16:57 UTC, merged