[WIP] Non-blocking alter for vanilla merge tree
ClickHouse/ClickHouse pull request #9606
Opened 2020-03-11 15:52 UTC by alesapin

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Implementation of "non-blocking" alter for StorageMergeTree

2020-03-11 15:54 UTC, alesapin commented
Need to remove:
- [ ] AlterDataPartTransaction
- [ ] alterDataPart
- [ ] analyzeAlterConversions
- [ ] columns_lock from MergeTreeDataPart (finally)
- [ ] removeEmptyColumnsFromPart
Make code less clumsy.

2020-03-17 11:04 UTC, alesapin commented
Do not merge.

2020-03-18 08:09 UTC, qoega commented
Please check that changes in docs are not needed after this changes https://clickhouse.tech/docs/en/query_language/alter/#query_language_queries_alter

2020-03-20 17:02 UTC, Jokser requested changes

2020-03-20 17:02 UTC, Jokser commented on dbms/src/Storages/MergeTree/IMergedBlockOutputStream.cpp
> +            if (0 != unlink(path_to_remove.c_str()))
Should go through disk interface.
disk->remove(data_part->getFullRelativePath() + removed_file)

2020-03-21 07:31 UTC, alesapin commented
test failure is ok, just need to fix the test.

2020-03-22 00:43 UTC, alexey-milovidov commented on dbms/src/Storages/AlterCommands.cpp
> +            throw Exception(R"("ALTER TABLE table DROP CONSTRAINT constraint_name" queries are not supported yet. Use "DROP CONSTRAINT constraint_name IN PARTITION".)", ErrorCodes::NOT_IMPLEMENTED);
Does not make sense.

2020-03-22 00:48 UTC, alexey-milovidov commented on dbms/src/Storages/StorageMergeTree.cpp
> +                LOG_DEBUG(log, "Loading mutation:" << it->name() << " entry commands size " << entry.commands.size());
Whitespace.

2020-03-22 00:52 UTC, alexey-milovidov approved these changes
Awesome!

2020-03-22 00:56 UTC, merged