DOCS-549: Updated info about keywords case-sensivity.
ClickHouse/ClickHouse pull request #9626
Opened 2020-03-12 13:21 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Documentation

2020-03-12 18:55 UTC, blinkov requested changes

2020-03-12 18:55 UTC, blinkov commented on docs/en/query_language/syntax.md
> +Keywords are not case-sensitive when they correspond to:
```suggestion
Keywords are case-insensitive when they correspond to:
```

2020-03-12 18:55 UTC, blinkov commented on docs/en/query_language/syntax.md
> +- SQL standard. For example, `SELECT = select`, `AS = as`.
```suggestion
- SQL standard. For example, `SELECT`,  `select` and `SeLeCt` are all valid.
```

2020-03-12 18:55 UTC, blinkov commented on docs/en/query_language/syntax.md
> +- Implementation in some popular DBMS (MySQL or Postgres). For example, `DateTime = datetime`.
```suggestion
- Implementation in some popular DBMS (MySQL or Postgres). For example, `DateTime` is same as  `datetime`.
```

2020-03-12 18:55 UTC, blinkov commented on docs/en/query_language/syntax.md
> +Case-sensitivity of data type names you can check in the `system.data_type_families` table.
```suggestion
Whether data type name is case-sensitive can be checked in the `system.data_type_families` table.
```

link to system table?

2020-03-12 18:55 UTC, blinkov commented on docs/en/query_language/syntax.md
> +All other keywords (column names, functions, and so on), in contrast to standard SQL, are case-sensitive.
```suggestion
In contrast to standard SQL all other keywords (including functions names)  are **case-sensitive**.
```
column name is an identifier, not a keyword

2020-03-13 05:46 UTC, BayoNet commented on docs/en/query_language/syntax.md
> +Case-sensitivity of data type names you can check in the `system.data_type_families` table.
It is not described. I'll do it later.

2020-03-13 06:33 UTC, blinkov approved these changes

2020-03-13 07:29 UTC, merged