DOCS-526: ifNotFinite docs. Ternary operator RU translation
ClickHouse/ClickHouse pull request #9650
Opened 2020-03-13 16:51 UTC by BayoNet

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Documentation for #8710

2020-03-13 22:11 UTC, blinkov requested changes

2020-03-13 22:11 UTC, blinkov commented on docs/en/query_language/functions/conditional_functions.md
> +## Ternary operator {#ternary-operator}
```suggestion
## Ternary Operator {#ternary-operator}
```

2020-03-13 22:11 UTC, blinkov commented on docs/en/query_language/functions/conditional_functions.md
> +Returns `then` if the `cond` is truthy (greater than zero), otherwise returns `else`.
```suggestion
Returns `then` if the `cond` evaluates to be true (greater than zero), otherwise returns `else`.
```

2020-03-13 22:11 UTC, blinkov commented on docs/en/query_language/functions/other_functions.md
> +- `y` — Fallback value. Type: [Float*](../../data_types/float.md).
is it required or optional?

2020-03-13 22:11 UTC, blinkov commented on docs/en/query_language/functions/other_functions.md
> +Checks whether `x` is a finite value.
```suggestion
Checks whether floating point value is finite.
```

2020-03-13 22:11 UTC, blinkov commented on docs/en/query_language/functions/other_functions.md
> +You can get the similar result by [ternary operator](conditional_functions.md#ternary-operator) `isFinite(x) ? x : y`.
```suggestion
You can get similar result by using [ternary operator](conditional_functions.md#ternary-operator): `isFinite(x) ? x : y`.
```

2020-03-13 22:11 UTC, blinkov commented on docs/ru/query_language/functions/conditional_functions.md
> +* `then` и `else` могут быть типа `NULL`.
```suggestion
* `then` и `else` могут быть `NULL`.
```

2020-03-13 22:11 UTC, blinkov commented on docs/ru/query_language/functions/other_functions.md
> +Проверяет, является ли `x` конечным значением.
```suggestion
Проверяет, является ли значение дробного числа с плавающей точкой конечным.
```

2020-03-13 22:11 UTC, blinkov commented on docs/ru/query_language/functions/other_functions.md
> +- `x`, если  `x` принимает конечное значение.
```suggestion
- `x`, если `x` принимает конечное значение.
```

2020-03-17 11:38 UTC, BayoNet commented on docs/en/query_language/functions/other_functions.md
> +- `y` — Fallback value. Type: [Float*](../../data_types/float.md).
It's required.

```
SELECT ifNotFinite(4)

Received exception from server (version 20.2.1):
Code: 42. DB::Exception: Received from localhost:9000. DB::Exception: Number of arguments for function ifNotFinite doesn't match: passed 1, should be 2. ```

2020-03-17 15:24 UTC, merged